// ── DATA6.JS — Spanish (Mexican/Venezuelan) complete dataset ──────────────────
// CEFR levels via freq: A1=freq10, A2=freq9, B1=freq7-8, B2=freq5-6, C1=freq3-4

const SPANISH_WORDS = [

  // ── GREETINGS & BASICS ────────────────────────────────────────────────────
  {kr:"hola",ro:"hola",meaning:"hello / hi",example:"¡Hola! ¿Cómo estás? — Hello! How are you?",pos:"expression",freq:10,register:"casual"},
  {kr:"buenos días",ro:"buenos días",meaning:"good morning",example:"Buenos días, señora — Good morning, ma'am",pos:"expression",freq:9,register:"neutral"},
  {kr:"buenas tardes",ro:"buenas tardes",meaning:"good afternoon",example:"Buenas tardes a todos — Good afternoon everyone",pos:"expression",freq:9,register:"neutral"},
  {kr:"buenas noches",ro:"buenas noches",meaning:"good evening / good night",example:"Buenas noches, hasta mañana — Good night, see you tomorrow",pos:"expression",freq:9,register:"neutral"},
  {kr:"adiós",ro:"adiós",meaning:"goodbye",example:"Adiós, cuídate — Goodbye, take care",pos:"expression",freq:10,register:"neutral"},
  {kr:"hasta luego",ro:"hasta luego",meaning:"see you later",example:"Hasta luego, nos vemos — See you later",pos:"expression",freq:9,register:"casual"},
  {kr:"hasta mañana",ro:"hasta mañana",meaning:"see you tomorrow",example:"Hasta mañana — See you tomorrow",pos:"expression",freq:8,register:"casual"},
  {kr:"chao",ro:"chao",meaning:"bye (Latin American casual)",example:"¡Chao! — Bye!",pos:"expression",freq:8,register:"casual"},
  {kr:"gracias",ro:"gracias",meaning:"thank you",example:"Muchas gracias — Thank you very much",pos:"expression",freq:10,register:"neutral"},
  {kr:"de nada",ro:"de nada",meaning:"you're welcome",example:"De nada, con gusto — You're welcome, with pleasure",pos:"expression",freq:9,register:"neutral"},
  {kr:"con gusto",ro:"con gusto",meaning:"with pleasure / you're welcome (Venezuela/Colombia)",example:"Con gusto, para servirte — With pleasure, at your service",pos:"expression",freq:8,register:"neutral"},
  {kr:"por favor",ro:"por favor",meaning:"please",example:"Un café, por favor — A coffee, please",pos:"expression",freq:10,register:"neutral"},
  {kr:"perdón",ro:"perdón",meaning:"sorry / excuse me",example:"Perdón, no entendí — Sorry, I didn't understand",pos:"expression",freq:9,register:"neutral"},
  {kr:"disculpe",ro:"disculpe",meaning:"excuse me (formal)",example:"Disculpe, ¿dónde está el baño? — Excuse me, where is the bathroom?",pos:"expression",freq:8,register:"formal"},
  {kr:"sí",ro:"sí",meaning:"yes",example:"Sí, claro — Yes, of course",pos:"expression",freq:10,register:"neutral"},
  {kr:"no",ro:"no",meaning:"no",example:"No, gracias — No, thank you",pos:"expression",freq:10,register:"neutral"},
  {kr:"¿cómo estás?",ro:"¿cómo estás?",meaning:"how are you? (casual)",example:"¡Hola! ¿Cómo estás? — Hi! How are you?",pos:"expression",freq:10,register:"casual"},
  {kr:"¿cómo está usted?",ro:"¿cómo está usted?",meaning:"how are you? (formal)",example:"Buenos días, ¿cómo está usted? — Good morning, how are you?",pos:"expression",freq:8,register:"formal"},
  {kr:"bien",ro:"bien",meaning:"well / good / fine",example:"Estoy bien, gracias — I'm fine, thank you",pos:"expression",freq:10,register:"neutral"},
  {kr:"más o menos",ro:"más o menos",meaning:"so-so / more or less",example:"¿Cómo estás? Más o menos — How are you? So-so",pos:"expression",freq:8,register:"casual"},
  {kr:"¿cómo te llamas?",ro:"¿cómo te llamas?",meaning:"what's your name? (casual)",example:"¿Cómo te llamas? — What's your name?",pos:"expression",freq:9,register:"casual"},
  {kr:"me llamo",ro:"me llamo",meaning:"my name is",example:"Me llamo Ana — My name is Ana",pos:"expression",freq:10,register:"neutral"},
  {kr:"mucho gusto",ro:"mucho gusto",meaning:"nice to meet you",example:"Mucho gusto en conocerte — Nice to meet you",pos:"expression",freq:9,register:"neutral"},
  {kr:"igualmente",ro:"igualmente",meaning:"likewise / same to you",example:"Mucho gusto. — Igualmente. — Nice to meet you. — Likewise.",pos:"expression",freq:8,register:"neutral"},
  {kr:"¿qué tal?",ro:"¿qué tal?",meaning:"how's it going? (very casual)",example:"¡Oye, qué tal! — Hey, how's it going!",pos:"expression",freq:9,register:"casual"},
  {kr:"¿qué pasó?",ro:"¿qué pasó?",meaning:"what's up? / what happened? (Venezuela)",example:"¡Ey, qué pasó! — Hey, what's up!",pos:"expression",freq:8,register:"casual"},
  {kr:"dale",ro:"dale",meaning:"okay / go ahead / sounds good (Mexico/Venezuela)",example:"¿Vamos? — Dale. — Shall we go? — Sounds good.",pos:"expression",freq:8,register:"casual"},
  {kr:"órale",ro:"órale",meaning:"okay / alright / wow (Mexico)",example:"¿Listo? — Órale — Ready? — Alright",pos:"expression",freq:8,register:"casual"},
  {kr:"chévere",ro:"chévere",meaning:"cool / great (Venezuela/Caribbean)",example:"¡Eso está chévere! — That's cool!",pos:"expression",freq:7,register:"casual"},
  {kr:"padre",ro:"padre",meaning:"cool / awesome (Mexico)",example:"¡Está muy padre! — That's awesome!",pos:"expression",freq:7,register:"casual"},

  // ── PRONOUNS ──────────────────────────────────────────────────────────────
  {kr:"yo",ro:"yo",meaning:"I",example:"Yo soy de México — I am from Mexico",pos:"pronoun",freq:10,register:"neutral"},
  {kr:"tú",ro:"tú",meaning:"you (singular casual)",example:"¿Tú hablas español? — Do you speak Spanish?",pos:"pronoun",freq:10,register:"casual"},
  {kr:"usted",ro:"usted",meaning:"you (singular formal)",example:"¿Usted habla inglés? — Do you speak English?",pos:"pronoun",freq:9,register:"formal"},
  {kr:"él",ro:"él",meaning:"he",example:"Él es médico — He is a doctor",pos:"pronoun",freq:10,register:"neutral"},
  {kr:"ella",ro:"ella",meaning:"she",example:"Ella estudia medicina — She studies medicine",pos:"pronoun",freq:10,register:"neutral"},
  {kr:"nosotros",ro:"nosotros",meaning:"we",example:"Nosotros somos amigos — We are friends",pos:"pronoun",freq:9,register:"neutral"},
  {kr:"ustedes",ro:"ustedes",meaning:"you all (Latin American — replaces vosotros)",example:"¿Ustedes quieren comer? — Do you all want to eat?",pos:"pronoun",freq:9,register:"neutral"},
  {kr:"ellos",ro:"ellos",meaning:"they (mixed or all male)",example:"Ellos viven aquí — They live here",pos:"pronoun",freq:9,register:"neutral"},
  {kr:"ellas",ro:"ellas",meaning:"they (all female)",example:"Ellas trabajan juntas — They work together",pos:"pronoun",freq:8,register:"neutral"},
  {kr:"me",ro:"me",meaning:"me / myself",example:"Me llamo Carlos — My name is Carlos",pos:"pronoun",freq:10,register:"neutral"},
  {kr:"te",ro:"te",meaning:"you (object)",example:"Te quiero — I love you",pos:"pronoun",freq:10,register:"casual"},
  {kr:"lo / la",ro:"lo / la",meaning:"it / him / her (direct object)",example:"Lo veo todos los días — I see it every day",pos:"pronoun",freq:9,register:"neutral"},
  {kr:"nos",ro:"nos",meaning:"us",example:"Nos vemos mañana — We'll see each other tomorrow",pos:"pronoun",freq:9,register:"neutral"},
  {kr:"les",ro:"les",meaning:"them / to them",example:"Les dije la verdad — I told them the truth",pos:"pronoun",freq:8,register:"neutral"},

  // ── CORE VERBS ────────────────────────────────────────────────────────────
  {kr:"ser",ro:"ser",meaning:"to be (permanent)",example:"Soy mexicana — I am Mexican",pos:"verb",freq:10,register:"neutral"},
  {kr:"estar",ro:"estar",meaning:"to be (temporary / location)",example:"Estoy cansada — I am tired",pos:"verb",freq:10,register:"neutral"},
  {kr:"tener",ro:"tener",meaning:"to have",example:"Tengo hambre — I'm hungry (I have hunger)",pos:"verb",freq:10,register:"neutral"},
  {kr:"hacer",ro:"hacer",meaning:"to do / to make",example:"¿Qué haces? — What are you doing?",pos:"verb",freq:10,register:"neutral"},
  {kr:"ir",ro:"ir",meaning:"to go",example:"Voy al mercado — I'm going to the market",pos:"verb",freq:10,register:"neutral"},
  {kr:"venir",ro:"venir",meaning:"to come",example:"¿Puedes venir mañana? — Can you come tomorrow?",pos:"verb",freq:9,register:"neutral"},
  {kr:"querer",ro:"querer",meaning:"to want / to love",example:"Quiero un café — I want a coffee",pos:"verb",freq:10,register:"neutral"},
  {kr:"poder",ro:"poder",meaning:"to be able to / can",example:"No puedo ir — I can't go",pos:"verb",freq:10,register:"neutral"},
  {kr:"saber",ro:"saber",meaning:"to know (facts/how to)",example:"No sé — I don't know",pos:"verb",freq:10,register:"neutral"},
  {kr:"conocer",ro:"conocer",meaning:"to know (people/places)",example:"¿Conoces a María? — Do you know María?",pos:"verb",freq:8,register:"neutral"},
  {kr:"hablar",ro:"hablar",meaning:"to speak / to talk",example:"Hablo español — I speak Spanish",pos:"verb",freq:10,register:"neutral"},
  {kr:"comer",ro:"comer",meaning:"to eat",example:"¿Quieres comer? — Do you want to eat?",pos:"verb",freq:10,register:"neutral"},
  {kr:"beber",ro:"beber",meaning:"to drink",example:"Bebo agua — I drink water",pos:"verb",freq:9,register:"neutral"},
  {kr:"tomar",ro:"tomar",meaning:"to take / to drink (Latin America)",example:"Voy a tomar un café — I'm going to have a coffee",pos:"verb",freq:9,register:"neutral"},
  {kr:"dormir",ro:"dormir",meaning:"to sleep",example:"Dormí muy bien — I slept very well",pos:"verb",freq:9,register:"neutral"},
  {kr:"trabajar",ro:"trabajar",meaning:"to work",example:"Trabajo en una oficina — I work in an office",pos:"verb",freq:9,register:"neutral"},
  {kr:"vivir",ro:"vivir",meaning:"to live",example:"Vivo en Caracas — I live in Caracas",pos:"verb",freq:9,register:"neutral"},
  {kr:"estudiar",ro:"estudiar",meaning:"to study",example:"Estudio medicina — I study medicine",pos:"verb",freq:9,register:"neutral"},
  {kr:"ver",ro:"ver",meaning:"to see / to watch",example:"Veo televisión — I watch television",pos:"verb",freq:9,register:"neutral"},
  {kr:"escuchar",ro:"escuchar",meaning:"to listen",example:"Escucho música — I listen to music",pos:"verb",freq:8,register:"neutral"},
  {kr:"leer",ro:"leer",meaning:"to read",example:"Leo mucho — I read a lot",pos:"verb",freq:8,register:"neutral"},
  {kr:"escribir",ro:"escribir",meaning:"to write",example:"Escribo en mi diario — I write in my diary",pos:"verb",freq:8,register:"neutral"},
  {kr:"comprar",ro:"comprar",meaning:"to buy",example:"Voy a comprar leche — I'm going to buy milk",pos:"verb",freq:8,register:"neutral"},
  {kr:"llegar",ro:"llegar",meaning:"to arrive",example:"Llegué tarde — I arrived late",pos:"verb",freq:8,register:"neutral"},
  {kr:"salir",ro:"salir",meaning:"to leave / to go out",example:"Salgo a las ocho — I leave at eight",pos:"verb",freq:8,register:"neutral"},
  {kr:"entrar",ro:"entrar",meaning:"to enter",example:"Entra, por favor — Come in, please",pos:"verb",freq:7,register:"neutral"},
  {kr:"poner",ro:"poner",meaning:"to put / to place",example:"Pon la mesa — Set the table",pos:"verb",freq:8,register:"neutral"},
  {kr:"traer",ro:"traer",meaning:"to bring",example:"Trae el menú, por favor — Bring the menu, please",pos:"verb",freq:7,register:"neutral"},
  {kr:"decir",ro:"decir",meaning:"to say / to tell",example:"¿Qué dijiste? — What did you say?",pos:"verb",freq:10,register:"neutral"},
  {kr:"pensar",ro:"pensar",meaning:"to think",example:"Pienso que sí — I think so",pos:"verb",freq:8,register:"neutral"},
  {kr:"creer",ro:"creer",meaning:"to believe / to think",example:"Creo que tienes razón — I think you're right",pos:"verb",freq:8,register:"neutral"},
  {kr:"sentir",ro:"sentir",meaning:"to feel / to regret",example:"Me siento bien — I feel good",pos:"verb",freq:8,register:"neutral"},
  {kr:"llamar",ro:"llamar",meaning:"to call",example:"Te llamo más tarde — I'll call you later",pos:"verb",freq:8,register:"neutral"},
  {kr:"necesitar",ro:"necesitar",meaning:"to need",example:"Necesito ayuda — I need help",pos:"verb",freq:8,register:"neutral"},
  {kr:"ayudar",ro:"ayudar",meaning:"to help",example:"¿Puedes ayudarme? — Can you help me?",pos:"verb",freq:8,register:"neutral"},
  {kr:"empezar",ro:"empezar",meaning:"to start / to begin",example:"La clase empieza a las nueve — The class starts at nine",pos:"verb",freq:7,register:"neutral"},
  {kr:"terminar",ro:"terminar",meaning:"to finish / to end",example:"Terminé el trabajo — I finished the work",pos:"verb",freq:7,register:"neutral"},
  {kr:"buscar",ro:"buscar",meaning:"to look for",example:"Busco mis llaves — I'm looking for my keys",pos:"verb",freq:7,register:"neutral"},
  {kr:"encontrar",ro:"encontrar",meaning:"to find / to meet",example:"No encuentro mi teléfono — I can't find my phone",pos:"verb",freq:7,register:"neutral"},
  {kr:"esperar",ro:"esperar",meaning:"to wait / to hope",example:"Espera un momento — Wait a moment",pos:"verb",freq:8,register:"neutral"},
  {kr:"abrir",ro:"abrir",meaning:"to open",example:"Abre la puerta — Open the door",pos:"verb",freq:7,register:"neutral"},
  {kr:"cerrar",ro:"cerrar",meaning:"to close",example:"Cierra la ventana — Close the window",pos:"verb",freq:7,register:"neutral"},
  {kr:"dar",ro:"dar",meaning:"to give",example:"Dame tu número — Give me your number",pos:"verb",freq:9,register:"neutral"},
  {kr:"recibir",ro:"recibir",meaning:"to receive",example:"Recibí tu mensaje — I received your message",pos:"verb",freq:7,register:"neutral"},
  {kr:"preguntar",ro:"preguntar",meaning:"to ask",example:"Quiero preguntar algo — I want to ask something",pos:"verb",freq:7,register:"neutral"},
  {kr:"contestar",ro:"contestar",meaning:"to answer",example:"Contesta el teléfono — Answer the phone",pos:"verb",freq:7,register:"neutral"},
  {kr:"aprender",ro:"aprender",meaning:"to learn",example:"Aprendo español — I'm learning Spanish",pos:"verb",freq:8,register:"neutral"},
  {kr:"enseñar",ro:"enseñar",meaning:"to teach",example:"Ella enseña matemáticas — She teaches math",pos:"verb",freq:7,register:"neutral"},
  {kr:"caminar",ro:"caminar",meaning:"to walk",example:"Camino al trabajo — I walk to work",pos:"verb",freq:7,register:"neutral"},
  {kr:"correr",ro:"correr",meaning:"to run",example:"Corro todos los días — I run every day",pos:"verb",freq:7,register:"neutral"},
  {kr:"cocinar",ro:"cocinar",meaning:"to cook",example:"Me gusta cocinar — I like to cook",pos:"verb",freq:7,register:"neutral"},
  {kr:"limpiar",ro:"limpiar",meaning:"to clean",example:"Limpio mi cuarto — I clean my room",pos:"verb",freq:7,register:"neutral"},
  {kr:"pagar",ro:"pagar",meaning:"to pay",example:"¿Cómo vas a pagar? — How are you going to pay?",pos:"verb",freq:7,register:"neutral"},
  {kr:"costar",ro:"costar",meaning:"to cost",example:"¿Cuánto cuesta? — How much does it cost?",pos:"verb",freq:8,register:"neutral"},
  {kr:"gustar",ro:"gustar",meaning:"to like (lit: to please)",example:"Me gusta el café — I like coffee",pos:"verb",freq:10,register:"neutral"},
  {kr:"encantar",ro:"encantar",meaning:"to love (like gustar but stronger)",example:"Me encanta la música — I love music",pos:"verb",freq:8,register:"neutral"},
  {kr:"doler",ro:"doler",meaning:"to hurt / to ache",example:"Me duele la cabeza — My head hurts",pos:"verb",freq:7,register:"neutral"},
  {kr:"quedar",ro:"quedar",meaning:"to remain / to meet up (LatAm)",example:"¿Quedamos a las seis? — Shall we meet at six?",pos:"verb",freq:7,register:"neutral"},
  {kr:"volver",ro:"volver",meaning:"to return / to come back",example:"Vuelvo en una hora — I'll be back in an hour",pos:"verb",freq:7,register:"neutral"},
  {kr:"pasar",ro:"pasar",meaning:"to pass / to happen / to spend (time)",example:"¿Qué pasó? — What happened?",pos:"verb",freq:8,register:"neutral"},
  {kr:"subir",ro:"subir",meaning:"to go up / to upload / to get in",example:"Sube al carro — Get in the car",pos:"verb",freq:6,register:"neutral"},
  {kr:"bajar",ro:"bajar",meaning:"to go down / to download / to get off",example:"Bajo en la próxima — I get off at the next stop",pos:"verb",freq:6,register:"neutral"},

  // ── NOUNS — People & Relationships ───────────────────────────────────────
  {kr:"persona",ro:"persona",meaning:"person",example:"Es una buena persona — She's a good person",pos:"noun",freq:9,register:"neutral"},
  {kr:"hombre",ro:"hombre",meaning:"man",example:"Un hombre joven — A young man",pos:"noun",freq:8,register:"neutral"},
  {kr:"mujer",ro:"mujer",meaning:"woman / wife",example:"Una mujer inteligente — An intelligent woman",pos:"noun",freq:8,register:"neutral"},
  {kr:"niño",ro:"niño",meaning:"boy / child",example:"El niño juega — The boy plays",pos:"noun",freq:8,register:"neutral"},
  {kr:"niña",ro:"niña",meaning:"girl / child",example:"La niña estudia — The girl studies",pos:"noun",freq:8,register:"neutral"},
  {kr:"familia",ro:"familia",meaning:"family",example:"Mi familia es grande — My family is big",pos:"noun",freq:9,register:"neutral"},
  {kr:"mamá",ro:"mamá",meaning:"mom / mother",example:"Mi mamá cocina muy bien — My mom cooks very well",pos:"noun",freq:9,register:"casual"},
  {kr:"papá",ro:"papá",meaning:"dad / father",example:"Mi papá trabaja mucho — My dad works a lot",pos:"noun",freq:9,register:"casual"},
  {kr:"madre",ro:"madre",meaning:"mother (formal)",example:"La madre de Juan es médica — Juan's mother is a doctor",pos:"noun",freq:8,register:"neutral"},
  {kr:"padre",ro:"padre",meaning:"father (formal)",example:"Su padre es ingeniero — His father is an engineer",pos:"noun",freq:8,register:"neutral"},
  {kr:"hermano",ro:"hermano",meaning:"brother",example:"Tengo un hermano mayor — I have an older brother",pos:"noun",freq:8,register:"neutral"},
  {kr:"hermana",ro:"hermana",meaning:"sister",example:"Mi hermana vive en Venezuela — My sister lives in Venezuela",pos:"noun",freq:8,register:"neutral"},
  {kr:"hijo",ro:"hijo",meaning:"son",example:"Mi hijo tiene cinco años — My son is five years old",pos:"noun",freq:8,register:"neutral"},
  {kr:"hija",ro:"hija",meaning:"daughter",example:"Mi hija estudia derecho — My daughter studies law",pos:"noun",freq:7,register:"neutral"},
  {kr:"abuelo",ro:"abuelo",meaning:"grandfather",example:"Mi abuelo tiene ochenta años — My grandfather is eighty",pos:"noun",freq:7,register:"neutral"},
  {kr:"abuela",ro:"abuela",meaning:"grandmother",example:"La abuela hace arepas — Grandma makes arepas",pos:"noun",freq:7,register:"neutral"},
  {kr:"esposo",ro:"esposo",meaning:"husband",example:"Mi esposo es muy cariñoso — My husband is very affectionate",pos:"noun",freq:7,register:"neutral"},
  {kr:"esposa",ro:"esposa",meaning:"wife",example:"Su esposa es venezolana — His wife is Venezuelan",pos:"noun",freq:7,register:"neutral"},
  {kr:"novio",ro:"novio",meaning:"boyfriend / groom",example:"Mi novio es muy guapo — My boyfriend is very handsome",pos:"noun",freq:7,register:"casual"},
  {kr:"novia",ro:"novia",meaning:"girlfriend / bride",example:"Su novia es actriz — His girlfriend is an actress",pos:"noun",freq:7,register:"casual"},
  {kr:"amigo",ro:"amigo",meaning:"friend (male)",example:"Mi mejor amigo — My best friend",pos:"noun",freq:9,register:"neutral"},
  {kr:"amiga",ro:"amiga",meaning:"friend (female)",example:"Es mi amiga de toda la vida — She's my lifelong friend",pos:"noun",freq:8,register:"neutral"},
  {kr:"vecino",ro:"vecino",meaning:"neighbor",example:"El vecino es muy amable — The neighbor is very friendly",pos:"noun",freq:6,register:"neutral"},

  // ── NOUNS — Food & Drink ─────────────────────────────────────────────────
  {kr:"agua",ro:"agua",meaning:"water",example:"Un vaso de agua, por favor — A glass of water, please",pos:"noun",freq:10,register:"neutral"},
  {kr:"café",ro:"café",meaning:"coffee",example:"¿Quieres café? — Do you want coffee?",pos:"noun",freq:9,register:"neutral"},
  {kr:"leche",ro:"leche",meaning:"milk",example:"Café con leche — Coffee with milk",pos:"noun",freq:8,register:"neutral"},
  {kr:"jugo",ro:"jugo",meaning:"juice (Latin American)",example:"Jugo de naranja — Orange juice",pos:"noun",freq:8,register:"neutral"},
  {kr:"refresco",ro:"refresco",meaning:"soda / soft drink",example:"Un refresco de cola — A cola",pos:"noun",freq:7,register:"casual"},
  {kr:"cerveza",ro:"cerveza",meaning:"beer",example:"Una cerveza fría — A cold beer",pos:"noun",freq:7,register:"casual"},
  {kr:"vino",ro:"vino",meaning:"wine",example:"Una copa de vino tinto — A glass of red wine",pos:"noun",freq:7,register:"neutral"},
  {kr:"pan",ro:"pan",meaning:"bread",example:"Pan recién horneado — Freshly baked bread",pos:"noun",freq:9,register:"neutral"},
  {kr:"arroz",ro:"arroz",meaning:"rice",example:"Arroz con frijoles — Rice and beans",pos:"noun",freq:9,register:"neutral"},
  {kr:"frijoles",ro:"frijoles",meaning:"beans (Mexico)",example:"Frijoles negros — Black beans",pos:"noun",freq:8,register:"neutral"},
  {kr:"caraotas",ro:"caraotas",meaning:"beans (Venezuela)",example:"Caraotas negras — Black beans",pos:"noun",freq:7,register:"neutral"},
  {kr:"carne",ro:"carne",meaning:"meat",example:"Carne asada — Grilled meat",pos:"noun",freq:8,register:"neutral"},
  {kr:"pollo",ro:"pollo",meaning:"chicken",example:"Pollo a la plancha — Grilled chicken",pos:"noun",freq:8,register:"neutral"},
  {kr:"pescado",ro:"pescado",meaning:"fish (to eat)",example:"Pescado frito — Fried fish",pos:"noun",freq:7,register:"neutral"},
  {kr:"verduras",ro:"verduras",meaning:"vegetables",example:"Hay que comer verduras — You have to eat vegetables",pos:"noun",freq:7,register:"neutral"},
  {kr:"frutas",ro:"frutas",meaning:"fruit",example:"Las frutas tropicales — Tropical fruits",pos:"noun",freq:7,register:"neutral"},
  {kr:"huevo",ro:"huevo",meaning:"egg",example:"Huevos revueltos — Scrambled eggs",pos:"noun",freq:8,register:"neutral"},
  {kr:"queso",ro:"queso",meaning:"cheese",example:"Queso fresco — Fresh cheese",pos:"noun",freq:8,register:"neutral"},
  {kr:"sal",ro:"sal",meaning:"salt",example:"Más sal, por favor — More salt, please",pos:"noun",freq:7,register:"neutral"},
  {kr:"azúcar",ro:"azúcar",meaning:"sugar",example:"Sin azúcar — Without sugar",pos:"noun",freq:7,register:"neutral"},
  {kr:"tacos",ro:"tacos",meaning:"tacos (Mexico staple)",example:"Unos tacos al pastor — Some tacos al pastor",pos:"noun",freq:8,register:"casual"},
  {kr:"arepa",ro:"arepa",meaning:"arepa — corn flatbread (Venezuela staple)",example:"Una arepa con queso — An arepa with cheese",pos:"noun",freq:7,register:"neutral"},
  {kr:"tortilla",ro:"tortilla",meaning:"tortilla (Mexico) / omelette (rest of LatAm)",example:"Tortillas de maíz — Corn tortillas",pos:"noun",freq:7,register:"neutral"},
  {kr:"salsa",ro:"salsa",meaning:"sauce / salsa",example:"Salsa picante — Hot sauce",pos:"noun",freq:8,register:"casual"},
  {kr:"comida",ro:"comida",meaning:"food / meal",example:"La comida está lista — The food is ready",pos:"noun",freq:9,register:"neutral"},
  {kr:"desayuno",ro:"desayuno",meaning:"breakfast",example:"El desayuno es a las ocho — Breakfast is at eight",pos:"noun",freq:8,register:"neutral"},
  {kr:"almuerzo",ro:"almuerzo",meaning:"lunch",example:"¿Qué hay de almuerzo? — What's for lunch?",pos:"noun",freq:8,register:"neutral"},
  {kr:"cena",ro:"cena",meaning:"dinner",example:"La cena es a las ocho — Dinner is at eight",pos:"noun",freq:8,register:"neutral"},
  {kr:"merienda",ro:"merienda",meaning:"snack / afternoon snack",example:"La merienda de los niños — The kids' afternoon snack",pos:"noun",freq:6,register:"neutral"},
  {kr:"restaurante",ro:"restaurante",meaning:"restaurant",example:"Vamos a un restaurante — Let's go to a restaurant",pos:"noun",freq:8,register:"neutral"},
  {kr:"menú",ro:"menú",meaning:"menu",example:"¿Me trae el menú? — Can you bring me the menu?",pos:"noun",freq:7,register:"neutral"},
  {kr:"cuenta",ro:"cuenta",meaning:"bill / check / account",example:"La cuenta, por favor — The check, please",pos:"noun",freq:7,register:"neutral"},
  {kr:"propina",ro:"propina",meaning:"tip (gratuity)",example:"Dejé una buena propina — I left a good tip",pos:"noun",freq:6,register:"neutral"},

  // ── NOUNS — Places & Transport ───────────────────────────────────────────
  {kr:"casa",ro:"casa",meaning:"house / home",example:"Voy a mi casa — I'm going home",pos:"noun",freq:10,register:"neutral"},
  {kr:"departamento",ro:"departamento",meaning:"apartment (Mexico)",example:"Vivo en un departamento — I live in an apartment",pos:"noun",freq:7,register:"neutral"},
  {kr:"apartamento",ro:"apartamento",meaning:"apartment (Venezuela/rest of LatAm)",example:"Mi apartamento es pequeño — My apartment is small",pos:"noun",freq:7,register:"neutral"},
  {kr:"cuarto",ro:"cuarto",meaning:"room / bedroom",example:"Mi cuarto está arriba — My room is upstairs",pos:"noun",freq:8,register:"neutral"},
  {kr:"baño",ro:"baño",meaning:"bathroom",example:"¿Dónde está el baño? — Where is the bathroom?",pos:"noun",freq:9,register:"neutral"},
  {kr:"cocina",ro:"cocina",meaning:"kitchen",example:"Cocino en la cocina — I cook in the kitchen",pos:"noun",freq:7,register:"neutral"},
  {kr:"sala",ro:"sala",meaning:"living room",example:"La familia está en la sala — The family is in the living room",pos:"noun",freq:7,register:"neutral"},
  {kr:"ciudad",ro:"ciudad",meaning:"city",example:"Esta ciudad es hermosa — This city is beautiful",pos:"noun",freq:9,register:"neutral"},
  {kr:"calle",ro:"calle",meaning:"street",example:"Vivo en esta calle — I live on this street",pos:"noun",freq:8,register:"neutral"},
  {kr:"avenida",ro:"avenida",meaning:"avenue",example:"La Avenida Bolívar — Bolívar Avenue",pos:"noun",freq:6,register:"neutral"},
  {kr:"mercado",ro:"mercado",meaning:"market",example:"Voy al mercado — I'm going to the market",pos:"noun",freq:8,register:"neutral"},
  {kr:"tienda",ro:"tienda",meaning:"store / shop",example:"La tienda está cerrada — The store is closed",pos:"noun",freq:8,register:"neutral"},
  {kr:"supermercado",ro:"supermercado",meaning:"supermarket",example:"Voy al supermercado — I'm going to the supermarket",pos:"noun",freq:7,register:"neutral"},
  {kr:"farmacia",ro:"farmacia",meaning:"pharmacy",example:"Hay una farmacia cerca — There's a pharmacy nearby",pos:"noun",freq:7,register:"neutral"},
  {kr:"hospital",ro:"hospital",meaning:"hospital",example:"Me llevaron al hospital — They took me to the hospital",pos:"noun",freq:7,register:"neutral"},
  {kr:"escuela",ro:"escuela",meaning:"school",example:"Los niños van a la escuela — The children go to school",pos:"noun",freq:8,register:"neutral"},
  {kr:"universidad",ro:"universidad",meaning:"university",example:"Estudio en la universidad — I study at the university",pos:"noun",freq:8,register:"neutral"},
  {kr:"oficina",ro:"oficina",meaning:"office",example:"Trabajo en una oficina — I work in an office",pos:"noun",freq:7,register:"neutral"},
  {kr:"banco",ro:"banco",meaning:"bank / bench",example:"Voy al banco a depositar — I'm going to the bank to deposit",pos:"noun",freq:7,register:"neutral"},
  {kr:"iglesia",ro:"iglesia",meaning:"church",example:"La iglesia está en el centro — The church is downtown",pos:"noun",freq:6,register:"neutral"},
  {kr:"parque",ro:"parque",meaning:"park",example:"Los niños juegan en el parque — The children play in the park",pos:"noun",freq:7,register:"neutral"},
  {kr:"playa",ro:"playa",meaning:"beach",example:"Vamos a la playa — Let's go to the beach",pos:"noun",freq:7,register:"neutral"},
  {kr:"montaña",ro:"montaña",meaning:"mountain",example:"Las montañas de Venezuela — The mountains of Venezuela",pos:"noun",freq:6,register:"neutral"},
  {kr:"aeropuerto",ro:"aeropuerto",meaning:"airport",example:"El vuelo sale del aeropuerto — The flight departs from the airport",pos:"noun",freq:7,register:"neutral"},
  {kr:"metro",ro:"metro",meaning:"subway / metro",example:"Tomo el metro — I take the metro",pos:"noun",freq:7,register:"neutral"},
  {kr:"camión",ro:"camión",meaning:"bus (Mexico)",example:"Me voy en camión — I'm going by bus",pos:"noun",freq:7,register:"casual"},
  {kr:"autobús",ro:"autobús",meaning:"bus",example:"El autobús llega tarde — The bus arrives late",pos:"noun",freq:7,register:"neutral"},
  {kr:"carrito",ro:"carrito",meaning:"bus/minibus (Venezuela)",example:"Tomo el carrito — I take the minibus",pos:"noun",freq:6,register:"casual"},
  {kr:"taxi",ro:"taxi",meaning:"taxi",example:"Pedí un taxi — I ordered a taxi",pos:"noun",freq:7,register:"neutral"},
  {kr:"carro",ro:"carro",meaning:"car (Latin American)",example:"Mi carro está en el taller — My car is at the shop",pos:"noun",freq:8,register:"neutral"},
  {kr:"carretera",ro:"carretera",meaning:"highway / road",example:"La carretera está bloqueada — The highway is blocked",pos:"noun",freq:6,register:"neutral"},

  // ── ADJECTIVES ────────────────────────────────────────────────────────────
  {kr:"grande",ro:"grande",meaning:"big / large / great",example:"Una ciudad grande — A big city",pos:"adjective",freq:10,register:"neutral"},
  {kr:"pequeño",ro:"pequeño",meaning:"small / little",example:"Un apartamento pequeño — A small apartment",pos:"adjective",freq:9,register:"neutral"},
  {kr:"nuevo",ro:"nuevo",meaning:"new",example:"Un teléfono nuevo — A new phone",pos:"adjective",freq:9,register:"neutral"},
  {kr:"viejo",ro:"viejo",meaning:"old / elderly",example:"Un edificio viejo — An old building",pos:"adjective",freq:8,register:"neutral"},
  {kr:"bueno",ro:"bueno",meaning:"good",example:"¡Qué buena idea! — What a good idea!",pos:"adjective",freq:10,register:"neutral"},
  {kr:"malo",ro:"malo",meaning:"bad",example:"Tuve un día malo — I had a bad day",pos:"adjective",freq:8,register:"neutral"},
  {kr:"bonito",ro:"bonito",meaning:"pretty / nice",example:"¡Qué bonito lugar! — What a pretty place!",pos:"adjective",freq:8,register:"neutral"},
  {kr:"feo",ro:"feo",meaning:"ugly",example:"No seas feo — Don't be ugly/mean",pos:"adjective",freq:6,register:"casual"},
  {kr:"guapo",ro:"guapo",meaning:"handsome / good-looking",example:"Ese chico está muy guapo — That guy looks very handsome",pos:"adjective",freq:7,register:"casual"},
  {kr:"hermoso",ro:"hermoso",meaning:"beautiful",example:"¡Qué paisaje más hermoso! — What a beautiful landscape!",pos:"adjective",freq:7,register:"neutral"},
  {kr:"rico",ro:"rico",meaning:"delicious / rich",example:"¡Qué rico está esto! — This is delicious!",pos:"adjective",freq:8,register:"casual"},
  {kr:"caro",ro:"caro",meaning:"expensive",example:"Está muy caro — It's very expensive",pos:"adjective",freq:8,register:"neutral"},
  {kr:"barato",ro:"barato",meaning:"cheap / inexpensive",example:"¡Qué barato! — How cheap!",pos:"adjective",freq:7,register:"neutral"},
  {kr:"rápido",ro:"rápido",meaning:"fast / quick",example:"¡Más rápido! — Faster!",pos:"adjective",freq:7,register:"neutral"},
  {kr:"lento",ro:"lento",meaning:"slow",example:"El tráfico está muy lento — Traffic is very slow",pos:"adjective",freq:7,register:"neutral"},
  {kr:"fácil",ro:"fácil",meaning:"easy",example:"El español es fácil — Spanish is easy",pos:"adjective",freq:8,register:"neutral"},
  {kr:"difícil",ro:"difícil",meaning:"difficult / hard",example:"El examen fue difícil — The exam was difficult",pos:"adjective",freq:8,register:"neutral"},
  {kr:"ocupado",ro:"ocupado",meaning:"busy / occupied",example:"Estoy muy ocupada — I'm very busy",pos:"adjective",freq:7,register:"neutral"},
  {kr:"libre",ro:"libre",meaning:"free / available",example:"¿Estás libre mañana? — Are you free tomorrow?",pos:"adjective",freq:7,register:"neutral"},
  {kr:"cansado",ro:"cansado",meaning:"tired",example:"Estoy muy cansado — I'm very tired",pos:"adjective",freq:8,register:"neutral"},
  {kr:"aburrido",ro:"aburrido",meaning:"bored / boring",example:"Estoy aburrida — I'm bored",pos:"adjective",freq:7,register:"casual"},
  {kr:"emocionado",ro:"emocionado",meaning:"excited",example:"Estoy muy emocionada — I'm very excited",pos:"adjective",freq:7,register:"neutral"},
  {kr:"feliz",ro:"feliz",meaning:"happy",example:"Soy feliz aquí — I am happy here",pos:"adjective",freq:8,register:"neutral"},
  {kr:"triste",ro:"triste",meaning:"sad",example:"Estoy triste hoy — I'm sad today",pos:"adjective",freq:7,register:"neutral"},
  {kr:"enojado",ro:"enojado",meaning:"angry (Mexico)",example:"Está muy enojado — He's very angry",pos:"adjective",freq:7,register:"neutral"},
  {kr:"bravo",ro:"bravo",meaning:"angry (Venezuela/Caribbean)",example:"Está bravo — He's angry",pos:"adjective",freq:6,register:"casual"},
  {kr:"asustado",ro:"asustado",meaning:"scared / frightened",example:"Estoy asustada — I'm scared",pos:"adjective",freq:6,register:"neutral"},
  {kr:"seguro",ro:"seguro",meaning:"sure / safe / certain",example:"¿Estás seguro? — Are you sure?",pos:"adjective",freq:7,register:"neutral"},
  {kr:"listo",ro:"listo",meaning:"ready / smart",example:"¿Estás listo? — Are you ready?",pos:"adjective",freq:8,register:"neutral"},
  {kr:"interesante",ro:"interesante",meaning:"interesting",example:"Es muy interesante — It's very interesting",pos:"adjective",freq:7,register:"neutral"},
  {kr:"importante",ro:"importante",meaning:"important",example:"Esto es muy importante — This is very important",pos:"adjective",freq:7,register:"neutral"},
  {kr:"necesario",ro:"necesario",meaning:"necessary",example:"Es necesario estudiar — It's necessary to study",pos:"adjective",freq:6,register:"neutral"},
  {kr:"igual",ro:"igual",meaning:"equal / the same",example:"Son iguales — They're the same",pos:"adjective",freq:6,register:"neutral"},
  {kr:"diferente",ro:"diferente",meaning:"different",example:"Somos muy diferentes — We are very different",pos:"adjective",freq:6,register:"neutral"},

  // ── NUMBERS ───────────────────────────────────────────────────────────────
  {kr:"uno",ro:"uno",meaning:"one",example:"Un café, por favor — One coffee, please",pos:"noun",freq:10,register:"neutral"},
  {kr:"dos",ro:"dos",meaning:"two",example:"Dos boletos — Two tickets",pos:"noun",freq:10,register:"neutral"},
  {kr:"tres",ro:"tres",meaning:"three",example:"Tres horas — Three hours",pos:"noun",freq:10,register:"neutral"},
  {kr:"cuatro",ro:"cuatro",meaning:"four",example:"Cuatro personas — Four people",pos:"noun",freq:9,register:"neutral"},
  {kr:"cinco",ro:"cinco",meaning:"five",example:"Cinco minutos — Five minutes",pos:"noun",freq:9,register:"neutral"},
  {kr:"seis",ro:"seis",meaning:"six",example:"A las seis — At six o'clock",pos:"noun",freq:8,register:"neutral"},
  {kr:"siete",ro:"siete",meaning:"seven",example:"Siete días — Seven days",pos:"noun",freq:8,register:"neutral"},
  {kr:"ocho",ro:"ocho",meaning:"eight",example:"Son las ocho — It's eight o'clock",pos:"noun",freq:8,register:"neutral"},
  {kr:"nueve",ro:"nueve",meaning:"nine",example:"Nueve meses — Nine months",pos:"noun",freq:8,register:"neutral"},
  {kr:"diez",ro:"diez",meaning:"ten",example:"Diez pesos — Ten pesos",pos:"noun",freq:8,register:"neutral"},
  {kr:"veinte",ro:"veinte",meaning:"twenty",example:"Veinte años — Twenty years",pos:"noun",freq:7,register:"neutral"},
  {kr:"cien",ro:"cien",meaning:"one hundred",example:"Cien pesos — One hundred pesos",pos:"noun",freq:7,register:"neutral"},
  {kr:"mil",ro:"mil",meaning:"one thousand",example:"Mil bolívares — One thousand bolívares",pos:"noun",freq:7,register:"neutral"},

  // ── TIME EXPRESSIONS ──────────────────────────────────────────────────────
  {kr:"hoy",ro:"hoy",meaning:"today",example:"¿Qué haces hoy? — What are you doing today?",pos:"adverb",freq:10,register:"neutral"},
  {kr:"mañana",ro:"mañana",meaning:"tomorrow / morning",example:"Hasta mañana — See you tomorrow",pos:"adverb",freq:10,register:"neutral"},
  {kr:"ayer",ro:"ayer",meaning:"yesterday",example:"¿Qué hiciste ayer? — What did you do yesterday?",pos:"adverb",freq:9,register:"neutral"},
  {kr:"ahora",ro:"ahora",meaning:"now",example:"Hazlo ahora — Do it now",pos:"adverb",freq:10,register:"neutral"},
  {kr:"ahorita",ro:"ahorita",meaning:"right now / in a bit (Mexico — context dependent)",example:"Ahorita voy — I'm going right now / I'll go in a bit",pos:"adverb",freq:9,register:"casual"},
  {kr:"ahorita mismo",ro:"ahorita mismo",meaning:"right now (immediately — Mexico)",example:"¡Ahorita mismo! — Right now!",pos:"adverb",freq:7,register:"casual"},
  {kr:"después",ro:"después",meaning:"after / later",example:"Hablamos después — We'll talk later",pos:"adverb",freq:9,register:"neutral"},
  {kr:"antes",ro:"antes",meaning:"before / earlier",example:"Antes no lo sabía — Before, I didn't know",pos:"adverb",freq:8,register:"neutral"},
  {kr:"siempre",ro:"siempre",meaning:"always",example:"Siempre llego tarde — I always arrive late",pos:"adverb",freq:9,register:"neutral"},
  {kr:"nunca",ro:"nunca",meaning:"never",example:"Nunca he ido a México — I've never been to Mexico",pos:"adverb",freq:8,register:"neutral"},
  {kr:"a veces",ro:"a veces",meaning:"sometimes",example:"A veces cocino en casa — Sometimes I cook at home",pos:"adverb",freq:8,register:"neutral"},
  {kr:"ya",ro:"ya",meaning:"already / now / okay",example:"Ya llegué — I already arrived",pos:"adverb",freq:10,register:"casual"},
  {kr:"todavía",ro:"todavía",meaning:"still / yet",example:"Todavía no termino — I haven't finished yet",pos:"adverb",freq:7,register:"neutral"},
  {kr:"tarde",ro:"tarde",meaning:"late / afternoon",example:"Es tarde — It's late",pos:"adverb",freq:8,register:"neutral"},
  {kr:"temprano",ro:"temprano",meaning:"early",example:"Llegó temprano — She arrived early",pos:"adverb",freq:7,register:"neutral"},
  {kr:"tiempo",ro:"tiempo",meaning:"time / weather",example:"No tengo tiempo — I don't have time",pos:"noun",freq:9,register:"neutral"},
  {kr:"hora",ro:"hora",meaning:"hour / time (clock)",example:"¿Qué hora es? — What time is it?",pos:"noun",freq:9,register:"neutral"},
  {kr:"día",ro:"día",meaning:"day",example:"Un buen día — A good day",pos:"noun",freq:10,register:"neutral"},
  {kr:"semana",ro:"semana",meaning:"week",example:"Esta semana — This week",pos:"noun",freq:8,register:"neutral"},
  {kr:"mes",ro:"mes",meaning:"month",example:"El mes que viene — Next month",pos:"noun",freq:8,register:"neutral"},
  {kr:"año",ro:"año",meaning:"year",example:"Este año — This year",pos:"noun",freq:8,register:"neutral"},

  // ── QUESTION WORDS ────────────────────────────────────────────────────────
  {kr:"¿qué?",ro:"¿qué?",meaning:"what?",example:"¿Qué quieres? — What do you want?",pos:"pronoun",freq:10,register:"neutral"},
  {kr:"¿quién?",ro:"¿quién?",meaning:"who?",example:"¿Quién es ella? — Who is she?",pos:"pronoun",freq:9,register:"neutral"},
  {kr:"¿dónde?",ro:"¿dónde?",meaning:"where?",example:"¿Dónde vives? — Where do you live?",pos:"adverb",freq:10,register:"neutral"},
  {kr:"¿cuándo?",ro:"¿cuándo?",meaning:"when?",example:"¿Cuándo llegas? — When do you arrive?",pos:"adverb",freq:9,register:"neutral"},
  {kr:"¿por qué?",ro:"¿por qué?",meaning:"why?",example:"¿Por qué no viniste? — Why didn't you come?",pos:"adverb",freq:9,register:"neutral"},
  {kr:"¿cómo?",ro:"¿cómo?",meaning:"how?",example:"¿Cómo lo hiciste? — How did you do it?",pos:"adverb",freq:10,register:"neutral"},
  {kr:"¿cuánto?",ro:"¿cuánto?",meaning:"how much?",example:"¿Cuánto cuesta? — How much does it cost?",pos:"adjective",freq:9,register:"neutral"},
  {kr:"¿cuál?",ro:"¿cuál?",meaning:"which? / what?",example:"¿Cuál prefieres? — Which do you prefer?",pos:"pronoun",freq:8,register:"neutral"},

  // ── CONNECTORS ────────────────────────────────────────────────────────────
  {kr:"y",ro:"y",meaning:"and",example:"Café y leche — Coffee and milk",pos:"adverb",freq:10,register:"neutral"},
  {kr:"o",ro:"o",meaning:"or",example:"¿Café o té? — Coffee or tea?",pos:"adverb",freq:9,register:"neutral"},
  {kr:"pero",ro:"pero",meaning:"but",example:"Me gusta, pero es caro — I like it, but it's expensive",pos:"adverb",freq:10,register:"neutral"},
  {kr:"porque",ro:"porque",meaning:"because",example:"No fui porque estaba enfermo — I didn't go because I was sick",pos:"adverb",freq:9,register:"neutral"},
  {kr:"que",ro:"que",meaning:"that / which / than",example:"Creo que sí — I think so",pos:"adverb",freq:10,register:"neutral"},
  {kr:"si",ro:"si",meaning:"if",example:"Si quieres, vamos — If you want, let's go",pos:"adverb",freq:9,register:"neutral"},
  {kr:"también",ro:"también",meaning:"also / too",example:"Yo también — Me too",pos:"adverb",freq:9,register:"neutral"},
  {kr:"tampoco",ro:"tampoco",meaning:"neither / not either",example:"Yo tampoco — Me neither",pos:"adverb",freq:7,register:"neutral"},
  {kr:"solo",ro:"solo",meaning:"only / alone / just",example:"Solo quiero agua — I just want water",pos:"adverb",freq:9,register:"neutral"},
  {kr:"muy",ro:"muy",meaning:"very",example:"Estoy muy cansado — I'm very tired",pos:"adverb",freq:10,register:"neutral"},
  {kr:"mucho",ro:"mucho",meaning:"a lot / much / very",example:"Te quiero mucho — I love you a lot",pos:"adverb",freq:10,register:"neutral"},
  {kr:"poco",ro:"poco",meaning:"a little / few",example:"Habla un poco — Speak a little",pos:"adverb",freq:8,register:"neutral"},
  {kr:"más",ro:"más",meaning:"more",example:"Quiero más — I want more",pos:"adverb",freq:10,register:"neutral"},
  {kr:"menos",ro:"menos",meaning:"less / fewer",example:"Menos sal, por favor — Less salt, please",pos:"adverb",freq:8,register:"neutral"},
  {kr:"ya",ro:"ya",meaning:"already / now",example:"Ya terminé — I already finished",pos:"adverb",freq:9,register:"neutral"},
  {kr:"todavía no",ro:"todavía no",meaning:"not yet",example:"Todavía no llega — She hasn't arrived yet",pos:"adverb",freq:7,register:"neutral"},
  {kr:"claro",ro:"claro",meaning:"of course / clear / sure",example:"¡Claro que sí! — Of course!",pos:"adverb",freq:9,register:"neutral"},
  {kr:"quizás",ro:"quizás",meaning:"maybe / perhaps",example:"Quizás mañana — Maybe tomorrow",pos:"adverb",freq:7,register:"neutral"},
  {kr:"tal vez",ro:"tal vez",meaning:"maybe / perhaps",example:"Tal vez vengo — Maybe I'll come",pos:"adverb",freq:7,register:"neutral"},
  {kr:"aquí",ro:"aquí",meaning:"here",example:"Estoy aquí — I'm here",pos:"adverb",freq:10,register:"neutral"},
  {kr:"allí / allá",ro:"allí / allá",meaning:"there",example:"Está allá — It's over there",pos:"adverb",freq:8,register:"neutral"},
  {kr:"cerca",ro:"cerca",meaning:"nearby / close",example:"Está cerca — It's nearby",pos:"adverb",freq:8,register:"neutral"},
  {kr:"lejos",ro:"lejos",meaning:"far",example:"¿Está lejos? — Is it far?",pos:"adverb",freq:7,register:"neutral"},

  // ── BODY & HEALTH ─────────────────────────────────────────────────────────
  {kr:"cabeza",ro:"cabeza",meaning:"head",example:"Me duele la cabeza — My head hurts",pos:"noun",freq:8,register:"neutral"},
  {kr:"pelo",ro:"pelo",meaning:"hair",example:"Tiene el pelo largo — She has long hair",pos:"noun",freq:7,register:"neutral"},
  {kr:"cara",ro:"cara",meaning:"face",example:"Tienes una cara bonita — You have a pretty face",pos:"noun",freq:7,register:"neutral"},
  {kr:"ojo",ro:"ojo",meaning:"eye",example:"Tiene los ojos verdes — She has green eyes",pos:"noun",freq:8,register:"neutral"},
  {kr:"nariz",ro:"nariz",meaning:"nose",example:"Me sangra la nariz — My nose is bleeding",pos:"noun",freq:6,register:"neutral"},
  {kr:"boca",ro:"boca",meaning:"mouth",example:"Abre la boca — Open your mouth",pos:"noun",freq:7,register:"neutral"},
  {kr:"mano",ro:"mano",meaning:"hand",example:"Dame la mano — Give me your hand",pos:"noun",freq:8,register:"neutral"},
  {kr:"pie",ro:"pie",meaning:"foot",example:"Me duele el pie — My foot hurts",pos:"noun",freq:7,register:"neutral"},
  {kr:"espalda",ro:"espalda",meaning:"back",example:"Me duele la espalda — My back hurts",pos:"noun",freq:7,register:"neutral"},
  {kr:"estómago",ro:"estómago",meaning:"stomach",example:"Me duele el estómago — My stomach hurts",pos:"noun",freq:7,register:"neutral"},
  {kr:"corazón",ro:"corazón",meaning:"heart",example:"Mi corazón late rápido — My heart beats fast",pos:"noun",freq:7,register:"neutral"},
  {kr:"enfermo",ro:"enfermo",meaning:"sick / ill",example:"Estoy enfermo — I am sick",pos:"adjective",freq:7,register:"neutral"},
  {kr:"medicina",ro:"medicina",meaning:"medicine",example:"Toma tu medicina — Take your medicine",pos:"noun",freq:7,register:"neutral"},
  {kr:"médico",ro:"médico",meaning:"doctor",example:"El médico llegó — The doctor arrived",pos:"noun",freq:7,register:"neutral"},
  {kr:"dolor",ro:"dolor",meaning:"pain / ache",example:"Tengo un dolor de cabeza — I have a headache",pos:"noun",freq:7,register:"neutral"},
  {kr:"fiebre",ro:"fiebre",meaning:"fever",example:"Tengo fiebre — I have a fever",pos:"noun",freq:6,register:"neutral"},
  {kr:"gripa",ro:"gripa",meaning:"cold / flu (Mexico/Venezuela)",example:"Agarré la gripa — I caught a cold",pos:"noun",freq:6,register:"casual"},
  {kr:"alergia",ro:"alergia",meaning:"allergy",example:"Tengo alergia al polvo — I have a dust allergy",pos:"noun",freq:5,register:"neutral"},

  // ── WORK & SCHOOL ─────────────────────────────────────────────────────────
  {kr:"trabajo",ro:"trabajo",meaning:"work / job",example:"Busco trabajo — I'm looking for work",pos:"noun",freq:9,register:"neutral"},
  {kr:"jefe",ro:"jefe",meaning:"boss / chief",example:"Mi jefa es muy exigente — My boss is very demanding",pos:"noun",freq:7,register:"neutral"},
  {kr:"compañero",ro:"compañero",meaning:"colleague / classmate",example:"Mi compañero de trabajo — My work colleague",pos:"noun",freq:6,register:"neutral"},
  {kr:"reunión",ro:"reunión",meaning:"meeting",example:"Tengo una reunión — I have a meeting",pos:"noun",freq:6,register:"formal"},
  {kr:"sueldo",ro:"sueldo",meaning:"salary",example:"El sueldo es bajo — The salary is low",pos:"noun",freq:6,register:"neutral"},
  {kr:"negocio",ro:"negocio",meaning:"business",example:"Tengo un negocio propio — I have my own business",pos:"noun",freq:6,register:"neutral"},
  {kr:"estudiante",ro:"estudiante",meaning:"student",example:"Soy estudiante de medicina — I'm a medical student",pos:"noun",freq:8,register:"neutral"},
  {kr:"maestro",ro:"maestro",meaning:"teacher (Mexico)",example:"El maestro es muy bueno — The teacher is very good",pos:"noun",freq:7,register:"neutral"},
  {kr:"profesor",ro:"profesor",meaning:"professor / teacher",example:"La profesora explica muy bien — The professor explains very well",pos:"noun",freq:7,register:"neutral"},
  {kr:"tarea",ro:"tarea",meaning:"homework / task",example:"Tengo mucha tarea — I have a lot of homework",pos:"noun",freq:7,register:"neutral"},
  {kr:"examen",ro:"examen",meaning:"exam / test",example:"Mañana tengo examen — Tomorrow I have an exam",pos:"noun",freq:7,register:"neutral"},
  {kr:"materia",ro:"materia",meaning:"subject / course",example:"Mi materia favorita — My favorite subject",pos:"noun",freq:6,register:"neutral"},
  {kr:"calificación",ro:"calificación",meaning:"grade / score",example:"Saqué buena calificación — I got a good grade",pos:"noun",freq:5,register:"neutral"},

  // ── TECHNOLOGY ────────────────────────────────────────────────────────────
  {kr:"teléfono",ro:"teléfono",meaning:"phone",example:"¿Me prestas tu teléfono? — Can I borrow your phone?",pos:"noun",freq:9,register:"neutral"},
  {kr:"celular",ro:"celular",meaning:"cell phone (Latin American)",example:"Se me olvidó el celular — I forgot my cell phone",pos:"noun",freq:9,register:"casual"},
  {kr:"computadora",ro:"computadora",meaning:"computer (Mexico/LatAm)",example:"Mi computadora se apagó — My computer turned off",pos:"noun",freq:8,register:"neutral"},
  {kr:"internet",ro:"internet",meaning:"internet",example:"No hay internet — There's no internet",pos:"noun",freq:8,register:"neutral"},
  {kr:"mensaje",ro:"mensaje",meaning:"message",example:"Te mando un mensaje — I'll send you a message",pos:"noun",freq:8,register:"neutral"},
  {kr:"foto",ro:"foto",meaning:"photo",example:"¿Me sacas una foto? — Can you take my photo?",pos:"noun",freq:7,register:"casual"},
  {kr:"red social",ro:"red social",meaning:"social media / social network",example:"Lo vi en las redes sociales — I saw it on social media",pos:"noun",freq:6,register:"neutral"},
  {kr:"contraseña",ro:"contraseña",meaning:"password",example:"Olvidé mi contraseña — I forgot my password",pos:"noun",freq:5,register:"neutral"},

  // ── NATURE & WEATHER ──────────────────────────────────────────────────────
  {kr:"clima",ro:"clima",meaning:"weather / climate",example:"El clima aquí es agradable — The weather here is pleasant",pos:"noun",freq:7,register:"neutral"},
  {kr:"sol",ro:"sol",meaning:"sun",example:"Hace mucho sol — It's very sunny",pos:"noun",freq:8,register:"neutral"},
  {kr:"lluvia",ro:"lluvia",meaning:"rain",example:"Viene la lluvia — The rain is coming",pos:"noun",freq:7,register:"neutral"},
  {kr:"nube",ro:"nube",meaning:"cloud",example:"El cielo está nublado — The sky is cloudy",pos:"noun",freq:6,register:"neutral"},
  {kr:"viento",ro:"viento",meaning:"wind",example:"Hay mucho viento — It's very windy",pos:"noun",freq:6,register:"neutral"},
  {kr:"calor",ro:"calor",meaning:"heat / hot weather",example:"¡Qué calor! — It's so hot!",pos:"noun",freq:8,register:"neutral"},
  {kr:"frío",ro:"frío",meaning:"cold / cold weather",example:"Tengo frío — I'm cold",pos:"noun",freq:8,register:"neutral"},
  {kr:"río",ro:"río",meaning:"river",example:"El río está crecido — The river is high",pos:"noun",freq:6,register:"neutral"},
  {kr:"árbol",ro:"árbol",meaning:"tree",example:"Un árbol de mango — A mango tree",pos:"noun",freq:6,register:"neutral"},
  {kr:"flor",ro:"flor",meaning:"flower",example:"Las flores son bonitas — The flowers are pretty",pos:"noun",freq:6,register:"neutral"},

  // ── HOBBIES & ENTERTAINMENT ───────────────────────────────────────────────
  {kr:"música",ro:"música",meaning:"music",example:"Me encanta la música — I love music",pos:"noun",freq:8,register:"neutral"},
  {kr:"película",ro:"película",meaning:"movie / film",example:"¿Vemos una película? — Shall we watch a movie?",pos:"noun",freq:8,register:"neutral"},
  {kr:"serie",ro:"serie",meaning:"TV series",example:"Estoy viendo una serie — I'm watching a series",pos:"noun",freq:7,register:"casual"},
  {kr:"libro",ro:"libro",meaning:"book",example:"Leo un libro — I'm reading a book",pos:"noun",freq:8,register:"neutral"},
  {kr:"fútbol",ro:"fútbol",meaning:"soccer / football",example:"Jugamos fútbol — We play soccer",pos:"noun",freq:8,register:"neutral"},
  {kr:"viaje",ro:"viaje",meaning:"trip / travel",example:"Me gusta viajar — I like to travel",pos:"noun",freq:7,register:"neutral"},
  {kr:"fiesta",ro:"fiesta",meaning:"party / celebration",example:"Hay una fiesta esta noche — There's a party tonight",pos:"noun",freq:7,register:"casual"},
  {kr:"baile",ro:"baile",meaning:"dance",example:"El baile es parte de nuestra cultura — Dance is part of our culture",pos:"noun",freq:6,register:"neutral"},
  {kr:"cocina",ro:"cocina",meaning:"cooking / cuisine",example:"La cocina mexicana es increíble — Mexican cuisine is incredible",pos:"noun",freq:6,register:"neutral"},

  // ── COLORS ───────────────────────────────────────────────────────────────
  {kr:"rojo",ro:"rojo",meaning:"red",example:"Una rosa roja — A red rose",pos:"adjective",freq:7,register:"neutral"},
  {kr:"azul",ro:"azul",meaning:"blue",example:"El cielo azul — The blue sky",pos:"adjective",freq:7,register:"neutral"},
  {kr:"verde",ro:"verde",meaning:"green",example:"Los árboles son verdes — The trees are green",pos:"adjective",freq:7,register:"neutral"},
  {kr:"amarillo",ro:"amarillo",meaning:"yellow",example:"Un taxi amarillo — A yellow taxi",pos:"adjective",freq:7,register:"neutral"},
  {kr:"negro",ro:"negro",meaning:"black",example:"Un gato negro — A black cat",pos:"adjective",freq:7,register:"neutral"},
  {kr:"blanco",ro:"blanco",meaning:"white",example:"Una camisa blanca — A white shirt",pos:"adjective",freq:7,register:"neutral"},
  {kr:"gris",ro:"gris",meaning:"grey",example:"Un día gris — A grey day",pos:"adjective",freq:6,register:"neutral"},
  {kr:"morado",ro:"morado",meaning:"purple",example:"Las flores moradas — The purple flowers",pos:"adjective",freq:5,register:"neutral"},
  {kr:"rosado",ro:"rosado",meaning:"pink",example:"Un vestido rosado — A pink dress",pos:"adjective",freq:5,register:"neutral"},
  {kr:"naranja",ro:"naranja",meaning:"orange",example:"El color naranja — The color orange",pos:"adjective",freq:5,register:"neutral"},
  {kr:"café",ro:"café",meaning:"brown (Mexico/LatAm)",example:"Ojos café — Brown eyes",pos:"adjective",freq:5,register:"neutral"},

];

// ── SPANISH GRAMMAR NOTES ─────────────────────────────────────────────────────
(function() {
  if (typeof GRAMMAR === 'undefined') return;
  if (!GRAMMAR.spanish) GRAMMAR.spanish = [];

  GRAMMAR.spanish.push(
    {
      title: 'Ser vs Estar — two verbs for "to be"',
      short: 'Ser is for permanent things. Estar is for temporary things and location.',
      body: 'This is the first wall English speakers hit in Spanish. "To be" is one verb in English but two in Spanish.\n\nSer — permanent or defining:\n  Soy mexicana — I am Mexican\n  Es médico — He is a doctor\n  La casa es grande — The house is big\n  Son las tres — It\'s three o\'clock\n\nEstar — temporary state or location:\n  Estoy cansada — I\'m tired\n  El restaurante está cerrado — The restaurant is closed\n  ¿Dónde está el baño? — Where is the bathroom?\n  Estoy en casa — I\'m at home\n\nThe classic trick: ser for who/what something IS, estar for how it IS right now or WHERE it is.',
      example: 'Soy aburrido — I am a boring person (this is my personality)\nEstoy aburrido — I am bored (right now, in this moment)\n\nLa sopa es caliente — Soup is hot (hot soup, by nature)\nLa sopa está caliente — The soup is hot (right now, this bowl)',
      level: 1
    },
    {
      title: 'Tener hambre — Spanish uses "have" where English uses "be"',
      short: 'Many physical states use tener (to have) where English uses to be.',
      body: 'One of the trickiest early patterns: in Spanish you "have" hunger, cold, heat, fear, etc. You don\'t "be" those things.\n\nTener + noun:\n  Tengo hambre — I\'m hungry (I have hunger)\n  Tengo sed — I\'m thirsty (I have thirst)\n  Tengo frío — I\'m cold (I have cold)\n  Tengo calor — I\'m hot (I have heat)\n  Tengo miedo — I\'m scared (I have fear)\n  Tengo sueño — I\'m sleepy (I have sleepiness)\n  Tengo prisa — I\'m in a hurry (I have hurry)\n  Tengo razón — I\'m right (I have reason)\n\nAlso age:\n  Tengo veinte años — I\'m twenty years old (I have twenty years)',
      example: '¿Tienes hambre? — Are you hungry?\nSí, tengo mucha hambre — Yes, I\'m very hungry\n\nTenemos frío — We\'re cold\nEl niño tiene miedo — The child is scared',
      level: 1
    },
    {
      title: 'Gustar works backwards — the thing you like is the subject',
      short: 'Me gusta el café means "coffee pleases me" not "I like coffee."',
      body: 'Gustar doesn\'t mean "to like." It means "to please" — and the thing you like is the subject of the sentence, not you.\n\nThis flips the sentence structure:\n  Me gusta el café — Coffee pleases me (I like coffee)\n  Me gustan los tacos — Tacos please me (I like tacos)\n\nNotice:\n  gusta — singular (one thing pleases me)\n  gustan — plural (multiple things please me)\n\nThe pronouns:\n  Me gusta — I like it\n  Te gusta — You like it\n  Le gusta — He/she/you (formal) likes it\n  Nos gusta — We like it\n  Les gusta — They/you all like it\n\nEncantar works the same way but stronger:\n  Me encanta la música — I love music',
      example: 'Me gusta el café. — I like coffee. (coffee pleases me)\nMe gustan los libros. — I like books. (books please me)\nLe gusta bailar. — She likes to dance.\n¿Te gusta el fútbol? — Do you like soccer?',
      level: 1
    },
    {
      title: 'Ahorita — the most context-dependent word in Mexican Spanish',
      short: 'Ahorita can mean right now, in a bit, or later — tone decides which.',
      body: 'Ahorita is one of the first things that confuses Spanish learners in Mexico. It looks like it should mean "right now" but it can mean three very different things depending on tone, context, and who\'s speaking.\n\nAhorita mismo — truly right now, immediately\n¡Ahorita mismo! — Right now! (this second)\n\nAhorita — in a little while (vague, could be 5 minutes or 2 hours)\n"Ahorita vengo" at a restaurant = I\'ll be right with you (but don\'t time it)\n\nAhorita — later, eventually (dismissive or relaxed)\n"Ahorita lo hago" from a procrastinator = I\'ll do it... at some point\n\nVenezuela uses "ahoritica" (even more diminutive) with similar flexibility.\n\nThe safest rule: ahorita = soon-ish. When you need an exact time, ask for one.',
      example: 'Mexico City taquero: "Ahorita te atiendo" — I\'ll help you in a moment\nMexican mom: "Ahorita lo limpio" — I\'ll clean it later (could be tomorrow)\n"¡Ahorita mismo vengo!" — I\'m coming right now (immediately)',
      level: 1
    },
    {
      title: 'Por qué vs porque vs por qué vs porqué',
      short: 'Four words that look almost identical mean completely different things.',
      body: 'This trips up even native speakers in writing.\n\n¿Por qué? — why? (question, two words, accent on the é)\n¿Por qué no vienes? — Why aren\'t you coming?\n\nporque — because (answer, one word, no accent)\nNo voy porque estoy cansado — I\'m not going because I\'m tired\n\npor qué — the "why" inside a sentence, no question mark\nNo entiendo por qué — I don\'t understand why\n\nel porqué — the reason (noun)\nQuiero saber el porqué — I want to know the reason\n\nA simple rule that covers 95% of use:\n  Question mark coming? → ¿Por qué?\n  Answering why? → porque',
      example: '¿Por qué lloras? — Why are you crying?\nLloro porque estoy feliz — I\'m crying because I\'m happy\n\nNo sé por qué me siento así — I don\'t know why I feel this way\nEl porqué de todo — The reason for everything',
      level: 2
    }
  );
})();

// Append to SPANISH_WORDS if it exists from other files
if (typeof window !== 'undefined') window.SPANISH_WORDS = SPANISH_WORDS;
