// ── DATA4.JS — Korean & Italian expansion to match Japanese word count ─────────

// ── KOREAN EXPANSION ──────────────────────────────────────────────────────────
const KOREAN_WORDS_4 = [
  // Body & Health
  {kr:"머리",ro:"meori",meaning:"head / hair",example:"머리가 아파요 — meori ga apayo — I have a headache",pos:"noun",freq:9,register:"neutral"},
  {kr:"얼굴",ro:"eolgul",meaning:"face",example:"얼굴이 예뻐요 — eolguli yeppeoyo — your face is pretty",pos:"noun",freq:9,register:"neutral"},
  {kr:"손",ro:"son",meaning:"hand",example:"손을 씻어요 — soneul ssiseoyo — wash your hands",pos:"noun",freq:10,register:"neutral"},
  {kr:"발",ro:"bal",meaning:"foot / feet",example:"발이 아파요 — bari apayo — my feet hurt",pos:"noun",freq:9,register:"neutral"},
  {kr:"입",ro:"ip",meaning:"mouth",example:"입을 열어요 — ibeul yeoreoyo — open your mouth",pos:"noun",freq:9,register:"neutral"},
  {kr:"코",ro:"ko",meaning:"nose",example:"코가 막혔어요 — koga makyeosseoyo — my nose is blocked",pos:"noun",freq:8,register:"neutral"},
  {kr:"귀",ro:"gwi",meaning:"ear",example:"귀가 아파요 — gwiga apayo — my ear hurts",pos:"noun",freq:8,register:"neutral"},
  {kr:"이",ro:"i",meaning:"tooth / teeth",example:"이를 닦아요 — ireul dakkayo — brush your teeth",pos:"noun",freq:8,register:"neutral"},
  {kr:"배",ro:"bae",meaning:"stomach / belly",example:"배가 고파요 — baega gopayo — I'm hungry",pos:"noun",freq:9,register:"neutral"},
  {kr:"등",ro:"deung",meaning:"back",example:"등이 아파요 — deungi apayo — my back hurts",pos:"noun",freq:8,register:"neutral"},
  {kr:"목",ro:"mok",meaning:"neck / throat",example:"목이 아파요 — mogi apayo — my throat hurts",pos:"noun",freq:8,register:"neutral"},
  {kr:"가슴",ro:"gaseum",meaning:"chest / heart (emotional)",example:"가슴이 두근거려요 — gaseumi dugeungeoryeoyo — my heart is pounding",pos:"noun",freq:8,register:"neutral"},
  {kr:"다리",ro:"dari",meaning:"leg",example:"다리가 길어요 — dariga gireoyo — legs are long",pos:"noun",freq:8,register:"neutral"},
  {kr:"팔",ro:"pal",meaning:"arm",example:"팔을 들어요 — pareul deureoyo — raise your arm",pos:"noun",freq:8,register:"neutral"},
  {kr:"피부",ro:"pibu",meaning:"skin",example:"피부가 좋아요 — pibuga joayo — your skin is nice",pos:"noun",freq:7,register:"neutral"},
  {kr:"뼈",ro:"ppyeo",meaning:"bone",example:"뼈가 부러졌어요 — ppyeoga bureojyeosseoyo — the bone is broken",pos:"noun",freq:7,register:"neutral"},
  {kr:"피",ro:"pi",meaning:"blood",example:"피가 나요 — piga nayo — bleeding",pos:"noun",freq:7,register:"neutral"},
  {kr:"심장",ro:"simjang",meaning:"heart (organ)",example:"심장이 빨리 뛰어요 — simjangi ppalli ttwieyo — heart is beating fast",pos:"noun",freq:7,register:"neutral"},
  {kr:"뇌",ro:"noe",meaning:"brain",example:"뇌가 중요해요 — noega jungyohaeyo — the brain is important",pos:"noun",freq:7,register:"neutral"},
  {kr:"폐",ro:"pye",meaning:"lungs",example:"폐가 건강해요 — pyega geonganghaeyo — lungs are healthy",pos:"noun",freq:6,register:"neutral"},

  // Daily Actions
  {kr:"일어나다",ro:"ireonada",meaning:"to get up / to wake up",example:"아침에 일어나요 — achime ireonayo — I get up in the morning",pos:"verb",freq:9,register:"neutral"},
  {kr:"씻다",ro:"ssitda",meaning:"to wash",example:"손을 씻어요 — soneul ssiseoyo — wash hands",pos:"verb",freq:9,register:"neutral"},
  {kr:"입다",ro:"ipda",meaning:"to wear / to put on",example:"옷을 입어요 — oseul ibeoyo — put on clothes",pos:"verb",freq:9,register:"neutral"},
  {kr:"벗다",ro:"beotda",meaning:"to take off (clothes)",example:"신발을 벗어요 — sinbareul beoseoyo — take off shoes",pos:"verb",freq:8,register:"neutral"},
  {kr:"앉다",ro:"anda",meaning:"to sit",example:"의자에 앉아요 — uijae anjayo — sit on the chair",pos:"verb",freq:9,register:"neutral"},
  {kr:"서다",ro:"seoda",meaning:"to stand",example:"여기 서세요 — yeogi seoseyo — stand here",pos:"verb",freq:9,register:"neutral"},
  {kr:"걷다",ro:"geotda",meaning:"to walk",example:"공원을 걸어요 — gongwoneul georeoyo — walk in the park",pos:"verb",freq:9,register:"neutral"},
  {kr:"뛰다",ro:"ttwida",meaning:"to run / to jump",example:"빨리 뛰어요 — ppalli ttwieyo — run fast",pos:"verb",freq:8,register:"neutral"},
  {kr:"자다",ro:"jada",meaning:"to sleep",example:"일찍 자요 — iljjik jayo — sleep early",pos:"verb",freq:10,register:"neutral"},
  {kr:"요리하다",ro:"yorihada",meaning:"to cook",example:"저녁을 요리해요 — jeonyeogeul yorihaeyo — cook dinner",pos:"verb",freq:8,register:"neutral"},
  {kr:"청소하다",ro:"cheongsohada",meaning:"to clean",example:"방을 청소해요 — bangeul cheongsohaeyo — clean the room",pos:"verb",freq:8,register:"neutral"},
  {kr:"빨다",ro:"ppalda",meaning:"to wash (laundry)",example:"빨래를 해요 — ppallaereul haeyo — do laundry",pos:"verb",freq:7,register:"neutral"},
  {kr:"닦다",ro:"dakkda",meaning:"to wipe / to polish",example:"이를 닦아요 — ireul dakkayo — brush teeth",pos:"verb",freq:8,register:"neutral"},
  {kr:"켜다",ro:"kyeoda",meaning:"to turn on",example:"불을 켜요 — bureul kyeoyo — turn on the light",pos:"verb",freq:8,register:"neutral"},
  {kr:"끄다",ro:"kkeuda",meaning:"to turn off",example:"TV를 꺼요 — TV reul kkeoyo — turn off the TV",pos:"verb",freq:8,register:"neutral"},
  {kr:"열다",ro:"yeolda",meaning:"to open",example:"창문을 열어요 — changmuneul yeoreoyo — open the window",pos:"verb",freq:9,register:"neutral"},
  {kr:"닫다",ro:"datda",meaning:"to close",example:"문을 닫아요 — muneul dadayo — close the door",pos:"verb",freq:9,register:"neutral"},
  {kr:"잠그다",ro:"jamgeuda",meaning:"to lock",example:"문을 잠가요 — muneul jamgayo — lock the door",pos:"verb",freq:7,register:"neutral"},
  {kr:"찾다",ro:"chatda",meaning:"to look for / to find",example:"열쇠를 찾아요 — yeolsoereul chajayo — looking for keys",pos:"verb",freq:9,register:"neutral"},
  {kr:"버리다",ro:"beorida",meaning:"to throw away",example:"쓰레기를 버려요 — sseureagireul beoryeoyo — throw away trash",pos:"verb",freq:8,register:"neutral"},

  // Food & Drink
  {kr:"밥",ro:"bap",meaning:"rice / meal",example:"밥을 먹어요 — babeul meogeoyo — eat rice",pos:"noun",freq:10,register:"neutral"},
  {kr:"국",ro:"guk",meaning:"soup",example:"국이 뜨거워요 — gugi ddeugeowo yo — the soup is hot",pos:"noun",freq:9,register:"neutral"},
  {kr:"김치",ro:"gimchi",meaning:"kimchi",example:"김치가 매워요 — gimchiga maewoyo — kimchi is spicy",pos:"noun",freq:9,register:"neutral"},
  {kr:"고기",ro:"gogi",meaning:"meat",example:"고기를 구워요 — gogireul guwoyo — grill meat",pos:"noun",freq:9,register:"neutral"},
  {kr:"생선",ro:"saengseon",meaning:"fish",example:"생선이 신선해요 — saengseoni sinseonnhaeyo — the fish is fresh",pos:"noun",freq:8,register:"neutral"},
  {kr:"채소",ro:"chaeso",meaning:"vegetables",example:"채소를 많이 먹어요 — chaesoReul mani meogeoyo — eat lots of vegetables",pos:"noun",freq:8,register:"neutral"},
  {kr:"과일",ro:"gwail",meaning:"fruit",example:"과일이 달아요 — gwailI darayo — the fruit is sweet",pos:"noun",freq:8,register:"neutral"},
  {kr:"빵",ro:"ppang",meaning:"bread",example:"빵을 먹어요 — ppangeul meogeoyo — eat bread",pos:"noun",freq:8,register:"neutral"},
  {kr:"달걀",ro:"dalgyal",meaning:"egg",example:"달걀을 삶아요 — dalgyareul salmayo — boil eggs",pos:"noun",freq:8,register:"neutral"},
  {kr:"우유",ro:"uyu",meaning:"milk",example:"우유를 마셔요 — uyureul masyeoyo — drink milk",pos:"noun",freq:8,register:"neutral"},
  {kr:"물",ro:"mul",meaning:"water",example:"물을 마셔요 — mureul masyeoyo — drink water",pos:"noun",freq:10,register:"neutral"},
  {kr:"커피",ro:"keopi",meaning:"coffee",example:"커피를 마셔요 — keopireul masyeoyo — drink coffee",pos:"noun",freq:9,register:"neutral"},
  {kr:"차",ro:"cha",meaning:"tea",example:"차를 마셔요 — chareul masyeoyo — drink tea",pos:"noun",freq:8,register:"neutral"},
  {kr:"주스",ro:"juseu",meaning:"juice",example:"오렌지 주스 — orenji juseu — orange juice",pos:"noun",freq:7,register:"neutral"},
  {kr:"술",ro:"sul",meaning:"alcohol / drink",example:"술을 마셔요 — sureul masyeoyo — drink alcohol",pos:"noun",freq:8,register:"casual"},
  {kr:"맥주",ro:"maekju",meaning:"beer",example:"맥주 한 잔 — maekju han jan — one glass of beer",pos:"noun",freq:7,register:"casual"},
  {kr:"소주",ro:"soju",meaning:"soju",example:"소주를 마셔요 — sojureul masyeoyo — drink soju",pos:"noun",freq:7,register:"casual"},
  {kr:"라면",ro:"ramyeon",meaning:"ramen / instant noodles",example:"라면을 끓여요 — ramyeoneul kkeeuryeoyo — boil ramen",pos:"noun",freq:8,register:"casual"},
  {kr:"떡",ro:"tteok",meaning:"rice cake",example:"떡이 맛있어요 — tteogi massisseoyo — rice cake is delicious",pos:"noun",freq:7,register:"neutral"},
  {kr:"과자",ro:"gwaja",meaning:"snack / crackers",example:"과자를 먹어요 — gwajareul meogeoyo — eat snacks",pos:"noun",freq:7,register:"casual"},

  // Home & Objects
  {kr:"집",ro:"jip",meaning:"house / home",example:"집에 가요 — jibe gayo — go home",pos:"noun",freq:10,register:"neutral"},
  {kr:"방",ro:"bang",meaning:"room",example:"방이 깨끗해요 — bangi kkaekkeuseohaeyo — the room is clean",pos:"noun",freq:9,register:"neutral"},
  {kr:"부엌",ro:"bueok",meaning:"kitchen",example:"부엌에서 요리해요 — bueokeseo yorihaeyo — cook in the kitchen",pos:"noun",freq:8,register:"neutral"},
  {kr:"욕실",ro:"yoksil",meaning:"bathroom",example:"욕실이 커요 — yoksiri keoyo — the bathroom is big",pos:"noun",freq:8,register:"neutral"},
  {kr:"거실",ro:"geosil",meaning:"living room",example:"거실에서 쉬어요 — geosureseo swieoyo — rest in the living room",pos:"noun",freq:8,register:"neutral"},
  {kr:"침대",ro:"chimdae",meaning:"bed",example:"침대에서 자요 — chimdaeeseo jayo — sleep in bed",pos:"noun",freq:9,register:"neutral"},
  {kr:"소파",ro:"sopa",meaning:"sofa / couch",example:"소파에 앉아요 — sopaee anjayo — sit on the sofa",pos:"noun",freq:8,register:"neutral"},
  {kr:"책상",ro:"chaeksang",meaning:"desk",example:"책상에서 공부해요 — chaeksangeseo gongbuhaeyo — study at the desk",pos:"noun",freq:8,register:"neutral"},
  {kr:"의자",ro:"uija",meaning:"chair",example:"의자에 앉아요 — uijae anjayo — sit on the chair",pos:"noun",freq:9,register:"neutral"},
  {kr:"창문",ro:"changmun",meaning:"window",example:"창문을 열어요 — changmuneul yeoreoyo — open the window",pos:"noun",freq:8,register:"neutral"},
  {kr:"문",ro:"mun",meaning:"door",example:"문을 닫아요 — muneul dadayo — close the door",pos:"noun",freq:10,register:"neutral"},
  {kr:"계단",ro:"gyedan",meaning:"stairs",example:"계단을 올라요 — gyedaneul ollayo — go up the stairs",pos:"noun",freq:7,register:"neutral"},
  {kr:"엘리베이터",ro:"elribeiteo",meaning:"elevator",example:"엘리베이터를 타요 — elribeiteoreul tayo — take the elevator",pos:"noun",freq:7,register:"neutral"},
  {kr:"냉장고",ro:"naengjanggo",meaning:"refrigerator",example:"냉장고에 넣어요 — naengjanggoe neeoyo — put in the fridge",pos:"noun",freq:8,register:"neutral"},
  {kr:"전자레인지",ro:"jeonjareInji",meaning:"microwave",example:"전자레인지로 데워요 — jeonjareinjiro dewoyo — heat in the microwave",pos:"noun",freq:7,register:"neutral"},
  {kr:"세탁기",ro:"setakgi",meaning:"washing machine",example:"세탁기를 돌려요 — setakgireul dollyeoyo — run the washing machine",pos:"noun",freq:7,register:"neutral"},
  {kr:"청소기",ro:"cheongsogi",meaning:"vacuum cleaner",example:"청소기를 돌려요 — cheongsogireul dollyeoyo — vacuum",pos:"noun",freq:7,register:"neutral"},
  {kr:"수건",ro:"sugeon",meaning:"towel",example:"수건으로 닦아요 — sugeoneurro dakkayo — wipe with a towel",pos:"noun",freq:7,register:"neutral"},
  {kr:"베개",ro:"begae",meaning:"pillow",example:"베개가 편해요 — begaega pyeonhaeyo — the pillow is comfortable",pos:"noun",freq:7,register:"neutral"},
  {kr:"이불",ro:"ibul",meaning:"blanket / duvet",example:"이불을 덮어요 — ibureul deobeoyo — cover with a blanket",pos:"noun",freq:7,register:"neutral"},

  // Transport
  {kr:"버스",ro:"beoseu",meaning:"bus",example:"버스를 타요 — beoseureul tayo — take the bus",pos:"noun",freq:9,register:"neutral"},
  {kr:"지하철",ro:"jihacheol",meaning:"subway / metro",example:"지하철로 가요 — jihacheolro gayo — go by subway",pos:"noun",freq:9,register:"neutral"},
  {kr:"택시",ro:"taeksi",meaning:"taxi",example:"택시를 불러요 — taeksireul bulleoyo — call a taxi",pos:"noun",freq:8,register:"neutral"},
  {kr:"자동차",ro:"jadongcha",meaning:"car",example:"자동차로 가요 — jadongcharo gayo — go by car",pos:"noun",freq:9,register:"neutral"},
  {kr:"자전거",ro:"jajeongeo",meaning:"bicycle",example:"자전거를 타요 — jajeongoreul tayo — ride a bicycle",pos:"noun",freq:8,register:"neutral"},
  {kr:"오토바이",ro:"otobai",meaning:"motorcycle",example:"오토바이를 타요 — otobaireul tayo — ride a motorcycle",pos:"noun",freq:7,register:"neutral"},
  {kr:"기차",ro:"gicha",meaning:"train",example:"기차를 타요 — gichareul tayo — take the train",pos:"noun",freq:8,register:"neutral"},
  {kr:"비행기",ro:"bihaenggi",meaning:"airplane",example:"비행기를 타요 — bihaenggireul tayo — take a plane",pos:"noun",freq:8,register:"neutral"},
  {kr:"배",ro:"bae",meaning:"ship / boat",example:"배를 타요 — baereul tayo — take a boat",pos:"noun",freq:7,register:"neutral"},
  {kr:"역",ro:"yeok",meaning:"station",example:"역에서 만나요 — yeokeseo mannayo — meet at the station",pos:"noun",freq:9,register:"neutral"},
  {kr:"정류장",ro:"jeongnyujang",meaning:"bus stop",example:"정류장에서 기다려요 — jeongnyujangeseo gidaryeoyo — wait at the bus stop",pos:"noun",freq:7,register:"neutral"},
  {kr:"공항",ro:"gonghang",meaning:"airport",example:"공항에 가요 — gonghange gayo — go to the airport",pos:"noun",freq:8,register:"neutral"},
  {kr:"길",ro:"gil",meaning:"road / street / way",example:"길을 건너요 — gireul geonneoyo — cross the road",pos:"noun",freq:10,register:"neutral"},
  {kr:"교통",ro:"gyotong",meaning:"traffic / transportation",example:"교통이 막혀요 — gyotongi makyeoyo — traffic is jammed",pos:"noun",freq:8,register:"neutral"},
  {kr:"신호등",ro:"sinhodeung",meaning:"traffic light",example:"신호등이 빨개요 — sinhodeungi ppalgaeyo — traffic light is red",pos:"noun",freq:7,register:"neutral"},

  // School & Work
  {kr:"학교",ro:"hakgyo",meaning:"school",example:"학교에 가요 — hakgyoe gayo — go to school",pos:"noun",freq:10,register:"neutral"},
  {kr:"대학교",ro:"daehakgyo",meaning:"university",example:"대학교에 다녀요 — daehakgyoe danyeoyo — attend university",pos:"noun",freq:9,register:"neutral"},
  {kr:"선생님",ro:"seonsaengnim",meaning:"teacher",example:"선생님이 친절해요 — seonsaengnami chinjeolhaeyo — the teacher is kind",pos:"noun",freq:9,register:"formal"},
  {kr:"학생",ro:"haksaeng",meaning:"student",example:"저는 학생이에요 — jeoneun haksaengieyo — I am a student",pos:"noun",freq:10,register:"neutral"},
  {kr:"교실",ro:"gyosil",meaning:"classroom",example:"교실이 넓어요 — gyosili neolbeoyo — the classroom is wide",pos:"noun",freq:8,register:"neutral"},
  {kr:"칠판",ro:"chilpan",meaning:"blackboard / whiteboard",example:"칠판에 쓰세요 — chilpane sseuseyo — write on the board",pos:"noun",freq:7,register:"neutral"},
  {kr:"공부하다",ro:"gongbuhada",meaning:"to study",example:"열심히 공부해요 — yeolsimhi gongbuhaeyo — study hard",pos:"verb",freq:9,register:"neutral"},
  {kr:"숙제",ro:"sukje",meaning:"homework",example:"숙제를 해요 — sukjereul haeyo — do homework",pos:"noun",freq:8,register:"neutral"},
  {kr:"시험",ro:"siheom",meaning:"exam / test",example:"시험을 봐요 — siheomeul bwayo — take an exam",pos:"noun",freq:8,register:"neutral"},
  {kr:"성적",ro:"seongjeok",meaning:"grade / score",example:"성적이 좋아요 — seongjeoGI joayo — grades are good",pos:"noun",freq:7,register:"neutral"},
  {kr:"회사",ro:"hoesa",meaning:"company / workplace",example:"회사에 가요 — hoesae gayo — go to work",pos:"noun",freq:9,register:"neutral"},
  {kr:"직장",ro:"jikjang",meaning:"workplace / job",example:"직장이 좋아요 — jikjangi joayo — the job is good",pos:"noun",freq:8,register:"neutral"},
  {kr:"일하다",ro:"ilhada",meaning:"to work",example:"열심히 일해요 — yeolsimhi ilhaeyo — work hard",pos:"verb",freq:9,register:"neutral"},
  {kr:"월급",ro:"wolgeup",meaning:"salary / monthly pay",example:"월급이 올랐어요 — wolgeupi ollasseoyo — salary went up",pos:"noun",freq:7,register:"neutral"},
  {kr:"회의",ro:"hoeui",meaning:"meeting",example:"회의가 있어요 — hoeuiga isseoyo — there is a meeting",pos:"noun",freq:7,register:"formal"},
  {kr:"출근하다",ro:"chulgeunhada",meaning:"to go to work",example:"아침에 출근해요 — achime chulgeunhaeyo — go to work in the morning",pos:"verb",freq:8,register:"neutral"},
  {kr:"퇴근하다",ro:"toegeunhada",meaning:"to leave work",example:"여섯 시에 퇴근해요 — yeoseot sie toegeunhaeyo — leave work at six",pos:"verb",freq:8,register:"neutral"},
  {kr:"상사",ro:"sangsa",meaning:"boss / superior",example:"상사가 엄격해요 — sangsaga eomgyeokhaeyo — the boss is strict",pos:"noun",freq:7,register:"formal"},
  {kr:"동료",ro:"dongnyo",meaning:"colleague",example:"동료가 친절해요 — dongnyoga chinjeolhaeyo — colleagues are friendly",pos:"noun",freq:7,register:"neutral"},

  // Nature & Weather
  {kr:"날씨",ro:"nalsi",meaning:"weather",example:"날씨가 좋아요 — nalsiga joayo — the weather is nice",pos:"noun",freq:9,register:"neutral"},
  {kr:"하늘",ro:"haneul",meaning:"sky",example:"하늘이 맑아요 — haneuri malgayo — the sky is clear",pos:"noun",freq:9,register:"neutral"},
  {kr:"태양",ro:"taeyang",meaning:"sun",example:"태양이 밝아요 — taeyangI balkayo — the sun is bright",pos:"noun",freq:8,register:"neutral"},
  {kr:"달",ro:"dal",meaning:"moon",example:"달이 예뻐요 — dari yeppeoyo — the moon is beautiful",pos:"noun",freq:8,register:"neutral"},
  {kr:"별",ro:"byeol",meaning:"star",example:"별이 반짝여요 — byeori banjjakyeoyo — stars are twinkling",pos:"noun",freq:8,register:"neutral"},
  {kr:"구름",ro:"gureum",meaning:"cloud",example:"구름이 많아요 — gureumi manayo — there are many clouds",pos:"noun",freq:8,register:"neutral"},
  {kr:"비",ro:"bi",meaning:"rain",example:"비가 와요 — biga wayo — it's raining",pos:"noun",freq:9,register:"neutral"},
  {kr:"눈",ro:"nun",meaning:"snow",example:"눈이 내려요 — nuni naeryeoyo — snow is falling",pos:"noun",freq:8,register:"neutral"},
  {kr:"바람",ro:"baram",meaning:"wind",example:"바람이 강해요 — barami ganghaeyo — the wind is strong",pos:"noun",freq:8,register:"neutral"},
  {kr:"번개",ro:"beongae",meaning:"lightning",example:"번개가 쳤어요 — beongaega chyeosseoyo — lightning struck",pos:"noun",freq:6,register:"neutral"},
  {kr:"천둥",ro:"cheondung",meaning:"thunder",example:"천둥이 울려요 — cheondungi ullyeoyo — thunder rumbles",pos:"noun",freq:6,register:"neutral"},
  {kr:"안개",ro:"angae",meaning:"fog / mist",example:"안개가 끼었어요 — angaega kkieosseoyo — there is fog",pos:"noun",freq:6,register:"neutral"},
  {kr:"무지개",ro:"mujigae",meaning:"rainbow",example:"무지개가 떴어요 — mujigaega tteosseoyo — a rainbow appeared",pos:"noun",freq:6,register:"neutral"},
  {kr:"산",ro:"san",meaning:"mountain",example:"산에 올라요 — sane ollayo — climb the mountain",pos:"noun",freq:9,register:"neutral"},
  {kr:"강",ro:"gang",meaning:"river",example:"강이 흘러요 — gangi heulreoyo — the river flows",pos:"noun",freq:9,register:"neutral"},
  {kr:"바다",ro:"bada",meaning:"sea / ocean",example:"바다에 가고 싶어요 — badae gago sipeoyo — I want to go to the sea",pos:"noun",freq:9,register:"neutral"},
  {kr:"호수",ro:"hosu",meaning:"lake",example:"호수가 아름다워요 — hosuga areumtawoyo — the lake is beautiful",pos:"noun",freq:7,register:"neutral"},
  {kr:"숲",ro:"sup",meaning:"forest",example:"숲이 시원해요 — supi siwonhaeyo — the forest is cool",pos:"noun",freq:7,register:"neutral"},
  {kr:"꽃",ro:"kkot",meaning:"flower",example:"꽃이 피어요 — kkochi pieoyo — flowers bloom",pos:"noun",freq:8,register:"neutral"},
  {kr:"나무",ro:"namu",meaning:"tree",example:"나무가 커요 — namuga keoyo — the tree is big",pos:"noun",freq:9,register:"neutral"},

  // Emotions & Feelings
  {kr:"행복하다",ro:"haengbokhada",meaning:"to be happy",example:"지금 행복해요 — jigeum haengbokhaeyo — I am happy now",pos:"adjective",freq:9,register:"neutral"},
  {kr:"슬프다",ro:"seulpeuda",meaning:"to be sad",example:"너무 슬퍼요 — neomu seulpeoyo — I am very sad",pos:"adjective",freq:8,register:"neutral"},
  {kr:"화나다",ro:"hwanada",meaning:"to be angry",example:"화가 났어요 — hwaga nasseoyo — I got angry",pos:"adjective",freq:8,register:"neutral"},
  {kr:"무섭다",ro:"museopda",meaning:"to be scared",example:"너무 무서워요 — neomu museowo yo — I am very scared",pos:"adjective",freq:8,register:"neutral"},
  {kr:"부끄럽다",ro:"bukkeureupda",meaning:"to be embarrassed",example:"부끄러워요 — bukkeureowo yo — I am embarrassed",pos:"adjective",freq:7,register:"neutral"},
  {kr:"외롭다",ro:"oeropda",meaning:"to be lonely",example:"혼자라 외로워요 — honijara oerowoyo — I'm alone so I'm lonely",pos:"adjective",freq:7,register:"neutral"},
  {kr:"그립다",ro:"geuripda",meaning:"to miss / to long for",example:"보고 싶어요 그리워요 — bogo sipeoyo geuriwoyo — I miss you",pos:"adjective",freq:7,register:"neutral"},
  {kr:"긴장하다",ro:"ginjanghadA",meaning:"to be nervous / tense",example:"긴장돼요 — ginjangttwaeyo — I'm nervous",pos:"adjective",freq:7,register:"neutral"},
  {kr:"피곤하다",ro:"pigonhada",meaning:"to be tired",example:"너무 피곤해요 — neomu pigonhaeyo — I'm very tired",pos:"adjective",freq:9,register:"neutral"},
  {kr:"지루하다",ro:"jiruhada",meaning:"to be bored",example:"지루해요 — jiruhaeyo — I'm bored",pos:"adjective",freq:7,register:"casual"},
  {kr:"신나다",ro:"sinnada",meaning:"to be excited / thrilled",example:"너무 신나요 — neomu sinnayo — I'm so excited",pos:"adjective",freq:8,register:"casual"},
  {kr:"놀라다",ro:"nollada",meaning:"to be surprised",example:"깜짝 놀랐어요 — kkamjjak nollasseoyo — I was startled",pos:"verb",freq:8,register:"neutral"},
  {kr:"웃다",ro:"utda",meaning:"to laugh / to smile",example:"많이 웃어요 — mani useoyo — laugh a lot",pos:"verb",freq:9,register:"neutral"},
  {kr:"울다",ro:"ulda",meaning:"to cry",example:"영화를 보고 울었어요 — yeonghwareul bogo ureosseoyo — cried watching the movie",pos:"verb",freq:8,register:"neutral"},
  {kr:"걱정하다",ro:"geokjeonghada",meaning:"to worry",example:"걱정하지 마세요 — geokjeongaji maseyo — don't worry",pos:"verb",freq:8,register:"neutral"},

  // Personality & Description  
  {kr:"친절하다",ro:"chinjeolhada",meaning:"to be kind",example:"선생님이 친절해요 — seonsaengnami chinjeolhaeyo — the teacher is kind",pos:"adjective",freq:8,register:"neutral"},
  {kr:"착하다",ro:"chakada",meaning:"to be good-natured / nice",example:"그 사람은 착해요 — geu sarameun chakaeyo — that person is kind",pos:"adjective",freq:8,register:"neutral"},
  {kr:"똑똑하다",ro:"ttokttokada",meaning:"to be smart / clever",example:"매우 똑똑해요 — maeu ttokttokaeyo — very smart",pos:"adjective",freq:7,register:"neutral"},
  {kr:"게으르다",ro:"geeureuda",meaning:"to be lazy",example:"너무 게을러요 — neomu geeureoyo — too lazy",pos:"adjective",freq:6,register:"casual"},
  {kr:"부지런하다",ro:"bujireonhada",meaning:"to be diligent / hardworking",example:"매우 부지런해요 — maeu bujireonhaeyo — very hardworking",pos:"adjective",freq:7,register:"neutral"},
  {kr:"용감하다",ro:"yonggamhada",meaning:"to be brave",example:"용감한 사람이에요 — yonggaman saramieyo — a brave person",pos:"adjective",freq:7,register:"neutral"},
  {kr:"소심하다",ro:"sosimhada",meaning:"to be timid / shy",example:"좀 소심해요 — jom sosimhaeyo — a bit timid",pos:"adjective",freq:6,register:"neutral"},
  {kr:"활발하다",ro:"hwalbalhada",meaning:"to be lively / outgoing",example:"성격이 활발해요 — seongyeogi hwalbalHaeyo — personality is lively",pos:"adjective",freq:7,register:"neutral"},
  {kr:"조용하다",ro:"joyonghada",meaning:"to be quiet",example:"성격이 조용해요 — seongyeogi joyonghaeyo — personality is quiet",pos:"adjective",freq:7,register:"neutral"},
  {kr:"솔직하다",ro:"soljikada",meaning:"to be honest / frank",example:"솔직하게 말해요 — soljikage malhaeyo — speak frankly",pos:"adjective",freq:7,register:"neutral"},

  // Technology
  {kr:"핸드폰",ro:"haendeupon",meaning:"cell phone / mobile",example:"핸드폰이 없어요 — haendeuponi eopseoyo — no cell phone",pos:"noun",freq:9,register:"casual"},
  {kr:"스마트폰",ro:"seumateupon",meaning:"smartphone",example:"스마트폰을 써요 — seumateupo neul sseoyo — use a smartphone",pos:"noun",freq:9,register:"neutral"},
  {kr:"컴퓨터",ro:"keompyuteo",meaning:"computer",example:"컴퓨터로 일해요 — keompyuteoro ilhaeyo — work on a computer",pos:"noun",freq:9,register:"neutral"},
  {kr:"노트북",ro:"noteubuk",meaning:"laptop",example:"노트북을 가져왔어요 — noteubuguel gajyeowasseoyo — brought a laptop",pos:"noun",freq:8,register:"neutral"},
  {kr:"인터넷",ro:"inteonet",meaning:"internet",example:"인터넷이 빨라요 — inteoneti ppallayo — the internet is fast",pos:"noun",freq:9,register:"neutral"},
  {kr:"앱",ro:"aep",meaning:"app",example:"앱을 다운받아요 — aebeul daundadayo — download an app",pos:"noun",freq:8,register:"casual"},
  {kr:"사진",ro:"sajin",meaning:"photo / picture",example:"사진을 찍어요 — sajineul jjigeoyo — take a photo",pos:"noun",freq:9,register:"neutral"},
  {kr:"동영상",ro:"dongyeongsang",meaning:"video",example:"동영상을 봐요 — dongyeongsangeul bwayo — watch a video",pos:"noun",freq:8,register:"neutral"},
  {kr:"검색하다",ro:"geomsaekada",meaning:"to search",example:"인터넷에서 검색해요 — inteoneteseo geomsaekhaeyo — search on the internet",pos:"verb",freq:8,register:"neutral"},
  {kr:"다운로드",ro:"daunnodeu",meaning:"download",example:"파일을 다운받아요 — paireul daunopadayo — download a file",pos:"noun",freq:7,register:"neutral"},

  // Time expressions
  {kr:"지금",ro:"jigeum",meaning:"now",example:"지금 어디예요? — jigeum eodiyeyo? — where are you now?",pos:"adverb",freq:10,register:"neutral"},
  {kr:"오늘",ro:"oneul",meaning:"today",example:"오늘 뭐 해요? — oneul mwo haeyo? — what are you doing today?",pos:"noun",freq:10,register:"neutral"},
  {kr:"내일",ro:"naeil",meaning:"tomorrow",example:"내일 만나요 — naeil mannayo — see you tomorrow",pos:"noun",freq:10,register:"neutral"},
  {kr:"어제",ro:"eoje",meaning:"yesterday",example:"어제 뭐 했어요? — eoje mwo haesseoyo? — what did you do yesterday?",pos:"noun",freq:9,register:"neutral"},
  {kr:"아침",ro:"achim",meaning:"morning",example:"아침에 일어나요 — achime ireonayo — wake up in the morning",pos:"noun",freq:9,register:"neutral"},
  {kr:"점심",ro:"jeomsim",meaning:"lunch / noon",example:"점심 먹었어요? — jeomsim meogeosseoyo? — did you eat lunch?",pos:"noun",freq:9,register:"neutral"},
  {kr:"저녁",ro:"jeonyeok",meaning:"evening / dinner",example:"저녁에 만나요 — jeonyeoge mannayo — meet in the evening",pos:"noun",freq:9,register:"neutral"},
  {kr:"밤",ro:"bam",meaning:"night",example:"밤에 자요 — bame jayo — sleep at night",pos:"noun",freq:9,register:"neutral"},
  {kr:"주말",ro:"jumal",meaning:"weekend",example:"주말에 뭐 해요? — jUmale mwo haeyo? — what do you do on weekends?",pos:"noun",freq:9,register:"neutral"},
  {kr:"평일",ro:"pyeongil",meaning:"weekday",example:"평일에는 바빠요 — pyeongileneun bappayo — I'm busy on weekdays",pos:"noun",freq:7,register:"neutral"},
  {kr:"이번",ro:"ibeon",meaning:"this time / this (week/month)",example:"이번 주에 — ibeon jue — this week",pos:"adjective",freq:8,register:"neutral"},
  {kr:"다음",ro:"daeum",meaning:"next",example:"다음 주에 — daeum jue — next week",pos:"adjective",freq:9,register:"neutral"},
  {kr:"지난",ro:"jinan",meaning:"last / past",example:"지난 주에 — jinan jue — last week",pos:"adjective",freq:8,register:"neutral"},

  // Shopping
  {kr:"쇼핑하다",ro:"syopinghada",meaning:"to shop",example:"쇼핑하러 가요 — syopinghareo gayo — go shopping",pos:"verb",freq:8,register:"neutral"},
  {kr:"가게",ro:"gage",meaning:"store / shop",example:"가게에 가요 — gagee gayo — go to the store",pos:"noun",freq:8,register:"neutral"},
  {kr:"시장",ro:"sijang",meaning:"market",example:"시장에서 사요 — sijangeseo sayo — buy at the market",pos:"noun",freq:8,register:"neutral"},
  {kr:"마트",ro:"mateu",meaning:"mart / supermarket",example:"마트에서 장 봐요 — mateueseo jang bwayo — grocery shop at the mart",pos:"noun",freq:8,register:"neutral"},
  {kr:"편의점",ro:"pyeonuijeom",meaning:"convenience store",example:"편의점에서 사요 — pyeonuijeomeseo sayo — buy at the convenience store",pos:"noun",freq:8,register:"neutral"},
  {kr:"영수증",ro:"yeongsujeung",meaning:"receipt",example:"영수증 주세요 — yeongsujeung juseyo — please give me a receipt",pos:"noun",freq:7,register:"neutral"},
  {kr:"할인",ro:"harin",meaning:"discount / sale",example:"할인이 있어요 — harini isseoyo — there is a discount",pos:"noun",freq:7,register:"neutral"},
  {kr:"계산",ro:"gyesan",meaning:"payment / calculation",example:"계산해 주세요 — gyesane juseyo — please calculate the bill",pos:"noun",freq:8,register:"neutral"},
  {kr:"현금",ro:"hyeongeum",meaning:"cash",example:"현금으로 내요 — hyeongeumeurro naeyo — pay by cash",pos:"noun",freq:7,register:"neutral"},
  {kr:"카드",ro:"kadeu",meaning:"card (credit/debit)",example:"카드로 내요 — kadeuro naeyo — pay by card",pos:"noun",freq:8,register:"neutral"},

  // Connectors & Grammar expressions
  {kr:"그리고",ro:"geurigo",meaning:"and / and then",example:"밥을 먹고 그리고 자요 — babeul meokgo geurigo jayo — eat and then sleep",pos:"adverb",freq:9,register:"neutral"},
  {kr:"그런데",ro:"geureonde",meaning:"but / however / by the way",example:"좋아요, 그런데 비싸요 — joayo, geureonde bissayo — it's nice, but expensive",pos:"adverb",freq:9,register:"neutral"},
  {kr:"그래서",ro:"geuraeseo",meaning:"so / therefore",example:"아파서 그래서 못 가요 — apaseo geraeseo mot gayo — I'm sick, so I can't go",pos:"adverb",freq:9,register:"neutral"},
  {kr:"왜냐하면",ro:"waenyahamyeon",meaning:"because / the reason is",example:"왜냐하면 바빠서요 — waenyahamyeon bappaseoyo — because I'm busy",pos:"adverb",freq:7,register:"neutral"},
  {kr:"만약",ro:"manyak",meaning:"if / in case",example:"만약 시간이 있으면 — manyak sigani isseumyeon — if there is time",pos:"adverb",freq:7,register:"neutral"},
  {kr:"아니면",ro:"animyeon",meaning:"or / if not",example:"커피 아니면 차 — keopi animyeon cha — coffee or tea",pos:"adverb",freq:8,register:"neutral"},
  {kr:"그러면",ro:"geureomyeon",meaning:"then / in that case",example:"그러면 내일 봐요 — geureomyeon naeil bwayo — then see you tomorrow",pos:"adverb",freq:8,register:"neutral"},
  {kr:"그냥",ro:"geunyang",meaning:"just / simply",example:"그냥 해요 — geunyang haeyo — just do it",pos:"adverb",freq:9,register:"casual"},
  {kr:"너무",ro:"neomu",meaning:"too / very / so",example:"너무 좋아요 — neomu joayo — so good",pos:"adverb",freq:10,register:"neutral"},
  {kr:"정말",ro:"jeongmal",meaning:"really / truly",example:"정말 고마워요 — jeongmal gomawoyo — really thank you",pos:"adverb",freq:10,register:"neutral"},
  {kr:"진짜",ro:"jinjja",meaning:"real / really (casual)",example:"진짜요? — jinjjayo? — really?",pos:"adverb",freq:9,register:"casual"},
  {kr:"아직",ro:"ajik",meaning:"still / yet",example:"아직 몰라요 — ajik mollayo — still don't know",pos:"adverb",freq:8,register:"neutral"},
  {kr:"벌써",ro:"beolsseo",meaning:"already",example:"벌써 갔어요 — beolsseo gasseoyo — already left",pos:"adverb",freq:7,register:"neutral"},
  {kr:"계속",ro:"gyesok",meaning:"continuously / keep on",example:"계속 해요 — gyesok haeyo — keep going",pos:"adverb",freq:8,register:"neutral"},

  // Relationships
  {kr:"가족",ro:"gajok",meaning:"family",example:"가족이 중요해요 — gajogi jungyohaeyo — family is important",pos:"noun",freq:9,register:"neutral"},
  {kr:"부모님",ro:"bumonim",meaning:"parents",example:"부모님을 사랑해요 — bumonimeul saranghaeyo — I love my parents",pos:"noun",freq:8,register:"neutral"},
  {kr:"아버지",ro:"abeoji",meaning:"father",example:"아버지가 일해요 — abeojiga ilhaeyo — father works",pos:"noun",freq:8,register:"neutral"},
  {kr:"어머니",ro:"eomeoni",meaning:"mother",example:"어머니가 요리해요 — eomeoniga yorihaeyo — mother cooks",pos:"noun",freq:8,register:"neutral"},
  {kr:"형",ro:"hyeong",meaning:"older brother (male speaker)",example:"형이 있어요 — hyeongi isseoyo — I have an older brother",pos:"noun",freq:7,register:"casual"},
  {kr:"오빠",ro:"oppa",meaning:"older brother (female speaker)",example:"오빠가 멋있어요 — oppaga meossisseoyo — my older brother is cool",pos:"noun",freq:7,register:"casual"},
  {kr:"언니",ro:"eonni",meaning:"older sister (female speaker)",example:"언니가 예뻐요 — eonniga yeppeoyo — my older sister is pretty",pos:"noun",freq:7,register:"casual"},
  {kr:"누나",ro:"nuna",meaning:"older sister (male speaker)",example:"누나가 친절해요 — nunaga chinjeolhaeyo — my older sister is kind",pos:"noun",freq:7,register:"casual"},
  {kr:"남동생",ro:"namdongsaeng",meaning:"younger brother",example:"남동생이 있어요 — namdongsaengi isseoyo — I have a younger brother",pos:"noun",freq:7,register:"neutral"},
  {kr:"여동생",ro:"yeodongsaeng",meaning:"younger sister",example:"여동생이 귀여워요 — yeodongsaengi gwiyeowoyo — younger sister is cute",pos:"noun",freq:7,register:"neutral"},
  {kr:"친구",ro:"chingu",meaning:"friend",example:"친구를 만나요 — chingureul mannayo — meet a friend",pos:"noun",freq:10,register:"neutral"},
  {kr:"남자친구",ro:"namjachingu",meaning:"boyfriend",example:"남자친구가 있어요 — namjachinguga isseoyo — I have a boyfriend",pos:"noun",freq:7,register:"casual"},
  {kr:"여자친구",ro:"yeojachingu",meaning:"girlfriend",example:"여자친구가 있어요 — yeojachinguga isseoyo — I have a girlfriend",pos:"noun",freq:7,register:"casual"},
  {kr:"이웃",ro:"iut",meaning:"neighbor",example:"이웃이 친절해요 — iuti chinjeolhaeyo — neighbors are kind",pos:"noun",freq:7,register:"neutral"},

  // Health
  {kr:"아프다",ro:"apeuda",meaning:"to be sick / to hurt",example:"머리가 아파요 — meoriga apayo — I have a headache",pos:"adjective",freq:9,register:"neutral"},
  {kr:"열",ro:"yeol",meaning:"fever",example:"열이 나요 — yeori nayo — I have a fever",pos:"noun",freq:7,register:"neutral"},
  {kr:"기침",ro:"gichim",meaning:"cough",example:"기침이 나요 — gichimi nayo — I have a cough",pos:"noun",freq:7,register:"neutral"},
  {kr:"감기",ro:"gamgi",meaning:"cold (illness)",example:"감기에 걸렸어요 — gamgie geollyeosseoyo — I caught a cold",pos:"noun",freq:7,register:"neutral"},
  {kr:"병원",ro:"byeongwon",meaning:"hospital",example:"병원에 가요 — byeongwone gayo — go to the hospital",pos:"noun",freq:8,register:"neutral"},
  {kr:"약",ro:"yak",meaning:"medicine",example:"약을 먹어요 — yageul meogeoyo — take medicine",pos:"noun",freq:8,register:"neutral"},
  {kr:"의사",ro:"uisa",meaning:"doctor",example:"의사 선생님 — uisa seonsaengnim — doctor",pos:"noun",freq:8,register:"neutral"},
  {kr:"간호사",ro:"ganhosa",meaning:"nurse",example:"간호사가 친절해요 — ganhosaga chinjeolhaeyo — the nurse is kind",pos:"noun",freq:7,register:"neutral"},
  {kr:"건강하다",ro:"geonganghada",meaning:"to be healthy",example:"건강하게 지내요 — geonganghage jInaeyo — living healthily",pos:"adjective",freq:8,register:"neutral"},
  {kr:"운동하다",ro:"undonghada",meaning:"to exercise",example:"매일 운동해요 — maeil undonghaeyo — exercise every day",pos:"verb",freq:8,register:"neutral"},

  // Hobbies & Entertainment
  {kr:"취미",ro:"chwimi",meaning:"hobby",example:"취미가 뭐예요? — chwimiga mwoyeyo? — what is your hobby?",pos:"noun",freq:8,register:"neutral"},
  {kr:"음악",ro:"eumak",meaning:"music",example:"음악을 들어요 — eumageul deureoyo — listen to music",pos:"noun",freq:9,register:"neutral"},
  {kr:"영화",ro:"yeonghwa",meaning:"movie",example:"영화를 봐요 — yeonghwareul bwayo — watch a movie",pos:"noun",freq:9,register:"neutral"},
  {kr:"드라마",ro:"deurama",meaning:"drama / TV show",example:"드라마를 봐요 — deurAmareul bwayo — watch a drama",pos:"noun",freq:8,register:"casual"},
  {kr:"게임",ro:"geim",meaning:"game",example:"게임을 해요 — geimeul haeyo — play a game",pos:"noun",freq:8,register:"casual"},
  {kr:"독서",ro:"dokseo",meaning:"reading (books)",example:"독서가 취미예요 — dokseoga chwimiyeyo — reading is my hobby",pos:"noun",freq:7,register:"neutral"},
  {kr:"그림",ro:"geurim",meaning:"drawing / painting / picture",example:"그림을 그려요 — geurimeul geuryeoyo — draw a picture",pos:"noun",freq:7,register:"neutral"},
  {kr:"여행",ro:"yeohaeng",meaning:"travel",example:"여행을 좋아해요 — yeohaengeul joahaeyo — I like traveling",pos:"noun",freq:8,register:"neutral"},
  {kr:"등산",ro:"deungsan",meaning:"hiking",example:"주말에 등산해요 — jumale deungsanhaeyo — go hiking on weekends",pos:"noun",freq:7,register:"neutral"},
  {kr:"수영",ro:"suyeong",meaning:"swimming",example:"수영을 잘 해요 — suyeongeul jal haeyo — swim well",pos:"noun",freq:7,register:"neutral"},
  {kr:"요가",ro:"yoga",meaning:"yoga",example:"아침에 요가를 해요 — achime yogareul haeyo — do yoga in the morning",pos:"noun",freq:7,register:"neutral"},
  {kr:"노래",ro:"norae",meaning:"song / singing",example:"노래를 불러요 — noraereul bulleoyo — sing a song",pos:"noun",freq:8,register:"neutral"},
  {kr:"춤",ro:"chum",meaning:"dance",example:"춤을 춰요 — chumeul chwoyo — dance",pos:"noun",freq:7,register:"neutral"},
  {kr:"사진 찍기",ro:"sajin jjikgi",meaning:"photography",example:"사진 찍기가 좋아요 — sajin jjikgiga joayo — I like photography",pos:"noun",freq:7,register:"neutral"},
  {kr:"낚시",ro:"naksi",meaning:"fishing",example:"낚시하러 가요 — naksihareo gayo — go fishing",pos:"noun",freq:6,register:"neutral"},
];

// ── ITALIAN EXPANSION ──────────────────────────────────────────────────────────
const ITALIAN_WORDS_4 = [
  // Body & Health  
  {kr:"testa",ro:"testa",meaning:"head",example:"mi fa male la testa — the head hurts me — ho mal di testa",pos:"noun",freq:9,register:"neutral"},
  {kr:"capelli",ro:"capelli",meaning:"hair",example:"hai i capelli bellissimi — you have beautiful hair",pos:"noun",freq:8,register:"neutral"},
  {kr:"occhio",ro:"occhio",meaning:"eye",example:"ha gli occhi verdi — he has green eyes",pos:"noun",freq:9,register:"neutral"},
  {kr:"naso",ro:"naso",meaning:"nose",example:"mi cola il naso — my nose is running",pos:"noun",freq:8,register:"neutral"},
  {kr:"bocca",ro:"bocca",meaning:"mouth",example:"apri la bocca — open your mouth",pos:"noun",freq:8,register:"neutral"},
  {kr:"orecchio",ro:"orecchio",meaning:"ear",example:"mi fa male l'orecchio — my ear hurts",pos:"noun",freq:8,register:"neutral"},
  {kr:"dente",ro:"dente",meaning:"tooth",example:"mi fa male un dente — I have a toothache",pos:"noun",freq:8,register:"neutral"},
  {kr:"mano",ro:"mano",meaning:"hand",example:"lavati le mani — wash your hands",pos:"noun",freq:9,register:"neutral"},
  {kr:"piede",ro:"piede",meaning:"foot",example:"mi fanno male i piedi — my feet hurt",pos:"noun",freq:8,register:"neutral"},
  {kr:"gamba",ro:"gamba",meaning:"leg",example:"mi fa male la gamba — my leg hurts",pos:"noun",freq:8,register:"neutral"},
  {kr:"braccio",ro:"braccio",meaning:"arm",example:"alza il braccio — raise your arm",pos:"noun",freq:8,register:"neutral"},
  {kr:"schiena",ro:"schiena",meaning:"back",example:"mi fa male la schiena — my back hurts",pos:"noun",freq:8,register:"neutral"},
  {kr:"stomaco",ro:"stomaco",meaning:"stomach",example:"ho mal di stomaco — I have a stomachache",pos:"noun",freq:8,register:"neutral"},
  {kr:"cuore",ro:"cuore",meaning:"heart",example:"il cuore batte forte — the heart beats hard",pos:"noun",freq:9,register:"neutral"},
  {kr:"pelle",ro:"pelle",meaning:"skin",example:"hai la pelle morbida — you have soft skin",pos:"noun",freq:7,register:"neutral"},
  {kr:"stanco",ro:"stanco",meaning:"tired",example:"sono molto stanco — I am very tired",pos:"adjective",freq:9,register:"neutral"},
  {kr:"ammalato",ro:"ammalato",meaning:"sick / ill",example:"sono ammalato — I am sick",pos:"adjective",freq:8,register:"neutral"},
  {kr:"febbre",ro:"febbre",meaning:"fever",example:"ho la febbre — I have a fever",pos:"noun",freq:7,register:"neutral"},
  {kr:"tosse",ro:"tosse",meaning:"cough",example:"ho la tosse — I have a cough",pos:"noun",freq:7,register:"neutral"},
  {kr:"raffreddore",ro:"raffreddore",meaning:"cold (illness)",example:"ho il raffreddore — I have a cold",pos:"noun",freq:7,register:"neutral"},
  {kr:"ospedale",ro:"ospedale",meaning:"hospital",example:"vado all'ospedale — I'm going to the hospital",pos:"noun",freq:8,register:"neutral"},
  {kr:"medico",ro:"medico",meaning:"doctor",example:"il medico mi ha visitato — the doctor examined me",pos:"noun",freq:8,register:"neutral"},
  {kr:"farmacia",ro:"farmacia",meaning:"pharmacy",example:"vado in farmacia — going to the pharmacy",pos:"noun",freq:7,register:"neutral"},
  {kr:"medicina",ro:"medicina",meaning:"medicine",example:"prendo la medicina — I take the medicine",pos:"noun",freq:7,register:"neutral"},
  {kr:"sano",ro:"sano",meaning:"healthy",example:"mangia sano — eat healthy",pos:"adjective",freq:7,register:"neutral"},

  // Daily Life & Actions
  {kr:"svegliarsi",ro:"svegliarsi",meaning:"to wake up",example:"mi sveglio alle sette — I wake up at seven",pos:"verb",freq:9,register:"neutral"},
  {kr:"alzarsi",ro:"alzarsi",meaning:"to get up",example:"mi alzo presto — I get up early",pos:"verb",freq:9,register:"neutral"},
  {kr:"lavarsi",ro:"lavarsi",meaning:"to wash oneself",example:"mi lavo le mani — I wash my hands",pos:"verb",freq:8,register:"neutral"},
  {kr:"vestirsi",ro:"vestirsi",meaning:"to get dressed",example:"mi vesto in fretta — I get dressed quickly",pos:"verb",freq:8,register:"neutral"},
  {kr:"sedersi",ro:"sedersi",meaning:"to sit down",example:"siediti qui — sit here",pos:"verb",freq:9,register:"neutral"},
  {kr:"alzare",ro:"alzare",meaning:"to raise / lift",example:"alza la mano — raise your hand",pos:"verb",freq:8,register:"neutral"},
  {kr:"camminare",ro:"camminare",meaning:"to walk",example:"cammino nel parco — I walk in the park",pos:"verb",freq:9,register:"neutral"},
  {kr:"correre",ro:"correre",meaning:"to run",example:"corro ogni mattina — I run every morning",pos:"verb",freq:8,range:"neutral"},
  {kr:"dormire",ro:"dormire",meaning:"to sleep",example:"vado a dormire — I'm going to sleep",pos:"verb",freq:10,register:"neutral"},
  {kr:"cucinare",ro:"cucinare",meaning:"to cook",example:"cucino la cena — I cook dinner",pos:"verb",freq:8,register:"neutral"},
  {kr:"pulire",ro:"pulire",meaning:"to clean",example:"pulisco la camera — I clean the room",pos:"verb",freq:8,register:"neutral"},
  {kr:"aprire",ro:"aprire",meaning:"to open",example:"apri la finestra — open the window",pos:"verb",freq:9,register:"neutral"},
  {kr:"chiudere",ro:"chiudere",meaning:"to close",example:"chiudi la porta — close the door",pos:"verb",freq:9,register:"neutral"},
  {kr:"cercare",ro:"cercare",meaning:"to look for",example:"cerco le chiavi — I'm looking for the keys",pos:"verb",freq:9,register:"neutral"},
  {kr:"trovare",ro:"trovare",meaning:"to find",example:"ho trovato il portafoglio — I found the wallet",pos:"verb",freq:9,register:"neutral"},
  {kr:"portare",ro:"portare",meaning:"to bring / to carry / to wear",example:"porta un cappotto — wear a coat",pos:"verb",freq:9,register:"neutral"},
  {kr:"mettere",ro:"mettere",meaning:"to put / to place",example:"metti qui — put it here",pos:"verb",freq:9,register:"neutral"},
  {kr:"togliere",ro:"togliere",meaning:"to take off / to remove",example:"togli le scarpe — take off your shoes",pos:"verb",freq:8,register:"neutral"},
  {kr:"accendere",ro:"accendere",meaning:"to turn on / to light",example:"accendi la luce — turn on the light",pos:"verb",freq:8,register:"neutral"},
  {kr:"spegnere",ro:"spegnere",meaning:"to turn off",example:"spegni la TV — turn off the TV",pos:"verb",freq:8,register:"neutral"},

  // Food & Eating
  {kr:"colazione",ro:"colazione",meaning:"breakfast",example:"faccio colazione — I have breakfast",pos:"noun",freq:9,register:"neutral"},
  {kr:"pranzo",ro:"pranzo",meaning:"lunch",example:"a pranzo mangio pasta — I eat pasta for lunch",pos:"noun",freq:9,register:"neutral"},
  {kr:"cena",ro:"cena",meaning:"dinner",example:"la cena è pronta — dinner is ready",pos:"noun",freq:9,register:"neutral"},
  {kr:"pasta",ro:"pasta",meaning:"pasta",example:"mangio la pasta — I eat pasta",pos:"noun",freq:9,register:"neutral"},
  {kr:"pane",ro:"pane",meaning:"bread",example:"compro il pane — I buy bread",pos:"noun",freq:9,register:"neutral"},
  {kr:"carne",ro:"carne",meaning:"meat",example:"non mangio carne — I don't eat meat",pos:"noun",freq:8,register:"neutral"},
  {kr:"pesce",ro:"pesce",meaning:"fish",example:"il pesce è fresco — the fish is fresh",pos:"noun",freq:8,register:"neutral"},
  {kr:"verdura",ro:"verdura",meaning:"vegetables",example:"mangia più verdura — eat more vegetables",pos:"noun",freq:8,register:"neutral"},
  {kr:"frutta",ro:"frutta",meaning:"fruit",example:"la frutta fa bene — fruit is good for you",pos:"noun",freq:8,register:"neutral"},
  {kr:"formaggio",ro:"formaggio",meaning:"cheese",example:"questo formaggio è buonissimo — this cheese is very good",pos:"noun",freq:8,register:"neutral"},
  {kr:"uovo",ro:"uovo",meaning:"egg",example:"uova strapazzate — scrambled eggs",pos:"noun",freq:8,register:"neutral"},
  {kr:"latte",ro:"latte",meaning:"milk",example:"un bicchiere di latte — a glass of milk",pos:"noun",freq:8,register:"neutral"},
  {kr:"acqua",ro:"acqua",meaning:"water",example:"un bicchiere d'acqua — a glass of water",pos:"noun",freq:10,register:"neutral"},
  {kr:"vino",ro:"vino",meaning:"wine",example:"un bicchiere di vino rosso — a glass of red wine",pos:"noun",freq:8,register:"neutral"},
  {kr:"birra",ro:"birra",meaning:"beer",example:"una birra fredda — a cold beer",pos:"noun",freq:7,register:"casual"},
  {kr:"caffè",ro:"caffè",meaning:"coffee",example:"un caffè per favore — a coffee please",pos:"noun",freq:10,register:"neutral"},
  {kr:"tè",ro:"tè",meaning:"tea",example:"una tazza di tè — a cup of tea",pos:"noun",freq:8,register:"neutral"},
  {kr:"dolce",ro:"dolce",meaning:"sweet / dessert",example:"vuoi un dolce? — do you want a dessert?",pos:"noun",freq:8,register:"neutral"},
  {kr:"gelato",ro:"gelato",meaning:"ice cream / gelato",example:"un gelato al cioccolato — a chocolate ice cream",pos:"noun",freq:8,register:"neutral"},
  {kr:"pizza",ro:"pizza",meaning:"pizza",example:"una pizza margherita — a margherita pizza",pos:"noun",freq:9,register:"neutral"},

  // Home & Objects
  {kr:"casa",ro:"casa",meaning:"house / home",example:"vado a casa — I'm going home",pos:"noun",freq:10,register:"neutral"},
  {kr:"camera",ro:"camera",meaning:"room / bedroom",example:"la mia camera è piccola — my room is small",pos:"noun",freq:9,register:"neutral"},
  {kr:"cucina",ro:"cucina",meaning:"kitchen",example:"cucino in cucina — I cook in the kitchen",pos:"noun",freq:8,register:"neutral"},
  {kr:"bagno",ro:"bagno",meaning:"bathroom",example:"dov'è il bagno? — where is the bathroom?",pos:"noun",freq:9,register:"neutral"},
  {kr:"salotto",ro:"salotto",meaning:"living room",example:"ci vediamo in salotto — see you in the living room",pos:"noun",freq:8,register:"neutral"},
  {kr:"letto",ro:"letto",meaning:"bed",example:"vado a letto — I'm going to bed",pos:"noun",freq:9,register:"neutral"},
  {kr:"divano",ro:"divano",meaning:"sofa / couch",example:"mi sdraio sul divano — I lie on the sofa",pos:"noun",freq:8,register:"neutral"},
  {kr:"tavolo",ro:"tavolo",meaning:"table",example:"metti a tavola — set the table",pos:"noun",freq:9,register:"neutral"},
  {kr:"sedia",ro:"sedia",meaning:"chair",example:"siediti sulla sedia — sit on the chair",pos:"noun",freq:9,register:"neutral"},
  {kr:"finestra",ro:"finestra",meaning:"window",example:"apri la finestra — open the window",pos:"noun",freq:8,register:"neutral"},
  {kr:"porta",ro:"porta",meaning:"door",example:"chiudi la porta — close the door",pos:"noun",freq:10,register:"neutral"},
  {kr:"specchio",ro:"specchio",meaning:"mirror",example:"mi guardo allo specchio — I look in the mirror",pos:"noun",freq:7,register:"neutral"},
  {kr:"armadio",ro:"armadio",meaning:"wardrobe / closet",example:"i vestiti sono nell'armadio — clothes are in the wardrobe",pos:"noun",freq:7,register:"neutral"},
  {kr:"frigorifero",ro:"frigorifero",meaning:"refrigerator",example:"metti in frigo — put it in the fridge",pos:"noun",freq:7,register:"neutral"},
  {kr:"lavatrice",ro:"lavatrice",meaning:"washing machine",example:"metto il bucato in lavatrice — I put laundry in the washing machine",pos:"noun",freq:7,register:"neutral"},
  {kr:"asciugamano",ro:"asciugamano",meaning:"towel",example:"prendi un asciugamano — take a towel",pos:"noun",freq:7,register:"neutral"},
  {kr:"cuscino",ro:"cuscino",meaning:"pillow / cushion",example:"il cuscino è morbido — the pillow is soft",pos:"noun",freq:7,register:"neutral"},
  {kr:"coperta",ro:"coperta",meaning:"blanket",example:"ho freddo, dammi la coperta — I'm cold, give me the blanket",pos:"noun",freq:7,register:"neutral"},
  {kr:"lampada",ro:"lampada",meaning:"lamp",example:"accendi la lampada — turn on the lamp",pos:"noun",freq:7,register:"neutral"},
  {kr:"chiave",ro:"chiave",meaning:"key",example:"ho dimenticato le chiavi — I forgot the keys",pos:"noun",freq:8,register:"neutral"},

  // Transport
  {kr:"autobus",ro:"autobus",meaning:"bus",example:"prendo l'autobus — I take the bus",pos:"noun",freq:9,register:"neutral"},
  {kr:"metro",ro:"metro",meaning:"subway / metro",example:"prendo la metro — I take the metro",pos:"noun",freq:8,register:"neutral"},
  {kr:"taxi",ro:"taxi",meaning:"taxi",example:"chiamo un taxi — I call a taxi",pos:"noun",freq:8,register:"neutral"},
  {kr:"macchina",ro:"macchina",meaning:"car",example:"vado in macchina — I go by car",pos:"noun",freq:9,register:"neutral"},
  {kr:"bicicletta",ro:"bicicletta",meaning:"bicycle",example:"vado in bicicletta — I go by bicycle",pos:"noun",freq:8,register:"neutral"},
  {kr:"treno",ro:"treno",meaning:"train",example:"prendo il treno — I take the train",pos:"noun",freq:9,register:"neutral"},
  {kr:"aereo",ro:"aereo",meaning:"airplane",example:"prendo l'aereo — I take the plane",pos:"noun",freq:8,register:"neutral"},
  {kr:"nave",ro:"nave",meaning:"ship",example:"viaggio in nave — I travel by ship",pos:"noun",freq:7,register:"neutral"},
  {kr:"stazione",ro:"stazione",meaning:"station",example:"ci vediamo alla stazione — meet at the station",pos:"noun",freq:8,register:"neutral"},
  {kr:"fermata",ro:"fermata",meaning:"bus/tram stop",example:"la fermata è qui vicino — the stop is nearby",pos:"noun",freq:7,register:"neutral"},
  {kr:"aeroporto",ro:"aeroporto",meaning:"airport",example:"vado all'aeroporto — I'm going to the airport",pos:"noun",freq:8,register:"neutral"},
  {kr:"strada",ro:"strada",meaning:"road / street",example:"attraversa la strada — cross the street",pos:"noun",freq:9,register:"neutral"},
  {kr:"semaforo",ro:"semaforo",meaning:"traffic light",example:"il semaforo è rosso — the traffic light is red",pos:"noun",freq:7,register:"neutral"},
  {kr:"incrocio",ro:"incrocio",meaning:"intersection / crossroads",example:"gira a sinistra all'incrocio — turn left at the intersection",pos:"noun",freq:7,register:"neutral"},
  {kr:"parcheggio",ro:"parcheggio",meaning:"parking",example:"trovo un parcheggio — I find parking",pos:"noun",freq:7,register:"neutral"},

  // School & Work
  {kr:"scuola",ro:"scuola",meaning:"school",example:"vado a scuola — I go to school",pos:"noun",freq:9,register:"neutral"},
  {kr:"università",ro:"università",meaning:"university",example:"studio all'università — I study at university",pos:"noun",freq:9,register:"neutral"},
  {kr:"insegnante",ro:"insegnante",meaning:"teacher",example:"l'insegnante è brava — the teacher is good",pos:"noun",freq:8,register:"neutral"},
  {kr:"studente",ro:"studente",meaning:"student",example:"sono uno studente — I am a student",pos:"noun",freq:9,register:"neutral"},
  {kr:"classe",ro:"classe",meaning:"class / classroom",example:"la classe è grande — the class is big",pos:"noun",freq:8,register:"neutral"},
  {kr:"libro",ro:"libro",meaning:"book",example:"leggo un libro — I read a book",pos:"noun",freq:9,register:"neutral"},
  {kr:"quaderno",ro:"quaderno",meaning:"notebook",example:"scrivo sul quaderno — I write in the notebook",pos:"noun",freq:8,register:"neutral"},
  {kr:"penna",ro:"penna",meaning:"pen",example:"mi presti la penna? — can you lend me your pen?",pos:"noun",freq:8,register:"neutral"},
  {kr:"matita",ro:"matita",meaning:"pencil",example:"disegno con la matita — I draw with a pencil",pos:"noun",freq:7,register:"neutral"},
  {kr:"esame",ro:"esame",meaning:"exam",example:"domani ho un esame — tomorrow I have an exam",pos:"noun",freq:8,register:"neutral"},
  {kr:"studiare",ro:"studiare",meaning:"to study",example:"studio molto — I study a lot",pos:"verb",freq:9,register:"neutral"},
  {kr:"ufficio",ro:"ufficio",meaning:"office",example:"lavoro in ufficio — I work in the office",pos:"noun",freq:8,register:"neutral"},
  {kr:"lavoro",ro:"lavoro",meaning:"work / job",example:"ho trovato lavoro — I found work",pos:"noun",freq:9,register:"neutral"},
  {kr:"lavorare",ro:"lavorare",meaning:"to work",example:"lavoro molto — I work a lot",pos:"verb",freq:9,register:"neutral"},
  {kr:"stipendio",ro:"stipendio",meaning:"salary",example:"ho ricevuto lo stipendio — I received my salary",pos:"noun",freq:7,register:"neutral"},
  {kr:"riunione",ro:"riunione",meaning:"meeting",example:"ho una riunione — I have a meeting",pos:"noun",freq:7,register:"formal"},
  {kr:"capo",ro:"capo",meaning:"boss / head",example:"il mio capo è severo — my boss is strict",pos:"noun",freq:7,register:"neutral"},
  {kr:"collega",ro:"collega",meaning:"colleague",example:"il mio collega è simpatico — my colleague is nice",pos:"noun",freq:7,register:"neutral"},

  // Nature & Weather
  {kr:"tempo",ro:"tempo",meaning:"weather / time",example:"che tempo fa? — what's the weather like?",pos:"noun",freq:9,register:"neutral"},
  {kr:"sole",ro:"sole",meaning:"sun",example:"c'è il sole — the sun is out",pos:"noun",freq:9,register:"neutral"},
  {kr:"cielo",ro:"cielo",meaning:"sky",example:"il cielo è blu — the sky is blue",pos:"noun",freq:8,register:"neutral"},
  {kr:"nuvola",ro:"nuvola",meaning:"cloud",example:"ci sono molte nuvole — there are many clouds",pos:"noun",freq:7,register:"neutral"},
  {kr:"pioggia",ro:"pioggia",meaning:"rain",example:"sta piovendo — it's raining",pos:"noun",freq:8,register:"neutral"},
  {kr:"neve",ro:"neve",meaning:"snow",example:"sta nevicando — it's snowing",pos:"noun",freq:7,register:"neutral"},
  {kr:"vento",ro:"vento",meaning:"wind",example:"c'è molto vento — it's very windy",pos:"noun",freq:7,register:"neutral"},
  {kr:"freddo",ro:"freddo",meaning:"cold",example:"fa freddo — it's cold",pos:"adjective",freq:9,register:"neutral"},
  {kr:"caldo",ro:"caldo",meaning:"hot / warm",example:"fa caldo — it's hot",pos:"adjective",freq:9,register:"neutral"},
  {kr:"umido",ro:"umido",meaning:"humid / damp",example:"è molto umido — it's very humid",pos:"adjective",freq:6,register:"neutral"},
  {kr:"mare",ro:"mare",meaning:"sea",example:"andiamo al mare — let's go to the sea",pos:"noun",freq:9,register:"neutral"},
  {kr:"montagna",ro:"montagna",meaning:"mountain",example:"vado in montagna — I go to the mountain",pos:"noun",freq:8,register:"neutral"},
  {kr:"fiume",ro:"fiume",meaning:"river",example:"il fiume è largo — the river is wide",pos:"noun",freq:7,register:"neutral"},
  {kr:"lago",ro:"lago",meaning:"lake",example:"il lago è bellissimo — the lake is beautiful",pos:"noun",freq:7,register:"neutral"},
  {kr:"bosco",ro:"bosco",meaning:"forest / woods",example:"passeggio nel bosco — I walk in the woods",pos:"noun",freq:7,register:"neutral"},
  {kr:"fiore",ro:"fiore",meaning:"flower",example:"i fiori sono bellissimi — the flowers are beautiful",pos:"noun",freq:8,register:"neutral"},
  {kr:"albero",ro:"albero",meaning:"tree",example:"l'albero è alto — the tree is tall",pos:"noun",freq:8,register:"neutral"},
  {kr:"erba",ro:"erba",meaning:"grass",example:"l'erba è verde — the grass is green",pos:"noun",freq:7,register:"neutral"},

  // Emotions & Personality
  {kr:"felice",ro:"felice",meaning:"happy",example:"sono molto felice — I am very happy",pos:"adjective",freq:9,register:"neutral"},
  {kr:"triste",ro:"triste",meaning:"sad",example:"sono triste oggi — I am sad today",pos:"adjective",freq:8,register:"neutral"},
  {kr:"arrabbiato",ro:"arrabbiato",meaning:"angry",example:"sono arrabbiato — I am angry",pos:"adjective",freq:7,register:"neutral"},
  {kr:"spaventato",ro:"spaventato",meaning:"scared / frightened",example:"sono spaventato — I am scared",pos:"adjective",freq:7,register:"neutral"},
  {kr:"emozionato",ro:"emozionato",meaning:"excited / emotional",example:"sono molto emozionato — I am very excited",pos:"adjective",freq:7,register:"neutral"},
  {kr:"sorpreso",ro:"sorpreso",meaning:"surprised",example:"sono sorpreso — I am surprised",pos:"adjective",freq:7,register:"neutral"},
  {kr:"annoiato",ro:"annoiato",meaning:"bored",example:"sono annoiato — I am bored",pos:"adjective",freq:7,register:"casual"},
  {kr:"nervoso",ro:"nervoso",meaning:"nervous / anxious",example:"sono nervoso per l'esame — I am nervous about the exam",pos:"adjective",freq:7,register:"neutral"},
  {kr:"gentile",ro:"gentile",meaning:"kind / gentle",example:"sei molto gentile — you are very kind",pos:"adjective",freq:8,register:"neutral"},
  {kr:"simpatico",ro:"simpatico",meaning:"nice / likeable",example:"è molto simpatico — he is very likeable",pos:"adjective",freq:8,register:"neutral"},
  {kr:"intelligente",ro:"intelligente",meaning:"intelligent / smart",example:"è una persona intelligente — a smart person",pos:"adjective",freq:8,register:"neutral"},
  {kr:"pigro",ro:"pigro",meaning:"lazy",example:"sono un po' pigro — I am a bit lazy",pos:"adjective",freq:6,register:"casual"},
  {kr:"coraggioso",ro:"coraggioso",meaning:"brave / courageous",example:"è molto coraggioso — very brave",pos:"adjective",freq:7,register:"neutral"},
  {kr:"timido",ro:"timido",meaning:"shy / timid",example:"sono un po' timido — I am a bit shy",pos:"adjective",freq:7,register:"neutral"},
  {kr:"onesto",ro:"onesto",meaning:"honest",example:"è una persona onesta — an honest person",pos:"adjective",freq:7,register:"neutral"},

  // Technology
  {kr:"telefono",ro:"telefono",meaning:"phone",example:"il telefono squilla — the phone rings",pos:"noun",freq:9,register:"neutral"},
  {kr:"computer",ro:"computer",meaning:"computer",example:"lavoro al computer — I work at the computer",pos:"noun",freq:9,register:"neutral"},
  {kr:"internet",ro:"internet",meaning:"internet",example:"cerco su internet — I search on the internet",pos:"noun",freq:9,register:"neutral"},
  {kr:"messaggio",ro:"messaggio",meaning:"message",example:"ti mando un messaggio — I'll send you a message",pos:"noun",freq:8,register:"neutral"},
  {kr:"foto",ro:"foto",meaning:"photo",example:"scatto una foto — I take a photo",pos:"noun",freq:8,register:"neutral"},
  {kr:"video",ro:"video",meaning:"video",example:"guardo un video — I watch a video",pos:"noun",freq:8,register:"neutral"},
  {kr:"applicazione",ro:"applicazione",meaning:"application / app",example:"scarico l'applicazione — I download the app",pos:"noun",freq:7,register:"neutral"},
  {kr:"schermo",ro:"schermo",meaning:"screen",example:"lo schermo è rotto — the screen is broken",pos:"noun",freq:7,register:"neutral"},

  // Connectors & Grammar
  {kr:"perché",ro:"perché",meaning:"because / why",example:"perché sei triste? — why are you sad?",pos:"adverb",freq:10,register:"neutral"},
  {kr:"però",ro:"però",meaning:"but / however",example:"mi piace, però è caro — I like it but it's expensive",pos:"adverb",freq:9,register:"neutral"},
  {kr:"quindi",ro:"quindi",meaning:"so / therefore",example:"sono stanco, quindi vado a dormire — I'm tired, so I'm going to sleep",pos:"adverb",freq:9,register:"neutral"},
  {kr:"anche",ro:"anche",meaning:"also / too / even",example:"anch'io — me too",pos:"adverb",freq:10,register:"neutral"},
  {kr:"solo",ro:"solo",meaning:"only / alone / just",example:"ho solo dieci euro — I only have ten euros",pos:"adverb",freq:10,register:"neutral"},
  {kr:"ancora",ro:"ancora",meaning:"still / again / yet",example:"non è ancora arrivato — he hasn't arrived yet",pos:"adverb",freq:9,register:"neutral"},
  {kr:"già",ro:"già",meaning:"already",example:"l'ho già fatto — I've already done it",pos:"adverb",freq:8,register:"neutral"},
  {kr:"sempre",ro:"sempre",meaning:"always",example:"arrivo sempre in ritardo — I always arrive late",pos:"adverb",freq:9,register:"neutral"},
  {kr:"mai",ro:"mai",meaning:"never / ever",example:"non arrivo mai in orario — I never arrive on time",pos:"adverb",freq:9,register:"neutral"},
  {kr:"spesso",ro:"spesso",meaning:"often",example:"vengo spesso qui — I come here often",pos:"adverb",freq:8,register:"neutral"},
  {kr:"qualche volta",ro:"qualche volta",meaning:"sometimes",example:"qualche volta cucino — sometimes I cook",pos:"adverb",freq:7,register:"neutral"},
  {kr:"forse",ro:"forse",meaning:"maybe / perhaps",example:"forse vengo — maybe I'll come",pos:"adverb",freq:8,register:"neutral"},
  {kr:"abbastanza",ro:"abbastanza",meaning:"enough / quite",example:"è abbastanza grande — it's quite big",pos:"adverb",freq:7,register:"neutral"},
  {kr:"troppo",ro:"troppo",meaning:"too much / too",example:"è troppo caro — it's too expensive",pos:"adverb",freq:8,register:"neutral"},
  {kr:"poco",ro:"poco",meaning:"little / few",example:"ho poco tempo — I have little time",pos:"adverb",freq:8,register:"neutral"},
  {kr:"molto",ro:"molto",meaning:"very / a lot / much",example:"mi piace molto — I like it a lot",pos:"adverb",freq:10,register:"neutral"},

  // Relationships
  {kr:"famiglia",ro:"famiglia",meaning:"family",example:"la mia famiglia è grande — my family is big",pos:"noun",freq:9,register:"neutral"},
  {kr:"padre",ro:"padre",meaning:"father",example:"mio padre lavora molto — my father works a lot",pos:"noun",freq:8,register:"neutral"},
  {kr:"madre",ro:"madre",meaning:"mother",example:"mia madre cucina bene — my mother cooks well",pos:"noun",freq:8,register:"neutral"},
  {kr:"fratello",ro:"fratello",meaning:"brother",example:"ho un fratello maggiore — I have an older brother",pos:"noun",freq:8,register:"neutral"},
  {kr:"sorella",ro:"sorella",meaning:"sister",example:"mia sorella è simpatica — my sister is nice",pos:"noun",freq:8,register:"neutral"},
  {kr:"figlio",ro:"figlio",meaning:"son / child",example:"ho due figli — I have two children",pos:"noun",freq:8,register:"neutral"},
  {kr:"figlia",ro:"figlia",meaning:"daughter",example:"mia figlia studia medicina — my daughter studies medicine",pos:"noun",freq:7,register:"neutral"},
  {kr:"nonno",ro:"nonno",meaning:"grandfather",example:"mio nonno ha ottant'anni — my grandfather is eighty",pos:"noun",freq:7,register:"neutral"},
  {kr:"nonna",ro:"nonna",meaning:"grandmother",example:"mia nonna cucina benissimo — my grandmother cooks very well",pos:"noun",freq:7,register:"neutral"},
  {kr:"marito",ro:"marito",meaning:"husband",example:"mio marito lavora a Milano — my husband works in Milan",pos:"noun",freq:7,register:"neutral"},
  {kr:"moglie",ro:"moglie",meaning:"wife",example:"mia moglie è medico — my wife is a doctor",pos:"noun",freq:7,register:"neutral"},
  {kr:"amico",ro:"amico",meaning:"friend (male)",example:"il mio migliore amico — my best friend",pos:"noun",freq:9,register:"neutral"},
  {kr:"amica",ro:"amica",meaning:"friend (female)",example:"la mia amica si chiama Lucia — my friend is called Lucia",pos:"noun",freq:8,register:"neutral"},
  {kr:"fidanzato",ro:"fidanzato",meaning:"boyfriend / fiancé",example:"il mio fidanzato è simpatico — my boyfriend is nice",pos:"noun",freq:7,register:"casual"},
  {kr:"fidanzata",ro:"fidanzata",meaning:"girlfriend / fiancée",example:"la mia fidanzata è bella — my girlfriend is beautiful",pos:"noun",freq:7,register:"casual"},

  // Shopping
  {kr:"negozio",ro:"negozio",meaning:"shop / store",example:"vado al negozio — I go to the shop",pos:"noun",freq:8,register:"neutral"},
  {kr:"mercato",ro:"mercato",meaning:"market",example:"compro frutta al mercato — I buy fruit at the market",pos:"noun",freq:8,register:"neutral"},
  {kr:"supermercato",ro:"supermercato",meaning:"supermarket",example:"vado al supermercato — I go to the supermarket",pos:"noun",freq:8,register:"neutral"},
  {kr:"comprare",ro:"comprare",meaning:"to buy",example:"voglio comprare una borsa — I want to buy a bag",pos:"verb",freq:9,register:"neutral"},
  {kr:"vendere",ro:"vendere",meaning:"to sell",example:"vendo la mia macchina — I'm selling my car",pos:"verb",freq:8,register:"neutral"},
  {kr:"prezzo",ro:"prezzo",meaning:"price",example:"qual è il prezzo? — what is the price?",pos:"noun",freq:8,register:"neutral"},
  {kr:"sconto",ro:"sconto",meaning:"discount",example:"c'è uno sconto? — is there a discount?",pos:"noun",freq:7,register:"neutral"},
  {kr:"scontrino",ro:"scontrino",meaning:"receipt",example:"mi dà lo scontrino? — can you give me the receipt?",pos:"noun",freq:7,register:"neutral"},
  {kr:"contanti",ro:"contanti",meaning:"cash",example:"pago in contanti — I pay in cash",pos:"noun",freq:7,register:"neutral"},
  {kr:"carta di credito",ro:"carta di credito",meaning:"credit card",example:"pago con la carta — I pay by card",pos:"noun",freq:7,register:"neutral"},

  // Hobbies
  {kr:"hobby",ro:"hobby",meaning:"hobby",example:"qual è il tuo hobby? — what is your hobby?",pos:"noun",freq:7,register:"neutral"},
  {kr:"musica",ro:"musica",meaning:"music",example:"ascolto musica — I listen to music",pos:"noun",freq:9,register:"neutral"},
  {kr:"film",ro:"film",meaning:"film / movie",example:"guardo un film — I watch a film",pos:"noun",freq:9,register:"neutral"},
  {kr:"libro",ro:"libro",meaning:"book",example:"leggo un libro — I read a book",pos:"noun",freq:9,register:"neutral"},
  {kr:"viaggiare",ro:"viaggiare",meaning:"to travel",example:"amo viaggiare — I love to travel",pos:"verb",freq:8,register:"neutral"},
  {kr:"cucinare",ro:"cucinare",meaning:"to cook",example:"mi piace cucinare — I like to cook",pos:"verb",freq:8,register:"neutral"},
  {kr:"disegnare",ro:"disegnare",meaning:"to draw",example:"mi piace disegnare — I like to draw",pos:"verb",freq:7,register:"neutral"},
  {kr:"dipingere",ro:"dipingere",meaning:"to paint",example:"dipingo nel weekend — I paint on weekends",pos:"verb",freq:7,register:"neutral"},
  {kr:"fotografare",ro:"fotografare",meaning:"to photograph",example:"fotografo la natura — I photograph nature",pos:"verb",freq:7,register:"neutral"},
  {kr:"nuotare",ro:"nuotare",meaning:"to swim",example:"nuoto ogni giorno — I swim every day",pos:"verb",freq:7,register:"neutral"},
  {kr:"cantare",ro:"cantare",meaning:"to sing",example:"canto sotto la doccia — I sing in the shower",pos:"verb",freq:7,register:"neutral"},
  {kr:"ballare",ro:"ballare",meaning:"to dance",example:"mi piace ballare — I like to dance",pos:"verb",freq:7,register:"neutral"},
  {kr:"giocare",ro:"giocare",meaning:"to play",example:"gioco a calcio — I play football",pos:"verb",freq:8,register:"neutral"},
  {kr:"sport",ro:"sport",meaning:"sport",example:"faccio sport — I do sports",pos:"noun",freq:8,register:"neutral"},
  {kr:"calcio",ro:"calcio",meaning:"football / soccer",example:"guardo il calcio — I watch football",pos:"noun",freq:8,register:"neutral"},
];

// Append to existing arrays
if (typeof KOREAN_WORDS !== 'undefined') {
  KOREAN_WORDS.push(...KOREAN_WORDS_4);
}
if (typeof ITALIAN_WORDS !== 'undefined') {
  ITALIAN_WORDS.push(...ITALIAN_WORDS_4);
}
