// ── JAPANESE WORDS 3 — Everyday vocabulary (N5–N3 gaps) ───────────────────────
// Adds ~500 words not already present in data.js / data2.js.
// Categories: body & health extension, personality & character, school & work
// extension, daily actions, nature & environment, society & abstract,
// connectors & grammar words, counters, colors & shapes, cooking & food ext,
// housing & objects, transport ext, shopping ext, emotions ext, social life,
// communication, technology ext, sports & hobbies ext, culture & events,
// expressions & set phrases, numbers & quantity.

const JAPANESE_WORDS_3 = [

  // ── BODY & HEALTH ───────────────────────────────────────────────────────────
  {kr:"額",ro:"hitai",meaning:"forehead",example:"額に汗をかく — hitai ni ase wo kaku — to sweat on the forehead",pos:"noun",freq:5,register:"neutral"},
  {kr:"頬",ro:"hoho",meaning:"cheek",example:"頬が赤い — hoho ga akai — cheeks are red",pos:"noun",freq:5,register:"neutral"},
  {kr:"唇",ro:"kuchibiru",meaning:"lips",example:"唇が乾く — kuchibiru ga kawaku — lips become dry",pos:"noun",freq:6,register:"neutral"},
  {kr:"まゆげ",ro:"mayuge",meaning:"eyebrow",example:"まゆげが濃い — mayuge ga koi — thick eyebrows",pos:"noun",freq:5,register:"neutral"},
  {kr:"まつげ",ro:"matsuge",meaning:"eyelash",example:"長いまつげ — nagai matsuge — long eyelashes",pos:"noun",freq:4,register:"neutral"},
  {kr:"舌",ro:"shita",meaning:"tongue",example:"舌を出す — shita wo dasu — to stick out your tongue",pos:"noun",freq:5,register:"neutral"},
  {kr:"喉",ro:"nodo",meaning:"throat",example:"喉が痛い — nodo ga itai — my throat hurts",pos:"noun",freq:7,register:"neutral"},
  {kr:"肩こり",ro:"katakori",meaning:"stiff shoulders / shoulder tension",example:"肩こりがひどい — katakori ga hidoi — my shoulders are very stiff",pos:"noun",freq:6,register:"neutral"},
  {kr:"血圧",ro:"ketsuatsu",meaning:"blood pressure",example:"血圧を測る — ketsuatsu wo hakaru — to measure blood pressure",pos:"noun",freq:6,register:"neutral"},
  {kr:"アレルギー",ro:"arerugii",meaning:"allergy",example:"花粉アレルギーがある — kafun arerugii ga aru — I have a pollen allergy",pos:"noun",freq:7,register:"neutral"},
  {kr:"花粉",ro:"kafun",meaning:"pollen",example:"花粉の季節 — kafun no kisetsu — pollen season",pos:"noun",freq:6,register:"neutral"},
  {kr:"くしゃみ",ro:"kushami",meaning:"sneeze",example:"くしゃみが止まらない — kushami ga tomaranai — can't stop sneezing",pos:"noun",freq:6,register:"neutral"},
  {kr:"鼻水",ro:"hanamizu",meaning:"runny nose",example:"鼻水が出る — hanamizu ga deru — runny nose",pos:"noun",freq:6,register:"casual"},
  {kr:"下痢",ro:"geri",meaning:"diarrhea",example:"下痢になった — geri ni natta — I got diarrhea",pos:"noun",freq:5,register:"neutral"},
  {kr:"便秘",ro:"benpi",meaning:"constipation",example:"便秘で困っている — benpi de komatteiru — suffering from constipation",pos:"noun",freq:5,register:"neutral"},
  {kr:"吐く",ro:"haku",meaning:"to vomit / to exhale",example:"気持ち悪くて吐いた — kimochi warukute haita — I felt sick and vomited",pos:"verb",freq:5,register:"neutral"},
  {kr:"めまい",ro:"memai",meaning:"dizziness",example:"めまいがする — memai ga suru — I feel dizzy",pos:"noun",freq:6,register:"neutral"},
  {kr:"むくみ",ro:"mukumi",meaning:"swelling / puffiness",example:"足がむくんでいる — ashi ga mukunde iru — my feet are swollen",pos:"noun",freq:5,register:"neutral"},
  {kr:"包帯",ro:"houtai",meaning:"bandage",example:"包帯を巻く — houtai wo maku — to wrap a bandage",pos:"noun",freq:5,register:"neutral"},
  {kr:"注射",ro:"chuusha",meaning:"injection / shot",example:"注射を打つ — chuusha wo utsu — to give an injection",pos:"noun",freq:6,register:"neutral"},
  {kr:"点滴",ro:"tenteki",meaning:"IV drip / intravenous drip",example:"点滴を受ける — tenteki wo ukeru — to receive an IV drip",pos:"noun",freq:5,register:"neutral"},
  {kr:"体温",ro:"taion",meaning:"body temperature",example:"体温を測る — taion wo hakaru — to take one's temperature",pos:"noun",freq:7,register:"neutral"},
  {kr:"体重",ro:"taijuu",meaning:"body weight",example:"体重が増えた — taijuu ga fueta — I gained weight",pos:"noun",freq:7,register:"neutral"},
  {kr:"身長",ro:"shinchou",meaning:"height (of a person)",example:"身長は170センチ — shinchou wa hyakunanajuu senchi — I'm 170cm tall",pos:"noun",freq:7,register:"neutral"},
  {kr:"視力",ro:"shiryoku",meaning:"eyesight / vision",example:"視力が落ちた — shiryoku ga ochita — my eyesight got worse",pos:"noun",freq:6,register:"neutral"},
  {kr:"歯医者",ro:"haisha",meaning:"dentist",example:"歯医者に行く — haisha ni iku — to go to the dentist",pos:"noun",freq:7,register:"neutral"},
  {kr:"虫歯",ro:"mushiba",meaning:"cavity / tooth decay",example:"虫歯ができた — mushiba ga dekita — I got a cavity",pos:"noun",freq:6,register:"neutral"},

  // ── PERSONALITY & CHARACTER ─────────────────────────────────────────────────
  {kr:"性格",ro:"seikaku",meaning:"personality / character",example:"性格がいい人 — seikaku ga ii hito — a person with a good personality",pos:"noun",freq:8,register:"neutral"},
  {kr:"真面目",ro:"majime",meaning:"serious / earnest / diligent",example:"真面目に取り組む — majime ni torikumu — to tackle seriously",pos:"adjective",freq:7,register:"neutral"},
  {kr:"積極的",ro:"sekkyokuteki",meaning:"proactive / positive / aggressive",example:"積極的に行動する — sekkyokuteki ni koudou suru — to act proactively",pos:"adjective",freq:7,register:"neutral"},
  {kr:"消極的",ro:"shoukyokuteki",meaning:"passive / negative / reserved",example:"消極的な態度 — shoukyokuteki na taido — a passive attitude",pos:"adjective",freq:6,register:"neutral"},
  {kr:"明るい",ro:"akarui",meaning:"cheerful / bright / positive (personality)",example:"明るい性格 — akarui seikaku — a cheerful personality",pos:"adjective",freq:8,register:"neutral"},
  {kr:"おとなしい",ro:"otonashii",meaning:"quiet / gentle / well-behaved",example:"おとなしい子 — otonashii ko — a quiet child",pos:"adjective",freq:7,register:"neutral"},
  {kr:"頑固",ro:"ganko",meaning:"stubborn / obstinate",example:"頑固な人 — ganko na hito — a stubborn person",pos:"adjective",freq:6,register:"neutral"},
  {kr:"正直",ro:"shoujiki",meaning:"honest / frank / straightforward",example:"正直に言う — shoujiki ni iu — to say honestly",pos:"adjective",freq:7,register:"neutral"},
  {kr:"慎重",ro:"shinchou",meaning:"careful / cautious / prudent",example:"慎重に考える — shinchou ni kangaeru — to think carefully",pos:"adjective",freq:7,register:"neutral"},
  {kr:"大胆",ro:"daitan",meaning:"bold / daring / audacious",example:"大胆な決断 — daitan na ketsudan — a bold decision",pos:"adjective",freq:6,register:"neutral"},
  {kr:"素敵",ro:"suteki",meaning:"lovely / wonderful / stylish",example:"素敵なデザイン — suteki na dezain — a lovely design",pos:"adjective",freq:8,register:"casual"},
  {kr:"怠け者",ro:"namakemono",meaning:"lazy person / slacker",example:"怠け者だから失敗した — namakemono dakara shippai shita — I failed because I'm lazy",pos:"noun",freq:5,register:"casual"},
  {kr:"うそつき",ro:"usotsuki",meaning:"liar",example:"うそつきは信用できない — usotsuki wa shinyou dekinai — you can't trust a liar",pos:"noun",freq:5,register:"casual"},
  {kr:"お人好し",ro:"ohitoyoshi",meaning:"good-natured person / pushover",example:"お人好しすぎる — ohitoyoshi sugiru — too good-natured",pos:"noun",freq:5,register:"neutral"},
  {kr:"完璧主義",ro:"kanpeki shugi",meaning:"perfectionism",example:"完璧主義で疲れる — kanpeki shugi de tsukareru — exhausted by perfectionism",pos:"noun",freq:5,register:"neutral"},

  // ── SCHOOL & STUDY (extension) ──────────────────────────────────────────────
  {kr:"予習",ro:"yoshuu",meaning:"preparation / studying in advance",example:"予習をしてから授業に出る — yoshuu wo shite kara jugyou ni deru — to attend class after preparing",pos:"noun",freq:6,register:"neutral"},
  {kr:"欠席",ro:"kesseki",meaning:"absence / being absent",example:"授業を欠席する — jugyou wo kesseki suru — to be absent from class",pos:"noun",freq:6,register:"neutral"},
  {kr:"出席",ro:"shusseki",meaning:"attendance / being present",example:"出席を取る — shusseki wo toru — to take attendance",pos:"noun",freq:6,register:"neutral"},
  {kr:"点数",ro:"tensuu",meaning:"score / points",example:"テストの点数が悪かった — tesuto no tensuu ga warukatta — I got a bad score on the test",pos:"noun",freq:7,register:"neutral"},
  {kr:"単位",ro:"tan'i",meaning:"credit / unit (academic)",example:"単位を取る — tan'i wo toru — to earn a credit",pos:"noun",freq:6,register:"neutral"},
  {kr:"クラブ",ro:"kurabu",meaning:"club / club activity",example:"クラブに入る — kurabu ni hairu — to join a club",pos:"noun",freq:7,register:"neutral"},
  {kr:"校長",ro:"kouchou",meaning:"principal / school principal",example:"校長先生に会う — kouchou sensei ni au — to meet the principal",pos:"noun",freq:5,register:"neutral"},
  {kr:"担任",ro:"tannin",meaning:"homeroom teacher / class teacher",example:"担任の先生 — tannin no sensei — homeroom teacher",pos:"noun",freq:6,register:"neutral"},
  {kr:"黒板",ro:"kokuban",meaning:"blackboard / chalkboard",example:"黒板に書く — kokuban ni kaku — to write on the blackboard",pos:"noun",freq:6,register:"neutral"},
  {kr:"チョーク",ro:"chooku",meaning:"chalk",example:"チョークで書く — chooku de kaku — to write with chalk",pos:"noun",freq:5,register:"neutral"},
  {kr:"定規",ro:"jogi",meaning:"ruler (measuring)",example:"定規で線を引く — jogi de sen wo hiku — to draw a line with a ruler",pos:"noun",freq:5,register:"neutral"},
  {kr:"はさみ",ro:"hasami",meaning:"scissors",example:"はさみで切る — hasami de kiru — to cut with scissors",pos:"noun",freq:6,register:"neutral"},
  {kr:"のり",ro:"nori glue",meaning:"glue / paste",example:"のりで貼る — nori de haru — to glue / paste",pos:"noun",freq:5,register:"neutral"},
  {kr:"通知表",ro:"tsuuchihyou",meaning:"report card",example:"通知表をもらう — tsuuchihyou wo morau — to receive a report card",pos:"noun",freq:5,register:"neutral"},
  {kr:"奨学金",ro:"shouгakukin",meaning:"scholarship",example:"奨学金をもらう — shouがくkin wo morau — to receive a scholarship",pos:"noun",freq:6,register:"neutral"},

  // ── WORK & CAREER (extension) ───────────────────────────────────────────────
  {kr:"履歴書",ro:"rishokusho",meaning:"resume / CV",example:"履歴書を書く — rishokusho wo kaku — to write a resume",pos:"noun",freq:6,register:"neutral"},
  {kr:"採用",ro:"saiyou",meaning:"hiring / employment / adoption",example:"採用が決まった — saiyou ga kimatta — I got hired",pos:"noun",freq:6,register:"neutral"},
  {kr:"退職",ro:"taishoku",meaning:"retirement / resignation",example:"退職する — taishoku suru — to resign / retire",pos:"noun",freq:6,register:"neutral"},
  {kr:"転職",ro:"tenshoku",meaning:"changing jobs / career change",example:"転職を考えている — tenshoku wo kangaete iru — I'm considering changing jobs",pos:"noun",freq:6,register:"neutral"},
  {kr:"昇進",ro:"shoushin",meaning:"promotion (at work)",example:"昇進おめでとう — shoushin omedetou — congratulations on your promotion",pos:"noun",freq:6,register:"neutral"},
  {kr:"解雇",ro:"kaiko",meaning:"dismissal / firing",example:"解雇された — kaiko sareta — I was fired",pos:"noun",freq:5,register:"neutral"},
  {kr:"有給",ro:"yuukyuu",meaning:"paid leave / paid vacation",example:"有給を取る — yuukyuu wo toru — to take paid leave",pos:"noun",freq:7,register:"neutral"},
  {kr:"出勤",ro:"shukkin",meaning:"going to work / coming in",example:"毎日8時に出勤する — mainichi hachiji ni shukkin suru — to go to work at 8 every day",pos:"noun",freq:6,register:"neutral"},
  {kr:"退勤",ro:"taikin",meaning:"leaving work / clocking out",example:"退勤時間は6時 — taikin jikan wa rokuji — clocking out time is 6",pos:"noun",freq:5,register:"neutral"},
  {kr:"上司",ro:"joushi",meaning:"boss / superior",example:"上司に報告する — joushi ni houkoku suru — to report to one's boss",pos:"noun",freq:7,register:"neutral"},
  {kr:"部下",ro:"buka",meaning:"subordinate / staff under you",example:"部下を指導する — buka wo shidou suru — to guide one's subordinates",pos:"noun",freq:6,register:"neutral"},
  {kr:"取引先",ro:"torihikisaki",meaning:"business partner / client company",example:"取引先と会議する — torihikisaki to kaigi suru — to have a meeting with a client",pos:"noun",freq:6,register:"neutral"},
  {kr:"出張",ro:"shucchou",meaning:"business trip",example:"来週出張がある — raishuu shucchou ga aru — I have a business trip next week",pos:"noun",freq:7,register:"neutral"},
  {kr:"締め切り",ro:"shimekiri",meaning:"deadline",example:"締め切りを守る — shimekiri wo mamoru — to meet the deadline",pos:"noun",freq:7,register:"neutral"},
  {kr:"残業代",ro:"zangyoudai",meaning:"overtime pay",example:"残業代が出る — zangyoudai ga deru — overtime pay is given",pos:"noun",freq:5,register:"neutral"},
  {kr:"ボーナス",ro:"boonasu",meaning:"bonus",example:"ボーナスをもらった — boonasu wo moratta — I received a bonus",pos:"noun",freq:7,register:"neutral"},
  {kr:"名刺交換",ro:"meishi koukan",meaning:"business card exchange",example:"名刺交換をする — meishi koukan wo suru — to exchange business cards",pos:"noun",freq:5,register:"neutral"},
  {kr:"見積もり",ro:"mitsumori",meaning:"estimate / quotation",example:"見積もりを出す — mitsumori wo dasu — to give an estimate",pos:"noun",freq:5,register:"neutral"},
  {kr:"請求書",ro:"seikyuusho",meaning:"invoice / bill",example:"請求書を送る — seikyuusho wo okuru — to send an invoice",pos:"noun",freq:5,register:"neutral"},
  {kr:"領収書",ro:"ryoushuusho",meaning:"receipt (official)",example:"領収書をください — ryoushuusho wo kudasai — please give me a receipt",pos:"noun",freq:6,register:"neutral"},

  // ── DAILY ACTIONS (extension) ────────────────────────────────────────────────
  {kr:"起こる",ro:"okoru",meaning:"to happen / to occur",example:"事故が起こった — jiko ga okotta — an accident happened",pos:"verb",freq:8,register:"neutral"},
  {kr:"増やす",ro:"fuyasu",meaning:"to increase / to add more",example:"語彙を増やす — goi wo fuyasu — to increase vocabulary",pos:"verb",freq:7,register:"neutral"},
  {kr:"減らす",ro:"herasu",meaning:"to decrease / to reduce",example:"カロリーを減らす — karorii wo herasu — to reduce calories",pos:"verb",freq:7,register:"neutral"},
  {kr:"着く",ro:"tsuku",meaning:"to arrive",example:"駅に着いた — eki ni tsuita — I arrived at the station",pos:"verb",freq:9,register:"neutral"},
  {kr:"触れる",ro:"fureru",meaning:"to touch / to come into contact",example:"花に触れる — hana ni fureru — to touch a flower",pos:"verb",freq:7,register:"neutral"},
  {kr:"折る",ro:"oru",meaning:"to fold / to break (bone etc)",example:"紙を折る — kami wo oru — to fold paper",pos:"verb",freq:6,register:"neutral"},
  {kr:"曲げる",ro:"mageru",meaning:"to bend / to curve",example:"針金を曲げる — harigane wo mageru — to bend a wire",pos:"verb",freq:5,register:"neutral"},
  {kr:"結ぶ",ro:"musubu",meaning:"to tie / to connect / to form",example:"靴ひもを結ぶ — kutsu himo wo musubu — to tie shoelaces",pos:"verb",freq:6,register:"neutral"},
  {kr:"ほどく",ro:"hodoku",meaning:"to untie / to undo",example:"ひもをほどく — himo wo hodoku — to untie the string",pos:"verb",freq:5,register:"neutral"},
  {kr:"包む",ro:"tsutsumu",meaning:"to wrap / to pack",example:"プレゼントを包む — purezento wo tsutsumu — to wrap a gift",pos:"verb",freq:6,register:"neutral"},
  {kr:"外す",ro:"hazusu",meaning:"to remove / to take off / to miss",example:"ボタンを外す — botan wo hazusu — to undo a button",pos:"verb",freq:7,register:"neutral"},
  {kr:"付ける",ro:"tsukeru",meaning:"to attach / to turn on / to add",example:"ライトを付ける — raito wo tsukeru — to turn on the light",pos:"verb",freq:8,register:"neutral"},
  {kr:"消える",ro:"kieru",meaning:"to disappear / to go out",example:"ライトが消えた — raito ga kieta — the light went out",pos:"verb",freq:7,register:"neutral"},
  {kr:"育つ",ro:"sodatsu",meaning:"to grow up / to be raised",example:"田舎で育った — inaka de sodatta — I grew up in the countryside",pos:"verb",freq:6,register:"neutral"},
  {kr:"濡れる",ro:"nureru",meaning:"to get wet",example:"雨で濡れた — ame de nureta — I got wet in the rain",pos:"verb",freq:6,register:"neutral"},
  {kr:"乾く",ro:"kawaku",meaning:"to dry / to become dry",example:"洗濯物が乾く — sentakumono ga kawaku — the laundry dries",pos:"verb",freq:6,register:"neutral"},
  {kr:"汚れる",ro:"yogoreru",meaning:"to get dirty",example:"服が汚れた — fuku ga yogoreta — the clothes got dirty",pos:"verb",freq:6,register:"neutral"},
  {kr:"汚す",ro:"yogosu",meaning:"to make dirty / to stain",example:"シャツを汚す — shatsu wo yogosu — to stain a shirt",pos:"verb",freq:6,register:"neutral"},
  {kr:"いじる",ro:"ijiru",meaning:"to fiddle with / to touch / to tinker",example:"スマホをいじる — sumaho wo ijiru — to fiddle with a smartphone",pos:"verb",freq:6,register:"casual"},
  {kr:"眺める",ro:"nagameru",meaning:"to gaze at / to look out at",example:"海を眺める — umi wo nagameru — to gaze at the sea",pos:"verb",freq:6,register:"neutral"},
  {kr:"のぞく",ro:"nozoku",meaning:"to peek / to look into",example:"窓からのぞく — mado kara nozoku — to peek through the window",pos:"verb",freq:6,register:"casual"},
  {kr:"迎える",ro:"mukaeru",meaning:"to welcome / to go to meet",example:"駅で迎える — eki de mukaeru — to meet someone at the station",pos:"verb",freq:7,register:"neutral"},
  {kr:"見送る",ro:"miokuru",meaning:"to see off / to watch go",example:"空港で見送る — kuukou de miokuru — to see someone off at the airport",pos:"verb",freq:6,register:"neutral"},
  {kr:"訪ねる",ro:"tazuneru",meaning:"to visit / to call on",example:"友人を訪ねる — yuujin wo tazuneru — to visit a friend",pos:"verb",freq:6,register:"neutral"},
  {kr:"頼る",ro:"tayoru",meaning:"to rely on / to depend on",example:"友達に頼る — tomodachi ni tayoru — to rely on a friend",pos:"verb",freq:7,register:"neutral"},
  {kr:"養う",ro:"yashinau",meaning:"to support / to raise / to nurture",example:"家族を養う — kazoku wo yashinau — to support the family",pos:"verb",freq:5,register:"neutral"},
  {kr:"踏む",ro:"fumu",meaning:"to step on / to tread",example:"落ち葉を踏む — ochiba wo fumu — to step on fallen leaves",pos:"verb",freq:6,register:"neutral"},
  {kr:"蹴る",ro:"keru",meaning:"to kick",example:"ボールを蹴る — booru wo keru — to kick a ball",pos:"verb",freq:6,register:"neutral"},
  {kr:"殴る",ro:"naguru",meaning:"to punch / to hit",example:"壁を殴る — kabe wo naguru — to punch a wall",pos:"verb",freq:5,register:"neutral"},
  {kr:"握る",ro:"nigiru",meaning:"to grip / to hold / to squeeze",example:"手を握る — te wo nigiru — to hold someone's hand",pos:"verb",freq:6,register:"neutral"},
  {kr:"つかむ",ro:"tsukamu",meaning:"to grab / to catch / to seize",example:"チャンスをつかむ — chansu wo tsukamu — to seize a chance",pos:"verb",freq:7,register:"neutral"},
  {kr:"離す",ro:"hanasu",meaning:"to release / to let go / to separate",example:"手を離す — te wo hanasu — to let go of the hand",pos:"verb",freq:7,register:"neutral"},
  {kr:"投げかける",ro:"nagekakeru",meaning:"to throw at / to pose (a question)",example:"質問を投げかける — shitsumon wo nagekakeru — to pose a question",pos:"verb",freq:5,register:"neutral"},
  {kr:"叩き起こす",ro:"tataki okosu",meaning:"to wake someone up forcefully",example:"朝叩き起こされた — asa tataki okosareta — I was woken up forcefully in the morning",pos:"verb",freq:4,register:"casual"},

  // ── NATURE & WEATHER (extension) ────────────────────────────────────────────
  {kr:"大雪",ro:"ooyuki",meaning:"heavy snow",example:"大雪で交通が止まった — ooyuki de koutsuu ga tomatta — traffic stopped due to heavy snow",pos:"noun",freq:6,register:"neutral"},
  {kr:"吹雪",ro:"fubuki",meaning:"blizzard / snowstorm",example:"吹雪で前が見えない — fubuki de mae ga mienai — can't see ahead in the blizzard",pos:"noun",freq:5,register:"neutral"},
  {kr:"梅雨",ro:"tsuyu",meaning:"rainy season",example:"梅雨入りした — tsuyu iri shita — the rainy season has begun",pos:"noun",freq:7,register:"neutral"},
  {kr:"猛暑",ro:"mousho",meaning:"extreme heat / scorching heat",example:"今年は猛暑だ — kotoshi wa mousho da — it's scorching hot this year",pos:"noun",freq:6,register:"neutral"},
  {kr:"乾燥",ro:"kansou",meaning:"dryness / arid",example:"空気が乾燥している — kuuki ga kansou shite iru — the air is dry",pos:"noun",freq:7,register:"neutral"},
  {kr:"湿気",ro:"shikke",meaning:"humidity / moisture",example:"湿気が多い — shikke ga ooi — high humidity",pos:"noun",freq:6,register:"neutral"},
  {kr:"霜",ro:"shimo",meaning:"frost",example:"霜が降りた — shimo ga orita — frost fell",pos:"noun",freq:5,register:"neutral"},
  {kr:"霧雨",ro:"kirisame",meaning:"drizzle / light rain",example:"霧雨が降っている — kirisame ga futte iru — it's drizzling",pos:"noun",freq:5,register:"neutral"},
  {kr:"洪水",ro:"kouzui",meaning:"flood",example:"洪水で家が水没した — kouzui de ie ga suibotsu shita — the house was submerged in the flood",pos:"noun",freq:6,register:"neutral"},
  {kr:"干ばつ",ro:"kanbatsu",meaning:"drought",example:"干ばつで農作物が枯れた — kanbatsu de nousakumotsu ga kareta — crops withered due to drought",pos:"noun",freq:5,register:"neutral"},
  {kr:"崖",ro:"gake",meaning:"cliff / precipice",example:"崖から落ちる — gake kara ochiru — to fall off a cliff",pos:"noun",freq:5,register:"neutral"},
  {kr:"滝",ro:"taki",meaning:"waterfall",example:"大きな滝を見た — ookina taki wo mita — I saw a large waterfall",pos:"noun",freq:6,register:"neutral"},
  {kr:"池",ro:"ike",meaning:"pond",example:"池に魚がいる — ike ni sakana ga iru — there are fish in the pond",pos:"noun",freq:7,register:"neutral"},
  {kr:"沼",ro:"numa",meaning:"swamp / marsh",example:"沼に落ちた — numa ni ochita — I fell into the swamp",pos:"noun",freq:5,register:"neutral"},
  {kr:"岩",ro:"iwa",meaning:"rock / boulder",example:"大きな岩の上に座る — ookina iwa no ue ni suwaru — to sit on a large rock",pos:"noun",freq:7,register:"neutral"},
  {kr:"砂",ro:"suna",meaning:"sand",example:"砂で遊ぶ — suna de asobu — to play in the sand",pos:"noun",freq:6,register:"neutral"},
  {kr:"砂漠",ro:"sabaku",meaning:"desert",example:"砂漠を横断する — sabaku wo oudan suru — to cross a desert",pos:"noun",freq:6,register:"neutral"},
  {kr:"草原",ro:"sougen",meaning:"grassland / meadow",example:"広い草原が広がる — hiroi sougen ga hirogaru — a vast grassland stretches out",pos:"noun",freq:5,register:"neutral"},
  {kr:"雑草",ro:"zassou",meaning:"weed(s)",example:"庭の雑草を抜く — niwa no zassou wo nuku — to pull weeds from the garden",pos:"noun",freq:6,register:"neutral"},
  {kr:"種",ro:"tane",meaning:"seed / type / kind",example:"種をまく — tane wo maku — to sow seeds",pos:"noun",freq:7,register:"neutral"},
  {kr:"根",ro:"ne",meaning:"root",example:"木の根 — ki no ne — tree root",pos:"noun",freq:6,register:"neutral"},
  {kr:"枝",ro:"eda",meaning:"branch / twig",example:"木の枝を折る — ki no eda wo oru — to break a tree branch",pos:"noun",freq:6,register:"neutral"},
  {kr:"幹",ro:"miki",meaning:"tree trunk / main body",example:"太い幹の木 — futoi miki no ki — a tree with a thick trunk",pos:"noun",freq:5,register:"neutral"},
  {kr:"実",ro:"mi",meaning:"fruit / berry / nut (on a plant)",example:"実がなる — mi ga naru — fruit grows",pos:"noun",freq:7,register:"neutral"},
  {kr:"波",ro:"nami",meaning:"wave",example:"波が高い — nami ga takai — the waves are high",pos:"noun",freq:7,register:"neutral"},
  {kr:"潮",ro:"shio",meaning:"tide / salt water / sea",example:"潮の香りがする — shio no kaori ga suru — the smell of the sea",pos:"noun",freq:6,register:"neutral"},
  {kr:"虹",ro:"niji",meaning:"rainbow",example:"雨上がりに虹が出た — ameagari ni niji ga deta — a rainbow appeared after the rain",pos:"noun",freq:7,register:"neutral"},
  {kr:"夕焼け",ro:"yuuyake",meaning:"sunset glow / evening glow",example:"綺麗な夕焼け — kirei na yuuyake — a beautiful sunset",pos:"noun",freq:7,register:"neutral"},
  {kr:"日の出",ro:"hinode",meaning:"sunrise",example:"日の出を見た — hinode wo mita — I watched the sunrise",pos:"noun",freq:6,register:"neutral"},
  {kr:"日の入り",ro:"hinoiri",meaning:"sunset",example:"日の入りは6時頃 — hinoiri wa rokuji goro — sunset is around 6",pos:"noun",freq:5,register:"neutral"},
  {kr:"月明かり",ro:"tsukiakari",meaning:"moonlight",example:"月明かりの夜 — tsukiakari no yoru — a moonlit night",pos:"noun",freq:5,register:"neutral"},

  // ── HOUSING & HOUSEHOLD OBJECTS (extension) ──────────────────────────────────
  {kr:"天井",ro:"tenjou",meaning:"ceiling",example:"天井が高い — tenjou ga takai — the ceiling is high",pos:"noun",freq:6,register:"neutral"},
  {kr:"廊下",ro:"rouka",meaning:"hallway / corridor",example:"廊下を走らないで — rouka wo hashiranai de — don't run in the hallway",pos:"noun",freq:6,register:"neutral"},
  {kr:"押し入れ",ro:"oshiire",meaning:"Japanese closet / built-in cupboard",example:"押し入れに布団を入れる — oshiire ni futon wo ireru — to put the futon in the closet",pos:"noun",freq:6,register:"neutral"},
  {kr:"クローゼット",ro:"kuroozetto",meaning:"closet / wardrobe",example:"服をクローゼットにしまう — fuku wo kuroozetto ni shimau — to put clothes in the closet",pos:"noun",freq:7,register:"neutral"},
  {kr:"引き出し",ro:"hikidashi",meaning:"drawer",example:"引き出しを開ける — hikidashi wo akeru — to open a drawer",pos:"noun",freq:6,register:"neutral"},
  {kr:"布団",ro:"futon",meaning:"futon / Japanese bedding",example:"布団を敷く — futon wo shiku — to lay out the futon",pos:"noun",freq:7,register:"neutral"},
  {kr:"まくら",ro:"makura",meaning:"pillow",example:"まくらを替える — makura wo kaeru — to change the pillow",pos:"noun",freq:6,register:"neutral"},
  {kr:"毛布",ro:"moufu",meaning:"blanket",example:"毛布をかける — moufu wo kakeru — to put on a blanket",pos:"noun",freq:6,register:"neutral"},
  {kr:"シーツ",ro:"shiitsu",meaning:"sheet (bedding)",example:"シーツを洗う — shiitsu wo arau — to wash the sheets",pos:"noun",freq:6,register:"neutral"},
  {kr:"タオル",ro:"taoru",meaning:"towel",example:"タオルで拭く — taoru de fuku — to wipe with a towel",pos:"noun",freq:8,register:"neutral"},
  {kr:"せっけん",ro:"sekken",meaning:"soap",example:"せっけんで洗う — sekken de arau — to wash with soap",pos:"noun",freq:7,register:"neutral"},
  {kr:"シャンプー",ro:"shanpuu",meaning:"shampoo",example:"シャンプーで髪を洗う — shanpuu de kami wo arau — to wash hair with shampoo",pos:"noun",freq:7,register:"neutral"},
  {kr:"トイレットペーパー",ro:"toiretto peepaa",meaning:"toilet paper",example:"トイレットペーパーが切れた — toiretto peepaa ga kireta — the toilet paper ran out",pos:"noun",freq:6,register:"neutral"},
  {kr:"ゴミ箱",ro:"gomibako",meaning:"trash can / waste bin",example:"ゴミ箱に捨てる — gomibako ni suteru — to throw in the trash can",pos:"noun",freq:7,register:"neutral"},
  {kr:"鍵穴",ro:"kagiana",meaning:"keyhole",example:"鍵穴に鍵を入れる — kagiana ni kagi wo ireru — to put the key in the keyhole",pos:"noun",freq:4,register:"neutral"},
  {kr:"玄関マット",ro:"genkan matto",meaning:"doormat / entrance mat",example:"玄関マットで靴を拭く — genkan matto de kutsu wo fuku — to wipe shoes on the doormat",pos:"noun",freq:4,register:"neutral"},
  {kr:"スリッパ",ro:"surippa",meaning:"slippers",example:"スリッパに履き替える — surippa ni hakikaeru — to change into slippers",pos:"noun",freq:6,register:"neutral"},
  {kr:"コンセント",ro:"konsento",meaning:"electrical outlet / socket",example:"コンセントに挿す — konsento ni sasu — to plug into the outlet",pos:"noun",freq:7,register:"neutral"},
  {kr:"延長コード",ro:"enchoukoodo",meaning:"extension cord",example:"延長コードを使う — enchoukoodo wo tsukau — to use an extension cord",pos:"noun",freq:5,register:"neutral"},
  {kr:"蛇口",ro:"jaguchi",meaning:"faucet / tap",example:"蛇口をひねる — jaguchi wo hineru — to turn the faucet",pos:"noun",freq:6,register:"neutral"},
  {kr:"ガス",ro:"gasu",meaning:"gas (fuel)",example:"ガスを止める — gasu wo tomeru — to turn off the gas",pos:"noun",freq:7,register:"neutral"},
  {kr:"水道",ro:"suidou",meaning:"water supply / tap water",example:"水道代を払う — suidoudai wo harau — to pay the water bill",pos:"noun",freq:6,register:"neutral"},
  {kr:"電気代",ro:"denkidai",meaning:"electricity bill",example:"電気代が高い — denkidai ga takai — the electricity bill is high",pos:"noun",freq:6,register:"neutral"},
  {kr:"ガス代",ro:"gasudai",meaning:"gas bill",example:"ガス代を節約する — gasudai wo setsuyaku suru — to save on the gas bill",pos:"noun",freq:5,register:"neutral"},

  // ── TRANSPORT & GETTING AROUND (extension) ──────────────────────────────────
  {kr:"乗り換え",ro:"norikae",meaning:"transfer / connection (transport)",example:"乗り換えが必要です — norikae ga hitsuyou desu — a transfer is necessary",pos:"noun",freq:7,register:"neutral"},
  {kr:"乗り場",ro:"noriba",meaning:"boarding area / platform",example:"バスの乗り場はどこですか？ — basu no noriba wa doko desu ka? — where is the bus stop?",pos:"noun",freq:6,register:"neutral"},
  {kr:"時刻表",ro:"jikokuhyou",meaning:"timetable / schedule",example:"時刻表を確認する — jikokuhyou wo kakunin suru — to check the timetable",pos:"noun",freq:6,register:"neutral"},
  {kr:"定期券",ro:"teikiken",meaning:"commuter pass / season ticket",example:"定期券を買う — teikiken wo kau — to buy a commuter pass",pos:"noun",freq:6,register:"neutral"},
  {kr:"回数券",ro:"kaisuuken",meaning:"book of tickets / multi-ride pass",example:"バスの回数券を使う — basu no kaisuuken wo tsukau — to use a bus multi-ride pass",pos:"noun",freq:5,register:"neutral"},
  {kr:"急行",ro:"kyuukou",meaning:"express (train)",example:"急行に乗る — kyuukou ni noru — to take the express",pos:"noun",freq:7,register:"neutral"},
  {kr:"各駅停車",ro:"kakueki teisha",meaning:"local train (stops at every station)",example:"各駅停車で行く — kakueki teisha de iku — to go by local train",pos:"noun",freq:5,register:"neutral"},
  {kr:"終電",ro:"shuuden",meaning:"last train",example:"終電を逃した — shuuden wo nogashita — I missed the last train",pos:"noun",freq:7,register:"casual"},
  {kr:"満員電車",ro:"manin densha",meaning:"packed train",example:"満員電車は辛い — manin densha wa tsurai — packed trains are tough",pos:"noun",freq:6,register:"casual"},
  {kr:"踏切",ro:"fumikiri",meaning:"railroad crossing",example:"踏切を渡る — fumikiri wo wataru — to cross the railroad crossing",pos:"noun",freq:5,register:"neutral"},
  {kr:"駐車場",ro:"chuushajou",meaning:"parking lot",example:"駐車場を探す — chuushajou wo sagasu — to look for a parking lot",pos:"noun",freq:7,register:"neutral"},
  {kr:"渋滞",ro:"juutai",meaning:"traffic jam / congestion",example:"渋滞にはまる — juutai ni hamaru — to get stuck in traffic",pos:"noun",freq:7,register:"neutral"},
  {kr:"スピード違反",ro:"supiido ihan",meaning:"speeding (traffic violation)",example:"スピード違反で捕まった — supiido ihan de tsukamatta — I was caught speeding",pos:"noun",freq:5,register:"neutral"},
  {kr:"信号",ro:"shingou",meaning:"traffic light / signal",example:"信号が赤になった — shingou ga aka ni natta — the traffic light turned red",pos:"noun",freq:8,register:"neutral"},
  {kr:"横断歩道",ro:"oudanhodou",meaning:"pedestrian crossing / crosswalk",example:"横断歩道を渡る — oudanhodou wo wataru — to cross at the crosswalk",pos:"noun",freq:7,register:"neutral"},
  {kr:"歩道",ro:"hodou",meaning:"sidewalk / footpath",example:"歩道を歩く — hodou wo aruku — to walk on the sidewalk",pos:"noun",freq:7,register:"neutral"},
  {kr:"車線",ro:"shasen",meaning:"traffic lane",example:"右の車線を走る — migi no shasen wo hashiru — to drive in the right lane",pos:"noun",freq:5,register:"neutral"},
  {kr:"高速道路",ro:"kousoku douro",meaning:"highway / expressway",example:"高速道路を使う — kousoku douro wo tsukau — to use the expressway",pos:"noun",freq:6,register:"neutral"},
  {kr:"ICカード",ro:"ai shii kaado",meaning:"IC card / transit card",example:"ICカードで払う — ai shii kaado de harau — to pay with an IC card",pos:"noun",freq:7,register:"neutral"},
  {kr:"Suica",ro:"suika",meaning:"Suica (transit card)",example:"SuicaでJRに乗る — suika de jei aru ni noru — to ride JR with Suica",pos:"noun",freq:7,register:"neutral"},

  // ── SHOPPING (extension) ────────────────────────────────────────────────────
  {kr:"値引き",ro:"nebiki",meaning:"price reduction / markdown",example:"値引きしてもらった — nebiki shite moratta — I got a price reduction",pos:"noun",freq:6,register:"neutral"},
  {kr:"定価",ro:"teika",meaning:"list price / retail price",example:"定価の半額で買った — teika no hangaku de katta — I bought it for half the list price",pos:"noun",freq:6,register:"neutral"},
  {kr:"セール",ro:"seeru",meaning:"sale",example:"セール中の商品 — seeru chuu no shouhin — items on sale",pos:"noun",freq:8,register:"neutral"},
  {kr:"在庫",ro:"zaiko",meaning:"stock / inventory",example:"在庫切れです — zaiko gire desu — out of stock",pos:"noun",freq:6,register:"neutral"},
  {kr:"おつり",ro:"otsuri",meaning:"change (money returned)",example:"おつりをください — otsuri wo kudasai — please give me my change",pos:"noun",freq:7,register:"neutral"},
  {kr:"消費税",ro:"shouhizei",meaning:"consumption tax / sales tax",example:"消費税込みの値段 — shouhizei komi no nedan — price including tax",pos:"noun",freq:7,register:"neutral"},
  {kr:"ポイントカード",ro:"pointo kaado",meaning:"points card / loyalty card",example:"ポイントカードはありますか？ — pointo kaado wa arimasu ka? — do you have a points card?",pos:"noun",freq:7,register:"neutral"},
  {kr:"試着",ro:"shichaku",meaning:"trying on (clothes)",example:"試着してもいいですか？ — shichaku shite mo ii desu ka? — may I try this on?",pos:"noun",freq:6,register:"neutral"},
  {kr:"返品",ro:"henpin",meaning:"return (of purchased goods)",example:"返品したい — henpin shitai — I want to return this",pos:"noun",freq:6,register:"neutral"},
  {kr:"交換",ro:"koukan",meaning:"exchange / swap",example:"サイズを交換したい — saizu wo koukan shitai — I want to exchange the size",pos:"noun",freq:7,register:"neutral"},
  {kr:"袋",ro:"fukuro",meaning:"bag / pouch / sack",example:"袋に入れてください — fukuro ni irete kudasai — please put it in a bag",pos:"noun",freq:8,register:"neutral"},
  {kr:"包装",ro:"housou",meaning:"packaging / wrapping",example:"プレゼント用に包装する — purezento you ni housou suru — to wrap for a gift",pos:"noun",freq:5,register:"neutral"},
  {kr:"ネットショッピング",ro:"netto shoppingu",meaning:"online shopping",example:"最近ネットショッピングをよく使う — saikin netto shoppingu wo yoku tsukau — I often use online shopping recently",pos:"noun",freq:7,register:"neutral"},
  {kr:"送料",ro:"souryo",meaning:"shipping fee / postage",example:"送料無料 — souryo muryou — free shipping",pos:"noun",freq:6,register:"neutral"},

  // ── FOOD & COOKING (extension) ──────────────────────────────────────────────
  {kr:"食欲",ro:"shokuyoku",meaning:"appetite",example:"食欲がない — shokuyoku ga nai — I have no appetite",pos:"noun",freq:7,register:"neutral"},
  {kr:"胃袋",ro:"ibukuro",meaning:"stomach (informal)",example:"胃袋をつかむ — ibukuro wo tsukamu — to win someone's heart through food",pos:"noun",freq:5,register:"casual"},
  {kr:"レシピ",ro:"reshipi",meaning:"recipe",example:"レシピを調べる — reshipi wo shiraberu — to look up a recipe",pos:"noun",freq:8,register:"neutral"},
  {kr:"材料",ro:"zairyou",meaning:"ingredients / materials",example:"材料を揃える — zairyou wo soroeru — to gather the ingredients",pos:"noun",freq:7,register:"neutral"},
  {kr:"分量",ro:"bunryou",meaning:"amount / quantity (recipe)",example:"分量を量る — bunryou wo hakaru — to measure the quantity",pos:"noun",freq:6,register:"neutral"},
  {kr:"下準備",ro:"shitajunbi",meaning:"prep work / mise en place",example:"料理の下準備をする — ryouri no shitajunbi wo suru — to do prep work for cooking",pos:"noun",freq:5,register:"neutral"},
  {kr:"味付け",ro:"ajitsuke",meaning:"seasoning / flavoring",example:"味付けが濃い — ajitsuke ga koi — heavily seasoned",pos:"noun",freq:6,register:"neutral"},
  {kr:"盛り付け",ro:"moritsuke",meaning:"plating / food presentation",example:"盛り付けが綺麗 — moritsuke ga kirei — the plating is beautiful",pos:"noun",freq:5,register:"neutral"},
  {kr:"茹でる",ro:"yuderu",meaning:"to boil / to parboil",example:"卵を茹でる — tamago wo yuderu — to boil an egg",pos:"verb",freq:6,register:"neutral"},
  {kr:"炊く",ro:"taku",meaning:"to cook rice / to boil",example:"ご飯を炊く — gohan wo taku — to cook rice",pos:"verb",freq:7,register:"neutral"},
  {kr:"ポタージュ",ro:"potaaju",meaning:"potage / thick soup",example:"かぼちゃのポタージュ — kabocha no potaaju — pumpkin potage",pos:"noun",freq:4,register:"neutral"},
  {kr:"鰹節",ro:"katsuobushi",meaning:"dried bonito flakes",example:"鰹節でだしを取る — katsuobushi de dashi wo toru — to make broth with bonito flakes",pos:"noun",freq:5,register:"neutral"},
  {kr:"だし",ro:"dashi",meaning:"broth / stock (Japanese)",example:"だしで煮る — dashi de niru — to simmer in broth",pos:"noun",freq:6,register:"neutral"},
  {kr:"味噌",ro:"miso",meaning:"miso paste",example:"味噌を溶かす — miso wo tokasu — to dissolve miso paste",pos:"noun",freq:7,register:"neutral"},
  {kr:"酢",ro:"su",meaning:"vinegar",example:"酢をかける — su wo kakeru — to pour vinegar on",pos:"noun",freq:6,register:"neutral"},
  {kr:"みりん",ro:"mirin",meaning:"mirin (sweet cooking rice wine)",example:"みりんを加える — mirin wo kuwaeru — to add mirin",pos:"noun",freq:6,register:"neutral"},
  {kr:"かぼちゃ",ro:"kabocha",meaning:"pumpkin / squash",example:"かぼちゃの煮物 — kabocha no nimono — simmered pumpkin",pos:"noun",freq:6,register:"neutral"},
  {kr:"ほうれん草",ro:"hourensou",meaning:"spinach",example:"ほうれん草のおひたし — hourensou no ohitashi — boiled spinach salad",pos:"noun",freq:6,register:"neutral"},
  {kr:"もやし",ro:"moyashi",meaning:"bean sprouts",example:"もやし炒め — moyashi itame — stir-fried bean sprouts",pos:"noun",freq:6,register:"neutral"},
  {kr:"ねぎ",ro:"negi",meaning:"green onion / scallion / leek",example:"ねぎを刻む — negi wo kizamu — to chop green onion",pos:"noun",freq:7,register:"neutral"},
  {kr:"大根",ro:"daikon",meaning:"daikon radish",example:"大根おろし — daikon oroshi — grated daikon",pos:"noun",freq:7,register:"neutral"},
  {kr:"れんこん",ro:"renkon",meaning:"lotus root",example:"れんこんのきんぴら — renkon no kinpira — stir-fried lotus root",pos:"noun",freq:5,register:"neutral"},
  {kr:"ごぼう",ro:"gobou",meaning:"burdock root",example:"ごぼうサラダ — gobou sarada — burdock salad",pos:"noun",freq:5,register:"neutral"},
  {kr:"とうもろこし",ro:"toumorokoshi",meaning:"corn",example:"とうもろこしを茹でる — toumorokoshi wo yuderu — to boil corn",pos:"noun",freq:6,register:"neutral"},
  {kr:"なす",ro:"nasu",meaning:"eggplant / aubergine",example:"なすの炒め物 — nasu no itamemono — stir-fried eggplant",pos:"noun",freq:6,register:"neutral"},
  {kr:"ピーマン",ro:"piiman",meaning:"bell pepper / green pepper",example:"ピーマンが苦手 — piiman ga nigate — I'm not good with bell peppers",pos:"noun",freq:6,register:"neutral"},
  {kr:"ブロッコリー",ro:"burokkorii",meaning:"broccoli",example:"ブロッコリーを茹でる — burokkorii wo yuderu — to boil broccoli",pos:"noun",freq:6,register:"neutral"},
  {kr:"豚肉",ro:"butaniku",meaning:"pork",example:"豚肉を炒める — butaniku wo itatmeru — to stir-fry pork",pos:"noun",freq:7,register:"neutral"},
  {kr:"牛肉",ro:"gyuuniku",meaning:"beef",example:"牛肉のステーキ — gyuuniku no suteeki — beef steak",pos:"noun",freq:7,register:"neutral"},
  {kr:"鶏肉",ro:"toriniku",meaning:"chicken (meat)",example:"鶏肉を焼く — toriniku wo yaku — to grill chicken",pos:"noun",freq:7,register:"neutral"},
  {kr:"刺身",ro:"sashimi",meaning:"sashimi / raw fish",example:"マグロの刺身 — maguro no sashimi — tuna sashimi",pos:"noun",freq:7,register:"neutral"},
  {kr:"味",ro:"aji",meaning:"taste / flavor",example:"この料理の味はどうですか？ — kono ryouri no aji wa dou desu ka? — how does this dish taste?",pos:"noun",freq:9,register:"neutral"},
  {kr:"においがする",ro:"nioi ga suru",meaning:"to smell (of something)",example:"焦げたにおいがする — kogeta nioi ga suru — there's a burning smell",pos:"expression",freq:7,register:"neutral"},
  {kr:"冷める",ro:"sameru",meaning:"to cool down / to go cold (food)",example:"料理が冷めた — ryouri ga sameta — the food got cold",pos:"verb",freq:7,register:"neutral"},
  {kr:"温める",ro:"atatameru",meaning:"to warm up / to heat",example:"電子レンジで温める — denshi renji de atatameru — to heat in the microwave",pos:"verb",freq:7,register:"neutral"},
  {kr:"解凍する",ro:"kaitou suru",meaning:"to defrost / to thaw",example:"冷凍食品を解凍する — reito shokuhin wo kaitou suru — to defrost frozen food",pos:"verb",freq:6,register:"neutral"},
  {kr:"冷凍する",ro:"reitou suru",meaning:"to freeze",example:"余ったご飯を冷凍する — amatta gohan wo reitou suru — to freeze leftover rice",pos:"verb",freq:6,register:"neutral"},
  {kr:"冷蔵する",ro:"reizou suru",meaning:"to refrigerate",example:"余りは冷蔵してください — amari wa reizou shite kudasai — please refrigerate the leftovers",pos:"verb",freq:5,register:"neutral"},
  {kr:"腐る",ro:"kusaru",meaning:"to rot / to spoil / to go bad",example:"食べ物が腐った — tabemono ga kusatta — the food spoiled",pos:"verb",freq:6,register:"neutral"},

  // ── EMOTIONS & PSYCHOLOGY (extension) ──────────────────────────────────────
  {kr:"感情",ro:"kanjou",meaning:"emotion / feeling",example:"感情を表現する — kanjou wo hyougen suru — to express emotions",pos:"noun",freq:8,register:"neutral"},
  {kr:"喜怒哀楽",ro:"kidoairaku",meaning:"the four emotions (joy, anger, grief, pleasure)",example:"喜怒哀楽が激しい — kidoairaku ga hageshii — has strong emotions",pos:"noun",freq:5,register:"neutral"},
  {kr:"緊張",ro:"kinchou",meaning:"tension / nervousness / being tense",example:"緊張してきた — kinchou shite kita — I'm getting nervous",pos:"noun",freq:8,register:"neutral"},
  {kr:"リラックス",ro:"rirakkusu",meaning:"relaxation / to relax",example:"リラックスする — rirakkusu suru — to relax",pos:"noun",freq:8,register:"neutral"},
  {kr:"焦り",ro:"aseri",meaning:"impatience / panic / anxiety",example:"焦りを感じる — aseri wo kanjiru — to feel impatient",pos:"noun",freq:6,register:"neutral"},
  {kr:"焦る",ro:"aseru",meaning:"to be impatient / to panic",example:"焦らないで — asera nai de — don't panic",pos:"verb",freq:7,register:"neutral"},
  {kr:"うらやむ",ro:"urayamu",meaning:"to envy",example:"友達をうらやむ — tomodachi wo urayamu — to envy a friend",pos:"verb",freq:5,register:"neutral"},
  {kr:"妬む",ro:"netamu",meaning:"to be jealous of / to envy",example:"成功を妬む — seikou wo netamu — to be jealous of success",pos:"verb",freq:5,register:"neutral"},
  {kr:"甘える",ro:"amaeru",meaning:"to depend on / to act spoiled",example:"親に甘える — oya ni amaeru — to act spoiled with parents",pos:"verb",freq:6,register:"casual"},
  {kr:"照れくさい",ro:"terekusai",meaning:"embarrassed / shy / awkward",example:"照れくさくて言えない — terekusai kute ienai — too embarrassed to say it",pos:"adjective",freq:6,register:"casual"},
  {kr:"うんざり",ro:"unzari",meaning:"fed up / disgusted / sick of",example:"もううんざりだ — mou unzari da — I'm completely fed up",pos:"adverb",freq:6,register:"casual"},
  {kr:"ほっとする",ro:"hotto suru",meaning:"to feel relieved",example:"終わってほっとした — owatte hotto shita — I felt relieved when it was over",pos:"expression",freq:7,register:"neutral"},
  {kr:"ドキッとする",ro:"doki tto suru",meaning:"to be startled / heart skips a beat",example:"突然声をかけられてドキッとした — totsuzen koe wo kakerarete doki tto shita — I was startled when someone suddenly spoke to me",pos:"expression",freq:6,register:"casual"},
  {kr:"うっとりする",ro:"uttori suru",meaning:"to be enchanted / to be captivated",example:"美しい音楽にうっとりする — utsukushii ongaku ni uttori suru — to be enchanted by beautiful music",pos:"expression",freq:5,register:"neutral"},
  {kr:"気が重い",ro:"ki ga omoi",meaning:"feeling heavy-hearted / dreading something",example:"会議の前は気が重い — kaigi no mae wa ki ga omoi — I dread things before meetings",pos:"expression",freq:6,register:"neutral"},
  {kr:"気が楽になる",ro:"ki ga raku ni naru",meaning:"to feel relieved / to feel lighter",example:"話して気が楽になった — hanashite ki ga raku ni natta — talking made me feel better",pos:"expression",freq:6,register:"neutral"},
  {kr:"ムカムカする",ro:"mukamuka suru",meaning:"to feel nauseated / to feel irritated",example:"ムカムカして気持ち悪い — mukamuka shite kimochi warui — feeling nauseated",pos:"expression",freq:5,register:"casual"},
  {kr:"ぞっとする",ro:"zotto suru",meaning:"to shudder / to be horrified",example:"ぞっとするような話 — zotto suru you na hanashi — a horrifying story",pos:"expression",freq:5,register:"neutral"},

  // ── SOCIAL LIFE & RELATIONSHIPS (extension) ────────────────────────────────
  {kr:"恋人",ro:"koibito",meaning:"lover / partner / boyfriend or girlfriend",example:"恋人と旅行する — koibito to ryokou suru — to travel with a partner",pos:"noun",freq:7,register:"neutral"},
  {kr:"元彼",ro:"motokare",meaning:"ex-boyfriend",example:"元彼に会った — motokare ni atta — I ran into my ex-boyfriend",pos:"noun",freq:5,register:"casual"},
  {kr:"元カノ",ro:"moto kano",meaning:"ex-girlfriend",example:"元カノから連絡がきた — moto kano kara renraku ga kita — I heard from my ex-girlfriend",pos:"noun",freq:5,register:"casual"},
  {kr:"片思い",ro:"kataomoi",meaning:"unrequited love",example:"片思いで辛い — kataomoi de tsurai — unrequited love is painful",pos:"noun",freq:6,register:"casual"},
  {kr:"両思い",ro:"ryouomoi",meaning:"mutual feelings / both liking each other",example:"両思いだと知った — ryouomoi da to shitta — I found out we both like each other",pos:"noun",freq:5,register:"casual"},
  {kr:"デート",ro:"deeto",meaning:"date (romantic)",example:"デートに誘う — deeto ni sasou — to ask someone out on a date",pos:"noun",freq:8,register:"casual"},
  {kr:"告白",ro:"kokuhaku",meaning:"confession of love",example:"告白が成功した — kokuhaku ga seikou shita — the love confession succeeded",pos:"noun",freq:7,register:"casual"},
  {kr:"振る",ro:"furu",meaning:"to reject / to dump",example:"告白したら振られた — kokuhaku shitara furareta — I was rejected when I confessed",pos:"verb",freq:6,register:"casual"},
  {kr:"別れ話",ro:"wakarebana shi",meaning:"breakup talk / ending a relationship",example:"別れ話をされた — wakarebana shi wo sareta — I was broken up with",pos:"noun",freq:5,register:"casual"},
  {kr:"よりを戻す",ro:"yori wo modosu",meaning:"to get back together",example:"元彼とよりを戻した — motokare to yori wo modoshita — I got back together with my ex",pos:"expression",freq:4,register:"casual"},
  {kr:"縁",ro:"en",meaning:"fate / bond / connection / relationship",example:"縁があって知り合った — en ga atte shiriai atta — we met by chance/fate",pos:"noun",freq:6,register:"neutral"},
  {kr:"気が合う",ro:"ki ga au",meaning:"to get along / to click",example:"彼とは気が合う — kare to wa ki ga au — I click with him",pos:"expression",freq:6,register:"casual"},
  {kr:"仲がいい",ro:"naka ga ii",meaning:"on good terms / close",example:"二人は仲がいい — futari wa naka ga ii — the two are close",pos:"expression",freq:7,register:"neutral"},
  {kr:"仲が悪い",ro:"naka ga warui",meaning:"on bad terms / not getting along",example:"最近仲が悪い — saikin naka ga warui — we've been on bad terms lately",pos:"expression",freq:6,register:"casual"},
  {kr:"誤解",ro:"gokai",meaning:"misunderstanding",example:"誤解がある — gokai ga aru — there's a misunderstanding",pos:"noun",freq:7,register:"neutral"},
  {kr:"和解",ro:"wakai",meaning:"reconciliation / settlement",example:"二人は和解した — futari wa wakai shita — the two reconciled",pos:"noun",freq:5,register:"neutral"},
  {kr:"世話をする",ro:"sewa wo suru",meaning:"to look after / to take care of",example:"ペットの世話をする — petto no sewa wo suru — to take care of a pet",pos:"expression",freq:7,register:"neutral"},

  // ── COMMUNICATION & LANGUAGE (extension) ────────────────────────────────────
  {kr:"伝える",ro:"tsutaeru",meaning:"to convey / to communicate / to pass on",example:"気持ちを伝える — kimochi wo tsutaeru — to convey one's feelings",pos:"verb",freq:8,register:"neutral"},
  {kr:"伝わる",ro:"tsutawaru",meaning:"to be conveyed / to reach / to spread",example:"気持ちが伝わった — kimochi ga tsutawatta — my feelings were conveyed",pos:"verb",freq:7,register:"neutral"},
  {kr:"遠回し",ro:"toomawashi",meaning:"indirect / roundabout",example:"遠回しに言う — toomawashi ni iu — to say it indirectly",pos:"noun",freq:5,register:"neutral"},
  {kr:"はっきり言う",ro:"hakkiri iu",meaning:"to say clearly / to speak plainly",example:"はっきり言ってください — hakkiri itte kudasai — please say it clearly",pos:"expression",freq:7,register:"neutral"},
  {kr:"遠慮する",ro:"enryo suru",meaning:"to hold back / to refrain / to be reserved",example:"遠慮しないで食べてください — enryo shinai de tabete kudasai — please eat without holding back",pos:"verb",freq:7,register:"neutral"},
  {kr:"気を遣う",ro:"ki wo tsukau",meaning:"to be considerate / to be thoughtful",example:"彼はいつも気を遣う — kare wa itsumo ki wo tsukau — he is always considerate",pos:"expression",freq:6,register:"neutral"},
  {kr:"話題",ro:"wadai",meaning:"topic / subject of conversation",example:"話題を変える — wadai wo kaeru — to change the topic",pos:"noun",freq:7,register:"neutral"},
  {kr:"うわさ話",ro:"uwasabanashi",meaning:"gossip",example:"うわさ話が好き — uwasabanashi ga suki — I like gossip",pos:"noun",freq:5,register:"casual"},
  {kr:"言い訳",ro:"iiwake",meaning:"excuse",example:"言い訳をしない — iiwake wo shinai — to not make excuses",pos:"noun",freq:7,register:"neutral"},
  {kr:"説得",ro:"settoku",meaning:"persuasion",example:"説得に成功した — settoku ni seikou shita — the persuasion succeeded",pos:"noun",freq:6,register:"neutral"},
  {kr:"議論",ro:"giron",meaning:"argument / debate / discussion",example:"議論が白熱した — giron ga hakunetsu shita — the debate got heated",pos:"noun",freq:6,register:"neutral"},
  {kr:"反論",ro:"hanron",meaning:"counterargument / rebuttal",example:"反論する — hanron suru — to argue back",pos:"noun",freq:5,register:"neutral"},
  {kr:"つぶやく",ro:"tsubuyaku",meaning:"to mutter / to whisper / to tweet",example:"ひとりごとをつぶやく — hitorigoto wo tsubuyaku — to mutter to oneself",pos:"verb",freq:5,register:"neutral"},

  // ── TECHNOLOGY (extension) ──────────────────────────────────────────────────
  {kr:"充電器",ro:"juudenki",meaning:"charger",example:"充電器を忘れた — juudenki wo wasureta — I forgot my charger",pos:"noun",freq:7,register:"neutral"},
  {kr:"ケーブル",ro:"keeburu",meaning:"cable / cord",example:"USBケーブルをつなぐ — USB keeburu wo tsunagu — to connect a USB cable",pos:"noun",freq:7,register:"neutral"},
  {kr:"イヤホン",ro:"iyahon",meaning:"earphones / earbuds",example:"イヤホンで音楽を聴く — iyahon de ongaku wo kiku — to listen to music with earphones",pos:"noun",freq:8,register:"neutral"},
  {kr:"スピーカー",ro:"supiikaa",meaning:"speaker",example:"スピーカーで音楽を流す — supiikaa de ongaku wo nagasu — to play music through a speaker",pos:"noun",freq:7,register:"neutral"},
  {kr:"プリンター",ro:"purintaa",meaning:"printer",example:"プリンターで印刷する — purintaa de insatsu suru — to print with a printer",pos:"noun",freq:6,register:"neutral"},
  {kr:"スキャン",ro:"sukyan",meaning:"scan / scanning",example:"書類をスキャンする — shorui wo sukyan suru — to scan a document",pos:"noun",freq:6,register:"neutral"},
  {kr:"クリック",ro:"kurikku",meaning:"click",example:"ボタンをクリックする — botan wo kurikku suru — to click a button",pos:"noun",freq:7,register:"neutral"},
  {kr:"スクロール",ro:"sukurooru",meaning:"scroll",example:"画面をスクロールする — gamen wo sukurooru suru — to scroll the screen",pos:"noun",freq:7,register:"neutral"},
  {kr:"アップデート",ro:"appudeeto",meaning:"update",example:"アプリをアップデートする — apuri wo appudeeto suru — to update an app",pos:"noun",freq:7,register:"neutral"},
  {kr:"バグ",ro:"bagu",meaning:"bug (software)",example:"バグを修正する — bagu wo shuusei suru — to fix a bug",pos:"noun",freq:6,register:"neutral"},
  {kr:"フォルダ",ro:"foruda",meaning:"folder",example:"フォルダを作成する — foruda wo sakusei suru — to create a folder",pos:"noun",freq:6,register:"neutral"},
  {kr:"スマートウォッチ",ro:"sumaato wocchi",meaning:"smartwatch",example:"スマートウォッチで通知を確認する — sumaato wocchi de tsuuchi wo kakunin suru — to check notifications on a smartwatch",pos:"noun",freq:6,register:"neutral"},
  {kr:"タブレット",ro:"taburetto",meaning:"tablet (device)",example:"タブレットで本を読む — taburetto de hon wo yomu — to read a book on a tablet",pos:"noun",freq:7,register:"neutral"},
  {kr:"QRコード",ro:"kyuu aru koodo",meaning:"QR code",example:"QRコードを読み取る — kyuu aru koodo wo yomitoru — to scan a QR code",pos:"noun",freq:7,register:"neutral"},
  {kr:"通知",ro:"tsuuchi",meaning:"notification",example:"通知をオフにする — tsuuchi wo ofu ni suru — to turn off notifications",pos:"noun",freq:7,register:"neutral"},
  {kr:"ログイン",ro:"roguin",meaning:"log in",example:"アカウントにログインする — akaunto ni roguin suru — to log in to an account",pos:"noun",freq:7,register:"neutral"},
  {kr:"ログアウト",ro:"rogauto",meaning:"log out",example:"ログアウトを忘れずに — rogauto wo wasurezu ni — don't forget to log out",pos:"noun",freq:6,register:"neutral"},
  {kr:"データ",ro:"deeta",meaning:"data",example:"データをバックアップする — deeta wo bakkuappu suru — to back up data",pos:"noun",freq:8,register:"neutral"},
  {kr:"ストレージ",ro:"sutoreejji",meaning:"storage",example:"ストレージが足りない — sutoreejji ga tarinai — storage is running out",pos:"noun",freq:6,register:"neutral"},
  {kr:"スクリーンショット",ro:"sukuriin shotto",meaning:"screenshot",example:"スクリーンショットを撮る — sukuriin shotto wo toru — to take a screenshot",pos:"noun",freq:7,register:"casual"},

  // ── SPORTS & HOBBIES (extension) ────────────────────────────────────────────
  {kr:"運動会",ro:"undoukai",meaning:"sports day / field day",example:"小学校の運動会 — shougakkou no undoukai — elementary school sports day",pos:"noun",freq:6,register:"neutral"},
  {kr:"試合",ro:"shiai",meaning:"match / game / competition",example:"試合に勝った — shiai ni katta — I won the match",pos:"noun",freq:8,register:"neutral"},
  {kr:"選手",ro:"senshu",meaning:"player / athlete / competitor",example:"オリンピック選手 — orinpikku senshu — Olympic athlete",pos:"noun",freq:7,register:"neutral"},
  {kr:"監督",ro:"kantoku",meaning:"director / coach / manager",example:"チームの監督 — chiimu no kantoku — team coach",pos:"noun",freq:7,register:"neutral"},
  {kr:"トレーニング",ro:"toreening gu",meaning:"training / workout",example:"毎日トレーニングする — mainichi toreening gu suru — to train every day",pos:"noun",freq:7,register:"neutral"},
  {kr:"ウォーミングアップ",ro:"woomingu appu",meaning:"warm-up",example:"試合前にウォーミングアップする — shiai mae ni woomingu appu suru — to warm up before a match",pos:"noun",freq:5,register:"neutral"},
  {kr:"クールダウン",ro:"kuuru daun",meaning:"cool-down",example:"運動後にクールダウンする — undou go ni kuuru daun suru — to cool down after exercise",pos:"noun",freq:5,register:"neutral"},
  {kr:"優勝",ro:"yuushou",meaning:"championship / winning first place",example:"優勝おめでとう！ — yuushou omedetou! — congratulations on winning!",pos:"noun",freq:6,register:"neutral"},
  {kr:"準優勝",ro:"jun yuushou",meaning:"runner-up / second place",example:"準優勝になった — jun yuushou ni natta — I came in second place",pos:"noun",freq:5,register:"neutral"},
  {kr:"記録",ro:"kiroku",meaning:"record / personal best",example:"記録を更新した — kiroku wo koushin shita — I broke my record",pos:"noun",freq:7,register:"neutral"},
  {kr:"球",ro:"tama/kyuu",meaning:"ball / sphere",example:"球を投げる — tama wo nageru — to throw a ball",pos:"noun",freq:6,register:"neutral"},
  {kr:"コート",ro:"kooto sports",meaning:"court (sports)",example:"テニスコートを予約する — tenisu kooto wo yoyaku suru — to book a tennis court",pos:"noun",freq:6,register:"neutral"},
  {kr:"プール",ro:"puuru",meaning:"pool (swimming)",example:"プールで泳ぐ — puuru de oyogu — to swim in the pool",pos:"noun",freq:7,register:"neutral"},
  {kr:"スキー",ro:"sukii",meaning:"skiing",example:"冬にスキーをする — fuyu ni sukii wo suru — to ski in winter",pos:"noun",freq:7,register:"neutral"},
  {kr:"スノーボード",ro:"sunooboodo",meaning:"snowboard / snowboarding",example:"スノーボードに挑戦する — sunooboodo ni chousen suru — to try snowboarding",pos:"noun",freq:6,register:"neutral"},
  {kr:"サーフィン",ro:"saafin",meaning:"surfing",example:"サーフィンをする — saafin wo suru — to surf",pos:"noun",freq:6,register:"neutral"},
  {kr:"登山",ro:"tozan",meaning:"mountain climbing / hiking",example:"登山が趣味 — tozan ga shumi — hiking is my hobby",pos:"noun",freq:6,register:"neutral"},
  {kr:"ハイキング",ro:"haikingu",meaning:"hiking",example:"週末にハイキングに行く — shuumatsu ni haikingu ni iku — to go hiking on weekends",pos:"noun",freq:6,register:"neutral"},
  {kr:"キャンプ",ro:"kyanpu",meaning:"camping",example:"山でキャンプする — yama de kyanpu suru — to go camping in the mountains",pos:"noun",freq:7,register:"neutral"},
  {kr:"釣り",ro:"tsuri",meaning:"fishing",example:"川で釣りをする — kawa de tsuri wo suru — to fish in the river",pos:"noun",freq:6,register:"neutral"},
  {kr:"将棋",ro:"shougi",meaning:"shogi (Japanese chess)",example:"将棋を指す — shougi wo sasu — to play shogi",pos:"noun",freq:5,register:"neutral"},
  {kr:"囲碁",ro:"igo",meaning:"go (board game)",example:"囲碁を打つ — igo wo utsu — to play go",pos:"noun",freq:4,register:"neutral"},
  {kr:"手芸",ro:"shugei",meaning:"needlework / handicraft",example:"手芸が得意 — shugei ga tokui — good at needlework",pos:"noun",freq:5,register:"neutral"},
  {kr:"陶芸",ro:"tougei",meaning:"ceramics / pottery",example:"陶芸教室に通う — tougei kyoushitsu ni kayou — to attend a pottery class",pos:"noun",freq:5,register:"neutral"},
  {kr:"習い事",ro:"naraigoto",meaning:"lesson / thing one is learning",example:"子供の習い事 — kodomo no naraigoto — children's lessons/activities",pos:"noun",freq:6,register:"neutral"},

  // ── MONEY & FINANCE (extension) ─────────────────────────────────────────────
  {kr:"家計",ro:"kakei",meaning:"household budget / family finances",example:"家計を管理する — kakei wo kanri suru — to manage the household budget",pos:"noun",freq:6,register:"neutral"},
  {kr:"出費",ro:"shuppi",meaning:"expense / expenditure",example:"今月は出費が多い — kongetsu wa shuppi ga ooi — I have a lot of expenses this month",pos:"noun",freq:6,register:"neutral"},
  {kr:"赤字",ro:"akaji",meaning:"deficit / in the red",example:"今月は赤字だ — kongetsu wa akaji da — I'm in the red this month",pos:"noun",freq:6,register:"neutral"},
  {kr:"黒字",ro:"kuroji",meaning:"surplus / in the black / profit",example:"今期は黒字だった — konki wa kuroji datta — we were in the black this period",pos:"noun",freq:5,register:"neutral"},
  {kr:"ローン",ro:"roon",meaning:"loan",example:"車をローンで買う — kuruma wo roon de kau — to buy a car on loan",pos:"noun",freq:7,register:"neutral"},
  {kr:"利子",ro:"rishi",meaning:"interest (on loan/savings)",example:"利子が高い — rishi ga takai — high interest",pos:"noun",freq:5,register:"neutral"},
  {kr:"口座",ro:"kouza",meaning:"bank account",example:"口座を開く — kouza wo hiraku — to open a bank account",pos:"noun",freq:7,register:"neutral"},
  {kr:"引き出す",ro:"hikidasu",meaning:"to withdraw",example:"ATMでお金を引き出す — ATM de okane wo hikidasu — to withdraw money from an ATM",pos:"verb",freq:7,register:"neutral"},
  {kr:"振り込む",ro:"furikomu",meaning:"to transfer money / to wire",example:"銀行に振り込む — ginkou ni furikomu — to wire money to a bank",pos:"verb",freq:6,register:"neutral"},
  {kr:"ATM",ro:"eetiemu",meaning:"ATM",example:"ATMでお金を下ろす — eetiemu de okane wo orosu — to withdraw money from an ATM",pos:"noun",freq:8,register:"neutral"},

  // ── ABSTRACT & FORMAL CONCEPTS ──────────────────────────────────────────────
  {kr:"概念",ro:"gainen",meaning:"concept / notion / idea",example:"難しい概念 — muzukashii gainen — a difficult concept",pos:"noun",freq:6,register:"neutral"},
  {kr:"本来",ro:"honrai",meaning:"originally / by nature / essentially",example:"本来の意味 — honrai no imi — the original meaning",pos:"adverb",freq:6,register:"neutral"},
  {kr:"そもそも",ro:"somosomo",meaning:"in the first place / to begin with",example:"そもそも間違いだった — somosomo machigai datta — it was wrong from the start",pos:"adverb",freq:7,register:"neutral"},
  {kr:"むしろ",ro:"mushiro",meaning:"rather / instead / if anything",example:"むしろ好きだ — mushiro suki da — I actually like it",pos:"adverb",freq:6,register:"neutral"},
  {kr:"一方",ro:"ippou",meaning:"on the other hand / one side",example:"一方で問題がある — ippou de mondai ga aru — on the other hand there is a problem",pos:"adverb",freq:7,register:"neutral"},
  {kr:"なお",ro:"nao",meaning:"furthermore / still / in addition (written)",example:"なお詳細は後ほど — nao shousai wa nochihodo — furthermore, details to follow",pos:"adverb",freq:6,register:"formal"},
  {kr:"ただし",ro:"tadashi",meaning:"however / provided that / but",example:"参加可能、ただし事前登録が必要 — sanka kanou, tadashi jizen touroku ga hitsuyou — can participate, however pre-registration is required",pos:"adverb",freq:7,register:"neutral"},
  {kr:"すなわち",ro:"sunawachi",meaning:"that is / namely / in other words",example:"すなわち失敗だ — sunawachi shippai da — in other words, it's a failure",pos:"adverb",freq:5,register:"formal"},
  {kr:"それゆえ",ro:"soreyue",meaning:"therefore / for that reason",example:"それゆえ大切だ — soreyue taisetsu da — therefore it is important",pos:"adverb",freq:5,register:"formal"},
  {kr:"にもかかわらず",ro:"ni mo kakawarazu",meaning:"despite / in spite of / nevertheless",example:"雨にもかかわらず来た — ame ni mo kakawarazu kita — came despite the rain",pos:"expression",freq:6,register:"neutral"},
  {kr:"たとえ〜ても",ro:"tatoe ~ te mo",meaning:"even if ~ / no matter how ~",example:"たとえ難しくても諦めない — tatoe muzukashikute mo akiramenai — even if it's difficult I won't give up",pos:"expression",freq:6,register:"neutral"},
  {kr:"〜に対して",ro:"~ ni taishite",meaning:"toward / in contrast to / against",example:"意見に対して反論する — iken ni taishite hanron suru — to argue against an opinion",pos:"expression",freq:7,register:"neutral"},
  {kr:"〜に関して",ro:"~ ni kanshite",meaning:"regarding / concerning / about",example:"この問題に関して — kono mondai ni kanshite — regarding this problem",pos:"expression",freq:6,register:"neutral"},
  {kr:"〜によって",ro:"~ ni yotte",meaning:"by / depending on / according to",example:"人によって違う — hito ni yotte chigau — it varies from person to person",pos:"expression",freq:8,register:"neutral"},
  {kr:"〜をはじめ",ro:"~ wo hajime",meaning:"starting with / not to mention / including",example:"東京をはじめ各都市で — toukyou wo hajime kaku toshi de — in various cities starting with Tokyo",pos:"expression",freq:6,register:"neutral"},
  {kr:"〜を通じて",ro:"~ wo tsujite",meaning:"through / throughout / via",example:"仕事を通じて成長する — shigoto wo tsujite seichou suru — to grow through work",pos:"expression",freq:6,register:"neutral"},

  // ── USEFUL EVERYDAY EXPRESSIONS ────────────────────────────────────────────
  {kr:"うそ！",ro:"uso!",meaning:"no way! / you're kidding! / liar!",example:"うそ！本当に？ — uso! hontou ni? — no way! really?",pos:"expression",freq:9,register:"casual"},
  {kr:"まじで？",ro:"maji de?",meaning:"seriously? / for real?",example:"まじで？信じられない！ — maji de? shinjirarenai! — seriously? I can't believe it!",pos:"expression",freq:9,register:"casual"},
  {kr:"なるほど",ro:"naruhodo",meaning:"I see / that makes sense",example:"なるほど、そういうことか — naruhodo, sou iu koto ka — I see, so that's how it is",pos:"expression",freq:8,register:"neutral"},
  {kr:"どういたしまして",ro:"dou itashimashite",meaning:"you're welcome",example:"どういたしまして！ — dou itashimashite! — you're welcome!",pos:"expression",freq:7,register:"formal"},
  {kr:"おかえり",ro:"okaeri",meaning:"welcome back / welcome home",example:"おかえり！ — okaeri! — welcome back!",pos:"expression",freq:8,register:"casual"},
  {kr:"いってきます",ro:"itte kimasu",meaning:"I'm heading out / see you later",example:"いってきます！ — itte kimasu! — I'm off!",pos:"expression",freq:8,register:"neutral"},
  {kr:"ただいま",ro:"tadaima",meaning:"I'm home",example:"ただいま！ — tadaima! — I'm home!",pos:"expression",freq:8,register:"neutral"},
  {kr:"お元気ですか",ro:"ogenki desu ka",meaning:"how are you?",example:"お元気ですか？ — ogenki desu ka? — how are you?",pos:"expression",freq:8,register:"formal"},
  {kr:"元気ですよ",ro:"genki desu yo",meaning:"I'm fine! / I'm doing well!",example:"元気ですよ、ありがとう — genki desu yo, arigatou — I'm fine, thank you",pos:"expression",freq:7,register:"neutral"},
  {kr:"お久しぶりですね",ro:"ohisashiburi desu ne",meaning:"it's been a long time (polite)",example:"お久しぶりですね、お元気ですか？ — ohisashiburi desu ne, ogenki desu ka? — long time no see, how are you?",pos:"expression",freq:7,register:"formal"},
  {kr:"少々お待ちください",ro:"shoushou omachi kudasai",meaning:"please wait a moment (formal)",example:"少々お待ちください — shoushou omachi kudasai — please wait just a moment",pos:"expression",freq:7,register:"formal"},
  {kr:"以上です",ro:"ijou desu",meaning:"that's all / that concludes",example:"報告は以上です — houkoku wa ijou desu — that concludes the report",pos:"expression",freq:7,register:"formal"},
  {kr:"お邪魔します",ro:"ojama shimasu",meaning:"excuse me for intruding (when entering someone's home)",example:"お邪魔します！ — ojama shimasu! — excuse me for intruding!",pos:"expression",freq:7,register:"neutral"},
  {kr:"お大事に",ro:"odaiji ni",meaning:"take care of yourself / get well soon",example:"お大事に！ — odaiji ni! — take care!",pos:"expression",freq:8,register:"neutral"},
  {kr:"もったいない",ro:"mottainai",meaning:"what a waste / too good to waste",example:"食べ物を捨てるなんてもったいない — tabemono wo suteru nante mottainai — what a waste to throw food away",pos:"expression",freq:7,register:"neutral"},
  {kr:"しょうがない",ro:"shouganai",meaning:"it can't be helped / oh well",example:"しょうがないな — shouganai na — well, it can't be helped",pos:"expression",freq:8,register:"casual"},
  {kr:"急いで",ro:"isoide",meaning:"hurry up / quickly",example:"急いで！遅れるよ！ — isoide! okureru yo! — hurry up! you'll be late!",pos:"expression",freq:8,register:"casual"},
  {kr:"もう少し",ro:"mou sukoshi",meaning:"a little more / just a bit more",example:"もう少し待ってください — mou sukoshi matte kudasai — please wait just a bit more",pos:"expression",freq:8,register:"neutral"},
  {kr:"お先に失礼します",ro:"osaki ni shitsurei shimasu",meaning:"excuse me for leaving first / goodbye (leaving work)",example:"お先に失礼します！ — osaki ni shitsurei shimasu! — excuse me, I'll be heading out first",pos:"expression",freq:6,register:"formal"},
  {kr:"よろしくお願いいたします",ro:"yoroshiku onegai itashimasu",meaning:"I humbly ask for your continued support (very formal)",example:"今後ともよろしくお願いいたします — kongotomo yoroshiku onegai itashimasu — please continue to look after me",pos:"expression",freq:6,register:"formal"},

  // ── COUNTERS & QUANTITY ─────────────────────────────────────────────────────
  {kr:"〜人",ro:"~nin/~ri",meaning:"counter for people",example:"三人で行く — san nin de iku — to go with three people",pos:"noun",freq:10,register:"neutral"},
  {kr:"〜冊",ro:"~satsu",meaning:"counter for books / notebooks",example:"本を三冊借りた — hon wo san satsu karita — I borrowed three books",pos:"noun",freq:7,register:"neutral"},
  {kr:"〜本",ro:"~hon",meaning:"counter for long thin objects",example:"ペンを二本ください — pen wo nihon kudasai — please give me two pens",pos:"noun",freq:7,register:"neutral"},
  {kr:"〜匹",ro:"~hiki",meaning:"counter for small animals",example:"猫を二匹飼っている — neko wo nihiki katte iru — I keep two cats",pos:"noun",freq:6,register:"neutral"},
  {kr:"〜羽",ro:"~wa",meaning:"counter for birds / rabbits",example:"鳥を三羽見た — tori wo san wa mita — I saw three birds",pos:"noun",freq:5,register:"neutral"},
  {kr:"〜頭",ro:"~tou",meaning:"counter for large animals",example:"馬が一頭いる — uma ga ittou iru — there is one horse",pos:"noun",freq:5,register:"neutral"},
  {kr:"〜着",ro:"~chaku",meaning:"counter for clothing",example:"スーツを二着持っている — suutsu wo nichaku motte iru — I own two suits",pos:"noun",freq:5,register:"neutral"},
  {kr:"〜足",ro:"~soku",meaning:"counter for footwear / socks",example:"靴下を三足買った — kutsushita wo san soku katta — I bought three pairs of socks",pos:"noun",freq:5,register:"neutral"},
  {kr:"〜枚",ro:"~mai",meaning:"counter for flat things",example:"紙を五枚使う — kami wo gomai tsukau — to use five sheets of paper",pos:"noun",freq:6,register:"neutral"},
  {kr:"〜軒",ro:"~ken",meaning:"counter for houses / shops",example:"家が三軒並んでいる — ie ga sangen narande iru — three houses stand in a row",pos:"noun",freq:5,register:"neutral"},
  {kr:"〜泊",ro:"~haku",meaning:"counter for nights (staying)",example:"ホテルに二泊した — hoteru ni nihaku shita — I stayed two nights at the hotel",pos:"noun",freq:6,register:"neutral"},
  {kr:"〜倍",ro:"~bai",meaning:"times / multiplier",example:"二倍の速さ — nibai no hayasa — twice the speed",pos:"noun",freq:7,register:"neutral"},
  {kr:"〜割",ro:"~wari",meaning:"10% increment",example:"三割引き — san wari biki — 30% off",pos:"noun",freq:6,register:"neutral"},
  {kr:"〜度",ro:"~do",meaning:"degree / time (occasion)",example:"三度目の挑戦 — sando me no chousen — the third attempt",pos:"noun",freq:7,register:"neutral"},

  // ── COLORS & APPEARANCE (extension) ────────────────────────────────────────
  {kr:"金色",ro:"kin'iro",meaning:"gold (color)",example:"金色の指輪 — kin'iro no yubiwa — a gold ring",pos:"noun",freq:6,register:"neutral"},
  {kr:"銀色",ro:"gin'iro",meaning:"silver (color)",example:"銀色の車 — gin'iro no kuruma — a silver car",pos:"noun",freq:6,register:"neutral"},
  {kr:"水色",ro:"mizuiro",meaning:"light blue / sky blue",example:"水色のドレス — mizuiro no doresu — a light blue dress",pos:"noun",freq:6,register:"neutral"},
  {kr:"肌色",ro:"hadairo",meaning:"skin color / peach",example:"肌色のソックス — hadairo no sokkusu — skin-colored socks",pos:"noun",freq:5,register:"neutral"},
  {kr:"透明",ro:"toumei",meaning:"transparent / clear",example:"透明なコップ — toumei na koppu — a transparent cup",pos:"adjective",freq:7,register:"neutral"},
  {kr:"派手",ro:"hade",meaning:"showy / flashy / loud (fashion)",example:"派手な服 — hade na fuku — flashy clothes",pos:"adjective",freq:6,register:"neutral"},
  {kr:"地味",ro:"jimi",meaning:"plain / subdued / modest (appearance)",example:"地味な色 — jimi na iro — a plain color",pos:"adjective",freq:6,register:"neutral"},
  {kr:"おしゃれ",ro:"oshare",meaning:"stylish / fashionable / chic",example:"おしゃれなカフェ — oshare na kafe — a stylish cafe",pos:"adjective",freq:8,register:"casual"},
  {kr:"かっこいい",ro:"kakkoii",meaning:"cool / cool-looking / handsome",example:"かっこいいデザイン — kakkoii dezain — a cool design",pos:"adjective",freq:9,register:"casual"},
  {kr:"ダサい",ro:"dasai",meaning:"uncool / tacky / lame",example:"ダサいファッション — dasai fasshon — tacky fashion",pos:"adjective",freq:6,register:"casual"},
  {kr:"スリム",ro:"surimu",meaning:"slim / slender",example:"スリムな体型 — surimu na taikei — a slim body shape",pos:"adjective",freq:6,register:"neutral"},
  {kr:"丸い",ro:"marui",meaning:"round / circular",example:"丸いテーブル — marui teburu — a round table",pos:"adjective",freq:7,register:"neutral"},
  {kr:"四角い",ro:"shikakui",meaning:"square / rectangular",example:"四角い箱 — shikakui hako — a square box",pos:"adjective",freq:6,register:"neutral"},
  {kr:"三角",ro:"sankaku",meaning:"triangle / triangular",example:"三角の形 — sankaku no katachi — a triangular shape",pos:"noun",freq:6,register:"neutral"},

  // ── PARTICLES & GRAMMAR HELPERS ─────────────────────────────────────────────
  {kr:"〜てみる",ro:"~te miru",meaning:"to try doing ~",example:"食べてみる — tabete miru — to try eating",pos:"expression",freq:9,register:"neutral"},
  {kr:"〜てしまう",ro:"~te shimau",meaning:"to end up doing ~ / to do ~ accidentally",example:"食べてしまった — tabete shimatta — I ended up eating it all",pos:"expression",freq:8,register:"neutral"},
  {kr:"〜ている",ro:"~te iru",meaning:"to be doing ~ / ongoing action or state",example:"食べている — tabete iru — I am eating",pos:"expression",freq:10,register:"neutral"},
  {kr:"〜てから",ro:"~te kara",meaning:"after doing ~",example:"食べてから行く — tabete kara iku — to go after eating",pos:"expression",freq:8,register:"neutral"},
  {kr:"〜ないで",ro:"~nai de",meaning:"without doing ~ / please don't ~",example:"泣かないで — nakanai de — don't cry",pos:"expression",freq:8,register:"neutral"},
  {kr:"〜なければならない",ro:"~nakereba naranai",meaning:"must ~ / have to ~",example:"行かなければならない — ikanakereba naranai — I have to go",pos:"expression",freq:7,register:"neutral"},
  {kr:"〜てもいい",ro:"~te mo ii",meaning:"it's okay to ~ / may I ~",example:"食べてもいいですか？ — tabete mo ii desu ka? — may I eat?",pos:"expression",freq:8,register:"neutral"},
  {kr:"〜てはいけない",ro:"~te wa ikenai",meaning:"must not ~ / it's not okay to ~",example:"ここで泳いではいけない — koko de oyoide wa ikenai — you must not swim here",pos:"expression",freq:7,register:"neutral"},
  {kr:"〜たことがある",ro:"~ta koto ga aru",meaning:"have experienced ~ / have done ~ before",example:"日本に行ったことがある — nihon ni itta koto ga aru — I have been to Japan",pos:"expression",freq:8,register:"neutral"},
  {kr:"〜たい",ro:"~tai",meaning:"want to ~",example:"食べたい — tabetai — I want to eat",pos:"expression",freq:10,register:"neutral"},
  {kr:"〜かもしれない",ro:"~kamo shirenai",meaning:"might ~ / maybe",example:"雨かもしれない — ame kamo shirenai — it might rain",pos:"expression",freq:8,register:"neutral"},
  {kr:"〜と思う",ro:"~to omou",meaning:"I think that ~ / I believe ~",example:"大丈夫だと思う — daijoubu da to omou — I think it's okay",pos:"expression",freq:9,register:"neutral"},
  {kr:"〜らしい",ro:"~rashii",meaning:"apparently ~ / seems like ~ (hearsay)",example:"彼は来るらしい — kare wa kuru rashii — apparently he's coming",pos:"expression",freq:7,register:"neutral"},
  {kr:"〜そうだ",ro:"~sou da",meaning:"looks like ~ / seems ~ / I heard ~",example:"難しそうだ — muzukashi sou da — it looks difficult",pos:"expression",freq:8,register:"neutral"},
  {kr:"〜ようだ",ro:"~you da",meaning:"it seems that ~ / it looks like ~ (observation)",example:"熱があるようだ — netsu ga aru you da — it seems they have a fever",pos:"expression",freq:7,register:"neutral"},

];

// Append to existing JAPANESE_WORDS array
if (typeof JAPANESE_WORDS !== 'undefined') {
  JAPANESE_WORDS.push(...JAPANESE_WORDS_3);
}
