const JAPANESE_WORDS_2 = [
  {kr:"服",ro:"fuku",meaning:"clothes",example:"新しい服を買った — atarashii fuku wo katta — I bought new clothes",pos:"noun",freq:8,register:"neutral"},
  {kr:"シャツ",ro:"shatsu",meaning:"shirt",example:"白いシャツを着る — shiroi shatsu wo kiru — to wear a white shirt",pos:"noun",freq:7,register:"neutral"},
  {kr:"ズボン",ro:"zubon",meaning:"pants / trousers",example:"ズボンが汚れた — zubon ga yogoreta — the pants got dirty",pos:"noun",freq:7,register:"neutral"},
  {kr:"スカート",ro:"sukaato",meaning:"skirt",example:"スカートを履く — sukaato wo haku — to wear a skirt",pos:"noun",freq:6,register:"neutral"},
  {kr:"コート",ro:"kooto",meaning:"coat",example:"冬はコートを着る — fuyu wa kooto wo kiru — I wear a coat in winter",pos:"noun",freq:7,register:"neutral"},
  {kr:"ジャケット",ro:"jaketto",meaning:"jacket",example:"ジャケットを羽織る — jaketto wo haoru — to put on a jacket",pos:"noun",freq:6,register:"neutral"},
  {kr:"セーター",ro:"seetaa",meaning:"sweater",example:"寒いのでセーターを着た — samui node seetaa wo kita — I wore a sweater because it was cold",pos:"noun",freq:6,register:"neutral"},
  {kr:"下着",ro:"shitagi",meaning:"underwear",example:"下着を洗う — shitagi wo arau — to wash underwear",pos:"noun",freq:5,register:"neutral"},
  {kr:"靴",ro:"kutsu",meaning:"shoes",example:"新しい靴を買った — atarashii kutsu wo katta — I bought new shoes",pos:"noun",freq:8,register:"neutral"},
  {kr:"靴下",ro:"kutsushita",meaning:"socks",example:"靴下を履く — kutsushita wo haku — to put on socks",pos:"noun",freq:7,register:"neutral"},
  {kr:"帽子",ro:"boushi",meaning:"hat",example:"帽子をかぶる — boushi wo kaburu — to wear a hat",pos:"noun",freq:7,register:"neutral"},
  {kr:"手袋",ro:"tebukuro",meaning:"gloves",example:"冬は手袋が必要 — fuyu wa tebukuro ga hitsuyou — gloves are necessary in winter",pos:"noun",freq:6,register:"neutral"},
  {kr:"マフラー",ro:"mafuraa",meaning:"scarf",example:"マフラーを巻く — mafuraa wo maku — to wrap a scarf",pos:"noun",freq:6,register:"neutral"},
  {kr:"傘",ro:"kasa",meaning:"umbrella",example:"傘を忘れた — kasa wo wasureta — I forgot my umbrella",pos:"noun",freq:8,register:"neutral"},
  {kr:"かばん",ro:"kaban",meaning:"bag",example:"かばんに入れる — kaban ni ireru — to put in the bag",pos:"noun",freq:8,register:"neutral"},
  {kr:"鍵",ro:"kagi",meaning:"key",example:"鍵を忘れた — kagi wo wasureta — I forgot the key",pos:"noun",freq:8,register:"neutral"},
  {kr:"時計",ro:"tokei",meaning:"watch / clock",example:"時計を見る — tokei wo miru — to look at the clock",pos:"noun",freq:8,register:"neutral"},
  {kr:"眼鏡",ro:"megane",meaning:"glasses",example:"眼鏡をかける — megane wo kakeru — to put on glasses",pos:"noun",freq:7,register:"neutral"},
  {kr:"指輪",ro:"yubiwa",meaning:"ring",example:"指輪を買う — yubiwa wo kau — to buy a ring",pos:"noun",freq:6,register:"neutral"},
  {kr:"家具",ro:"kagu",meaning:"furniture",example:"家具を運ぶ — kagu wo hakobu — to move furniture",pos:"noun",freq:6,register:"neutral"},
  {kr:"ベッド",ro:"beddo",meaning:"bed",example:"ベッドで寝る — beddo de neru — to sleep in bed",pos:"noun",freq:8,register:"neutral"},
  {kr:"机",ro:"tsukue",meaning:"desk",example:"机で勉強する — tsukue de benkyou suru — to study at a desk",pos:"noun",freq:8,register:"neutral"},
  {kr:"椅子",ro:"isu",meaning:"chair",example:"椅子に座る — isu ni suwaru — to sit in a chair",pos:"noun",freq:8,register:"neutral"},
  {kr:"テーブル",ro:"teburu",meaning:"table",example:"テーブルに置く — teburu ni oku — to put on the table",pos:"noun",freq:7,register:"neutral"},
  {kr:"棚",ro:"tana",meaning:"shelf",example:"棚に本を置く — tana ni hon wo oku — to put books on the shelf",pos:"noun",freq:6,register:"neutral"},
  {kr:"ソファ",ro:"sofa",meaning:"sofa",example:"ソファに座る — sofa ni suwaru — to sit on the sofa",pos:"noun",freq:7,register:"neutral"},
  {kr:"カーテン",ro:"kaaten",meaning:"curtain",example:"カーテンを閉める — kaaten wo shimeru — to close the curtain",pos:"noun",freq:6,register:"neutral"},
  {kr:"冷蔵庫",ro:"reizouko",meaning:"refrigerator",example:"冷蔵庫に入れる — reizouko ni ireru — to put in the refrigerator",pos:"noun",freq:7,register:"neutral"},
  {kr:"電子レンジ",ro:"denshi renji",meaning:"microwave",example:"電子レンジで温める — denshi renji de atatameru — to heat in the microwave",pos:"noun",freq:7,register:"neutral"},
  {kr:"洗濯機",ro:"sentakuki",meaning:"washing machine",example:"洗濯機で洗う — sentakuki de arau — to wash in the washing machine",pos:"noun",freq:6,register:"neutral"},
  {kr:"掃除機",ro:"soujiki",meaning:"vacuum cleaner",example:"掃除機をかける — soujiki wo kakeru — to vacuum",pos:"noun",freq:6,register:"neutral"},
  {kr:"エアコン",ro:"eakon",meaning:"air conditioner",example:"エアコンをつける — eakon wo tsukeru — to turn on the air conditioner",pos:"noun",freq:7,register:"neutral"},
  {kr:"電気",ro:"denki",meaning:"electricity / light",example:"電気をつける — denki wo tsukeru — to turn on the light",pos:"noun",freq:8,register:"neutral"},
  {kr:"ゴミ",ro:"gomi",meaning:"garbage / trash",example:"ゴミを捨てる — gomi wo suteru — to throw away trash",pos:"noun",freq:7,register:"neutral"},
  {kr:"掃除",ro:"souji",meaning:"cleaning",example:"部屋を掃除する — heya wo souji suru — to clean the room",pos:"noun",freq:7,register:"neutral"},
  {kr:"洗濯",ro:"sentaku",meaning:"laundry / washing",example:"洗濯をする — sentaku wo suru — to do laundry",pos:"noun",freq:7,register:"neutral"},
  {kr:"引っ越し",ro:"hikkoshi",meaning:"moving (house)",example:"来月引っ越しする — raigetsu hikkoshi suru — I'm moving next month",pos:"noun",freq:6,register:"neutral"},
  {kr:"家賃",ro:"yachin",meaning:"rent",example:"家賃を払う — yachin wo harau — to pay rent",pos:"noun",freq:6,register:"neutral"},
  {kr:"マンション",ro:"manshon",meaning:"apartment / condominium",example:"マンションに住む — manshon ni sumu — to live in an apartment",pos:"noun",freq:7,register:"neutral"},
  {kr:"アパート",ro:"apaato",meaning:"apartment",example:"アパートを借りる — apaato wo kariru — to rent an apartment",pos:"noun",freq:7,register:"neutral"},
  {kr:"趣味",ro:"shumi",meaning:"hobby",example:"趣味は何ですか？ — shumi wa nan desu ka? — what is your hobby?",pos:"noun",freq:8,register:"neutral"},
  {kr:"スポーツ",ro:"supootsu",meaning:"sports",example:"スポーツが好き — supootsu ga suki — I like sports",pos:"noun",freq:8,register:"neutral"},
  {kr:"サッカー",ro:"sakkaa",meaning:"soccer",example:"サッカーをする — sakkaa wo suru — to play soccer",pos:"noun",freq:7,register:"neutral"},
  {kr:"野球",ro:"yakyuu",meaning:"baseball",example:"野球を見る — yakyuu wo miru — to watch baseball",pos:"noun",freq:7,register:"neutral"},
  {kr:"テニス",ro:"tenisu",meaning:"tennis",example:"テニスをする — tenisu wo suru — to play tennis",pos:"noun",freq:6,register:"neutral"},
  {kr:"水泳",ro:"suiei",meaning:"swimming",example:"水泳が得意 — suiei ga tokui — I'm good at swimming",pos:"noun",freq:6,register:"neutral"},
  {kr:"ジョギング",ro:"jogingu",meaning:"jogging",example:"朝ジョギングする — asa jogingu suru — to jog in the morning",pos:"noun",freq:6,register:"neutral"},
  {kr:"映画",ro:"eiga",meaning:"movie",example:"映画を見る — eiga wo miru — to watch a movie",pos:"noun",freq:9,register:"neutral"},
  {kr:"漫画",ro:"manga",meaning:"manga / comics",example:"漫画を読む — manga wo yomu — to read manga",pos:"noun",freq:8,register:"neutral"},
  {kr:"アニメ",ro:"anime",meaning:"anime",example:"アニメが好き — anime ga suki — I like anime",pos:"noun",freq:8,register:"neutral"},
  {kr:"絵",ro:"e",meaning:"picture / painting",example:"絵を描く — e wo kaku — to draw a picture",pos:"noun",freq:7,register:"neutral"},
  {kr:"歌",ro:"uta",meaning:"song",example:"歌を歌う — uta wo utau — to sing a song",pos:"noun",freq:8,register:"neutral"},
  {kr:"楽器",ro:"gakki",meaning:"musical instrument",example:"楽器を弾く — gakki wo hiku — to play an instrument",pos:"noun",freq:6,register:"neutral"},
  {kr:"ピアノ",ro:"piano",meaning:"piano",example:"ピアノを弾く — piano wo hiku — to play piano",pos:"noun",freq:6,register:"neutral"},
  {kr:"ギター",ro:"gitaa",meaning:"guitar",example:"ギターを弾く — gitaa wo hiku — to play guitar",pos:"noun",freq:7,register:"neutral"},
  {kr:"コンサート",ro:"konsaato",meaning:"concert",example:"コンサートに行く — konsaato ni iku — to go to a concert",pos:"noun",freq:7,register:"neutral"},
  {kr:"温泉",ro:"onsen",meaning:"hot spring",example:"温泉に入る — onsen ni hairu — to soak in a hot spring",pos:"noun",freq:7,register:"neutral"},
  {kr:"花火",ro:"hanabi",meaning:"fireworks",example:"花火を見る — hanabi wo miru — to watch fireworks",pos:"noun",freq:7,register:"neutral"},
  {kr:"祭り",ro:"matsuri",meaning:"festival",example:"夏祭りに行く — natsumatsuri ni iku — to go to a summer festival",pos:"noun",freq:7,register:"neutral"},
  {kr:"お正月",ro:"oshougatsu",meaning:"New Year",example:"お正月に初詣に行く — oshougatsu ni hatsumoudeに iku — to visit a shrine for New Year",pos:"noun",freq:7,register:"neutral"},
  {kr:"クリスマス",ro:"kurisumasu",meaning:"Christmas",example:"クリスマスにプレゼントをもらう — kurisumasu ni purezento wo morau — to receive a present at Christmas",pos:"noun",freq:7,register:"neutral"},
  {kr:"赤",ro:"aka",meaning:"red",example:"赤い車 — akai kuruma — a red car",pos:"noun",freq:8,register:"neutral"},
  {kr:"青",ro:"ao",meaning:"blue",example:"青い空 — aoi sora — a blue sky",pos:"noun",freq:8,register:"neutral"},
  {kr:"黄色",ro:"kiiro",meaning:"yellow",example:"黄色い花 — kiiroi hana — a yellow flower",pos:"noun",freq:7,register:"neutral"},
  {kr:"緑",ro:"midori",meaning:"green",example:"緑の葉 — midori no ha — green leaves",pos:"noun",freq:7,register:"neutral"},
  {kr:"白",ro:"shiro",meaning:"white",example:"白い雪 — shiroi yuki — white snow",pos:"noun",freq:8,register:"neutral"},
  {kr:"黒",ro:"kuro",meaning:"black",example:"黒い猫 — kuroi neko — a black cat",pos:"noun",freq:8,register:"neutral"},
  {kr:"オレンジ",ro:"orenji",meaning:"orange (color)",example:"オレンジ色のかばん — orenji iro no kaban — an orange bag",pos:"noun",freq:6,register:"neutral"},
  {kr:"ピンク",ro:"pinku",meaning:"pink",example:"ピンクの花 — pinku no hana — a pink flower",pos:"noun",freq:6,register:"neutral"},
  {kr:"紫",ro:"murasaki",meaning:"purple",example:"紫の服 — murasaki no fuku — purple clothes",pos:"noun",freq:6,register:"neutral"},
  {kr:"茶色",ro:"chairo",meaning:"brown",example:"茶色い犬 — chairoi inu — a brown dog",pos:"noun",freq:6,register:"neutral"},
  {kr:"灰色",ro:"haiiro",meaning:"gray",example:"灰色の空 — haiiro no sora — a gray sky",pos:"noun",freq:5,register:"neutral"},
  {kr:"こんな",ro:"konna",meaning:"this kind of / like this",example:"こんな天気は嫌い — konna tenki wa kirai — I hate weather like this",pos:"expression",freq:7,register:"neutral"},
  {kr:"そんな",ro:"sonna",meaning:"that kind of / like that",example:"そんなこと言わないで — sonna koto iwanai de — don't say things like that",pos:"expression",freq:7,register:"neutral"},
  {kr:"あんな",ro:"anna",meaning:"that kind of (over there)",example:"あんな人になりたい — anna hito ni naritai — I want to become someone like that",pos:"expression",freq:6,register:"neutral"},
  {kr:"やはり",ro:"yahari",meaning:"as expected / after all",example:"やはり日本語は難しい — yahari nihongo wa muzukashii — as expected Japanese is difficult",pos:"adverb",freq:7,register:"neutral"},
  {kr:"ところで",ro:"tokoro de",meaning:"by the way",example:"ところで、明日の予定は？ — tokoro de, ashita no yotei wa? — by the way, what are tomorrow's plans?",pos:"expression",freq:7,register:"neutral"},
  {kr:"ちなみに",ro:"chinamini",meaning:"incidentally / by the way",example:"ちなみに私は東京出身です — chinamini watashi wa toukyou shusshin desu — incidentally I'm from Tokyo",pos:"adverb",freq:6,register:"neutral"},
  {kr:"要するに",ro:"you suru ni",meaning:"in short / to sum up",example:"要するに、無理だということ — you suru ni, muri da to iu koto — in short, it's impossible",pos:"adverb",freq:6,register:"neutral"},
  {kr:"なんとか",ro:"nantoka",meaning:"somehow / manage to",example:"なんとかなる — nantoka naru — it'll work out somehow",pos:"adverb",freq:7,register:"casual"},
  {kr:"きちんと",ro:"kichinto",meaning:"properly / neatly",example:"きちんとやる — kichinto yaru — to do it properly",pos:"adverb",freq:7,register:"neutral"},
  {kr:"ちゃんと",ro:"chanto",meaning:"properly / surely",example:"ちゃんと食べてね — chanto tabete ne — make sure you eat properly",pos:"adverb",freq:8,register:"casual"},
  {kr:"しっかり",ro:"shikkari",meaning:"firmly / properly",example:"しっかりしてください — shikkari shite kudasai — please pull yourself together",pos:"adverb",freq:7,register:"neutral"},
  {kr:"はっきり",ro:"hakkiri",meaning:"clearly / plainly",example:"はっきり言ってください — hakkiri itte kudasai — please say it clearly",pos:"adverb",freq:7,register:"neutral"},
  {kr:"急に",ro:"kyuu ni",meaning:"suddenly",example:"急に雨が降った — kyuu ni ame ga futta — it suddenly rained",pos:"adverb",freq:7,register:"neutral"},
  {kr:"だいたい",ro:"daitai",meaning:"approximately / mostly",example:"だいたい分かった — daitai wakatta — I mostly understand",pos:"adverb",freq:7,register:"neutral"},
  {kr:"一般的に",ro:"ippanteki ni",meaning:"generally",example:"一般的に言えば — ippanteki ni ieba — generally speaking",pos:"adverb",freq:6,register:"neutral"},
  {kr:"言葉",ro:"kotoba",meaning:"word / language",example:"日本語の言葉 — nihongo no kotoba — Japanese words",pos:"noun",freq:8,register:"neutral"},
  {kr:"文",ro:"bun",meaning:"sentence",example:"文を作る — bun wo tsukuru — to make a sentence",pos:"noun",freq:7,register:"neutral"},
  {kr:"手紙",ro:"tegami",meaning:"letter",example:"手紙を書く — tegami wo kaku — to write a letter",pos:"noun",freq:7,register:"neutral"},
  {kr:"発音",ro:"hatsuon",meaning:"pronunciation",example:"発音を練習する — hatsuon wo renshuu suru — to practice pronunciation",pos:"noun",freq:6,register:"neutral"},
  {kr:"文法",ro:"bunpou",meaning:"grammar",example:"文法を勉強する — bunpou wo benkyou suru — to study grammar",pos:"noun",freq:7,register:"neutral"},
  {kr:"翻訳",ro:"honyaku",meaning:"translation",example:"翻訳する — honyaku suru — to translate",pos:"noun",freq:6,register:"neutral"},
  {kr:"漢字",ro:"kanji char",meaning:"kanji",example:"漢字を覚える — kanji wo oboeru — to memorize kanji",pos:"noun",freq:7,register:"neutral"},
  {kr:"ローマ字",ro:"roomaji",meaning:"romaji",example:"ローマ字で書く — roomaji de kaku — to write in romaji",pos:"noun",freq:6,register:"neutral"},
  {kr:"集合",ro:"shuugou",meaning:"meeting up / gathering",example:"集合場所 — shuugou basho — meeting point",pos:"noun",freq:6,register:"neutral"},
  {kr:"遅刻",ro:"chikoku",meaning:"being late",example:"遅刻してごめんなさい — chikoku shite gomen nasai — sorry for being late",pos:"noun",freq:7,register:"neutral"},
  {kr:"休憩",ro:"kyuukei",meaning:"break / rest",example:"休憩を取る — kyuukei wo toru — to take a break",pos:"noun",freq:7,register:"neutral"},
  {kr:"昼休み",ro:"hiruyasumi",meaning:"lunch break",example:"昼休みに食べる — hiruyasumi ni taberu — to eat during lunch break",pos:"noun",freq:7,register:"neutral"},
  {kr:"締め切り",ro:"shimekiri",meaning:"deadline",example:"締め切りを守る — shimekiri wo mamoru — to meet a deadline",pos:"noun",freq:7,register:"neutral"},
  {kr:"協力",ro:"kyouryoku",meaning:"cooperation",example:"ご協力ありがとう — gokyouryoku arigatou — thank you for your cooperation",pos:"noun",freq:7,register:"neutral"},
  {kr:"感謝",ro:"kansha",meaning:"gratitude",example:"感謝しています — kansha shite imasu — I am grateful",pos:"noun",freq:7,register:"neutral"},
  {kr:"尊敬",ro:"sonkei",meaning:"respect",example:"先生を尊敬する — sensei wo sonkei suru — to respect a teacher",pos:"noun",freq:6,register:"neutral"},
  {kr:"理解",ro:"rikai",meaning:"understanding",example:"理解する — rikai suru — to understand",pos:"noun",freq:7,register:"neutral"},
  {kr:"感動",ro:"kandou",meaning:"being moved / deeply touched",example:"映画に感動した — eiga ni kandou shita — I was moved by the movie",pos:"noun",freq:7,register:"neutral"},
  {kr:"興奮",ro:"koufun",meaning:"excitement",example:"興奮する — koufun suru — to get excited",pos:"noun",freq:6,register:"neutral"},
  {kr:"挑戦",ro:"chousen",meaning:"challenge",example:"新しいことに挑戦する — atarashii koto ni chousen suru — to challenge something new",pos:"noun",freq:7,register:"neutral"},
  {kr:"達成",ro:"tassei",meaning:"achievement",example:"目標を達成する — mokuhyou wo tassei suru — to achieve a goal",pos:"noun",freq:6,register:"neutral"},
  {kr:"向上",ro:"koujou",meaning:"improvement",example:"スキルの向上 — sukiru no koujou — skill improvement",pos:"noun",freq:6,register:"neutral"},
  {kr:"決まる",ro:"kimaru",meaning:"to be decided",example:"予定が決まった — yotei ga kimatta — the schedule was decided",pos:"verb",freq:7,register:"neutral"},
  {kr:"集まる",ro:"atsumaru",meaning:"to gather / assemble",example:"みんなが集まった — minna ga atsumatta — everyone gathered",pos:"verb",freq:7,register:"neutral"},
  {kr:"連絡する",ro:"renraku suru",meaning:"to contact / to get in touch",example:"後で連絡します — ato de renraku shimasu — I'll contact you later",pos:"verb",freq:8,register:"neutral"},
  {kr:"参加する",ro:"sanka suru",meaning:"to participate",example:"イベントに参加する — ibento ni sanka suru — to participate in an event",pos:"verb",freq:7,register:"neutral"},
  {kr:"出席する",ro:"shusseki suru",meaning:"to attend",example:"会議に出席する — kaigi ni shusseki suru — to attend a meeting",pos:"verb",freq:6,register:"neutral"},
  {kr:"確かめる",ro:"tashikameru",meaning:"to make sure / to confirm",example:"事実を確かめる — jijitsu wo tashikameru — to confirm the facts",pos:"verb",freq:6,register:"neutral"},
  {kr:"見直す",ro:"minaoshi",meaning:"to review / to reconsider",example:"計画を見直す — keikaku wo minaoshi — to review the plan",pos:"verb",freq:6,register:"neutral"},
  {kr:"振り返る",ro:"furikaeru",meaning:"to look back / reflect",example:"一日を振り返る — ichinichi wo furikaeru — to reflect on the day",pos:"verb",freq:6,register:"neutral"},
  {kr:"成長する",ro:"seichou suru",meaning:"to grow / to develop",example:"子供が成長する — kodomo ga seichou suru — a child grows",pos:"verb",freq:7,register:"neutral"},
  {kr:"実現する",ro:"jitsugen suru",meaning:"to realize / to achieve",example:"夢を実現する — yume wo jitsugen suru — to realize a dream",pos:"verb",freq:6,register:"neutral"},
  {kr:"解決する",ro:"kaiketsu suru",meaning:"to solve / to resolve",example:"問題を解決する — mondai wo kaiketsu suru — to solve a problem",pos:"verb",freq:7,register:"neutral"},
  {kr:"開発する",ro:"kaihatsu suru",meaning:"to develop",example:"アプリを開発する — apuri wo kaihatsu suru — to develop an app",pos:"verb",freq:6,register:"neutral"},
  {kr:"利用する",ro:"riyou suru",meaning:"to use / to utilize",example:"サービスを利用する — saabisu wo riyou suru — to use a service",pos:"verb",freq:7,register:"neutral"},
  {kr:"注意する",ro:"chuui suru",meaning:"to be careful / to pay attention",example:"注意してください — chuui shite kudasai — please be careful",pos:"verb",freq:7,register:"neutral"},
  {kr:"反省する",ro:"hansei suru",meaning:"to reflect / to reconsider one's actions",example:"自分の行動を反省する — jibun no koudou wo hansei suru — to reflect on one's actions",pos:"verb",freq:6,register:"neutral"},
  {kr:"応援する",ro:"ouen suru",meaning:"to cheer / to support",example:"友達を応援する — tomodachi wo ouen suru — to cheer for a friend",pos:"verb",freq:7,register:"neutral"},
  {kr:"諦める",ro:"akirameru",meaning:"to give up",example:"夢を諦めない — yume wo akiramenai — don't give up on your dream",pos:"verb",freq:7,register:"neutral"},
  {kr:"乗り越える",ro:"norikoeru",meaning:"to overcome",example:"困難を乗り越える — konnan wo norikoeru — to overcome difficulties",pos:"verb",freq:6,register:"neutral"},
  {kr:"頼む",ro:"tanomu",meaning:"to ask / to request",example:"手伝いを頼む — tetsudai wo tanomu — to ask for help",pos:"verb",freq:7,register:"neutral"},
  {kr:"断る",ro:"kotowaru",meaning:"to refuse / to decline",example:"お誘いを断る — osasoi wo kotowaru — to decline an invitation",pos:"verb",freq:6,register:"neutral"},
  {kr:"謝る",ro:"ayamaru",meaning:"to apologize",example:"失礼を謝る — shitsurei wo ayamaru — to apologize for rudeness",pos:"verb",freq:7,register:"neutral"},
  {kr:"褒める",ro:"homeru",meaning:"to praise",example:"子供を褒める — kodomo wo homeru — to praise a child",pos:"verb",freq:6,register:"neutral"},
  {kr:"叱る",ro:"shikaru",meaning:"to scold",example:"子供を叱る — kodomo wo shikaru — to scold a child",pos:"verb",freq:5,register:"neutral"},
  {kr:"喜ぶ",ro:"yorokobu",meaning:"to be happy / to rejoice",example:"プレゼントに喜ぶ — purezento ni yorokobu — to be happy about a present",pos:"verb",freq:7,register:"neutral"},
  {kr:"悩む",ro:"nayamu",meaning:"to worry / to be troubled",example:"将来のことで悩む — shourai no koto de nayamu — to worry about the future",pos:"verb",freq:7,register:"neutral"},
  {kr:"諦める2",ro:"akirameru2",meaning:"to resign oneself",example:"仕方なく諦める — shikata naku akirameru — to reluctantly give up",pos:"verb",freq:6,register:"neutral"},
  {kr:"眠る",ro:"nemuru",meaning:"to sleep",example:"早く眠る — hayaku nemuru — to sleep early",pos:"verb",freq:7,register:"neutral"},
  {kr:"起こす",ro:"okosu",meaning:"to wake someone up",example:"子供を起こす — kodomo wo okosu — to wake up the child",pos:"verb",freq:6,register:"neutral"},
  {kr:"歌う",ro:"utau",meaning:"to sing",example:"歌を歌う — uta wo utau — to sing a song",pos:"verb",freq:8,register:"neutral"},
  {kr:"描く",ro:"kaku draw",meaning:"to draw / to paint",example:"絵を描く — e wo kaku — to draw a picture",pos:"verb",freq:6,register:"neutral"},
  {kr:"弾く",ro:"hiku play",meaning:"to play (instrument)",example:"ピアノを弾く — piano wo hiku — to play piano",pos:"verb",freq:6,register:"neutral"},
  {kr:"料理する",ro:"ryouri suru",meaning:"to cook",example:"夕食を料理する — yuushoku wo ryouri suru — to cook dinner",pos:"verb",freq:8,register:"neutral"},
  {kr:"掃除する",ro:"souji suru",meaning:"to clean",example:"部屋を掃除する — heya wo souji suru — to clean the room",pos:"verb",freq:7,register:"neutral"},
  {kr:"片付ける",ro:"katazukeru",meaning:"to tidy up / to put away",example:"部屋を片付ける — heya wo katazukeru — to tidy up the room",pos:"verb",freq:7,register:"neutral"},
  {kr:"捨てる",ro:"suteru",meaning:"to throw away / to discard",example:"ゴミを捨てる — gomi wo suteru — to throw away garbage",pos:"verb",freq:7,register:"neutral"},
  {kr:"拾う",ro:"hirou",meaning:"to pick up",example:"ゴミを拾う — gomi wo hirou — to pick up trash",pos:"verb",freq:6,register:"neutral"},
  {kr:"並ぶ",ro:"narabu",meaning:"to line up / to be in a row",example:"列に並ぶ — retsu ni narabu — to line up in a queue",pos:"verb",freq:7,register:"neutral"},
  {kr:"並べる",ro:"naraberu",meaning:"to line up / to arrange",example:"本を並べる — hon wo naraberu — to arrange books",pos:"verb",freq:6,register:"neutral"},
  {kr:"配る",ro:"kubaru",meaning:"to distribute / to hand out",example:"プリントを配る — purinto wo kubaru — to hand out printouts",pos:"verb",freq:6,register:"neutral"},
  {kr:"運ぶ",ro:"hakobu",meaning:"to carry / to transport",example:"荷物を運ぶ — nimotsu wo hakobu — to carry luggage",pos:"verb",freq:6,register:"neutral"},
  {kr:"届ける",ro:"todokeru",meaning:"to deliver",example:"手紙を届ける — tegami wo todokeru — to deliver a letter",pos:"verb",freq:6,register:"neutral"},
  {kr:"受け取る",ro:"uketoru",meaning:"to receive / to accept",example:"荷物を受け取る — nimotsu wo uketoru — to receive a package",pos:"verb",freq:7,register:"neutral"},
  {kr:"払う",ro:"harau",meaning:"to pay",example:"料金を払う — ryoukin wo harau — to pay the fee",pos:"verb",freq:8,register:"neutral"},
  {kr:"稼ぐ",ro:"kasegu",meaning:"to earn / to make money",example:"お金を稼ぐ — okane wo kasegu — to earn money",pos:"verb",freq:6,register:"neutral"},
  {kr:"節約する",ro:"setsuyaku suru",meaning:"to save / to economize",example:"お金を節約する — okane wo setsuyaku suru — to save money",pos:"verb",freq:6,register:"neutral"},
  {kr:"貯金する",ro:"chokin suru",meaning:"to save money",example:"毎月貯金する — maitsuki chokin suru — to save money every month",pos:"verb",freq:6,register:"neutral"},
  {kr:"予約する",ro:"yoyaku suru",meaning:"to reserve / to book",example:"レストランを予約する — resutoran wo yoyaku suru — to reserve a restaurant",pos:"verb",freq:7,register:"neutral"},
  {kr:"申し込む",ro:"moushikomu",meaning:"to apply / to sign up",example:"コースに申し込む — koosu ni moushikomu — to apply for a course",pos:"verb",freq:6,register:"neutral"},
  {kr:"登録する",ro:"touroku suru",meaning:"to register",example:"アカウントを登録する — akaunto wo touroku suru — to register an account",pos:"verb",freq:6,register:"neutral"},
  {kr:"検索する",ro:"kensaku suru",meaning:"to search",example:"インターネットで検索する — intaanetto de kensaku suru — to search the internet",pos:"verb",freq:7,register:"neutral"},
  {kr:"ダウンロードする",ro:"daunroodo suru",meaning:"to download",example:"アプリをダウンロードする — apuri wo daunroodo suru — to download an app",pos:"verb",freq:6,register:"neutral"},
  {kr:"アップロードする",ro:"appuroodo suru",meaning:"to upload",example:"写真をアップロードする — shashin wo appuroodo suru — to upload a photo",pos:"verb",freq:5,register:"neutral"},
  {kr:"コピーする",ro:"kopii suru",meaning:"to copy",example:"ファイルをコピーする — fairu wo kopii suru — to copy a file",pos:"verb",freq:6,register:"neutral"},
  {kr:"保存する",ro:"hozon suru",meaning:"to save / to store",example:"データを保存する — deeta wo hozon suru — to save data",pos:"verb",freq:6,register:"neutral"},
  {kr:"削除する",ro:"sakujo suru",meaning:"to delete",example:"ファイルを削除する — fairu wo sakujo suru — to delete a file",pos:"verb",freq:6,register:"neutral"},
  {kr:"更新する",ro:"koushin suru",meaning:"to update / to refresh",example:"アプリを更新する — apuri wo koushin suru — to update an app",pos:"verb",freq:6,register:"neutral"},
  {kr:"日課",ro:"nikka",meaning:"daily routine",example:"日課をこなす — nikka wo konasu — to complete one's daily routine",pos:"noun",freq:5,register:"neutral"},
  {kr:"生活",ro:"seikatsu",meaning:"daily life / living",example:"日常生活 — nichijou seikatsu — daily life",pos:"noun",freq:8,register:"neutral"},
  {kr:"食事",ro:"shokuji",meaning:"meal / eating",example:"食事をする — shokuji wo suru — to have a meal",pos:"noun",freq:8,register:"neutral"},
  {kr:"朝食",ro:"choushoku",meaning:"breakfast",example:"朝食を食べる — choushoku wo taberu — to eat breakfast",pos:"noun",freq:7,register:"neutral"},
  {kr:"昼食",ro:"chuushoku",meaning:"lunch",example:"昼食を取る — chuushoku wo toru — to have lunch",pos:"noun",freq:7,register:"neutral"},
  {kr:"夕食",ro:"yuushoku",meaning:"dinner",example:"家族と夕食を食べる — kazoku to yuushoku wo taberu — to have dinner with family",pos:"noun",freq:7,register:"neutral"},
  {kr:"おやつ",ro:"oyatsu",meaning:"snack",example:"おやつを食べる — oyatsu wo taberu — to eat a snack",pos:"noun",freq:7,register:"neutral"},
  {kr:"朝ごはん",ro:"asagohan",meaning:"breakfast (casual)",example:"朝ごはんを食べた？ — asagohan wo tabeta? — did you eat breakfast?",pos:"noun",freq:8,register:"casual"},
  {kr:"昼ごはん",ro:"hirugohan",meaning:"lunch (casual)",example:"昼ごはんは何にする？ — hirugohan wa nani ni suru? — what will you have for lunch?",pos:"noun",freq:8,register:"casual"},
  {kr:"晩ごはん",ro:"bangohan",meaning:"dinner (casual)",example:"晩ごはんを作る — bangohan wo tsukuru — to make dinner",pos:"noun",freq:8,register:"casual"},
  {kr:"外食",ro:"gaishoku",meaning:"eating out",example:"今日は外食しよう — kyou wa gaishoku shiyou — let's eat out today",pos:"noun",freq:7,register:"neutral"},
  {kr:"自炊",ro:"jisui",meaning:"cooking for oneself",example:"一人暮らしで自炊する — hitorigurasshi de jisui suru — to cook for myself while living alone",pos:"noun",freq:6,register:"neutral"},
  {kr:"お腹がすいた",ro:"onaka ga suita",meaning:"hungry",example:"お腹がすいたな — onaka ga suita na — I'm hungry",pos:"expression",freq:9,register:"casual"},
  {kr:"喉が渇いた",ro:"nodo ga kawaita",meaning:"thirsty",example:"喉が渇いた — nodo ga kawaita — I'm thirsty",pos:"expression",freq:8,register:"casual"},
  {kr:"疲れる",ro:"tsukareru",meaning:"to get tired",example:"仕事で疲れる — shigoto de tsukareru — to get tired from work",pos:"verb",freq:8,register:"neutral"},
  {kr:"痛む",ro:"itamu",meaning:"to hurt / to ache",example:"腰が痛む — koshi ga itamu — my back aches",pos:"verb",freq:6,register:"neutral"},
  {kr:"治る",ro:"naoru",meaning:"to heal / to recover",example:"風邪が治った — kaze ga naotta — the cold got better",pos:"verb",freq:7,register:"neutral"},
  {kr:"休む",ro:"yasumu2",meaning:"to rest / to be absent",example:"学校を休む — gakkou wo yasumu — to be absent from school",pos:"verb",freq:8,register:"neutral"},
  {kr:"太る",ro:"futoru",meaning:"to gain weight",example:"最近太った — saikin futotta — I gained weight recently",pos:"verb",freq:6,register:"casual"},
  {kr:"痩せる",ro:"yaseru",meaning:"to lose weight",example:"ダイエットして痩せた — daietto shite yaseta — I lost weight by dieting",pos:"verb",freq:6,register:"casual"},
  {kr:"植物",ro:"shokubutsu",meaning:"plant / vegetation",example:"植物を育てる — shokubutsu wo sodateru — to grow plants",pos:"noun",freq:6,register:"neutral"},
  {kr:"動物",ro:"doubutsu",meaning:"animal",example:"動物が好き — doubutsu ga suki — I like animals",pos:"noun",freq:7,register:"neutral"},
  {kr:"空気",ro:"kuuki",meaning:"air",example:"新鮮な空気 — shinsen na kuuki — fresh air",pos:"noun",freq:7,register:"neutral"},
  {kr:"気温",ro:"kion",meaning:"temperature (air)",example:"気温が上がる — kion ga agaru — the temperature rises",pos:"noun",freq:7,register:"neutral"},
  {kr:"天気予報",ro:"tenki yohou",meaning:"weather forecast",example:"天気予報を確認する — tenki yohou wo kakunin suru — to check the weather forecast",pos:"noun",freq:7,register:"neutral"},
  {kr:"湖",ro:"mizuumi",meaning:"lake",example:"湖で泳ぐ — mizuumi de oyogu — to swim in the lake",pos:"noun",freq:6,register:"neutral"},
  {kr:"砂浜",ro:"sunahama",meaning:"sandy beach",example:"砂浜を歩く — sunahama wo aruku — to walk on the sandy beach",pos:"noun",freq:6,register:"neutral"},
  {kr:"結婚",ro:"kekkon",meaning:"marriage",example:"結婚する — kekkon suru — to get married",pos:"noun",freq:7,register:"neutral"},
  {kr:"離婚",ro:"rikon",meaning:"divorce",example:"離婚した — rikon shita — I got divorced",pos:"noun",freq:5,register:"neutral"},
  {kr:"出産",ro:"shussan",meaning:"childbirth",example:"出産おめでとう — shussan omedetou — congratulations on the birth",pos:"noun",freq:6,register:"neutral"},
  {kr:"育てる",ro:"sodateru",meaning:"to raise / to bring up",example:"子供を育てる — kodomo wo sodateru — to raise a child",pos:"verb",freq:7,register:"neutral"},
  {kr:"付き合う",ro:"tsukiau",meaning:"to go out with / to date",example:"彼女と付き合う — kanojo to tsukiau — to date a girlfriend",pos:"verb",freq:7,register:"casual"},
  {kr:"別れる",ro:"wakareru",meaning:"to break up / to part",example:"彼氏と別れた — kareshi to wakareta — I broke up with my boyfriend",pos:"verb",freq:6,register:"casual"},
  {kr:"喧嘩する",ro:"kenka suru",meaning:"to fight / to argue",example:"友達と喧嘩した — tomodachi to kenka shita — I fought with a friend",pos:"verb",freq:6,register:"casual"},
  {kr:"仲直りする",ro:"nakanaori suru",meaning:"to make up / to reconcile",example:"喧嘩した後で仲直りした — kenka shita ato de nakanaori shita — we made up after the fight",pos:"verb",freq:6,register:"neutral"},
  {kr:"挨拶する",ro:"aisatsu suru",meaning:"to greet",example:"毎朝挨拶する — maiasa aisatsu suru — to greet every morning",pos:"verb",freq:7,register:"neutral"},
  {kr:"紹介する",ro:"shoukai suru2",meaning:"to introduce",example:"友達を紹介してもらった — tomodachi wo shoukai shite moratta — I was introduced to a friend",pos:"verb",freq:7,register:"neutral"},
  {kr:"一",ro:"ichi",meaning:"one",example:"一つ — hitotsu — one (thing)",pos:"noun",freq:9,register:"neutral"},
  {kr:"二",ro:"ni",meaning:"two",example:"二つ — futatsu — two (things)",pos:"noun",freq:9,register:"neutral"},
  {kr:"三",ro:"san",meaning:"three",example:"三つ — mittsu — three (things)",pos:"noun",freq:9,register:"neutral"},
  {kr:"四",ro:"shi/yon",meaning:"four",example:"四つ — yottsu — four (things)",pos:"noun",freq:8,register:"neutral"},
  {kr:"五",ro:"go",meaning:"five",example:"五つ — itsutsu — five (things)",pos:"noun",freq:8,register:"neutral"},
  {kr:"六",ro:"roku",meaning:"six",example:"六つ — muttsu — six (things)",pos:"noun",freq:8,register:"neutral"},
  {kr:"七",ro:"shichi/nana",meaning:"seven",example:"七つ — nanatsu — seven (things)",pos:"noun",freq:8,register:"neutral"},
  {kr:"八",ro:"hachi",meaning:"eight",example:"八つ — yattsu — eight (things)",pos:"noun",freq:8,register:"neutral"},
  {kr:"九",ro:"ku/kyuu",meaning:"nine",example:"九つ — kokonotsu — nine (things)",pos:"noun",freq:8,register:"neutral"},
  {kr:"十",ro:"juu",meaning:"ten",example:"十 — too — ten (things)",pos:"noun",freq:8,register:"neutral"},
  {kr:"百",ro:"hyaku",meaning:"hundred",example:"三百円 — sanbyaku en — 300 yen",pos:"noun",freq:7,register:"neutral"},
  {kr:"千",ro:"sen",meaning:"thousand",example:"五千円 — gosen en — 5000 yen",pos:"noun",freq:7,register:"neutral"},
  {kr:"万",ro:"man",meaning:"ten thousand",example:"一万円 — ichiman en — 10,000 yen",pos:"noun",freq:7,register:"neutral"},
  {kr:"個",ro:"ko",meaning:"counter for small objects",example:"三個ください — sanko kudasai — please give me three",pos:"noun",freq:7,register:"neutral"},
  {kr:"枚",ro:"mai",meaning:"counter for flat objects",example:"三枚 — sanmai — three sheets",pos:"noun",freq:6,register:"neutral"},
  {kr:"台",ro:"dai",meaning:"counter for machines/vehicles",example:"車一台 — kuruma ichidai — one car",pos:"noun",freq:6,register:"neutral"},
  {kr:"杯",ro:"hai",meaning:"counter for cups / bowls",example:"コーヒー一杯 — koohii ippai — one cup of coffee",pos:"noun",freq:7,register:"neutral"},
  {kr:"回",ro:"kai",meaning:"number of times",example:"三回 — sankai — three times",pos:"noun",freq:7,register:"neutral"},
  {kr:"階",ro:"kai floor",meaning:"floor / story",example:"三階 — sangai — third floor",pos:"noun",freq:7,register:"neutral"},
  {kr:"嫌い",ro:"kirai",meaning:"dislike / hate",example:"虫が嫌い — mushi ga kirai — I hate insects",pos:"adjective",freq:8,register:"neutral"},
  {kr:"苦手",ro:"nigate",meaning:"not good at / weak point",example:"数学が苦手 — suugaku ga nigate — I'm not good at math",pos:"adjective",freq:7,register:"neutral"},
  {kr:"得意",ro:"tokui",meaning:"good at / strong point",example:"英語が得意 — eigo ga tokui — I'm good at English",pos:"adjective",freq:7,register:"neutral"},
  {kr:"大丈夫",ro:"daijoubu2",meaning:"okay / fine / no problem",example:"大丈夫ですか？ — daijoubu desu ka? — are you okay?",pos:"adjective",freq:9,register:"neutral"},
  {kr:"相変わらず",ro:"aikawarazu",meaning:"as usual / same as always",example:"相変わらず元気です — aikawarazu genki desu — same as always, doing well",pos:"adverb",freq:6,register:"neutral"},
  {kr:"初めて",ro:"hajimete2",meaning:"for the first time",example:"日本に初めて来た — nihon ni hajimete kita — I came to Japan for the first time",pos:"adverb",freq:7,register:"neutral"},
  {kr:"もうすぐ",ro:"mousugu",meaning:"soon / before long",example:"もうすぐ春です — mousugu haru desu — spring is almost here",pos:"adverb",freq:7,register:"neutral"},
  {kr:"なかなか",ro:"nakanaka",meaning:"considerably / quite / not easily",example:"なかなか難しい — nakanaka muzukashii — it's quite difficult",pos:"adverb",freq:7,register:"neutral"},
  {kr:"せっかく",ro:"sekkaku",meaning:"having gone to the trouble of",example:"せっかく来たんだから — sekkaku kita n dakara — since you went to the trouble of coming",pos:"adverb",freq:6,register:"neutral"},
  {kr:"しかも",ro:"shikamo",meaning:"moreover / furthermore",example:"安くて、しかもおいしい — yasukute, shikamo oishii — cheap and moreover delicious",pos:"adverb",freq:6,register:"neutral"},
  {kr:"ただ",ro:"tada",meaning:"just / only / however",example:"ただ見ているだけ — tada mite iru dake — just watching",pos:"adverb",freq:7,register:"neutral"},
  {kr:"むしろ",ro:"mushiro",meaning:"rather / instead",example:"むしろ嬉しい — mushiro ureshii — I'm rather glad",pos:"adverb",freq:6,register:"neutral"},
  {kr:"さすがに",ro:"sasuga ni",meaning:"as expected / even so",example:"さすがに疲れた — sasuga ni tsukareta — I'm tired even so",pos:"adverb",freq:6,register:"neutral"},
  {kr:"たとえ",ro:"tatoe",meaning:"even if / suppose",example:"たとえ難しくても頑張る — tatoe muzukashikute mo ganbaru — I'll try even if it's difficult",pos:"adverb",freq:6,register:"neutral"},
  {kr:"もしも",ro:"moshimo",meaning:"if (hypothetical)",example:"もしも宝くじが当たったら — moshimo takarakuji ga atattara — if I won the lottery",pos:"adverb",freq:6,register:"neutral"},
  {kr:"手段",ro:"shudan",meaning:"means / method",example:"目的のための手段 — mokuteki no tame no shudan — means for the purpose",pos:"noun",freq:6,register:"neutral"},
  {kr:"結果",ro:"kekka2",meaning:"result / outcome",example:"実験の結果 — jikken no kekka — result of the experiment",pos:"noun",freq:7,register:"neutral"},
  {kr:"効果",ro:"kouka",meaning:"effect / result",example:"薬の効果 — kusuri no kouka — effect of medicine",pos:"noun",freq:6,register:"neutral"},
  {kr:"対策",ro:"taisaku",meaning:"countermeasure / measures",example:"対策を取る — taisaku wo toru — to take measures",pos:"noun",freq:6,register:"neutral"},
  {kr:"成果",ro:"seika",meaning:"result / outcome / achievement",example:"努力の成果 — doryoku no seika — result of effort",pos:"noun",freq:6,register:"neutral"},
  {kr:"経過",ro:"keika",meaning:"progress / passage of time",example:"時間の経過 — jikan no keika — passage of time",pos:"noun",freq:5,register:"neutral"},
  {kr:"理論",ro:"riron",meaning:"theory",example:"理論を証明する — riron wo shoumei suru — to prove a theory",pos:"noun",freq:6,register:"neutral"},
  {kr:"実践",ro:"jissen",meaning:"practice / putting into practice",example:"理論を実践する — riron wo jissen suru — to put theory into practice",pos:"noun",freq:6,register:"neutral"},
  {kr:"研究",ro:"kenkyuu",meaning:"research / study",example:"研究を続ける — kenkyuu wo tsuzukeru — to continue research",pos:"noun",freq:7,register:"neutral"},
  {kr:"調査",ro:"chousa",meaning:"investigation / research",example:"市場調査 — shijou chousa — market research",pos:"noun",freq:6,register:"neutral"},
  {kr:"分析",ro:"bunseki",meaning:"analysis",example:"データを分析する — deeta wo bunseki suru — to analyze data",pos:"noun",freq:6,register:"neutral"},
  {kr:"評価",ro:"hyouka",meaning:"evaluation / assessment",example:"仕事を評価する — shigoto wo hyouka suru — to evaluate work",pos:"noun",freq:7,register:"neutral"}
];

JAPANESE_WORDS.push(...JAPANESE_WORDS_2);
