const JAPANESE_WORDS_2 = [
  {kr:"服",ro:"fuku",meaning:"clothes",example:"新しい服を買った — atarashii fuku wo katta — I bought new clothes",pos:"noun",freq:8,register:"neutral"},
  {kr:"シャツ",ro:"shatsu",meaning:"shirt",example:"白いシャツを着る — shiroi shatsu wo kiru — to wear a white shirt",pos:"noun",freq:7,register:"neutral"},
  {kr:"ズボン",ro:"zubon",meaning:"pants / trousers",example:"ズボンが汚れた — zubon ga yogoreta — the pants got dirty",pos:"noun",freq:7,register:"neutral"},
  {kr:"スカート",ro:"sukaato",meaning:"skirt",example:"スカートを履く — sukaato wo haku — to wear a skirt",pos:"noun",freq:6,register:"neutral"},
  {kr:"コート",ro:"kooto",meaning:"coat",example:"冬はコートを着る — fuyu wa kooto wo kiru — I wear a coat in winter",pos:"noun",freq:7,register:"neutral"},
  {kr:"ジャケット",ro:"jaketto",meaning:"jacket",example:"ジャケットを羽織る — jaketto wo haoru — to put on a jacket",pos:"noun",freq:6,register:"neutral"},
  {kr:"セーター",ro:"seetaa",meaning:"sweater",example:"寒いのでセーターを着た — samui node seetaa wo kita — I wore a sweater because it was cold",pos:"noun",freq:6,register:"neutral"},
  {kr:"下着",ro:"shitagi",meaning:"underwear",example:"下着を洗う — shitagi wo arau — to wash underwear",pos:"noun",freq:5,register:"neutral"},
  {kr:"靴",ro:"kutsu",meaning:"shoes",example:"新しい靴を買った — atarashii kutsu wo katta — I bought new shoes",pos:"noun",freq:8,register:"neutral"},
  {kr:"靴下",ro:"kutsushita",meaning:"socks",example:"靴下を履く — kutsushita wo haku — to put on socks",pos:"noun",freq:7,register:"neutral"},
  {kr:"帽子",ro:"boushi",meaning:"hat",example:"帽子をかぶる — boushi wo kaburu — to wear a hat",pos:"noun",freq:7,register:"neutral"},
  {kr:"手袋",ro:"tebukuro",meaning:"gloves",example:"冬は手袋が必要 — fuyu wa tebukuro ga hitsuyou — gloves are necessary in winter",pos:"noun",freq:6,register:"neutral"},
  {kr:"マフラー",ro:"mafuraa",meaning:"scarf",example:"マフラーを巻く — mafuraa wo maku — to wrap a scarf",pos:"noun",freq:6,register:"neutral"},
  {kr:"傘",ro:"kasa",meaning:"umbrella",example:"傘を忘れた — kasa wo wasureta — I forgot my umbrella",pos:"noun",freq:8,register:"neutral"},
  {kr:"かばん",ro:"kaban",meaning:"bag",example:"かばんに入れる — kaban ni ireru — to put in the bag",pos:"noun",freq:8,register:"neutral"},
  {kr:"鍵",ro:"kagi",meaning:"key",example:"鍵を忘れた — kagi wo wasureta — I forgot the key",pos:"noun",freq:8,register:"neutral"},
  {kr:"時計",ro:"tokei",meaning:"watch / clock",example:"時計を見る — tokei wo miru — to look at the clock",pos:"noun",freq:8,register:"neutral"},
  {kr:"眼鏡",ro:"megane",meaning:"glasses",example:"眼鏡をかける — megane wo kakeru — to put on glasses",pos:"noun",freq:7,register:"neutral"},
  {kr:"指輪",ro:"yubiwa",meaning:"ring",example:"指輪を買う — yubiwa wo kau — to buy a ring",pos:"noun",freq:6,register:"neutral"},
  {kr:"家具",ro:"kagu",meaning:"furniture",example:"家具を運ぶ — kagu wo hakobu — to move furniture",pos:"noun",freq:6,register:"neutral"},
  {kr:"ベッド",ro:"beddo",meaning:"bed",example:"ベッドで寝る — beddo de neru — to sleep in bed",pos:"noun",freq:8,register:"neutral"},
  {kr:"机",ro:"tsukue",meaning:"desk",example:"机で勉強する — tsukue de benkyou suru — to study at a desk",pos:"noun",freq:8,register:"neutral"},
  {kr:"椅子",ro:"isu",meaning:"chair",example:"椅子に座る — isu ni suwaru — to sit in a chair",pos:"noun",freq:8,register:"neutral"},
  {kr:"テーブル",ro:"teburu",meaning:"table",example:"テーブルに置く — teburu ni oku — to put on the table",pos:"noun",freq:7,register:"neutral"},
  {kr:"棚",ro:"tana",meaning:"shelf",example:"棚に本を置く — tana ni hon wo oku — to put books on the shelf",pos:"noun",freq:6,register:"neutral"},
  {kr:"ソファ",ro:"sofa",meaning:"sofa",example:"ソファに座る — sofa ni suwaru — to sit on the sofa",pos:"noun",freq:7,register:"neutral"},
  {kr:"カーテン",ro:"kaaten",meaning:"curtain",example:"カーテンを閉める — kaaten wo shimeru — to close the curtain",pos:"noun",freq:6,register:"neutral"},
  {kr:"冷蔵庫",ro:"reizouko",meaning:"refrigerator",example:"冷蔵庫に入れる — reizouko ni ireru — to put in the refrigerator",pos:"noun",freq:7,register:"neutral"},
  {kr:"電子レンジ",ro:"denshi renji",meaning:"microwave",example:"電子レンジで温める — denshi renji de atatameru — to heat in the microwave",pos:"noun",freq:7,register:"neutral"},
  {kr:"洗濯機",ro:"sentakuki",meaning:"washing machine",example:"洗濯機で洗う — sentakuki de arau — to wash in the washing machine",pos:"noun",freq:6,register:"neutral"},
  {kr:"掃除機",ro:"soujiki",meaning:"vacuum cleaner",example:"掃除機をかける — soujiki wo kakeru — to vacuum",pos:"noun",freq:6,register:"neutral"},
  {kr:"エアコン",ro:"eakon",meaning:"air conditioner",example:"エアコンをつける — eakon wo tsukeru — to turn on the air conditioner",pos:"noun",freq:7,register:"neutral"},
  {kr:"電気",ro:"denki",meaning:"electricity / light",example:"電気をつける — denki wo tsukeru — to turn on the light",pos:"noun",freq:8,register:"neutral"},
  {kr:"ゴミ",ro:"gomi",meaning:"garbage / trash",example:"ゴミを捨てる — gomi wo suteru — to throw away trash",pos:"noun",freq:7,register:"neutral"},
  {kr:"掃除",ro:"souji",meaning:"cleaning",example:"部屋を掃除する — heya wo souji suru — to clean the room",pos:"noun",freq:7,register:"neutral"},
  {kr:"洗濯",ro:"sentaku",meaning:"laundry / washing",example:"洗濯をする — sentaku wo suru — to do laundry",pos:"noun",freq:7,register:"neutral"},
  {kr:"引っ越し",ro:"hikkoshi",meaning:"moving (house)",example:"来月引っ越しする — raigetsu hikkoshi suru — I'm moving next month",pos:"noun",freq:6,register:"neutral"},
  {kr:"家賃",ro:"yachin",meaning:"rent",example:"家賃を払う — yachin wo harau — to pay rent",pos:"noun",freq:6,register:"neutral"},
  {kr:"マンション",ro:"manshon",meaning:"apartment / condominium",example:"マンションに住む — manshon ni sumu — to live in an apartment",pos:"noun",freq:7,register:"neutral"},
  {kr:"アパート",ro:"apaato",meaning:"apartment",example:"アパートを借りる — apaato wo kariru — to rent an apartment",pos:"noun",freq:7,register:"neutral"},
  {kr:"趣味",ro:"shumi",meaning:"hobby",example:"趣味は何ですか？ — shumi wa nan desu ka? — what is your hobby?",pos:"noun",freq:8,register:"neutral"},
  {kr:"スポーツ",ro:"supootsu",meaning:"sports",example:"スポーツが好き — supootsu ga suki — I like sports",pos:"noun",freq:8,register:"neutral"},
  {kr:"サッカー",ro:"sakkaa",meaning:"soccer",example:"サッカーをする — sakkaa wo suru — to play soccer",pos:"noun",freq:7,register:"neutral"},
  {kr:"野球",ro:"yakyuu",meaning:"baseball",example:"野球を見る — yakyuu wo miru — to watch baseball",pos:"noun",freq:7,register:"neutral"},
  {kr:"テニス",ro:"tenisu",meaning:"tennis",example:"テニスをする — tenisu wo suru — to play tennis",pos:"noun",freq:6,register:"neutral"},
  {kr:"水泳",ro:"suiei",meaning:"swimming",example:"水泳が得意 — suiei ga tokui — I'm good at swimming",pos:"noun",freq:6,register:"neutral"},
  {kr:"ジョギング",ro:"jogingu",meaning:"jogging",example:"朝ジョギングする — asa jogingu suru — to jog in the morning",pos:"noun",freq:6,register:"neutral"},
  {kr:"映画",ro:"eiga",meaning:"movie",example:"映画を見る — eiga wo miru — to watch a movie",pos:"noun",freq:9,register:"neutral"},
  {kr:"漫画",ro:"manga",meaning:"manga / comics",example:"漫画を読む — manga wo yomu — to read manga",pos:"noun",freq:8,register:"neutral"},
  {kr:"アニメ",ro:"anime",meaning:"anime",example:"アニメが好き — anime ga suki — I like anime",pos:"noun",freq:8,register:"neutral"},
  {kr:"絵",ro:"e",meaning:"picture / painting",example:"絵を描く — e wo kaku — to draw a picture",pos:"noun",freq:7,register:"neutral"},
  {kr:"歌",ro:"uta",meaning:"song",example:"歌を歌う — uta wo utau — to sing a song",pos:"noun",freq:8,register:"neutral"},
  {kr:"楽器",ro:"gakki",meaning:"musical instrument",example:"楽器を弾く — gakki wo hiku — to play an instrument",pos:"noun",freq:6,register:"neutral"},
  {kr:"ピアノ",ro:"piano",meaning:"piano",example:"ピアノを弾く — piano wo hiku — to play piano",pos:"noun",freq:6,register:"neutral"},
  {kr:"ギター",ro:"gitaa",meaning:"guitar",example:"ギターを弾く — gitaa wo hiku — to play guitar",pos:"noun",freq:7,register:"neutral"},
  {kr:"コンサート",ro:"konsaato",meaning:"concert",example:"コンサートに行く — konsaato ni iku — to go to a concert",pos:"noun",freq:7,register:"neutral"},
  {kr:"温泉",ro:"onsen",meaning:"hot spring",example:"温泉に入る — onsen ni hairu — to soak in a hot spring",pos:"noun",freq:7,register:"neutral"},
  {kr:"花火",ro:"hanabi",meaning:"fireworks",example:"花火を見る — hanabi wo miru — to watch fireworks",pos:"noun",freq:7,register:"neutral"},
  {kr:"祭り",ro:"matsuri",meaning:"festival",example:"夏祭りに行く — natsumatsuri ni iku — to go to a summer festival",pos:"noun",freq:7,register:"neutral"},
  {kr:"お正月",ro:"oshougatsu",meaning:"New Year",example:"お正月に初詣に行く — oshougatsu ni hatsumoudeに iku — to visit a shrine for New Year",pos:"noun",freq:7,register:"neutral"},
  {kr:"クリスマス",ro:"kurisumasu",meaning:"Christmas",example:"クリスマスにプレゼントをもらう — kurisumasu ni purezento wo morau — to receive a present at Christmas",pos:"noun",freq:7,register:"neutral"},
  {kr:"赤",ro:"aka",meaning:"red",example:"赤い車 — akai kuruma — a red car",pos:"noun",freq:8,register:"neutral"},
  {kr:"青",ro:"ao",meaning:"blue",example:"青い空 — aoi sora — a blue sky",pos:"noun",freq:8,register:"neutral"},
  {kr:"黄色",ro:"kiiro",meaning:"yellow",example:"黄色い花 — kiiroi hana — a yellow flower",pos:"noun",freq:7,register:"neutral"},
  {kr:"緑",ro:"midori",meaning:"green",example:"緑の葉 — midori no ha — green leaves",pos:"noun",freq:7,register:"neutral"},
  {kr:"白",ro:"shiro",meaning:"white",example:"白い雪 — shiroi yuki — white snow",pos:"noun",freq:8,register:"neutral"},
  {kr:"黒",ro:"kuro",meaning:"black",example:"黒い猫 — kuroi neko — a black cat",pos:"noun",freq:8,register:"neutral"},
  {kr:"オレンジ",ro:"orenji",meaning:"orange (color)",example:"オレンジ色のかばん — orenji iro no kaban — an orange bag",pos:"noun",freq:6,register:"neutral"},
  {kr:"ピンク",ro:"pinku",meaning:"pink",example:"ピンクの花 — pinku no hana — a pink flower",pos:"noun",freq:6,register:"neutral"},
  {kr:"紫",ro:"murasaki",meaning:"purple",example:"紫の服 — murasaki no fuku — purple clothes",pos:"noun",freq:6,register:"neutral"},
  {kr:"茶色",ro:"chairo",meaning:"brown",example:"茶色い犬 — chairoi inu — a brown dog",pos:"noun",freq:6,register:"neutral"},
  {kr:"灰色",ro:"haiiro",meaning:"gray",example:"灰色の空 — haiiro no sora — a gray sky",pos:"noun",freq:5,register:"neutral"},
  {kr:"こんな",ro:"konna",meaning:"this kind of / like this",example:"こんな天気は嫌い — konna tenki wa kirai — I hate weather like this",pos:"expression",freq:7,register:"neutral"},
  {kr:"そんな",ro:"sonna",meaning:"that kind of / like that",example:"そんなこと言わないで — sonna koto iwanai de — don't say things like that",pos:"expression",freq:7,register:"neutral"},
  {kr:"あんな",ro:"anna",meaning:"that kind of (over there)",example:"あんな人になりたい — anna hito ni naritai — I want to become someone like that",pos:"expression",freq:6,register:"neutral"},
  {kr:"やはり",ro:"yahari",meaning:"as expected / after all",example:"やはり日本語は難しい — yahari nihongo wa muzukashii — as expected Japanese is difficult",pos:"adverb",freq:7,register:"neutral"},
  {kr:"ところで",ro:"tokoro de",meaning:"by the way",example:"ところで、明日の予定は？ — tokoro de, ashita no yotei wa? — by the way, what are tomorrow's plans?",pos:"expression",freq:7,register:"neutral"},
  {kr:"ちなみに",ro:"chinamini",meaning:"incidentally / by the way",example:"ちなみに私は東京出身です — chinamini watashi wa toukyou shusshin desu — incidentally I'm from Tokyo",pos:"adverb",freq:6,register:"neutral"},
  {kr:"要するに",ro:"you suru ni",meaning:"in short / to sum up",example:"要するに、無理だということ — you suru ni, muri da to iu koto — in short, it's impossible",pos:"adverb",freq:6,register:"neutral"},
  {kr:"なんとか",ro:"nantoka",meaning:"somehow / manage to",example:"なんとかなる — nantoka naru — it'll work out somehow",pos:"adverb",freq:7,register:"casual"},
  {kr:"きちんと",ro:"kichinto",meaning:"properly / neatly",example:"きちんとやる — kichinto yaru — to do it properly",pos:"adverb",freq:7,register:"neutral"},
  {kr:"ちゃんと",ro:"chanto",meaning:"properly / surely",example:"ちゃんと食べてね — chanto tabete ne — make sure you eat properly",pos:"adverb",freq:8,register:"casual"},
  {kr:"しっかり",ro:"shikkari",meaning:"firmly / properly",example:"しっかりしてください — shikkari shite kudasai — please pull yourself together",pos:"adverb",freq:7,register:"neutral"},
  {kr:"はっきり",ro:"hakkiri",meaning:"clearly / plainly",example:"はっきり言ってください — hakkiri itte kudasai — please say it clearly",pos:"adverb",freq:7,register:"neutral"},
  {kr:"急に",ro:"kyuu ni",meaning:"suddenly",example:"急に雨が降った — kyuu ni ame ga futta — it suddenly rained",pos:"adverb",freq:7,register:"neutral"},
  {kr:"だいたい",ro:"daitai",meaning:"approximately / mostly",example:"だいたい分かった — daitai wakatta — I mostly understand",pos:"adverb",freq:7,register:"neutral"},
  {kr:"一般的に",ro:"ippanteki ni",meaning:"generally",example:"一般的に言えば — ippanteki ni ieba — generally speaking",pos:"adverb",freq:6,register:"neutral"},
  {kr:"言葉",ro:"kotoba",meaning:"word / language",example:"日本語の言葉 — nihongo no kotoba — Japanese words",pos:"noun",freq:8,register:"neutral"},
  {kr:"文",ro:"bun",meaning:"sentence",example:"文を作る — bun wo tsukuru — to make a sentence",pos:"noun",freq:7,register:"neutral"},
  {kr:"手紙",ro:"tegami",meaning:"letter",example:"手紙を書く — tegami wo kaku — to write a letter",pos:"noun",freq:7,register:"neutral"},
  {kr:"発音",ro:"hatsuon",meaning:"pronunciation",example:"発音を練習する — hatsuon wo renshuu suru — to practice pronunciation",pos:"noun",freq:6,register:"neutral"},
  {kr:"文法",ro:"bunpou",meaning:"grammar",example:"文法を勉強する — bunpou wo benkyou suru — to study grammar",pos:"noun",freq:7,register:"neutral"},
  {kr:"翻訳",ro:"honyaku",meaning:"translation",example:"翻訳する — honyaku suru — to translate",pos:"noun",freq:6,register:"neutral"},
  {kr:"漢字",ro:"kanji char",meaning:"kanji",example:"漢字を覚える — kanji wo oboeru — to memorize kanji",pos:"noun",freq:7,register:"neutral"},
  {kr:"ローマ字",ro:"roomaji",meaning:"romaji",example:"ローマ字で書く — roomaji de kaku — to write in romaji",pos:"noun",freq:6,register:"neutral"},
  {kr:"集合",ro:"shuugou",meaning:"meeting up / gathering",example:"集合場所 — shuugou basho — meeting point",pos:"noun",freq:6,register:"neutral"},
  {kr:"遅刻",ro:"chikoku",meaning:"being late",example:"遅刻してごめんなさい — chikoku shite gomen nasai — sorry for being late",pos:"noun",freq:7,register:"neutral"},
  {kr:"休憩",ro:"kyuukei",meaning:"break / rest",example:"休憩を取る — kyuukei wo toru — to take a break",pos:"noun",freq:7,register:"neutral"},
  {kr:"昼休み",ro:"hiruyasumi",meaning:"lunch break",example:"昼休みに食べる — hiruyasumi ni taberu — to eat during lunch break",pos:"noun",freq:7,register:"neutral"},
  {kr:"締め切り",ro:"shimekiri",meaning:"deadline",example:"締め切りを守る — shimekiri wo mamoru — to meet a deadline",pos:"noun",freq:7,register:"neutral"},
  {kr:"協力",ro:"kyouryoku",meaning:"cooperation",example:"ご協力ありがとう — gokyouryoku arigatou — thank you for your cooperation",pos:"noun",freq:7,register:"neutral"},
  {kr:"感謝",ro:"kansha",meaning:"gratitude",example:"感謝しています — kansha shite imasu — I am grateful",pos:"noun",freq:7,register:"neutral"},
  {kr:"尊敬",ro:"sonkei",meaning:"respect",example:"先生を尊敬する — sensei wo sonkei suru — to respect a teacher",pos:"noun",freq:6,register:"neutral"},
  {kr:"理解",ro:"rikai",meaning:"understanding",example:"理解する — rikai suru — to understand",pos:"noun",freq:7,register:"neutral"},
  {kr:"感動",ro:"kandou",meaning:"being moved / deeply touched",example:"映画に感動した — eiga ni kandou shita — I was moved by the movie",pos:"noun",freq:7,register:"neutral"},
  {kr:"興奮",ro:"koufun",meaning:"excitement",example:"興奮する — koufun suru — to get excited",pos:"noun",freq:6,register:"neutral"},
  {kr:"挑戦",ro:"chousen",meaning:"challenge",example:"新しいことに挑戦する — atarashii koto ni chousen suru — to challenge something new",pos:"noun",freq:7,register:"neutral"},
  {kr:"達成",ro:"tassei",meaning:"achievement",example:"目標を達成する — mokuhyou wo tassei suru — to achieve a goal",pos:"noun",freq:6,register:"neutral"},
  {kr:"向上",ro:"koujou",meaning:"improvement",example:"スキルの向上 — sukiru no koujou — skill improvement",pos:"noun",freq:6,register:"neutral"},
  {kr:"決まる",ro:"kimaru",meaning:"to be decided",example:"予定が決まった — yotei ga kimatta — the schedule was decided",pos:"verb",freq:7,register:"neutral"},
  {kr:"集まる",ro:"atsumaru",meaning:"to gather / assemble",example:"みんなが集まった — minna ga atsumatta — everyone gathered",pos:"verb",freq:7,register:"neutral"},
  {kr:"連絡する",ro:"renraku suru",meaning:"to contact / to get in touch",example:"後で連絡します — ato de renraku shimasu — I'll contact you later",pos:"verb",freq:8,register:"neutral"},
  {kr:"参加する",ro:"sanka suru",meaning:"to participate",example:"イベントに参加する — ibento ni sanka suru — to participate in an event",pos:"verb",freq:7,register:"neutral"},
  {kr:"出席する",ro:"shusseki suru",meaning:"to attend",example:"会議に出席する — kaigi ni shusseki suru — to attend a meeting",pos:"verb",freq:6,register:"neutral"},
  {kr:"確かめる",ro:"tashikameru",meaning:"to make sure / to confirm",example:"事実を確かめる — jijitsu wo tashikameru — to confirm the facts",pos:"verb",freq:6,register:"neutral"},
  {kr:"見直す",ro:"minaoshi",meaning:"to review / to reconsider",example:"計画を見直す — keikaku wo minaoshi — to review the plan",pos:"verb",freq:6,register:"neutral"},
  {kr:"振り返る",ro:"furikaeru",meaning:"to look back / reflect",example:"一日を振り返る — ichinichi wo furikaeru — to reflect on the day",pos:"verb",freq:6,register:"neutral"},
  {kr:"成長する",ro:"seichou suru",meaning:"to grow / to develop",example:"子供が成長する — kodomo ga seichou suru — a child grows",pos:"verb",freq:7,register:"neutral"},
  {kr:"実現する",ro:"jitsugen suru",meaning:"to realize / to achieve",example:"夢を実現する — yume wo jitsugen suru — to realize a dream",pos:"verb",freq:6,register:"neutral"},
  {kr:"解決する",ro:"kaiketsu suru",meaning:"to solve / to resolve",example:"問題を解決する — mondai wo kaiketsu suru — to solve a problem",pos:"verb",freq:7,register:"neutral"},
  {kr:"開発する",ro:"kaihatsu suru",meaning:"to develop",example:"アプリを開発する — apuri wo kaihatsu suru — to develop an app",pos:"verb",freq:6,register:"neutral"},
  {kr:"利用する",ro:"riyou suru",meaning:"to use / to utilize",example:"サービスを利用する — saabisu wo riyou suru — to use a service",pos:"verb",freq:7,register:"neutral"},
  {kr:"注意する",ro:"chuui suru",meaning:"to be careful / to pay attention",example:"注意してください — chuui shite kudasai — please be careful",pos:"verb",freq:7,register:"neutral"},
  {kr:"反省する",ro:"hansei suru",meaning:"to reflect / to reconsider one's actions",example:"自分の行動を反省する — jibun no koudou wo hansei suru — to reflect on one's actions",pos:"verb",freq:6,register:"neutral"},
  {kr:"応援する",ro:"ouen suru",meaning:"to cheer / to support",example:"友達を応援する — tomodachi wo ouen suru — to cheer for a friend",pos:"verb",freq:7,register:"neutral"},
  {kr:"諦める",ro:"akirameru",meaning:"to give up",example:"夢を諦めない — yume wo akiramenai — don't give up on your dream",pos:"verb",freq:7,register:"neutral"},
  {kr:"乗り越える",ro:"norikoeru",meaning:"to overcome",example:"困難を乗り越える — konnan wo norikoeru — to overcome difficulties",pos:"verb",freq:6,register:"neutral"},
  {kr:"頼む",ro:"tanomu",meaning:"to ask / to request",example:"手伝いを頼む — tetsudai wo tanomu — to ask for help",pos:"verb",freq:7,register:"neutral"},
  {kr:"断る",ro:"kotowaru",meaning:"to refuse / to decline",example:"お誘いを断る — osasoi wo kotowaru — to decline an invitation",pos:"verb",freq:6,register:"neutral"},
  {kr:"謝る",ro:"ayamaru",meaning:"to apologize",example:"失礼を謝る — shitsurei wo ayamaru — to apologize for rudeness",pos:"verb",freq:7,register:"neutral"},
  {kr:"褒める",ro:"homeru",meaning:"to praise",example:"子供を褒める — kodomo wo homeru — to praise a child",pos:"verb",freq:6,register:"neutral"},
  {kr:"叱る",ro:"shikaru",meaning:"to scold",example:"子供を叱る — kodomo wo shikaru — to scold a child",pos:"verb",freq:5,register:"neutral"},
  {kr:"喜ぶ",ro:"yorokobu",meaning:"to be happy / to rejoice",example:"プレゼントに喜ぶ — purezento ni yorokobu — to be happy about a present",pos:"verb",freq:7,register:"neutral"},
  {kr:"悩む",ro:"nayamu",meaning:"to worry / to be troubled",example:"将来のことで悩む — shourai no koto de nayamu — to worry about the future",pos:"verb",freq:7,register:"neutral"},
  {kr:"諦める2",ro:"akirameru2",meaning:"to resign oneself",example:"仕方なく諦める — shikata naku akirameru — to reluctantly give up",pos:"verb",freq:6,register:"neutral"},
  {kr:"眠る",ro:"nemuru",meaning:"to sleep",example:"早く眠る — hayaku nemuru — to sleep early",pos:"verb",freq:7,register:"neutral"},
  {kr:"起こす",ro:"okosu",meaning:"to wake someone up",example:"子供を起こす — kodomo wo okosu — to wake up the child",pos:"verb",freq:6,register:"neutral"},
  {kr:"歌う",ro:"utau",meaning:"to sing",example:"歌を歌う — uta wo utau — to sing a song",pos:"verb",freq:8,register:"neutral"},
  {kr:"描く",ro:"kaku draw",meaning:"to draw / to paint",example:"絵を描く — e wo kaku — to draw a picture",pos:"verb",freq:6,register:"neutral"},
  {kr:"弾く",ro:"hiku play",meaning:"to play (instrument)",example:"ピアノを弾く — piano wo hiku — to play piano",pos:"verb",freq:6,register:"neutral"},
  {kr:"料理する",ro:"ryouri suru",meaning:"to cook",example:"夕食を料理する — yuushoku wo ryouri suru — to cook dinner",pos:"verb",freq:8,register:"neutral"},
  {kr:"掃除する",ro:"souji suru",meaning:"to clean",example:"部屋を掃除する — heya wo souji suru — to clean the room",pos:"verb",freq:7,register:"neutral"},
  {kr:"片付ける",ro:"katazukeru",meaning:"to tidy up / to put away",example:"部屋を片付ける — heya wo katazukeru — to tidy up the room",pos:"verb",freq:7,register:"neutral"},
  {kr:"捨てる",ro:"suteru",meaning:"to throw away / to discard",example:"ゴミを捨てる — gomi wo suteru — to throw away garbage",pos:"verb",freq:7,register:"neutral"},
  {kr:"拾う",ro:"hirou",meaning:"to pick up",example:"ゴミを拾う — gomi wo hirou — to pick up trash",pos:"verb",freq:6,register:"neutral"},
  {kr:"並ぶ",ro:"narabu",meaning:"to line up / to be in a row",example:"列に並ぶ — retsu ni narabu — to line up in a queue",pos:"verb",freq:7,register:"neutral"},
  {kr:"並べる",ro:"naraberu",meaning:"to line up / to arrange",example:"本を並べる — hon wo naraberu — to arrange books",pos:"verb",freq:6,register:"neutral"},
  {kr:"配る",ro:"kubaru",meaning:"to distribute / to hand out",example:"プリントを配る — purinto wo kubaru — to hand out printouts",pos:"verb",freq:6,register:"neutral"},
  {kr:"運ぶ",ro:"hakobu",meaning:"to carry / to transport",example:"荷物を運ぶ — nimotsu wo hakobu — to carry luggage",pos:"verb",freq:6,register:"neutral"},
  {kr:"届ける",ro:"todokeru",meaning:"to deliver",example:"手紙を届ける — tegami wo todokeru — to deliver a letter",pos:"verb",freq:6,register:"neutral"},
  {kr:"受け取る",ro:"uketoru",meaning:"to receive / to accept",example:"荷物を受け取る — nimotsu wo uketoru — to receive a package",pos:"verb",freq:7,register:"neutral"},
  {kr:"払う",ro:"harau",meaning:"to pay",example:"料金を払う — ryoukin wo harau — to pay the fee",pos:"verb",freq:8,register:"neutral"},
  {kr:"稼ぐ",ro:"kasegu",meaning:"to earn / to make money",example:"お金を稼ぐ — okane wo kasegu — to earn money",pos:"verb",freq:6,register:"neutral"},
  {kr:"節約する",ro:"setsuyaku suru",meaning:"to save / to economize",example:"お金を節約する — okane wo setsuyaku suru — to save money",pos:"verb",freq:6,register:"neutral"},
  {kr:"貯金する",ro:"chokin suru",meaning:"to save money",example:"毎月貯金する — maitsuki chokin suru — to save money every month",pos:"verb",freq:6,register:"neutral"},
  {kr:"予約する",ro:"yoyaku suru",meaning:"to reserve / to book",example:"レストランを予約する — resutoran wo yoyaku suru — to reserve a restaurant",pos:"verb",freq:7,register:"neutral"},
  {kr:"申し込む",ro:"moushikomu",meaning:"to apply / to sign up",example:"コースに申し込む — koosu ni moushikomu — to apply for a course",pos:"verb",freq:6,register:"neutral"},
  {kr:"登録する",ro:"touroku suru",meaning:"to register",example:"アカウントを登録する — akaunto wo touroku suru — to register an account",pos:"verb",freq:6,register:"neutral"},
  {kr:"検索する",ro:"kensaku suru",meaning:"to search",example:"インターネットで検索する — intaanetto de kensaku suru — to search the internet",pos:"verb",freq:7,register:"neutral"},
  {kr:"ダウンロードする",ro:"daunroodo suru",meaning:"to download",example:"アプリをダウンロードする — apuri wo daunroodo suru — to download an app",pos:"verb",freq:6,register:"neutral"},
  {kr:"アップロードする",ro:"appuroodo suru",meaning:"to upload",example:"写真をアップロードする — shashin wo appuroodo suru — to upload a photo",pos:"verb",freq:5,register:"neutral"},
  {kr:"コピーする",ro:"kopii suru",meaning:"to copy",example:"ファイルをコピーする — fairu wo kopii suru — to copy a file",pos:"verb",freq:6,register:"neutral"},
  {kr:"保存する",ro:"hozon suru",meaning:"to save / to store",example:"データを保存する — deeta wo hozon suru — to save data",pos:"verb",freq:6,register:"neutral"},
  {kr:"削除する",ro:"sakujo suru",meaning:"to delete",example:"ファイルを削除する — fairu wo sakujo suru — to delete a file",pos:"verb",freq:6,register:"neutral"},
  {kr:"更新する",ro:"koushin suru",meaning:"to update / to refresh",example:"アプリを更新する — apuri wo koushin suru — to update an app",pos:"verb",freq:6,register:"neutral"},
  {kr:"日課",ro:"nikka",meaning:"daily routine",example:"日課をこなす — nikka wo konasu — to complete one's daily routine",pos:"noun",freq:5,register:"neutral"},
  {kr:"生活",ro:"seikatsu",meaning:"daily life / living",example:"日常生活 — nichijou seikatsu — daily life",pos:"noun",freq:8,register:"neutral"},
  {kr:"食事",ro:"shokuji",meaning:"meal / eating",example:"食事をする — shokuji wo suru — to have a meal",pos:"noun",freq:8,register:"neutral"},
  {kr:"朝食",ro:"choushoku",meaning:"breakfast",example:"朝食を食べる — choushoku wo taberu — to eat breakfast",pos:"noun",freq:7,register:"neutral"},
  {kr:"昼食",ro:"chuushoku",meaning:"lunch",example:"昼食を取る — chuushoku wo toru — to have lunch",pos:"noun",freq:7,register:"neutral"},
  {kr:"夕食",ro:"yuushoku",meaning:"dinner",example:"家族と夕食を食べる — kazoku to yuushoku wo taberu — to have dinner with family",pos:"noun",freq:7,register:"neutral"},
  {kr:"おやつ",ro:"oyatsu",meaning:"snack",example:"おやつを食べる — oyatsu wo taberu — to eat a snack",pos:"noun",freq:7,register:"neutral"},
  {kr:"朝ごはん",ro:"asagohan",meaning:"breakfast (casual)",example:"朝ごはんを食べた？ — asagohan wo tabeta? — did you eat breakfast?",pos:"noun",freq:8,register:"casual"},
  {kr:"昼ごはん",ro:"hirugohan",meaning:"lunch (casual)",example:"昼ごはんは何にする？ — hirugohan wa nani ni suru? — what will you have for lunch?",pos:"noun",freq:8,register:"casual"},
  {kr:"晩ごはん",ro:"bangohan",meaning:"dinner (casual)",example:"晩ごはんを作る — bangohan wo tsukuru — to make dinner",pos:"noun",freq:8,register:"casual"},
  {kr:"外食",ro:"gaishoku",meaning:"eating out",example:"今日は外食しよう — kyou wa gaishoku shiyou — let's eat out today",pos:"noun",freq:7,register:"neutral"},
  {kr:"自炊",ro:"jisui",meaning:"cooking for oneself",example:"一人暮らしで自炊する — hitorigurasshi de jisui suru — to cook for myself while living alone",pos:"noun",freq:6,register:"neutral"},
  {kr:"お腹がすいた",ro:"onaka ga suita",meaning:"hungry",example:"お腹がすいたな — onaka ga suita na — I'm hungry",pos:"expression",freq:9,register:"casual"},
  {kr:"喉が渇いた",ro:"nodo ga kawaita",meaning:"thirsty",example:"喉が渇いた — nodo ga kawaita — I'm thirsty",pos:"expression",freq:8,register:"casual"},
  {kr:"疲れる",ro:"tsukareru",meaning:"to get tired",example:"仕事で疲れる — shigoto de tsukareru — to get tired from work",pos:"verb",freq:8,register:"neutral"},
  {kr:"痛む",ro:"itamu",meaning:"to hurt / to ache",example:"腰が痛む — koshi ga itamu — my back aches",pos:"verb",freq:6,register:"neutral"},
  {kr:"治る",ro:"naoru",meaning:"to heal / to recover",example:"風邪が治った — kaze ga naotta — the cold got better",pos:"verb",freq:7,register:"neutral"},
  {kr:"休む",ro:"yasumu2",meaning:"to rest / to be absent",example:"学校を休む — gakkou wo yasumu — to be absent from school",pos:"verb",freq:8,register:"neutral"},
  {kr:"太る",ro:"futoru",meaning:"to gain weight",example:"最近太った — saikin futotta — I gained weight recently",pos:"verb",freq:6,register:"casual"},
  {kr:"痩せる",ro:"yaseru",meaning:"to lose weight",example:"ダイエットして痩せた — daietto shite yaseta — I lost weight by dieting",pos:"verb",freq:6,register:"casual"},
  {kr:"植物",ro:"shokubutsu",meaning:"plant / vegetation",example:"植物を育てる — shokubutsu wo sodateru — to grow plants",pos:"noun",freq:6,register:"neutral"},
  {kr:"動物",ro:"doubutsu",meaning:"animal",example:"動物が好き — doubutsu ga suki — I like animals",pos:"noun",freq:7,register:"neutral"},
  {kr:"空気",ro:"kuuki",meaning:"air",example:"新鮮な空気 — shinsen na kuuki — fresh air",pos:"noun",freq:7,register:"neutral"},
  {kr:"気温",ro:"kion",meaning:"temperature (air)",example:"気温が上がる — kion ga agaru — the temperature rises",pos:"noun",freq:7,register:"neutral"},
  {kr:"天気予報",ro:"tenki yohou",meaning:"weather forecast",example:"天気予報を確認する — tenki yohou wo kakunin suru — to check the weather forecast",pos:"noun",freq:7,register:"neutral"},
  {kr:"湖",ro:"mizuumi",meaning:"lake",example:"湖で泳ぐ — mizuumi de oyogu — to swim in the lake",pos:"noun",freq:6,register:"neutral"},
  {kr:"砂浜",ro:"sunahama",meaning:"sandy beach",example:"砂浜を歩く — sunahama wo aruku — to walk on the sandy beach",pos:"noun",freq:6,register:"neutral"},
  {kr:"結婚",ro:"kekkon",meaning:"marriage",example:"結婚する — kekkon suru — to get married",pos:"noun",freq:7,register:"neutral"},
  {kr:"離婚",ro:"rikon",meaning:"divorce",example:"離婚した — rikon shita — I got divorced",pos:"noun",freq:5,register:"neutral"},
  {kr:"出産",ro:"shussan",meaning:"childbirth",example:"出産おめでとう — shussan omedetou — congratulations on the birth",pos:"noun",freq:6,register:"neutral"},
  {kr:"育てる",ro:"sodateru",meaning:"to raise / to bring up",example:"子供を育てる — kodomo wo sodateru — to raise a child",pos:"verb",freq:7,register:"neutral"},
  {kr:"付き合う",ro:"tsukiau",meaning:"to go out with / to date",example:"彼女と付き合う — kanojo to tsukiau — to date a girlfriend",pos:"verb",freq:7,register:"casual"},
  {kr:"別れる",ro:"wakareru",meaning:"to break up / to part",example:"彼氏と別れた — kareshi to wakareta — I broke up with my boyfriend",pos:"verb",freq:6,register:"casual"},
  {kr:"喧嘩する",ro:"kenka suru",meaning:"to fight / to argue",example:"友達と喧嘩した — tomodachi to kenka shita — I fought with a friend",pos:"verb",freq:6,register:"casual"},
  {kr:"仲直りする",ro:"nakanaori suru",meaning:"to make up / to reconcile",example:"喧嘩した後で仲直りした — kenka shita ato de nakanaori shita — we made up after the fight",pos:"verb",freq:6,register:"neutral"},
  {kr:"挨拶する",ro:"aisatsu suru",meaning:"to greet",example:"毎朝挨拶する — maiasa aisatsu suru — to greet every morning",pos:"verb",freq:7,register:"neutral"},
  {kr:"紹介する",ro:"shoukai suru2",meaning:"to introduce",example:"友達を紹介してもらった — tomodachi wo shoukai shite moratta — I was introduced to a friend",pos:"verb",freq:7,register:"neutral"},
  {kr:"一",ro:"ichi",meaning:"one",example:"一つ — hitotsu — one (thing)",pos:"noun",freq:9,register:"neutral"},
  {kr:"二",ro:"ni",meaning:"two",example:"二つ — futatsu — two (things)",pos:"noun",freq:9,register:"neutral"},
  {kr:"三",ro:"san",meaning:"three",example:"三つ — mittsu — three (things)",pos:"noun",freq:9,register:"neutral"},
  {kr:"四",ro:"shi/yon",meaning:"four",example:"四つ — yottsu — four (things)",pos:"noun",freq:8,register:"neutral"},
  {kr:"五",ro:"go",meaning:"five",example:"五つ — itsutsu — five (things)",pos:"noun",freq:8,register:"neutral"},
  {kr:"六",ro:"roku",meaning:"six",example:"六つ — muttsu — six (things)",pos:"noun",freq:8,register:"neutral"},
  {kr:"七",ro:"shichi/nana",meaning:"seven",example:"七つ — nanatsu — seven (things)",pos:"noun",freq:8,register:"neutral"},
  {kr:"八",ro:"hachi",meaning:"eight",example:"八つ — yattsu — eight (things)",pos:"noun",freq:8,register:"neutral"},
  {kr:"九",ro:"ku/kyuu",meaning:"nine",example:"九つ — kokonotsu — nine (things)",pos:"noun",freq:8,register:"neutral"},
  {kr:"十",ro:"juu",meaning:"ten",example:"十 — too — ten (things)",pos:"noun",freq:8,register:"neutral"},
  {kr:"百",ro:"hyaku",meaning:"hundred",example:"三百円 — sanbyaku en — 300 yen",pos:"noun",freq:7,register:"neutral"},
  {kr:"千",ro:"sen",meaning:"thousand",example:"五千円 — gosen en — 5000 yen",pos:"noun",freq:7,register:"neutral"},
  {kr:"万",ro:"man",meaning:"ten thousand",example:"一万円 — ichiman en — 10,000 yen",pos:"noun",freq:7,register:"neutral"},
  {kr:"個",ro:"ko",meaning:"counter for small objects",example:"三個ください — sanko kudasai — please give me three",pos:"noun",freq:7,register:"neutral"},
  {kr:"枚",ro:"mai",meaning:"counter for flat objects",example:"三枚 — sanmai — three sheets",pos:"noun",freq:6,register:"neutral"},
  {kr:"台",ro:"dai",meaning:"counter for machines/vehicles",example:"車一台 — kuruma ichidai — one car",pos:"noun",freq:6,register:"neutral"},
  {kr:"杯",ro:"hai",meaning:"counter for cups / bowls",example:"コーヒー一杯 — koohii ippai — one cup of coffee",pos:"noun",freq:7,register:"neutral"},
  {kr:"回",ro:"kai",meaning:"number of times",example:"三回 — sankai — three times",pos:"noun",freq:7,register:"neutral"},
  {kr:"階",ro:"kai floor",meaning:"floor / story",example:"三階 — sangai — third floor",pos:"noun",freq:7,register:"neutral"},
  {kr:"嫌い",ro:"kirai",meaning:"dislike / hate",example:"虫が嫌い — mushi ga kirai — I hate insects",pos:"adjective",freq:8,register:"neutral"},
  {kr:"苦手",ro:"nigate",meaning:"not good at / weak point",example:"数学が苦手 — suugaku ga nigate — I'm not good at math",pos:"adjective",freq:7,register:"neutral"},
  {kr:"得意",ro:"tokui",meaning:"good at / strong point",example:"英語が得意 — eigo ga tokui — I'm good at English",pos:"adjective",freq:7,register:"neutral"},
  {kr:"大丈夫",ro:"daijoubu2",meaning:"okay / fine / no problem",example:"大丈夫ですか？ — daijoubu desu ka? — are you okay?",pos:"adjective",freq:9,register:"neutral"},
  {kr:"相変わらず",ro:"aikawarazu",meaning:"as usual / same as always",example:"相変わらず元気です — aikawarazu genki desu — same as always, doing well",pos:"adverb",freq:6,register:"neutral"},
  {kr:"初めて",ro:"hajimete2",meaning:"for the first time",example:"日本に初めて来た — nihon ni hajimete kita — I came to Japan for the first time",pos:"adverb",freq:7,register:"neutral"},
  {kr:"もうすぐ",ro:"mousugu",meaning:"soon / before long",example:"もうすぐ春です — mousugu haru desu — spring is almost here",pos:"adverb",freq:7,register:"neutral"},
  {kr:"なかなか",ro:"nakanaka",meaning:"considerably / quite / not easily",example:"なかなか難しい — nakanaka muzukashii — it's quite difficult",pos:"adverb",freq:7,register:"neutral"},
  {kr:"せっかく",ro:"sekkaku",meaning:"having gone to the trouble of",example:"せっかく来たんだから — sekkaku kita n dakara — since you went to the trouble of coming",pos:"adverb",freq:6,register:"neutral"},
  {kr:"しかも",ro:"shikamo",meaning:"moreover / furthermore",example:"安くて、しかもおいしい — yasukute, shikamo oishii — cheap and moreover delicious",pos:"adverb",freq:6,register:"neutral"},
  {kr:"ただ",ro:"tada",meaning:"just / only / however",example:"ただ見ているだけ — tada mite iru dake — just watching",pos:"adverb",freq:7,register:"neutral"},
  {kr:"むしろ",ro:"mushiro",meaning:"rather / instead",example:"むしろ嬉しい — mushiro ureshii — I'm rather glad",pos:"adverb",freq:6,register:"neutral"},
  {kr:"さすがに",ro:"sasuga ni",meaning:"as expected / even so",example:"さすがに疲れた — sasuga ni tsukareta — I'm tired even so",pos:"adverb",freq:6,register:"neutral"},
  {kr:"たとえ",ro:"tatoe",meaning:"even if / suppose",example:"たとえ難しくても頑張る — tatoe muzukashikute mo ganbaru — I'll try even if it's difficult",pos:"adverb",freq:6,register:"neutral"},
  {kr:"もしも",ro:"moshimo",meaning:"if (hypothetical)",example:"もしも宝くじが当たったら — moshimo takarakuji ga atattara — if I won the lottery",pos:"adverb",freq:6,register:"neutral"},
  {kr:"手段",ro:"shudan",meaning:"means / method",example:"目的のための手段 — mokuteki no tame no shudan — means for the purpose",pos:"noun",freq:6,register:"neutral"},
  {kr:"結果",ro:"kekka2",meaning:"result / outcome",example:"実験の結果 — jikken no kekka — result of the experiment",pos:"noun",freq:7,register:"neutral"},
  {kr:"効果",ro:"kouka",meaning:"effect / result",example:"薬の効果 — kusuri no kouka — effect of medicine",pos:"noun",freq:6,register:"neutral"},
  {kr:"対策",ro:"taisaku",meaning:"countermeasure / measures",example:"対策を取る — taisaku wo toru — to take measures",pos:"noun",freq:6,register:"neutral"},
  {kr:"成果",ro:"seika",meaning:"result / outcome / achievement",example:"努力の成果 — doryoku no seika — result of effort",pos:"noun",freq:6,register:"neutral"},
  {kr:"経過",ro:"keika",meaning:"progress / passage of time",example:"時間の経過 — jikan no keika — passage of time",pos:"noun",freq:5,register:"neutral"},
  {kr:"理論",ro:"riron",meaning:"theory",example:"理論を証明する — riron wo shoumei suru — to prove a theory",pos:"noun",freq:6,register:"neutral"},
  {kr:"実践",ro:"jissen",meaning:"practice / putting into practice",example:"理論を実践する — riron wo jissen suru — to put theory into practice",pos:"noun",freq:6,register:"neutral"},
  {kr:"研究",ro:"kenkyuu",meaning:"research / study",example:"研究を続ける — kenkyuu wo tsuzukeru — to continue research",pos:"noun",freq:7,register:"neutral"},
  {kr:"調査",ro:"chousa",meaning:"investigation / research",example:"市場調査 — shijou chousa — market research",pos:"noun",freq:6,register:"neutral"},
  {kr:"分析",ro:"bunseki",meaning:"analysis",example:"データを分析する — deeta wo bunseki suru — to analyze data",pos:"noun",freq:6,register:"neutral"},
  {kr:"評価",ro:"hyouka",meaning:"evaluation / assessment",example:"仕事を評価する — shigoto wo hyouka suru — to evaluate work",pos:"noun",freq:7,register:"neutral"},
  {kr:"予め",ro:"arakajime",meaning:"in advance / beforehand",example:"予め準備する — arakajime junbi suru — to prepare in advance",pos:"adverb",freq:6,register:"neutral"},
  {kr:"まず",ro:"mazu",meaning:"first of all / to begin with",example:"まず自己紹介します — mazu jikoshoukai shimasu — first I'll introduce myself",pos:"adverb",freq:8,register:"neutral"},
  {kr:"その後",ro:"sono ato",meaning:"after that / following that",example:"その後どうなった？ — sono ato dou natta? — what happened after that?",pos:"expression",freq:7,register:"neutral"},
  {kr:"当然",ro:"touzen",meaning:"naturally / of course",example:"当然のことです — touzen no koto desu — it's only natural",pos:"adverb",freq:7,register:"neutral"},
  {kr:"意外と",ro:"igai to",meaning:"unexpectedly / surprisingly",example:"意外と簡単だった — igai to kantan datta — it was surprisingly easy",pos:"adverb",freq:7,register:"neutral"},
  {kr:"うまく",ro:"umaku",meaning:"successfully / skillfully",example:"うまくいった — umaku itta — it went well",pos:"adverb",freq:7,register:"neutral"},
  {kr:"ぼんやり",ro:"bonyari",meaning:"vaguely / absentmindedly",example:"ぼんやりしている — bonyari shite iru — spacing out",pos:"adverb",freq:5,register:"neutral"},
  {kr:"そっと",ro:"sotto",meaning:"softly / gently / quietly",example:"そっと触る — sotto sawaru — to touch gently",pos:"adverb",freq:6,register:"neutral"},
  {kr:"熱心に",ro:"nesshin ni",meaning:"enthusiastically / eagerly",example:"熱心に勉強する — nesshin ni benkyou suru — to study enthusiastically",pos:"adverb",freq:6,register:"neutral"},
  {kr:"冷静に",ro:"reisei ni",meaning:"calmly / coolly",example:"冷静に考える — reisei ni kangaeru — to think calmly",pos:"adverb",freq:6,register:"neutral"},
  {kr:"慌てて",ro:"awatete",meaning:"in a hurry / flustered",example:"慌てて出かけた — awatete dekaketa — left in a hurry",pos:"adverb",freq:6,register:"neutral"},
  {kr:"落ち着いて",ro:"ochitsuite",meaning:"calmly / composed",example:"落ち着いて聞いて — ochitsuite kiite — listen calmly",pos:"adverb",freq:7,register:"neutral"},
  {kr:"それにしても",ro:"sore ni shitemo",meaning:"even so / nevertheless",example:"それにしても大変だったね — sore ni shitemo taihen datta ne — even so it must have been hard",pos:"expression",freq:6,register:"neutral"},
  {kr:"特定",ro:"tokutei",meaning:"specific / particular",example:"特定の条件 — tokutei no jouken — specific conditions",pos:"noun",freq:6,register:"neutral"},
  {kr:"概要",ro:"gaiyou",meaning:"outline / overview",example:"概要を説明する — gaiyou wo setsumei suru — to explain the overview",pos:"noun",freq:6,register:"neutral"},
  {kr:"詳細",ro:"shousai",meaning:"detail / particulars",example:"詳細を確認する — shousai wo kakunin suru — to check the details",pos:"noun",freq:6,register:"neutral"},
  {kr:"内容",ro:"naiyou",meaning:"content / substance",example:"内容を確認する — naiyou wo kakunin suru — to check the content",pos:"noun",freq:7,register:"neutral"},
  {kr:"テーマ",ro:"teema",meaning:"theme / topic",example:"テーマを決める — teema wo kimeru — to decide the theme",pos:"noun",freq:7,register:"neutral"},
  {kr:"タイトル",ro:"taitoru",meaning:"title",example:"タイトルをつける — taitoru wo tsukeru — to give a title",pos:"noun",freq:6,register:"neutral"},
  {kr:"印象",ro:"inshou",meaning:"impression",example:"良い印象を与える — yoi inshou wo ataeru — to give a good impression",pos:"noun",freq:7,register:"neutral"},
  {kr:"雰囲気",ro:"funiki",meaning:"atmosphere / mood",example:"雰囲気がいい — funiki ga ii — the atmosphere is good",pos:"noun",freq:8,register:"neutral"},
  {kr:"景色",ro:"keshiki",meaning:"scenery / view",example:"景色が綺麗 — keshiki ga kirei — the scenery is beautiful",pos:"noun",freq:7,register:"neutral"},
  {kr:"背景",ro:"haikei",meaning:"background / backdrop",example:"背景を説明する — haikei wo setsumei suru — to explain the background",pos:"noun",freq:6,register:"neutral"},
  {kr:"場面",ro:"bamen",meaning:"scene / situation",example:"感動的な場面 — kandouteki na bamen — a moving scene",pos:"noun",freq:6,register:"neutral"},
  {kr:"機能",ro:"kinou",meaning:"function / feature",example:"機能を確認する — kinou wo kakunin suru — to check the function",pos:"noun",freq:7,register:"neutral"},
  {kr:"関連",ro:"kanren",meaning:"relation / connection / relevance",example:"関連情報 — kanren jouhou — related information",pos:"noun",freq:6,register:"neutral"},
  {kr:"共通",ro:"kyoutsuu",meaning:"common / shared",example:"共通点がある — kyoutsuu ten ga aru — there are common points",pos:"noun",freq:6,register:"neutral"},
  {kr:"矛盾",ro:"mujun",meaning:"contradiction / inconsistency",example:"矛盾している — mujun shite iru — it's contradictory",pos:"noun",freq:6,register:"neutral"},
  {kr:"バランス",ro:"baransu",meaning:"balance",example:"バランスを保つ — baransu wo tamotsu — to maintain balance",pos:"noun",freq:7,register:"neutral"},
  {kr:"全体",ro:"zentai",meaning:"the whole / overall",example:"全体的に見ると — zentai teki ni miru to — looking at it overall",pos:"noun",freq:7,register:"neutral"},
  {kr:"部分",ro:"bubun",meaning:"part / portion",example:"一部分だけ — ichiubun dake — just a part",pos:"noun",freq:7,register:"neutral"},
  {kr:"割合",ro:"wariai",meaning:"ratio / proportion / rate",example:"割合が高い — wariai ga takai — the ratio is high",pos:"noun",freq:6,register:"neutral"},
  {kr:"以上",ro:"ijou",meaning:"more than / above / that's all",example:"以上です — ijou desu — that's all",pos:"expression",freq:8,register:"neutral"},
  {kr:"以下",ro:"ika",meaning:"less than / below / the following",example:"以下の通り — ika no toori — as follows",pos:"expression",freq:7,register:"neutral"},
  {kr:"現在",ro:"genzai",meaning:"present / currently / now",example:"現在地 — genzaichi — current location",pos:"noun",freq:7,register:"neutral"},
  {kr:"未来",ro:"mirai",meaning:"future",example:"未来のために — mirai no tame ni — for the future",pos:"noun",freq:7,register:"neutral"},
  {kr:"現代",ro:"gendai",meaning:"modern times / present day",example:"現代社会 — gendai shakai — modern society",pos:"noun",freq:6,register:"neutral"},
  {kr:"昔",ro:"mukashi",meaning:"old times / long ago",example:"昔話 — mukashibanashi — old tale / folklore",pos:"noun",freq:7,register:"neutral"},
  {kr:"世代",ro:"sedai",meaning:"generation",example:"若い世代 — wakai sedai — the younger generation",pos:"noun",freq:6,register:"neutral"},
  {kr:"時代",ro:"jidai",meaning:"era / age / period",example:"江戸時代 — edo jidai — Edo period",pos:"noun",freq:7,register:"neutral"},
  {kr:"始まり",ro:"hajimari",meaning:"beginning / start",example:"物事の始まり — monogoto no hajimari — the beginning of things",pos:"noun",freq:6,register:"neutral"},
  {kr:"終わり",ro:"owari",meaning:"end / ending / conclusion",example:"終わりよければ全てよし — owari yokereba subete yoshi — all's well that ends well",pos:"noun",freq:7,register:"neutral"},
  {kr:"途中",ro:"tochuu",meaning:"on the way / midway / partway",example:"途中で止まる — tochuu de tomaru — to stop midway",pos:"noun",freq:7,register:"neutral"},
  {kr:"段階",ro:"dankai",meaning:"stage / phase / step",example:"次の段階へ — tsugi no dankai e — to the next stage",pos:"noun",freq:7,register:"neutral"},
  {kr:"革新",ro:"kakushin",meaning:"innovation / reform",example:"革新的なアイデア — kakushinteki na aidea — innovative idea",pos:"noun",freq:6,register:"neutral"},
  {kr:"改革",ro:"kaikaku",meaning:"reform / restructuring",example:"教育改革 — kyouiku kaikaku — education reform",pos:"noun",freq:6,register:"neutral"},
  {kr:"進化",ro:"shinka",meaning:"evolution / progress",example:"技術の進化 — gijutsu no shinka — technological evolution",pos:"noun",freq:7,register:"neutral"},
  {kr:"回復",ro:"kaifuku",meaning:"recovery / restoration",example:"経済の回復 — keizai no kaifuku — economic recovery",pos:"noun",freq:7,register:"neutral"},
  {kr:"構成",ro:"kousei",meaning:"composition / structure / makeup",example:"チームの構成 — chiimu no kousei — team composition",pos:"noun",freq:6,register:"neutral"},
  {kr:"仕組み",ro:"shikumi",meaning:"structure / mechanism / system",example:"仕組みを理解する — shikumi wo rikai suru — to understand the mechanism",pos:"noun",freq:7,register:"neutral"},
  {kr:"基盤",ro:"kiban",meaning:"foundation / base / infrastructure",example:"基盤を作る — kiban wo tsukuru — to build a foundation",pos:"noun",freq:6,register:"neutral"},
  {kr:"前提",ro:"zentei",meaning:"premise / precondition",example:"前提条件 — zentei jouken — prerequisite",pos:"noun",freq:6,register:"neutral"},
  {kr:"原理",ro:"genri",meaning:"principle / fundamental law",example:"基本原理 — kihon genri — basic principle",pos:"noun",freq:5,register:"neutral"},
  {kr:"組織",ro:"soshiki",meaning:"organization / structure",example:"組織を作る — soshiki wo tsukuru — to form an organization",pos:"noun",freq:7,register:"neutral"},
  {kr:"団体",ro:"dantai",meaning:"group / organization / body",example:"団体で行動する — dantai de koudou suru — to act as a group",pos:"noun",freq:6,register:"neutral"},
  {kr:"委員会",ro:"iinkai",meaning:"committee / board",example:"委員会を開く — iinkai wo hiraku — to hold a committee meeting",pos:"noun",freq:6,register:"neutral"},
  {kr:"部門",ro:"bumon",meaning:"department / division / section",example:"営業部門 — eigyou bumon — sales department",pos:"noun",freq:6,register:"neutral"},
  {kr:"担当",ro:"tantou",meaning:"in charge / person responsible",example:"担当者は誰ですか？ — tantousha wa dare desu ka? — who is in charge?",pos:"noun",freq:7,register:"neutral"},
  {kr:"社長",ro:"shachou",meaning:"company president / CEO",example:"社長に会う — shachou ni au — to meet the president",pos:"noun",freq:7,register:"neutral"},
  {kr:"部長",ro:"buchoo",meaning:"department head / manager",example:"部長に報告する — buchoo ni houkoku suru — to report to the manager",pos:"noun",freq:6,register:"neutral"},
  {kr:"アルバイト",ro:"arubaito",meaning:"part-time job",example:"アルバイトをする — arubaito wo suru — to work part-time",pos:"noun",freq:8,register:"casual"},
  {kr:"フリーランス",ro:"furiiransu",meaning:"freelance",example:"フリーランスで働く — furiiransu de hataraku — to work freelance",pos:"noun",freq:6,register:"neutral"},
  {kr:"起業",ro:"kigyou",meaning:"starting a business / entrepreneurship",example:"起業する — kigyou suru — to start a business",pos:"noun",freq:6,register:"neutral"},
  {kr:"需要",ro:"juyou",meaning:"demand",example:"需要が高い — juyou ga takai — demand is high",pos:"noun",freq:6,register:"neutral"},
  {kr:"供給",ro:"kyoukyuu",meaning:"supply",example:"需要と供給 — juyou to kyoukyuu — supply and demand",pos:"noun",freq:6,register:"neutral"},
  {kr:"価格",ro:"kakaku",meaning:"price / cost",example:"価格を下げる — kakaku wo sageru — to lower the price",pos:"noun",freq:7,register:"neutral"},
  {kr:"収益",ro:"shuueki",meaning:"revenue / profit / earnings",example:"収益を上げる — shuueki wo ageru — to increase revenue",pos:"noun",freq:6,register:"neutral"},
  {kr:"費用",ro:"hiyou",meaning:"cost / expense / fee",example:"費用がかかる — hiyou ga kakaru — it costs money",pos:"noun",freq:7,register:"neutral"},
  {kr:"広告",ro:"koukoku",meaning:"advertisement / advertising",example:"広告を出す — koukoku wo dasu — to place an advertisement",pos:"noun",freq:7,register:"neutral"},
  {kr:"品質",ro:"hinshitsu",meaning:"quality",example:"品質管理 — hinshitsu kanri — quality control",pos:"noun",freq:6,register:"neutral"},
  {kr:"サービス",ro:"saabisu",meaning:"service",example:"サービスが良い — saabisu ga yoi — the service is good",pos:"noun",freq:8,register:"neutral"},
  {kr:"ネットワーク",ro:"nettowaaku",meaning:"network",example:"ネットワークを広げる — nettowaaku wo hirogeru — to expand one's network",pos:"noun",freq:7,register:"neutral"},
  {kr:"ユーザー",ro:"yuuzaa",meaning:"user",example:"ユーザーの声 — yuuzaa no koe — voice of the user",pos:"noun",freq:7,register:"neutral"},
  {kr:"クライアント",ro:"kuraianto",meaning:"client",example:"クライアントの要望 — kuraianto no youbou — client's request",pos:"noun",freq:6,register:"neutral"},
  {kr:"デジタル",ro:"dejitaru",meaning:"digital",example:"デジタル化する — dejitaruka suru — to digitize",pos:"noun",freq:7,register:"neutral"},
  {kr:"オンライン",ro:"onrain",meaning:"online",example:"オンラインで会議する — onrain de kaigi suru — to meet online",pos:"noun",freq:8,register:"neutral"},
  {kr:"リモート",ro:"rimooto",meaning:"remote",example:"リモートワーク — rimooto waaku — remote work",pos:"noun",freq:7,register:"neutral"},
  {kr:"クラウド",ro:"kuraudo",meaning:"cloud",example:"クラウドに保存する — kuraudo ni hozon suru — to save to the cloud",pos:"noun",freq:6,register:"neutral"},
  {kr:"AI",ro:"eeeai",meaning:"artificial intelligence",example:"AIを活用する — eeeai wo katsuyou suru — to utilize AI",pos:"noun",freq:7,register:"neutral"},
  {kr:"セキュリティ",ro:"sekyuriti",meaning:"security",example:"セキュリティを強化する — sekyuriti wo kyouka suru — to strengthen security",pos:"noun",freq:7,register:"neutral"},
  {kr:"プライバシー",ro:"puraibashii",meaning:"privacy",example:"プライバシーを守る — puraibashii wo mamoru — to protect privacy",pos:"noun",freq:7,register:"neutral"},
  {kr:"リスク",ro:"risuku",meaning:"risk",example:"リスクを管理する — risuku wo kanri suru — to manage risk",pos:"noun",freq:7,register:"neutral"},
  {kr:"本質",ro:"honshitsu",meaning:"essence / true nature",example:"本質を見抜く — honshitsu wo minuku — to see through to the essence",pos:"noun",freq:6,register:"neutral"},
  {kr:"基本",ro:"kihon",meaning:"basics / fundamentals",example:"基本を大切に — kihon wo taisetsu ni — cherish the basics",pos:"noun",freq:8,register:"neutral"},
  {kr:"応用",ro:"ouyou",meaning:"application / applied use",example:"応用問題 — ouyou mondai — applied problem",pos:"noun",freq:6,register:"neutral"},
  {kr:"専門",ro:"senmon",meaning:"specialty / expertise",example:"専門分野 — senmon bunya — area of expertise",pos:"noun",freq:7,register:"neutral"},
  {kr:"専門家",ro:"senmonka",meaning:"specialist / expert",example:"専門家に相談する — senmonka ni soudan suru — to consult an expert",pos:"noun",freq:7,register:"neutral"},
  {kr:"初心者",ro:"shoshinsha",meaning:"beginner / novice",example:"初心者向け — shoshinsha muke — for beginners",pos:"noun",freq:7,register:"neutral"},
  {kr:"暗記",ro:"anki",meaning:"memorization / rote learning",example:"単語を暗記する — tango wo anki suru — to memorize vocabulary",pos:"noun",freq:7,register:"neutral"},
  {kr:"復習",ro:"fukushuu",meaning:"review / revision",example:"復習をする — fukushuu wo suru — to review",pos:"noun",freq:7,register:"neutral"},
  {kr:"予習",ro:"yoshuu",meaning:"preparation / preview",example:"予習をしてくる — yoshuu wo shite kuru — to come prepared",pos:"noun",freq:6,register:"neutral"},
  {kr:"論文",ro:"ronbun",meaning:"thesis / paper / essay",example:"論文を書く — ronbun wo kaku — to write a paper",pos:"noun",freq:6,register:"neutral"},
  {kr:"レポート",ro:"repooto",meaning:"report",example:"レポートを提出する — repooto wo teishutsu suru — to submit a report",pos:"noun",freq:7,register:"neutral"},
  {kr:"発表",ro:"happyou",meaning:"announcement / presentation / publication",example:"発表する — happyou suru — to present / to announce",pos:"noun",freq:7,register:"neutral"},
  {kr:"表現",ro:"hyougen",meaning:"expression / representation",example:"気持ちを表現する — kimochi wo hyougen suru — to express feelings",pos:"noun",freq:7,register:"neutral"},
  {kr:"言い方",ro:"iikata",meaning:"way of saying / phrasing",example:"言い方が大切 — iikata ga taisetsu — the way you say it matters",pos:"noun",freq:7,register:"neutral"},
  {kr:"使い方",ro:"tsukaikata",meaning:"how to use / usage",example:"正しい使い方 — tadashii tsukaikata — correct usage",pos:"noun",freq:7,register:"neutral"},
  {kr:"考え方",ro:"kangaekata",meaning:"way of thinking / perspective",example:"考え方を変える — kangaekata wo kaeru — to change the way of thinking",pos:"noun",freq:7,register:"neutral"},
  {kr:"見方",ro:"mikata",meaning:"way of looking / perspective / viewpoint",example:"見方を変える — mikata wo kaeru — to change one's perspective",pos:"noun",freq:6,register:"neutral"},
  {kr:"話し方",ro:"hanashikata",meaning:"way of speaking",example:"話し方を練習する — hanashikata wo renshuu suru — to practice speaking",pos:"noun",freq:6,register:"neutral"},
  {kr:"好奇心",ro:"koukishin",meaning:"curiosity",example:"好奇心旺盛 — koukishin ousei — full of curiosity",pos:"noun",freq:7,register:"neutral"},
  {kr:"情熱",ro:"jounetsu",meaning:"passion / enthusiasm",example:"情熱を持つ — jounetsu wo motsu — to have passion",pos:"noun",freq:7,register:"neutral"},
  {kr:"使命感",ro:"shimeikan",meaning:"sense of mission / calling",example:"使命感を持って働く — shimeikan wo motte hataraku — to work with a sense of mission",pos:"noun",freq:5,register:"neutral"},
  {kr:"こだわり",ro:"kodawari",meaning:"particular preference / commitment / perfectionism",example:"こだわりがある — kodawari ga aru — to have particular preferences",pos:"noun",freq:6,register:"neutral"},
  {kr:"プライド",ro:"puraido",meaning:"pride / ego",example:"プライドが高い — puraido ga takai — has a lot of pride",pos:"noun",freq:6,register:"neutral"},
  {kr:"アイデンティティ",ro:"aidentiti",meaning:"identity",example:"アイデンティティを持つ — aidentiti wo motsu — to have an identity",pos:"noun",freq:5,register:"neutral"},
  {kr:"個人",ro:"kojin",meaning:"individual / private person",example:"個人情報 — kojin jouhou — personal information",pos:"noun",freq:7,register:"neutral"},
  {kr:"集団",ro:"shuudan",meaning:"group / collective",example:"集団行動 — shuudan koudou — group behavior",pos:"noun",freq:6,register:"neutral"},
  {kr:"コミュニティ",ro:"komyuniti",meaning:"community",example:"地域コミュニティ — chiiki komyuniti — local community",pos:"noun",freq:6,register:"neutral"},
  {kr:"魅力",ro:"miryoku",meaning:"charm / appeal / attraction",example:"魅力的な人 — miryokuteki na hito — an attractive person",pos:"noun",freq:8,register:"neutral"},
  {kr:"注目",ro:"chuumoku",meaning:"attention / spotlight",example:"注目を集める — chuumoku wo atsumeru — to attract attention",pos:"noun",freq:7,register:"neutral"},
  {kr:"関心",ro:"kanshin",meaning:"interest / concern",example:"関心を持つ — kanshin wo motsu — to have an interest in",pos:"noun",freq:7,register:"neutral"},
  {kr:"興味",ro:"kyoumi",meaning:"interest / curiosity",example:"興味がある — kyoumi ga aru — to be interested",pos:"noun",freq:8,register:"neutral"},
  {kr:"共有",ro:"kyouyuu",meaning:"sharing / common possession",example:"情報を共有する — jouhou wo kyouyuu suru — to share information",pos:"noun",freq:7,register:"neutral"},
  {kr:"シェア",ro:"shea",meaning:"share / market share",example:"シェアする — shea suru — to share",pos:"noun",freq:7,register:"casual"},
  {kr:"いいね",ro:"iine",meaning:"like (social media)",example:"いいねを押す — iine wo osu — to press like",pos:"expression",freq:7,register:"casual"},
  {kr:"コメント",ro:"komento",meaning:"comment",example:"コメントを書く — komento wo kaku — to write a comment",pos:"noun",freq:7,register:"neutral"},
  {kr:"投稿",ro:"toukou",meaning:"post / submission",example:"投稿する — toukou suru — to post",pos:"noun",freq:7,register:"neutral"},
  {kr:"登録",ro:"touroku",meaning:"registration / enrollment",example:"登録する — touroku suru — to register",pos:"noun",freq:7,register:"neutral"},
  {kr:"設定",ro:"settei",meaning:"setting / configuration",example:"設定を変える — settei wo kaeru — to change settings",pos:"noun",freq:7,register:"neutral"},
  {kr:"アイデア",ro:"aidea",meaning:"idea",example:"アイデアを出す — aidea wo dasu — to come up with an idea",pos:"noun",freq:8,register:"neutral"},
  {kr:"ひらめき",ro:"hirameki",meaning:"flash of inspiration / bright idea",example:"ひらめいた！ — hirameta! — I just had an idea!",pos:"noun",freq:6,register:"neutral"},
  {kr:"デザイン",ro:"dezain",meaning:"design",example:"デザインする — dezain suru — to design",pos:"noun",freq:7,register:"neutral"},
  {kr:"ゴール",ro:"gooru",meaning:"goal / finish line",example:"ゴールを目指す — gooru wo mezasu — to aim for the goal",pos:"noun",freq:7,register:"neutral"},
  {kr:"ビジョン",ro:"bijon",meaning:"vision",example:"長期ビジョン — chouki bijon — long-term vision",pos:"noun",freq:6,register:"neutral"},
  {kr:"ミッション",ro:"misshon",meaning:"mission",example:"ミッションを果たす — misshon wo hatasu — to fulfill the mission",pos:"noun",freq:6,register:"neutral"},
  {kr:"プロセス",ro:"purosesu",meaning:"process",example:"プロセスを確認する — purosesu wo kakunin suru — to check the process",pos:"noun",freq:7,register:"neutral"},
  {kr:"レベル",ro:"reberu",meaning:"level",example:"レベルアップ — reberu appu — level up",pos:"noun",freq:7,register:"neutral"},
  {kr:"完了",ro:"kanryou",meaning:"completion / done",example:"作業完了 — sagyou kanryou — work complete",pos:"noun",freq:6,register:"neutral"},
  {kr:"承認",ro:"shounin",meaning:"approval / authorization",example:"承認を得る — shounin wo eru — to get approval",pos:"noun",freq:6,register:"neutral"},
  {kr:"指示",ro:"shiji",meaning:"instruction / direction / order",example:"指示に従う — shiji ni shitagau — to follow instructions",pos:"noun",freq:7,register:"neutral"},
  {kr:"命令",ro:"meirei",meaning:"order / command",example:"命令を出す — meirei wo dasu — to give an order",pos:"noun",freq:6,register:"neutral"},
  {kr:"依頼",ro:"irai",meaning:"request / commission",example:"依頼を受ける — irai wo ukeru — to accept a request",pos:"noun",freq:6,register:"neutral"},
  {kr:"要求",ro:"youkyuu",meaning:"demand / requirement",example:"要求を満たす — youkyuu wo mitasu — to meet requirements",pos:"noun",freq:6,register:"neutral"},
  {kr:"苦情",ro:"kujou",meaning:"complaint / grievance",example:"苦情を言う — kujou wo iu — to make a complaint",pos:"noun",freq:5,register:"neutral"},
  {kr:"問い合わせ",ro:"toiawase",meaning:"inquiry / inquiry",example:"問い合わせをする — toiawase wo suru — to make an inquiry",pos:"noun",freq:6,register:"neutral"},
  {kr:"ディスカッション",ro:"disukasshon",meaning:"discussion",example:"ディスカッションする — disukasshon suru — to have a discussion",pos:"noun",freq:6,register:"neutral"},
  {kr:"発想",ro:"hassou",meaning:"conception / idea / way of thinking",example:"発想が豊か — hassou ga yutaka — rich in ideas",pos:"noun",freq:6,register:"neutral"},
  {kr:"設計",ro:"sekkei",meaning:"design / planning / blueprint",example:"設計図 — sekkei zu — blueprint",pos:"noun",freq:6,register:"neutral"},
  {kr:"脳",ro:"nou",meaning:"brain",example:"脳を使う — nou wo tsukau — to use the brain",pos:"noun",freq:7,register:"neutral"},
  {kr:"心臓",ro:"shinzou",meaning:"heart (organ)",example:"心臓が強い — shinzou ga tsuyoi — has a strong heart",pos:"noun",freq:6,register:"neutral"},
  {kr:"肺",ro:"hai",meaning:"lung",example:"肺を鍛える — hai wo kitaeru — to train the lungs",pos:"noun",freq:5,register:"neutral"},
  {kr:"胃",ro:"i",meaning:"stomach (organ)",example:"胃が痛い — i ga itai — my stomach hurts",pos:"noun",freq:6,register:"neutral"},
  {kr:"ウイルス",ro:"uirusu",meaning:"virus",example:"ウイルスに感染する — uirusu ni kansen suru — to get infected with a virus",pos:"noun",freq:7,register:"neutral"},
  {kr:"免疫",ro:"meneki",meaning:"immunity / immune system",example:"免疫力を高める — menekiryoku wo takameru — to boost immunity",pos:"noun",freq:6,register:"neutral"},
  {kr:"感染",ro:"kansen",meaning:"infection / contagion",example:"感染を防ぐ — kansen wo fusegu — to prevent infection",pos:"noun",freq:7,register:"neutral"},
  {kr:"治療",ro:"chiryou",meaning:"treatment / therapy / cure",example:"治療を受ける — chiryou wo ukeru — to receive treatment",pos:"noun",freq:7,register:"neutral"},
  {kr:"副作用",ro:"fukusayou",meaning:"side effect",example:"副作用がある — fukusayou ga aru — there are side effects",pos:"noun",freq:6,register:"neutral"},
  {kr:"ロボット",ro:"robotto",meaning:"robot",example:"ロボットを作る — robotto wo tsukuru — to make a robot",pos:"noun",freq:6,register:"neutral"},
  {kr:"温暖化",ro:"ondanka",meaning:"global warming",example:"地球温暖化 — chikyuu ondanka — global warming",pos:"noun",freq:6,register:"neutral"},
  {kr:"汚染",ro:"osen",meaning:"pollution / contamination",example:"環境汚染 — kankyou osen — environmental pollution",pos:"noun",freq:6,register:"neutral"},
  {kr:"リサイクル",ro:"risaikuru",meaning:"recycling",example:"リサイクルする — risaikuru suru — to recycle",pos:"noun",freq:7,register:"neutral"},
  {kr:"エコ",ro:"eko",meaning:"eco / ecological / environmentally friendly",example:"エコな生活 — eko na seikatsu — eco-friendly lifestyle",pos:"noun",freq:6,register:"neutral"},
  {kr:"生態系",ro:"seitaikei",meaning:"ecosystem",example:"生態系を守る — seitaikei wo mamoru — to protect the ecosystem",pos:"noun",freq:5,register:"neutral"},
  {kr:"人口",ro:"jinkou",meaning:"population",example:"人口が増える — jinkou ga fueru — the population increases",pos:"noun",freq:7,register:"neutral"},
  {kr:"移住",ro:"ijuu",meaning:"migration / relocation / moving",example:"他の国に移住する — hoka no kuni ni ijuu suru — to move to another country",pos:"noun",freq:6,register:"neutral"},
  {kr:"故郷",ro:"kokyou",meaning:"hometown / birthplace",example:"故郷に帰る — kokyou ni kaeru — to return to one's hometown",pos:"noun",freq:7,register:"neutral"},
  {kr:"地域",ro:"chiiki",meaning:"area / region / community",example:"地域の人々 — chiiki no hitobito — people of the area",pos:"noun",freq:7,register:"neutral"},
  {kr:"ボランティア",ro:"borantia",meaning:"volunteer",example:"ボランティア活動 — borantia katsudou — volunteer activities",pos:"noun",freq:7,register:"neutral"},
  {kr:"福祉",ro:"fukushi",meaning:"welfare / well-being",example:"社会福祉 — shakai fukushi — social welfare",pos:"noun",freq:6,register:"neutral"},
  {kr:"介護",ro:"kaigo",meaning:"caregiving / nursing care",example:"介護をする — kaigo wo suru — to provide nursing care",pos:"noun",freq:6,register:"neutral"},
  {kr:"育児",ro:"ikuji",meaning:"child rearing / childcare",example:"育児に専念する — ikuji ni sennen suru — to devote oneself to childcare",pos:"noun",freq:6,register:"neutral"},
  {kr:"子育て",ro:"kosodaate",meaning:"raising children / parenting",example:"子育ては大変 — kosodaate wa taihen — raising children is hard",pos:"noun",freq:7,register:"neutral"},
  {kr:"テレワーク",ro:"terewaaku",meaning:"telework / remote work",example:"テレワークをする — terewaaku wo suru — to do telework",pos:"noun",freq:7,register:"neutral"},
  {kr:"在宅勤務",ro:"zaitaku kinmu",meaning:"working from home",example:"在宅勤務をする — zaitaku kinmu wo suru — to work from home",pos:"noun",freq:6,register:"neutral"},
  {kr:"副業",ro:"fukugyou",meaning:"side job / secondary work",example:"副業を始める — fukugyou wo hajimeru — to start a side job",pos:"noun",freq:6,register:"neutral"},
  {kr:"メンタルヘルス",ro:"mentaru herusu",meaning:"mental health",example:"メンタルヘルスを保つ — mentaru herusu wo tamotsu — to maintain mental health",pos:"noun",freq:6,register:"neutral"},
  {kr:"瞑想",ro:"meisou",meaning:"meditation",example:"瞑想をする — meisou wo suru — to meditate",pos:"noun",freq:6,register:"neutral"},
  {kr:"栄養",ro:"eiyou",meaning:"nutrition / nourishment",example:"栄養を取る — eiyou wo toru — to get nutrition",pos:"noun",freq:7,register:"neutral"},
  {kr:"体力",ro:"tairyoku",meaning:"physical strength / stamina",example:"体力をつける — tairyoku wo tsukeru — to build physical strength",pos:"noun",freq:7,register:"neutral"},
  {kr:"筋トレ",ro:"kin tore",meaning:"strength training / weight training",example:"筋トレをする — kin tore wo suru — to do strength training",pos:"noun",freq:6,register:"casual"},
  {kr:"ストレッチ",ro:"sutorecchi",meaning:"stretching",example:"ストレッチをする — sutorecchi wo suru — to stretch",pos:"noun",freq:6,register:"neutral"},
  {kr:"ダイエット",ro:"daietto",meaning:"diet / weight loss",example:"ダイエットをする — daietto wo suru — to go on a diet",pos:"noun",freq:7,register:"neutral"},
  {kr:"カロリー",ro:"karorii",meaning:"calorie",example:"カロリーを控える — karorii wo hikaeru — to cut calories",pos:"noun",freq:7,register:"neutral"},
  {kr:"タンパク質",ro:"tanpaku shitsu",meaning:"protein",example:"タンパク質を取る — tanpaku shitsu wo toru — to get protein",pos:"noun",freq:6,register:"neutral"},
  {kr:"ビタミン",ro:"bitamin",meaning:"vitamin",example:"ビタミンCが多い — bitamin shii ga ooi — high in vitamin C",pos:"noun",freq:6,register:"neutral"},
  {kr:"睡眠の質",ro:"suimin no shitsu",meaning:"quality of sleep",example:"睡眠の質を上げる — suimin no shitsu wo ageru — to improve sleep quality",pos:"noun",freq:6,register:"neutral"},
  {kr:"生活習慣",ro:"seikatsu shuukan",meaning:"lifestyle habits",example:"生活習慣を改善する — seikatsu shuukan wo kaizen suru — to improve lifestyle habits",pos:"noun",freq:6,register:"neutral"},
  {kr:"意志力",ro:"ishiryoku",meaning:"willpower / determination",example:"意志力が強い — ishiryoku ga tsuyoi — has strong willpower",pos:"noun",freq:5,register:"neutral"},
  {kr:"まあ",ro:"maa",meaning:"well / sort of / I suppose",example:"まあ、いいか — maa, ii ka — well, I guess it's okay",pos:"adverb",freq:8,register:"casual"},
  {kr:"ああ",ro:"aa",meaning:"ah / oh / I see",example:"ああ、そういうことか — aa, sou iu koto ka — ah, so that's what it means",pos:"expression",freq:8,register:"casual"},
  {kr:"えっ",ro:"e",meaning:"huh? / what? (surprised)",example:"えっ、本当に？ — e, hontou ni? — huh, really?",pos:"expression",freq:8,register:"casual"},
  {kr:"へえ",ro:"hee",meaning:"really? / oh! (impressed or surprised)",example:"へえ、知らなかった — hee, shiranakatta — oh, I didn't know that",pos:"expression",freq:8,register:"casual"},
  {kr:"ふーん",ro:"fuun",meaning:"hmm / I see (unimpressed or casual acknowledgment)",example:"ふーん、そうなんだ — fuun, sou nan da — hmm, is that so",pos:"expression",freq:7,register:"casual"},
  {kr:"そうか",ro:"souka",meaning:"I see / is that so",example:"そうか、わかった — souka, wakatta — I see, understood",pos:"expression",freq:8,register:"casual"},
  {kr:"そうかな",ro:"sou kana",meaning:"I wonder if that's right / hmm maybe",example:"そうかな、どうだろう — sou kana, dou darou — I wonder, what do you think",pos:"expression",freq:6,register:"casual"},
  {kr:"まさか",ro:"masaka",meaning:"no way / surely not / I can't believe it",example:"まさか、本当に？ — masaka, hontou ni? — no way, really?",pos:"expression",freq:7,register:"neutral"},
  {kr:"よかった",ro:"yokatta",meaning:"that's good / I'm glad / what a relief",example:"よかった、無事だった — yokatta, buji datta — I'm glad you're safe",pos:"expression",freq:9,register:"neutral"},
  {kr:"残念",ro:"zannen",meaning:"unfortunate / what a shame / too bad",example:"残念だな — zannen da na — that's too bad",pos:"expression",freq:8,register:"neutral"},
  {kr:"惜しい",ro:"oshii",meaning:"so close / what a waste / almost",example:"惜しい！あと少しだったのに — oshii! ato sukoshi datta noni — so close! you were almost there",pos:"expression",freq:7,register:"neutral"},
  {kr:"おめでとう",ro:"omedetou",meaning:"congratulations",example:"誕生日おめでとう — tanjoubi omedetou — happy birthday",pos:"expression",freq:9,register:"neutral"},
  {kr:"いいよ",ro:"ii yo",meaning:"it's fine / sure / go ahead (casual)",example:"いいよ、気にしないで — ii yo, ki ni shinai de — it's fine, don't worry about it",pos:"expression",freq:8,register:"casual"},
  {kr:"だめ",ro:"dame",meaning:"no good / not allowed / no",example:"だめだよ！ — dame da yo! — that's not allowed!",pos:"expression",freq:8,register:"casual"},
  {kr:"仕方ない",ro:"shikata nai",meaning:"it can't be helped / nothing to be done",example:"仕方ないね — shikata nai ne — nothing we can do about it",pos:"expression",freq:8,register:"neutral"},
  {kr:"どうしよう",ro:"doushiyou",meaning:"what should I do / what now",example:"どうしよう、忘れた — doushiyou, wasureta — what do I do, I forgot",pos:"expression",freq:8,register:"casual"},
  {kr:"気をつけて",ro:"ki wo tsukete",meaning:"take care / be careful",example:"気をつけて帰ってね — ki wo tsukete kaette ne — take care on your way home",pos:"expression",freq:8,register:"neutral"},
  {kr:"頑張って",ro:"ganbatte",meaning:"do your best / good luck",example:"頑張ってね！ — ganbatte ne! — do your best!",pos:"expression",freq:9,register:"neutral"},
  {kr:"行こう",ro:"ikou",meaning:"let's go",example:"さあ、行こう！ — saa, ikou! — come on, let's go!",pos:"expression",freq:8,register:"casual"},
  {kr:"待って",ro:"matte",meaning:"wait / hold on",example:"ちょっと待って！ — chotto matte! — wait a moment!",pos:"expression",freq:9,register:"casual"},
  {kr:"見て",ro:"mite",meaning:"look / look at this",example:"見て見て！ — mite mite! — look look!",pos:"expression",freq:8,register:"casual"},
  {kr:"助けて",ro:"tasukete",meaning:"help me / help!",example:"助けて！ — tasukete! — help!",pos:"expression",freq:8,register:"neutral"},
  {kr:"そこそこ",ro:"sokosoko",meaning:"so-so / moderately / decent",example:"そこそこできる — sokosoko dekiru — can do it reasonably well",pos:"adverb",freq:6,register:"casual"},
  {kr:"わりと",ro:"wari to",meaning:"relatively / rather / fairly",example:"わりと簡単だった — wari to kantan datta — it was fairly easy",pos:"adverb",freq:7,register:"casual"},
  {kr:"けっこう",ro:"kekkou",meaning:"quite / considerably / rather",example:"けっこう難しい — kekkou muzukashii — quite difficult",pos:"adverb",freq:7,register:"neutral"},
  {kr:"すごく",ro:"sugoku",meaning:"very / tremendously",example:"すごく美味しい — sugoku oishii — very delicious",pos:"adverb",freq:8,register:"casual"},
  {kr:"めちゃくちゃ",ro:"mechakucha",meaning:"very / extremely / messed up",example:"めちゃくちゃ楽しい — mechakucha tanoshii — extremely fun",pos:"adverb",freq:7,register:"casual"},
  {kr:"ぴったり",ro:"pittari",meaning:"perfectly / exactly / just right",example:"サイズがぴったり — saizu ga pittari — the size fits perfectly",pos:"adverb",freq:7,register:"neutral"},
  {kr:"どきどき",ro:"dokidoki",meaning:"heartbeat / nervous / excited feeling",example:"どきどきする — dokidoki suru — my heart is pounding",pos:"adverb",freq:7,register:"casual"},
  {kr:"わくわく",ro:"wakuwaku",meaning:"excited / thrilled / looking forward to",example:"わくわくしている — wakuwaku shite iru — I'm excited",pos:"adverb",freq:7,register:"casual"},
  {kr:"のんびり",ro:"nonbiri",meaning:"leisurely / easygoing / relaxed",example:"のんびりする — nonbiri suru — to take it easy",pos:"adverb",freq:7,register:"neutral"},
  {kr:"きらきら",ro:"kirakira",meaning:"sparkling / glittering / twinkling",example:"きらきら光る — kirakira hikaru — sparkling brightly",pos:"adverb",freq:6,register:"neutral"},
  {kr:"もやもや",ro:"moyamoya",meaning:"fuzzy / unclear / nagging feeling",example:"もやもやしている — moyamoya shite iru — I have a nagging feeling",pos:"adverb",freq:6,register:"casual"},
  {kr:"すっきり",ro:"sukkiri",meaning:"refreshed / clear / neat",example:"すっきりした！ — sukkiri shita! — I feel refreshed!",pos:"adverb",freq:7,register:"neutral"},
  {kr:"さっぱり",ro:"sappari",meaning:"refreshed / not at all / completely",example:"さっぱりわからない — sappari wakaranai — I have absolutely no idea",pos:"adverb",freq:7,register:"casual"},
  {kr:"余裕",ro:"yoyuu",meaning:"margin / leeway / composure",example:"余裕がある — yoyuu ga aru — there is room / I have composure",pos:"noun",freq:7,register:"neutral"},
  {kr:"気晴らし",ro:"kibarashi",meaning:"recreation / diversion / change of pace",example:"気晴らしをする — kibarashi wo suru — to have a diversion",pos:"noun",freq:6,register:"neutral"},
  {kr:"気分転換",ro:"kibun tenkan",meaning:"change of pace / refreshing oneself",example:"気分転換になる — kibun tenkan ni naru — to serve as a change of pace",pos:"noun",freq:7,register:"neutral"},
  {kr:"選択肢",ro:"sentakushi",meaning:"option / choice / alternative",example:"選択肢が多い — sentakushi ga ooi — there are many options",pos:"noun",freq:7,register:"neutral"},
  {kr:"交番",ro:"kouban",meaning:"police box / koban (small police post)",example:"交番で道を聞く — kouban de michi wo kiku — to ask directions at the police box",pos:"noun",freq:6,register:"neutral"},
  {kr:"消防署",ro:"shoubousho",meaning:"fire station",example:"消防署に電話する — shoubousho ni denwa suru — to call the fire station",pos:"noun",freq:5,register:"neutral"},
  {kr:"市役所",ro:"shiyakusho",meaning:"city hall",example:"市役所に届け出る — shiyakusho ni todokede ru — to file at city hall",pos:"noun",freq:6,register:"neutral"},
  {kr:"本屋",ro:"honya",meaning:"bookstore",example:"本屋で本を買う — honya de hon wo kau — to buy a book at the bookstore",pos:"noun",freq:7,register:"neutral"},
  {kr:"薬局",ro:"yakkyoku",meaning:"pharmacy / drugstore",example:"薬局で薬を買う — yakkyoku de kusuri wo kau — to buy medicine at the pharmacy",pos:"noun",freq:7,register:"neutral"},
  {kr:"美容院",ro:"biyouin",meaning:"beauty salon / hair salon",example:"美容院に行く — biyouin ni iku — to go to the hair salon",pos:"noun",freq:7,register:"neutral"},
  {kr:"ジム",ro:"jimu",meaning:"gym / fitness center",example:"ジムに通う — jimu ni kayou — to go to the gym regularly",pos:"noun",freq:7,register:"casual"},
  {kr:"出張",ro:"shucchou",meaning:"business trip",example:"出張で大阪へ行く — shucchou de oosaka e iku — to go to Osaka on a business trip",pos:"noun",freq:7,register:"neutral"},
  {kr:"日帰り",ro:"higaeri",meaning:"day trip",example:"日帰り旅行 — higaeri ryokou — day trip",pos:"noun",freq:6,register:"neutral"},
  {kr:"チェックイン",ro:"chekkuuin",meaning:"check-in",example:"ホテルにチェックインする — hoteru ni chekkuuin suru — to check in at the hotel",pos:"noun",freq:7,register:"neutral"},
  {kr:"チェックアウト",ro:"chekkuauto",meaning:"check-out",example:"チェックアウトは何時ですか？ — chekkuauto wa nanji desu ka? — what time is check-out?",pos:"noun",freq:7,register:"neutral"},
  {kr:"割り勘",ro:"warikan",meaning:"splitting the bill / going dutch",example:"割り勘にしよう — warikan ni shiyou — let's split the bill",pos:"noun",freq:7,register:"casual"},
  {kr:"証明書",ro:"shoumeisho",meaning:"certificate / document",example:"証明書を発行する — shoumeisho wo hakkou suru — to issue a certificate",pos:"noun",freq:6,register:"neutral"},
  {kr:"期限",ro:"kigen",meaning:"deadline / expiration date",example:"期限が切れる — kigen ga kireru — the deadline expires",pos:"noun",freq:7,register:"neutral"},
  {kr:"賞味期限",ro:"shoumi kigen",meaning:"best-by date / best before",example:"賞味期限を確認する — shoumi kigen wo kakunin suru — to check the best-by date",pos:"noun",freq:6,register:"neutral"},
  {kr:"和食",ro:"washoku",meaning:"Japanese cuisine",example:"和食が好き — washoku ga suki — I like Japanese cuisine",pos:"noun",freq:7,register:"neutral"},
  {kr:"洋食",ro:"youshoku",meaning:"Western food / Western cuisine",example:"洋食レストラン — youshoku resutoran — Western restaurant",pos:"noun",freq:6,register:"neutral"},
  {kr:"食材",ro:"shokuzai",meaning:"food ingredient / produce",example:"新鮮な食材 — shinsen na shokuzai — fresh ingredients",pos:"noun",freq:6,register:"neutral"},
  {kr:"蒸す",ro:"musu",meaning:"to steam",example:"蒸し料理 — mushi ryouri — steamed dish",pos:"verb",freq:5,register:"neutral"},
  {kr:"煮る",ro:"niru",meaning:"to boil / to simmer / to stew",example:"スープを煮る — suupu wo niru — to simmer soup",pos:"verb",freq:6,register:"neutral"},
  {kr:"焼く",ro:"yaku",meaning:"to grill / to bake / to roast",example:"パンを焼く — pan wo yaku — to bake bread",pos:"verb",freq:7,register:"neutral"},
  {kr:"炒める",ro:"itatmeru",meaning:"to stir-fry / to sauté",example:"野菜を炒める — yasai wo itatmeru — to stir-fry vegetables",pos:"verb",freq:6,register:"neutral"},
  {kr:"揚げる",ro:"ageru fry",meaning:"to deep-fry",example:"から揚げを揚げる — karaage wo ageru — to deep-fry karaage",pos:"verb",freq:6,register:"neutral"},
  {kr:"漬ける",ro:"tsukeru pickle",meaning:"to pickle / to marinate / to soak",example:"きゅうりを漬ける — kyuuri wo tsukeru — to pickle cucumber",pos:"verb",freq:5,register:"neutral"},
  {kr:"箸",ro:"hashi",meaning:"chopsticks",example:"箸を使う — hashi wo tsukau — to use chopsticks",pos:"noun",freq:8,register:"neutral"},
  {kr:"鍋",ro:"nabe",meaning:"pot / pan / hot pot dish",example:"鍋料理を作る — nabe ryouri wo tsukuru — to make hot pot",pos:"noun",freq:7,register:"neutral"},
  {kr:"豆腐",ro:"toufu",meaning:"tofu",example:"豆腐を食べる — toufu wo taberu — to eat tofu",pos:"noun",freq:7,register:"neutral"},
  {kr:"納豆",ro:"nattou",meaning:"natto (fermented soybeans)",example:"納豆が好きですか？ — nattou ga suki desu ka? — do you like natto?",pos:"noun",freq:6,register:"neutral"},
  {kr:"わさび",ro:"wasabi",meaning:"wasabi",example:"わさびを付ける — wasabi wo tsukeru — to put wasabi on",pos:"noun",freq:6,register:"neutral"},
  {kr:"生姜",ro:"shouga",meaning:"ginger",example:"生姜を入れる — shouga wo ireru — to add ginger",pos:"noun",freq:6,register:"neutral"},
  {kr:"にんにく",ro:"ninniku",meaning:"garlic",example:"にんにくを使う — ninniku wo tsukau — to use garlic",pos:"noun",freq:6,register:"neutral"},
  {kr:"玉ねぎ",ro:"tamanegi",meaning:"onion",example:"玉ねぎを切る — tamanegi wo kiru — to cut an onion",pos:"noun",freq:7,register:"neutral"},
  {kr:"じゃがいも",ro:"jagaimo",meaning:"potato",example:"じゃがいもを茹でる — jagaimo wo yuderu — to boil potatoes",pos:"noun",freq:7,register:"neutral"},
  {kr:"にんじん",ro:"ninjin",meaning:"carrot",example:"にんじんが入っている — ninjin ga haitte iru — carrots are included",pos:"noun",freq:7,register:"neutral"},
  {kr:"きゅうり",ro:"kyuuri",meaning:"cucumber",example:"きゅうりの漬物 — kyuuri no tsukemono — pickled cucumber",pos:"noun",freq:6,register:"neutral"},
  {kr:"トマト",ro:"tomato",meaning:"tomato",example:"トマトが好き — tomato ga suki — I like tomatoes",pos:"noun",freq:7,register:"neutral"},
  {kr:"りんご",ro:"ringo",meaning:"apple",example:"りんごを食べる — ringo wo taberu — to eat an apple",pos:"noun",freq:7,register:"neutral"},
  {kr:"バナナ",ro:"banana",meaning:"banana",example:"バナナを食べる — banana wo taberu — to eat a banana",pos:"noun",freq:7,register:"neutral"},
  {kr:"いちご",ro:"ichigo",meaning:"strawberry",example:"いちごが大好き — ichigo ga daisuki — I love strawberries",pos:"noun",freq:7,register:"neutral"},
  {kr:"米",ro:"kome",meaning:"rice (uncooked)",example:"お米を炊く — okome wo taku — to cook rice",pos:"noun",freq:7,register:"neutral"},
  {kr:"はちみつ",ro:"hachimitsu",meaning:"honey",example:"はちみつを入れる — hachimitsu wo ireru — to add honey",pos:"noun",freq:6,register:"neutral"},
  {kr:"エビ",ro:"ebi",meaning:"shrimp / prawn",example:"エビを料理する — ebi wo ryouri suru — to cook shrimp",pos:"noun",freq:7,register:"neutral"},
  {kr:"マグロ",ro:"maguro",meaning:"tuna",example:"マグロの刺身 — maguro no sashimi — tuna sashimi",pos:"noun",freq:7,register:"neutral"},
  {kr:"お好み焼き",ro:"okonomiyaki",meaning:"okonomiyaki (Japanese savory pancake)",example:"お好み焼きを作る — okonomiyaki wo tsukuru — to make okonomiyaki",pos:"noun",freq:7,register:"neutral"},
  {kr:"たこ焼き",ro:"takoyaki",meaning:"takoyaki (octopus balls)",example:"たこ焼きを食べる — takoyaki wo taberu — to eat takoyaki",pos:"noun",freq:7,register:"neutral"},
  {kr:"焼き鳥",ro:"yakitori",meaning:"grilled chicken skewers",example:"焼き鳥を食べる — yakitori wo taberu — to eat yakitori",pos:"noun",freq:7,register:"neutral"},
  {kr:"すき焼き",ro:"sukiyaki",meaning:"sukiyaki (hot pot dish)",example:"すき焼きを食べる — sukiyaki wo taberu — to eat sukiyaki",pos:"noun",freq:6,register:"neutral"},
  {kr:"おでん",ro:"oden",meaning:"oden (Japanese stew)",example:"おでんを食べる — oden wo taberu — to eat oden",pos:"noun",freq:6,register:"neutral"},
  {kr:"梅干し",ro:"umeboshi",meaning:"pickled plum",example:"梅干しご飯 — umeboshi gohan — rice with pickled plum",pos:"noun",freq:6,register:"neutral"},
  {kr:"海苔",ro:"nori",meaning:"seaweed / nori",example:"海苔を巻く — nori wo maku — to wrap with seaweed",pos:"noun",freq:7,register:"neutral"},
  {kr:"歌舞伎",ro:"kabuki",meaning:"kabuki theater",example:"歌舞伎を見る — kabuki wo miru — to watch kabuki",pos:"noun",freq:5,register:"neutral"},
  {kr:"忍者",ro:"ninja",meaning:"ninja",example:"忍者の衣装 — ninja no ishou — ninja costume",pos:"noun",freq:6,register:"neutral"},
  {kr:"将軍",ro:"shougun",meaning:"shogun / military commander",example:"江戸幕府の将軍 — edo bakufu no shougun — shogun of the Edo shogunate",pos:"noun",freq:5,register:"neutral"},
  {kr:"天皇",ro:"tennou",meaning:"Emperor (of Japan)",example:"天皇陛下 — tennou heika — His Majesty the Emperor",pos:"noun",freq:6,register:"neutral"},
  {kr:"七夕",ro:"tanabata",meaning:"Star Festival (July 7)",example:"七夕に願い事をする — tanabata ni negaigoto wo suru — to make a wish on Tanabata",pos:"noun",freq:5,register:"neutral"},
  {kr:"節分",ro:"setsubun",meaning:"bean-throwing festival (Feb 3)",example:"節分に豆まきをする — setsubun ni mamemaki wo suru — to throw beans on Setsubun",pos:"noun",freq:5,register:"neutral"},
  {kr:"大晦日",ro:"oomisoka",meaning:"New Year's Eve",example:"大晦日に除夜の鐘を聞く — oomisoka ni joya no kane wo kiku — to listen to the New Year's Eve bells",pos:"noun",freq:6,register:"neutral"},
  {kr:"初詣",ro:"hatsumoudeё",meaning:"first shrine visit of the New Year",example:"お正月に初詣に行く — oshougatsu ni hatsumoude ni iku — to visit a shrine on New Year's",pos:"noun",freq:6,register:"neutral"},
  {kr:"お守り",ro:"omamori",meaning:"amulet / good luck charm",example:"お守りを買う — omamori wo kau — to buy an amulet",pos:"noun",freq:6,register:"neutral"},
  {kr:"おみくじ",ro:"omikuji",meaning:"fortune slip (at shrines and temples)",example:"おみくじを引く — omikuji wo hiku — to draw a fortune slip",pos:"noun",freq:6,register:"neutral"},
  {kr:"神様",ro:"kamisama",meaning:"god / deity / divine being",example:"神様にお祈りする — kamisama ni oini ri suru — to pray to god",pos:"noun",freq:6,register:"neutral"},
  {kr:"信仰",ro:"shinkou",meaning:"faith / belief / religious devotion",example:"信仰を持つ — shinkou wo motsu — to have faith",pos:"noun",freq:5,register:"neutral"},
  {kr:"居酒屋",ro:"izakaya",meaning:"izakaya (Japanese pub)",example:"居酒屋で飲む — izakaya de nomu — to drink at an izakaya",pos:"noun",freq:7,register:"neutral"},
  {kr:"カラオケ",ro:"karaoke",meaning:"karaoke",example:"カラオケに行く — karaoke ni iku — to go to karaoke",pos:"noun",freq:8,register:"neutral"},
  {kr:"銭湯",ro:"sentou",meaning:"public bath / bathhouse",example:"銭湯に行く — sentou ni iku — to go to the public bath",pos:"noun",freq:6,register:"neutral"},
  {kr:"忘年会",ro:"bounenkai",meaning:"year-end party",example:"忘年会をする — bounenkai wo suru — to have a year-end party",pos:"noun",freq:6,register:"neutral"},
  {kr:"新年会",ro:"shinnenkai",meaning:"New Year party",example:"新年会に参加する — shinnenkai ni sanka suru — to attend a New Year party",pos:"noun",freq:5,register:"neutral"},
  {kr:"俳優",ro:"haiyuu",meaning:"actor / actress",example:"俳優になりたい — haiyuu ni naritai — I want to become an actor",pos:"noun",freq:6,register:"neutral"},
  {kr:"監督",ro:"kantoku",meaning:"director / manager / coach",example:"映画監督 — eiga kantoku — film director",pos:"noun",freq:7,register:"neutral"},
  {kr:"舞台",ro:"butai",meaning:"stage / the stage (theater)",example:"舞台に立つ — butai ni tatsu — to stand on stage",pos:"noun",freq:6,register:"neutral"},
  {kr:"演劇",ro:"engeki",meaning:"theater / drama / play",example:"演劇を見る — engeki wo miru — to watch a play",pos:"noun",freq:5,register:"neutral"},
  {kr:"ミュージカル",ro:"myuujiikaru",meaning:"musical (theater)",example:"ミュージカルを見る — myuujiikaru wo miru — to see a musical",pos:"noun",freq:6,register:"neutral"},
  {kr:"ジャズ",ro:"jazu",meaning:"jazz",example:"ジャズを聴く — jazu wo kiku — to listen to jazz",pos:"noun",freq:6,register:"neutral"},
  {kr:"ロック",ro:"rokku",meaning:"rock (music)",example:"ロックが好き — rokku ga suki — I like rock music",pos:"noun",freq:7,register:"casual"},
  {kr:"演歌",ro:"enka",meaning:"enka (traditional Japanese ballad)",example:"演歌を聴く — enka wo kiku — to listen to enka",pos:"noun",freq:5,register:"neutral"},
  {kr:"J-POP",ro:"jee poppu",meaning:"J-pop (Japanese pop music)",example:"J-POPが好き — jee poppu ga suki — I like J-pop",pos:"noun",freq:7,register:"casual"},
  {kr:"作曲",ro:"sakkyoku",meaning:"composing music / composition",example:"曲を作曲する — kyoku wo sakkyoku suru — to compose a song",pos:"noun",freq:5,register:"neutral"},
  {kr:"演奏",ro:"ensou",meaning:"musical performance / playing",example:"ピアノを演奏する — piano wo ensou suru — to perform on piano",pos:"noun",freq:6,register:"neutral"},
  {kr:"歌詞",ro:"kashi",meaning:"song lyrics",example:"歌詞を覚える — kashi wo oboeru — to memorize lyrics",pos:"noun",freq:7,register:"neutral"},
  {kr:"メロディー",ro:"merodii",meaning:"melody / tune",example:"美しいメロディー — utsukushii merodii — a beautiful melody",pos:"noun",freq:6,register:"neutral"},
  {kr:"リズム",ro:"rizumu",meaning:"rhythm",example:"リズムに乗る — rizumu ni noru — to ride the rhythm",pos:"noun",freq:7,register:"neutral"},
  {kr:"先輩",ro:"senpai",meaning:"senior / upperclassman",example:"先輩に教えてもらう — senpai ni oshiete morau — to be taught by a senior",pos:"noun",freq:8,register:"neutral"},
  {kr:"後輩",ro:"kouhai",meaning:"junior / underclassman",example:"後輩を指導する — kouhai wo shidou suru — to guide a junior",pos:"noun",freq:7,register:"neutral"},
  {kr:"同期",ro:"douki",meaning:"same year / same cohort / contemporary",example:"同期と仲が良い — douki to naka ga yoi — I get along well with my cohort",pos:"noun",freq:6,register:"neutral"},
  {kr:"ライバル",ro:"raibaru",meaning:"rival / competitor",example:"ライバルに負けない — raibaru ni makenai — I won't lose to my rival",pos:"noun",freq:7,register:"neutral"},
  {kr:"価値観",ro:"kachikan",meaning:"values / sense of values",example:"価値観が合う — kachikan ga au — our values match",pos:"noun",freq:7,register:"neutral"},
  {kr:"世界観",ro:"sekaikan",meaning:"worldview / outlook on life",example:"世界観が広がる — sekaikan ga hirogaru — one's worldview expands",pos:"noun",freq:6,register:"neutral"},
  {kr:"人生観",ro:"jinseikan",meaning:"philosophy of life / outlook on life",example:"人生観を持つ — jinseikan wo motsu — to have a philosophy of life",pos:"noun",freq:5,register:"neutral"},
  {kr:"感性",ro:"kansei",meaning:"sensitivity / sensibility / aesthetic sense",example:"豊かな感性 — yutaka na kansei — rich sensibility",pos:"noun",freq:6,register:"neutral"},
  {kr:"感覚",ro:"kankaku",meaning:"sense / feeling / intuition",example:"感覚を磨く — kankaku wo migaku — to sharpen one's senses",pos:"noun",freq:7,register:"neutral"},
  {kr:"直感",ro:"chokkan",meaning:"intuition / gut feeling",example:"直感を信じる — chokkan wo shinjiru — to trust one's intuition",pos:"noun",freq:6,register:"neutral"},
  {kr:"無意識",ro:"muishiki",meaning:"unconscious / subconscious",example:"無意識にやってしまう — muishiki ni yatte shimau — doing it unconsciously",pos:"noun",freq:5,register:"neutral"},
  {kr:"信念",ro:"shinnen",meaning:"belief / conviction / creed",example:"強い信念を持つ — tsuyoi shinnen wo motsu — to have strong convictions",pos:"noun",freq:6,register:"neutral"},
  {kr:"哲学",ro:"tetsugaku",meaning:"philosophy",example:"哲学を学ぶ — tetsugaku wo manabu — to study philosophy",pos:"noun",freq:6,register:"neutral"},
  {kr:"思想",ro:"shisou",meaning:"thought / ideology / idea",example:"思想を持つ — shisou wo motsu — to hold an ideology",pos:"noun",freq:5,register:"neutral"},
  {kr:"敬語",ro:"keigo",meaning:"honorific language / polite speech",example:"敬語を使う — keigo wo tsukau — to use honorific language",pos:"noun",freq:7,register:"neutral"},
  {kr:"名刺",ro:"meishi",meaning:"business card",example:"名刺を交換する — meishi wo koukan suru — to exchange business cards",pos:"noun",freq:7,register:"neutral"},
  {kr:"お辞儀",ro:"ojigi",meaning:"bow (gesture of respect)",example:"お辞儀をする — ojigi wo suru — to bow",pos:"noun",freq:6,register:"neutral"},
  {kr:"礼儀",ro:"reigi",meaning:"courtesy / manners / etiquette",example:"礼儀を守る — reigi wo mamoru — to observe proper manners",pos:"noun",freq:6,register:"neutral"},
  {kr:"外国語",ro:"gaikokugo",meaning:"foreign language",example:"外国語を学ぶ — gaikokugo wo manabu — to learn a foreign language",pos:"noun",freq:7,register:"neutral"},
  {kr:"母国語",ro:"bokokugo",meaning:"mother tongue / native language",example:"母国語は日本語です — bokokugo wa nihongo desu — my mother tongue is Japanese",pos:"noun",freq:6,register:"neutral"},
  {kr:"留学生",ro:"ryuugakusei",meaning:"international student / exchange student",example:"留学生が増えている — ryuugakusei ga fuete iru — the number of international students is increasing",pos:"noun",freq:6,register:"neutral"},
  {kr:"文化交流",ro:"bunka kouryuu",meaning:"cultural exchange",example:"文化交流をする — bunka kouryuu wo suru — to do cultural exchange",pos:"noun",freq:5,register:"neutral"},
  {kr:"マナー",ro:"manaa",meaning:"manners / etiquette",example:"マナーを守る — manaa wo mamoru — to follow proper manners",pos:"noun",freq:7,register:"neutral"},
  {kr:"節約",ro:"setsuyaku",meaning:"saving / economizing / frugality",example:"節約する — setsuyaku suru — to economize",pos:"noun",freq:7,register:"neutral"},
  {kr:"貯金",ro:"chokin",meaning:"savings / money saved",example:"貯金をする — chokin wo suru — to save money",pos:"noun",freq:7,register:"neutral"},
  {kr:"保険",ro:"hoken",meaning:"insurance",example:"保険に入る — hoken ni hairu — to get insurance",pos:"noun",freq:7,register:"neutral"},
  {kr:"借金",ro:"shakkin",meaning:"debt / loan",example:"借金を返す — shakkin wo kaesu — to repay a debt",pos:"noun",freq:6,register:"neutral"},
  {kr:"収入",ro:"shuunyuu",meaning:"income / earnings",example:"収入を増やす — shuunyuu wo fuyasu — to increase income",pos:"noun",freq:7,register:"neutral"},
  {kr:"景気",ro:"keiki",meaning:"economic conditions / business climate",example:"景気が良い — keiki ga yoi — the economy is good",pos:"noun",freq:7,register:"neutral"},
  {kr:"株",ro:"kabu",meaning:"stock / shares",example:"株を買う — kabu wo kau — to buy stocks",pos:"noun",freq:6,register:"neutral"},
  {kr:"為替",ro:"kawase",meaning:"foreign exchange / currency exchange",example:"為替レート — kawase reeto — exchange rate",pos:"noun",freq:5,register:"neutral"},
  {kr:"クレジットカード",ro:"kurejittto kaado",meaning:"credit card",example:"クレジットカードで払う — kurejittto kaado de harau — to pay by credit card",pos:"noun",freq:7,register:"neutral"},
  {kr:"キャッシュレス",ro:"kyasshu resu",meaning:"cashless",example:"キャッシュレス決済 — kyasshu resu kessai — cashless payment",pos:"noun",freq:6,register:"neutral"},
  {kr:"差別",ro:"sabetsu",meaning:"discrimination",example:"差別をなくす — sabetsu wo nakusu — to eliminate discrimination",pos:"noun",freq:7,register:"neutral"},
  {kr:"偏見",ro:"henken",meaning:"prejudice / bias",example:"偏見を持たない — henken wo motanai — to not hold prejudice",pos:"noun",freq:6,register:"neutral"},
  {kr:"ジェンダー",ro:"jendaa",meaning:"gender",example:"ジェンダー平等 — jendaa byoudou — gender equality",pos:"noun",freq:6,register:"neutral"},
  {kr:"平等",ro:"byoudou",meaning:"equality / equal rights",example:"平等に扱う — byoudou ni atsukau — to treat equally",pos:"noun",freq:7,register:"neutral"},
  {kr:"人権",ro:"jinken",meaning:"human rights",example:"人権を守る — jinken wo mamoru — to protect human rights",pos:"noun",freq:6,register:"neutral"},
  {kr:"憲法",ro:"kenpou",meaning:"constitution",example:"憲法を守る — kenpou wo mamoru — to uphold the constitution",pos:"noun",freq:6,register:"neutral"},
  {kr:"国会",ro:"kokkai",meaning:"national parliament / the Diet (Japan)",example:"国会で議論する — kokkai de giron suru — to debate in parliament",pos:"noun",freq:6,register:"neutral"},
  {kr:"選挙",ro:"senkyo",meaning:"election / vote",example:"選挙で投票する — senkyo de touhyou suru — to vote in an election",pos:"noun",freq:7,register:"neutral"},
  {kr:"犯罪",ro:"hanzai",meaning:"crime / criminal act",example:"犯罪を防ぐ — hanzai wo fusegu — to prevent crime",pos:"noun",freq:6,register:"neutral"},
  {kr:"事件",ro:"jiken",meaning:"incident / case / event",example:"事件が起きた — jiken ga okita — an incident occurred",pos:"noun",freq:7,register:"neutral"},
  {kr:"事故",ro:"jiko",meaning:"accident / incident",example:"交通事故 — koutsuu jiko — traffic accident",pos:"noun",freq:7,register:"neutral"},
  {kr:"災害",ro:"saigai",meaning:"disaster / calamity",example:"自然災害 — shizen saigai — natural disaster",pos:"noun",freq:6,register:"neutral"},
  {kr:"戦争",ro:"sensou",meaning:"war / warfare",example:"戦争はいけない — sensou wa ikenai — war is wrong",pos:"noun",freq:6,register:"neutral"},
  {kr:"条約",ro:"jouyaku",meaning:"treaty / agreement (between nations)",example:"条約を結ぶ — jouyaku wo musubu — to conclude a treaty",pos:"noun",freq:5,register:"neutral"}
];

JAPANESE_WORDS.push(...JAPANESE_WORDS_2);
