// ── DATA6.JS — Mexican Spanish & Venezuelan Spanish (separated) ───────────────
// Mexican Spanish uses SPANISH_MX_WORDS
// Venezuelan Spanish uses SPANISH_VE_WORDS
// No dialect-specific words cross between them

// ── SHARED CORE (neutral Latin American Spanish) ──────────────────────────────
// These go into both arrays at the end of this file
const SPANISH_CORE = [

  // Greetings shared by both
  {kr:"hola",ro:"hola",meaning:"hello / hi",example:"¡Hola! ¿Cómo estás? — Hello! How are you?",pos:"expression",freq:10,register:"casual"},
  {kr:"buenos días",ro:"buenos días",meaning:"good morning",example:"Buenos días — Good morning",pos:"expression",freq:9,register:"neutral"},
  {kr:"buenas tardes",ro:"buenas tardes",meaning:"good afternoon",example:"Buenas tardes — Good afternoon",pos:"expression",freq:9,register:"neutral"},
  {kr:"buenas noches",ro:"buenas noches",meaning:"good evening / good night",example:"Buenas noches — Good night",pos:"expression",freq:9,register:"neutral"},
  {kr:"adiós",ro:"adiós",meaning:"goodbye",example:"Adiós, cuídate — Goodbye, take care",pos:"expression",freq:10,register:"neutral"},
  {kr:"hasta luego",ro:"hasta luego",meaning:"see you later",example:"Hasta luego — See you later",pos:"expression",freq:9,register:"casual"},
  {kr:"gracias",ro:"gracias",meaning:"thank you",example:"Muchas gracias — Thank you very much",pos:"expression",freq:10,register:"neutral"},
  {kr:"por favor",ro:"por favor",meaning:"please",example:"Un café, por favor — A coffee, please",pos:"expression",freq:10,register:"neutral"},
  {kr:"perdón",ro:"perdón",meaning:"sorry / excuse me",example:"Perdón, no entendí — Sorry, I didn't understand",pos:"expression",freq:9,register:"neutral"},
  {kr:"sí",ro:"sí",meaning:"yes",example:"Sí, claro — Yes, of course",pos:"expression",freq:10,register:"neutral"},
  {kr:"no",ro:"no",meaning:"no",example:"No, gracias — No, thank you",pos:"expression",freq:10,register:"neutral"},
  {kr:"¿cómo estás?",ro:"¿cómo estás?",meaning:"how are you?",example:"¡Hola! ¿Cómo estás? — Hi! How are you?",pos:"expression",freq:10,register:"casual"},
  {kr:"bien",ro:"bien",meaning:"well / fine",example:"Estoy bien, gracias — I'm fine, thanks",pos:"expression",freq:10,register:"neutral"},
  {kr:"me llamo",ro:"me llamo",meaning:"my name is",example:"Me llamo Ana — My name is Ana",pos:"expression",freq:10,register:"neutral"},
  {kr:"mucho gusto",ro:"mucho gusto",meaning:"nice to meet you",example:"Mucho gusto — Nice to meet you",pos:"expression",freq:9,register:"neutral"},
  {kr:"de nada",ro:"de nada",meaning:"you're welcome",example:"De nada — You're welcome",pos:"expression",freq:9,register:"neutral"},
  {kr:"claro",ro:"claro",meaning:"of course / sure",example:"¡Claro que sí! — Of course!",pos:"expression",freq:9,register:"neutral"},

  // Core pronouns
  {kr:"yo",ro:"yo",meaning:"I",example:"Yo soy estudiante — I am a student",pos:"pronoun",freq:10,register:"neutral"},
  {kr:"tú",ro:"tú",meaning:"you (casual)",example:"¿Tú hablas español? — Do you speak Spanish?",pos:"pronoun",freq:10,register:"casual"},
  {kr:"él",ro:"él",meaning:"he",example:"Él es médico — He is a doctor",pos:"pronoun",freq:10,register:"neutral"},
  {kr:"ella",ro:"ella",meaning:"she",example:"Ella estudia — She studies",pos:"pronoun",freq:10,register:"neutral"},
  {kr:"nosotros",ro:"nosotros",meaning:"we",example:"Nosotros somos amigos — We are friends",pos:"pronoun",freq:9,register:"neutral"},
  {kr:"ustedes",ro:"ustedes",meaning:"you all",example:"¿Ustedes quieren comer? — Do you all want to eat?",pos:"pronoun",freq:9,register:"neutral"},
  {kr:"ellos",ro:"ellos",meaning:"they",example:"Ellos viven aquí — They live here",pos:"pronoun",freq:9,register:"neutral"},

  // Core verbs
  {kr:"ser",ro:"ser",meaning:"to be (permanent)",example:"Soy mexicana — I am Mexican",pos:"verb",freq:10,register:"neutral"},
  {kr:"estar",ro:"estar",meaning:"to be (temporary/location)",example:"Estoy cansada — I am tired",pos:"verb",freq:10,register:"neutral"},
  {kr:"tener",ro:"tener",meaning:"to have",example:"Tengo hambre — I'm hungry",pos:"verb",freq:10,register:"neutral"},
  {kr:"hacer",ro:"hacer",meaning:"to do / to make",example:"¿Qué haces? — What are you doing?",pos:"verb",freq:10,register:"neutral"},
  {kr:"ir",ro:"ir",meaning:"to go",example:"Voy al mercado — I'm going to the market",pos:"verb",freq:10,register:"neutral"},
  {kr:"querer",ro:"querer",meaning:"to want / to love",example:"Quiero un café — I want a coffee",pos:"verb",freq:10,register:"neutral"},
  {kr:"poder",ro:"poder",meaning:"to be able to / can",example:"No puedo ir — I can't go",pos:"verb",freq:10,register:"neutral"},
  {kr:"saber",ro:"saber",meaning:"to know",example:"No sé — I don't know",pos:"verb",freq:10,register:"neutral"},
  {kr:"hablar",ro:"hablar",meaning:"to speak",example:"Hablo español — I speak Spanish",pos:"verb",freq:10,register:"neutral"},
  {kr:"comer",ro:"comer",meaning:"to eat",example:"¿Quieres comer? — Do you want to eat?",pos:"verb",freq:10,register:"neutral"},
  {kr:"beber",ro:"beber",meaning:"to drink",example:"Bebo agua — I drink water",pos:"verb",freq:9,register:"neutral"},
  {kr:"dormir",ro:"dormir",meaning:"to sleep",example:"Dormí bien — I slept well",pos:"verb",freq:9,register:"neutral"},
  {kr:"trabajar",ro:"trabajar",meaning:"to work",example:"Trabajo mucho — I work a lot",pos:"verb",freq:9,register:"neutral"},
  {kr:"vivir",ro:"vivir",meaning:"to live",example:"¿Dónde vives? — Where do you live?",pos:"verb",freq:9,register:"neutral"},
  {kr:"decir",ro:"decir",meaning:"to say / to tell",example:"¿Qué dijiste? — What did you say?",pos:"verb",freq:10,register:"neutral"},
  {kr:"ver",ro:"ver",meaning:"to see / to watch",example:"Veo televisión — I watch TV",pos:"verb",freq:9,register:"neutral"},
  {kr:"venir",ro:"venir",meaning:"to come",example:"¿Puedes venir? — Can you come?",pos:"verb",freq:9,register:"neutral"},
  {kr:"dar",ro:"dar",meaning:"to give",example:"Dame tu número — Give me your number",pos:"verb",freq:9,register:"neutral"},
  {kr:"llegar",ro:"llegar",meaning:"to arrive",example:"Llegué tarde — I arrived late",pos:"verb",freq:8,register:"neutral"},
  {kr:"salir",ro:"salir",meaning:"to leave / go out",example:"Salgo a las ocho — I leave at eight",pos:"verb",freq:8,register:"neutral"},
  {kr:"gustar",ro:"gustar",meaning:"to like (lit: to please)",example:"Me gusta el café — I like coffee",pos:"verb",freq:10,register:"neutral"},
  {kr:"necesitar",ro:"necesitar",meaning:"to need",example:"Necesito ayuda — I need help",pos:"verb",freq:8,register:"neutral"},
  {kr:"llamar",ro:"llamar",meaning:"to call",example:"Te llamo después — I'll call you later",pos:"verb",freq:8,register:"neutral"},
  {kr:"esperar",ro:"esperar",meaning:"to wait / to hope",example:"Espera un momento — Wait a moment",pos:"verb",freq:8,register:"neutral"},
  {kr:"pensar",ro:"pensar",meaning:"to think",example:"Pienso que sí — I think so",pos:"verb",freq:8,register:"neutral"},
  {kr:"comprar",ro:"comprar",meaning:"to buy",example:"Voy a comprar leche — I'm going to buy milk",pos:"verb",freq:8,register:"neutral"},
  {kr:"leer",ro:"leer",meaning:"to read",example:"Leo mucho — I read a lot",pos:"verb",freq:8,register:"neutral"},
  {kr:"escribir",ro:"escribir",meaning:"to write",example:"Escribo cartas — I write letters",pos:"verb",freq:7,register:"neutral"},
  {kr:"estudiar",ro:"estudiar",meaning:"to study",example:"Estudio español — I study Spanish",pos:"verb",freq:9,register:"neutral"},
  {kr:"aprender",ro:"aprender",meaning:"to learn",example:"Aprendo español — I'm learning Spanish",pos:"verb",freq:8,register:"neutral"},

  // Core nouns shared
  {kr:"agua",ro:"agua",meaning:"water",example:"Un vaso de agua — A glass of water",pos:"noun",freq:10,register:"neutral"},
  {kr:"café",ro:"café",meaning:"coffee",example:"¿Quieres café? — Do you want coffee?",pos:"noun",freq:9,register:"neutral"},
  {kr:"pan",ro:"pan",meaning:"bread",example:"Pan fresco — Fresh bread",pos:"noun",freq:9,register:"neutral"},
  {kr:"arroz",ro:"arroz",meaning:"rice",example:"Arroz con pollo — Rice with chicken",pos:"noun",freq:9,register:"neutral"},
  {kr:"carne",ro:"carne",meaning:"meat",example:"Carne asada — Grilled meat",pos:"noun",freq:8,register:"neutral"},
  {kr:"pollo",ro:"pollo",meaning:"chicken",example:"Pollo a la plancha — Grilled chicken",pos:"noun",freq:8,register:"neutral"},
  {kr:"huevo",ro:"huevo",meaning:"egg",example:"Huevos revueltos — Scrambled eggs",pos:"noun",freq:8,register:"neutral"},
  {kr:"queso",ro:"queso",meaning:"cheese",example:"Queso fresco — Fresh cheese",pos:"noun",freq:8,register:"neutral"},
  {kr:"casa",ro:"casa",meaning:"house / home",example:"Voy a mi casa — I'm going home",pos:"noun",freq:10,register:"neutral"},
  {kr:"calle",ro:"calle",meaning:"street",example:"Esta calle — This street",pos:"noun",freq:8,register:"neutral"},
  {kr:"ciudad",ro:"ciudad",meaning:"city",example:"Una ciudad bonita — A pretty city",pos:"noun",freq:9,register:"neutral"},
  {kr:"familia",ro:"familia",meaning:"family",example:"Mi familia — My family",pos:"noun",freq:9,register:"neutral"},
  {kr:"amigo",ro:"amigo",meaning:"friend (male)",example:"Mi mejor amigo — My best friend",pos:"noun",freq:9,register:"neutral"},
  {kr:"amiga",ro:"amiga",meaning:"friend (female)",example:"Mi mejor amiga — My best friend",pos:"noun",freq:8,register:"neutral"},
  {kr:"trabajo",ro:"trabajo",meaning:"work / job",example:"Busco trabajo — I'm looking for work",pos:"noun",freq:9,register:"neutral"},
  {kr:"tiempo",ro:"tiempo",meaning:"time / weather",example:"No tengo tiempo — I don't have time",pos:"noun",freq:9,register:"neutral"},
  {kr:"día",ro:"día",meaning:"day",example:"Un buen día — A good day",pos:"noun",freq:10,register:"neutral"},
  {kr:"noche",ro:"noche",meaning:"night",example:"Buenas noches — Good night",pos:"noun",freq:9,register:"neutral"},

  // Shared adjectives
  {kr:"grande",ro:"grande",meaning:"big / great",example:"Una ciudad grande — A big city",pos:"adjective",freq:10,register:"neutral"},
  {kr:"pequeño",ro:"pequeño",meaning:"small",example:"Un cuarto pequeño — A small room",pos:"adjective",freq:9,register:"neutral"},
  {kr:"bueno",ro:"bueno",meaning:"good",example:"Muy bueno — Very good",pos:"adjective",freq:10,register:"neutral"},
  {kr:"malo",ro:"malo",meaning:"bad",example:"Un día malo — A bad day",pos:"adjective",freq:8,register:"neutral"},
  {kr:"nuevo",ro:"nuevo",meaning:"new",example:"Un teléfono nuevo — A new phone",pos:"adjective",freq:9,register:"neutral"},
  {kr:"viejo",ro:"viejo",meaning:"old",example:"Un edificio viejo — An old building",pos:"adjective",freq:8,register:"neutral"},
  {kr:"bonito",ro:"bonito",meaning:"pretty / nice",example:"¡Qué bonito! — How pretty!",pos:"adjective",freq:8,register:"neutral"},
  {kr:"rico",ro:"rico",meaning:"delicious / rich",example:"¡Qué rico! — How delicious!",pos:"adjective",freq:8,register:"casual"},
  {kr:"caro",ro:"caro",meaning:"expensive",example:"Está muy caro — Very expensive",pos:"adjective",freq:8,register:"neutral"},
  {kr:"barato",ro:"barato",meaning:"cheap",example:"¡Qué barato! — How cheap!",pos:"adjective",freq:7,register:"neutral"},
  {kr:"feliz",ro:"feliz",meaning:"happy",example:"Estoy feliz — I am happy",pos:"adjective",freq:8,register:"neutral"},
  {kr:"triste",ro:"triste",meaning:"sad",example:"Estoy triste — I am sad",pos:"adjective",freq:7,register:"neutral"},
  {kr:"cansado",ro:"cansado",meaning:"tired",example:"Estoy muy cansado — I'm very tired",pos:"adjective",freq:8,register:"neutral"},
  {kr:"ocupado",ro:"ocupado",meaning:"busy",example:"Estoy ocupada — I'm busy",pos:"adjective",freq:7,register:"neutral"},

  // Shared question words
  {kr:"¿qué?",ro:"¿qué?",meaning:"what?",example:"¿Qué quieres? — What do you want?",pos:"pronoun",freq:10,register:"neutral"},
  {kr:"¿quién?",ro:"¿quién?",meaning:"who?",example:"¿Quién es? — Who is it?",pos:"pronoun",freq:9,register:"neutral"},
  {kr:"¿dónde?",ro:"¿dónde?",meaning:"where?",example:"¿Dónde vives? — Where do you live?",pos:"adverb",freq:10,register:"neutral"},
  {kr:"¿cuándo?",ro:"¿cuándo?",meaning:"when?",example:"¿Cuándo llegas? — When do you arrive?",pos:"adverb",freq:9,register:"neutral"},
  {kr:"¿por qué?",ro:"¿por qué?",meaning:"why?",example:"¿Por qué no vienes? — Why aren't you coming?",pos:"adverb",freq:9,register:"neutral"},
  {kr:"¿cómo?",ro:"¿cómo?",meaning:"how?",example:"¿Cómo lo hiciste? — How did you do it?",pos:"adverb",freq:10,register:"neutral"},
  {kr:"¿cuánto?",ro:"¿cuánto?",meaning:"how much?",example:"¿Cuánto cuesta? — How much does it cost?",pos:"adjective",freq:9,register:"neutral"},

  // Shared connectors
  {kr:"y",ro:"y",meaning:"and",example:"Café y leche — Coffee and milk",pos:"adverb",freq:10,register:"neutral"},
  {kr:"o",ro:"o",meaning:"or",example:"¿Café o té? — Coffee or tea?",pos:"adverb",freq:9,register:"neutral"},
  {kr:"pero",ro:"pero",meaning:"but",example:"Me gusta, pero es caro — I like it but it's expensive",pos:"adverb",freq:10,register:"neutral"},
  {kr:"porque",ro:"porque",meaning:"because",example:"No fui porque estaba enfermo — I didn't go because I was sick",pos:"adverb",freq:9,register:"neutral"},
  {kr:"también",ro:"también",meaning:"also / too",example:"Yo también — Me too",pos:"adverb",freq:9,register:"neutral"},
  {kr:"muy",ro:"muy",meaning:"very",example:"Estoy muy cansado — I'm very tired",pos:"adverb",freq:10,register:"neutral"},
  {kr:"mucho",ro:"mucho",meaning:"a lot",example:"Te quiero mucho — I love you a lot",pos:"adverb",freq:10,register:"neutral"},
  {kr:"más",ro:"más",meaning:"more",example:"Quiero más — I want more",pos:"adverb",freq:10,register:"neutral"},
  {kr:"aquí",ro:"aquí",meaning:"here",example:"Estoy aquí — I'm here",pos:"adverb",freq:10,register:"neutral"},
  {kr:"ahora",ro:"ahora",meaning:"now",example:"Hazlo ahora — Do it now",pos:"adverb",freq:10,register:"neutral"},
  {kr:"hoy",ro:"hoy",meaning:"today",example:"¿Qué haces hoy? — What are you doing today?",pos:"adverb",freq:10,register:"neutral"},
  {kr:"mañana",ro:"mañana",meaning:"tomorrow / morning",example:"Hasta mañana — See you tomorrow",pos:"adverb",freq:10,register:"neutral"},
  {kr:"ayer",ro:"ayer",meaning:"yesterday",example:"¿Qué hiciste ayer? — What did you do yesterday?",pos:"adverb",freq:9,register:"neutral"},
  {kr:"siempre",ro:"siempre",meaning:"always",example:"Siempre llego tarde — I always arrive late",pos:"adverb",freq:9,register:"neutral"},
  {kr:"nunca",ro:"nunca",meaning:"never",example:"Nunca he ido — I've never been",pos:"adverb",freq:8,register:"neutral"},
  {kr:"ya",ro:"ya",meaning:"already / now",example:"Ya llegué — I already arrived",pos:"adverb",freq:10,register:"casual"},

  // Numbers
  {kr:"uno",ro:"uno",meaning:"one",example:"Un café — One coffee",pos:"noun",freq:10,register:"neutral"},
  {kr:"dos",ro:"dos",meaning:"two",example:"Dos boletos — Two tickets",pos:"noun",freq:10,register:"neutral"},
  {kr:"tres",ro:"tres",meaning:"three",example:"Tres horas — Three hours",pos:"noun",freq:10,register:"neutral"},
  {kr:"cuatro",ro:"cuatro",meaning:"four",example:"Cuatro personas — Four people",pos:"noun",freq:9,register:"neutral"},
  {kr:"cinco",ro:"cinco",meaning:"five",example:"Cinco minutos — Five minutes",pos:"noun",freq:9,register:"neutral"},
  {kr:"diez",ro:"diez",meaning:"ten",example:"Diez pesos — Ten pesos",pos:"noun",freq:8,register:"neutral"},
  {kr:"veinte",ro:"veinte",meaning:"twenty",example:"Veinte años — Twenty years",pos:"noun",freq:7,register:"neutral"},
  {kr:"cien",ro:"cien",meaning:"one hundred",example:"Cien pesos — One hundred pesos",pos:"noun",freq:7,register:"neutral"},
];

// ── MEXICAN SPANISH EXCLUSIVE ─────────────────────────────────────────────────
const SPANISH_MX_EXCLUSIVE = [
  // Mexican slang & expressions
  {kr:"órale",ro:"órale",meaning:"okay / alright / wow / let's go",example:"¿Listo? — Órale — Ready? — Alright",pos:"expression",freq:9,register:"casual"},
  {kr:"ahorita",ro:"ahorita",meaning:"right now / in a bit / later (context-dependent)",example:"Ahorita vengo — I'll be right there / I'll come later",pos:"adverb",freq:9,register:"casual"},
  {kr:"ahorita mismo",ro:"ahorita mismo",meaning:"right this second (truly immediate)",example:"¡Ahorita mismo! — Right now this instant!",pos:"adverb",freq:7,register:"casual"},
  {kr:"padre",ro:"padre",meaning:"cool / awesome",example:"¡Está muy padre! — That's awesome!",pos:"adjective",freq:8,register:"casual"},
  {kr:"chido",ro:"chido",meaning:"cool / great (youth slang)",example:"¡Qué chido! — How cool!",pos:"adjective",freq:7,register:"casual"},
  {kr:"chafa",ro:"chafa",meaning:"low quality / fake / bad",example:"Eso está muy chafa — That's really bad quality",pos:"adjective",freq:6,register:"casual"},
  {kr:"güey / wey",ro:"güey / wey",meaning:"dude / man / idiot (very common filler word)",example:"¡Órale, güey! — Come on, dude!",pos:"expression",freq:8,register:"casual"},
  {kr:"chavo",ro:"chavo",meaning:"kid / young guy",example:"Ese chavo es muy listo — That kid is very smart",pos:"noun",freq:7,register:"casual"},
  {kr:"chava",ro:"chava",meaning:"girl / young woman",example:"Una chava muy bonita — A very pretty girl",pos:"noun",freq:7,register:"casual"},
  {kr:"cuate",ro:"cuate",meaning:"buddy / twin / close friend",example:"Mi cuate de la escuela — My school buddy",pos:"noun",freq:6,register:"casual"},
  {kr:"mande",ro:"mande",meaning:"pardon? / yes? / I beg your pardon? (polite response)",example:"¿Mande? — Pardon me? / Yes?",pos:"expression",freq:8,register:"formal"},
  {kr:"antro",ro:"antro",meaning:"nightclub / bar",example:"Vamos al antro — Let's go to the club",pos:"noun",freq:6,register:"casual"},
  {kr:"torta",ro:"torta",meaning:"Mexican sandwich (on a bolillo roll)",example:"Una torta de jamón — A ham sandwich",pos:"noun",freq:7,register:"neutral"},
  {kr:"tacos",ro:"tacos",meaning:"tacos",example:"Unos tacos al pastor — Some tacos al pastor",pos:"noun",freq:8,register:"casual"},
  {kr:"quesadilla",ro:"quesadilla",meaning:"quesadilla (folded tortilla with cheese)",example:"Una quesadilla con queso — A cheese quesadilla",pos:"noun",freq:7,register:"neutral"},
  {kr:"elote",ro:"elote",meaning:"corn on the cob",example:"Elote con chile y limón — Corn with chile and lime",pos:"noun",freq:6,register:"neutral"},
  {kr:"chilango",ro:"chilango",meaning:"person from Mexico City",example:"Soy chilango — I'm from Mexico City",pos:"noun",freq:5,register:"casual"},
  {kr:"naco",ro:"naco",meaning:"tacky / low-class (informal insult)",example:"No seas naco — Don't be tacky",pos:"adjective",freq:5,register:"casual"},
  {kr:"feria",ro:"feria",meaning:"coins / loose change / money (slang)",example:"No tengo feria — I don't have change/money",pos:"noun",freq:6,register:"casual"},
  {kr:"camión",ro:"camión",meaning:"bus (Mexico)",example:"Me voy en camión — I'm going by bus",pos:"noun",freq:7,register:"casual"},
  {kr:"colonía",ro:"colonía",meaning:"neighborhood / district (Mexico)",example:"Vivo en la colonia Roma — I live in the Roma district",pos:"noun",freq:6,register:"neutral"},
  {kr:"popote",ro:"popote",meaning:"straw (drinking straw)",example:"¿Me da un popote? — Can I get a straw?",pos:"noun",freq:5,register:"casual"},
  {kr:"chamaco",ro:"chamaco",meaning:"kid / child",example:"Ese chamaco es travieso — That kid is mischievous",pos:"noun",freq:6,register:"casual"},
  {kr:"jefe",ro:"jefe",meaning:"boss / also used for dad (slang)",example:"Mi jefe llegó — My boss/dad arrived",pos:"noun",freq:7,register:"casual"},
  {kr:"jefa",ro:"jefa",meaning:"boss / also used for mom (slang)",example:"Mi jefa cocinó — My mom cooked",pos:"noun",freq:7,register:"casual"},
  {kr:"no manches",ro:"no manches",meaning:"no way! / come on! (mild expletive)",example:"¡No manches! ¿En serio? — No way! Seriously?",pos:"expression",freq:7,register:"casual"},
  {kr:"qué onda",ro:"qué onda",meaning:"what's up / what's going on",example:"¿Qué onda, güey? — What's up, dude?",pos:"expression",freq:8,register:"casual"},
  {kr:"al rato",ro:"al rato",meaning:"later / in a while",example:"Al rato nos vemos — We'll see each other later",pos:"adverb",freq:7,register:"casual"},
  {kr:"híjole",ro:"híjole",meaning:"wow / oh my / dang (exclamation)",example:"¡Híjole, qué problema! — Oh man, what a problem!",pos:"expression",freq:6,register:"casual"},
  {kr:"chingón",ro:"chingón",meaning:"awesome / badass (strong slang)",example:"¡Estás chingón! — You're awesome!",pos:"adjective",freq:5,register:"vulgar"},
  // Mexican food
  {kr:"salsa",ro:"salsa",meaning:"sauce / salsa",example:"Salsa picante — Hot sauce",pos:"noun",freq:8,register:"casual"},
  {kr:"chile",ro:"chile",meaning:"chili pepper",example:"Chile habanero — Habanero pepper",pos:"noun",freq:7,register:"neutral"},
  {kr:"limón",ro:"limón",meaning:"lime (in Mexico, limón = lime)",example:"Con limón y sal — With lime and salt",pos:"noun",freq:7,register:"neutral"},
  {kr:"aguacate",ro:"aguacate",meaning:"avocado",example:"Guacamole de aguacate — Avocado guacamole",pos:"noun",freq:7,register:"neutral"},
  {kr:"nopal",ro:"nopal",meaning:"cactus pad (food)",example:"Tacos de nopal — Cactus tacos",pos:"noun",freq:5,register:"neutral"},
  {kr:"mole",ro:"mole",meaning:"mole sauce",example:"Mole negro de Oaxaca — Oaxacan black mole",pos:"noun",freq:5,register:"neutral"},
  {kr:"frijoles",ro:"frijoles",meaning:"beans",example:"Frijoles de olla — Pot beans",pos:"noun",freq:8,register:"neutral"},
  {kr:"bolillo",ro:"bolillo",meaning:"Mexican bread roll",example:"Un bolillo con mantequilla — A bread roll with butter",pos:"noun",freq:5,register:"neutral"},
  // Mexican transport/places
  {kr:"CDMX",ro:"ciudad de México",meaning:"Mexico City (abbreviation)",example:"Vivo en CDMX — I live in Mexico City",pos:"noun",freq:6,register:"neutral"},
  {kr:"tianguis",ro:"tianguis",meaning:"outdoor market / flea market",example:"Compré en el tianguis — I bought it at the market",pos:"noun",freq:5,register:"casual"},
  {kr:"taquería",ro:"taquería",meaning:"taco stand / taco restaurant",example:"La mejor taquería del barrio — The best taco place in the neighborhood",pos:"noun",freq:5,register:"casual"},
];

// ── VENEZUELAN SPANISH EXCLUSIVE ──────────────────────────────────────────────
const SPANISH_VE_EXCLUSIVE = [
  // Venezuelan slang & expressions
  {kr:"chévere",ro:"chévere",meaning:"cool / great / awesome",example:"¡Eso está chévere! — That's cool!",pos:"adjective",freq:9,register:"casual"},
  {kr:"dale",ro:"dale",meaning:"okay / go for it / sounds good",example:"¿Vamos? — Dale — Shall we go? — Sure",pos:"expression",freq:9,register:"casual"},
  {kr:"pana",ro:"pana",meaning:"buddy / friend / mate",example:"Ese es mi pana — That's my buddy",pos:"noun",freq:9,register:"casual"},
  {kr:"chamo",ro:"chamo",meaning:"kid / young person / dude",example:"Ese chamo juega bien — That kid plays well",pos:"noun",freq:9,register:"casual"},
  {kr:"chama",ro:"chama",meaning:"girl / young woman",example:"Una chama muy inteligente — A very smart girl",pos:"noun",freq:8,register:"casual"},
  {kr:"vaina",ro:"vaina",meaning:"thing / stuff / situation (all-purpose word)",example:"¿Qué es esa vaina? — What is that thing?",pos:"noun",freq:10,register:"casual"},
  {kr:"¿qué es la vaina?",ro:"¿qué es la vaina?",meaning:"what's going on? / what's the deal?",example:"¿Qué es la vaina aquí? — What's going on here?",pos:"expression",freq:7,register:"casual"},
  {kr:"arrecho",ro:"arrecho",meaning:"angry / furious / also: awesome (context)",example:"Está arrecho — He's furious",pos:"adjective",freq:7,register:"casual"},
  {kr:"arrechera",ro:"arrechera",meaning:"anger / frustration",example:"Tengo una arrechera — I'm so frustrated",pos:"noun",freq:6,register:"casual"},
  {kr:"bravo",ro:"bravo",meaning:"angry (Venezuela/Caribbean)",example:"Está bravo — He's angry",pos:"adjective",freq:7,register:"casual"},
  {kr:"marico",ro:"marico",meaning:"dude / man (casual, not offensive in context)",example:"¡Marico, no me digas! — Dude, no way!",pos:"expression",freq:6,register:"casual"},
  {kr:"coño",ro:"coño",meaning:"damn / wow / expression of surprise/frustration",example:"¡Coño, qué calor! — Damn, it's so hot!",pos:"expression",freq:7,register:"casual"},
  {kr:"coñazo",ro:"coñazo",meaning:"a hard hit / something very intense",example:"Me di un coñazo — I hit myself hard",pos:"noun",freq:5,register:"casual"},
  {kr:"verga",ro:"verga",meaning:"strong exclamation (vulgar but very common)",example:"¡Verga, qué bueno! — Damn, that's good!",pos:"expression",freq:5,register:"vulgar"},
  {kr:"parcharse",ro:"parcharse",meaning:"to hang out / to meet up",example:"Vamos a parcharnos — Let's hang out",pos:"verb",freq:7,register:"casual"},
  {kr:"parche",ro:"parche",meaning:"hangout / group of friends",example:"El parche de siempre — The usual crew",pos:"noun",freq:6,register:"casual"},
  {kr:"ladilla",ro:"ladilla",meaning:"annoying / a nuisance",example:"¡Qué ladilla! — What a pain!",pos:"noun",freq:6,register:"casual"},
  {kr:"nojoda",ro:"nojoda",meaning:"no way / seriously (mild expletive)",example:"¡Nojoda, qué bueno! — No way, that's great!",pos:"expression",freq:6,register:"casual"},
  {kr:"cheverísimo",ro:"cheverísimo",meaning:"extremely cool / the coolest",example:"¡Estuvo cheverísimo! — It was amazing!",pos:"adjective",freq:6,register:"casual"},
  {kr:"pela",ro:"pela",meaning:"beating / thrashing",example:"Le dieron una pela — They beat him",pos:"noun",freq:5,register:"casual"},
  {kr:"broma",ro:"broma",meaning:"joke",example:"Es una broma — It's a joke",pos:"noun",freq:7,register:"neutral"},
  {kr:"joder",ro:"joder",meaning:"to bother / to mess with",example:"No me jodas — Don't mess with me",pos:"verb",freq:6,register:"casual"},
  {kr:"chota",ro:"chota",meaning:"police (slang)",example:"Viene la chota — The cops are coming",pos:"noun",freq:4,register:"casual"},
  {kr:"real",ro:"real",meaning:"money / Venezuelan currency (historical)",example:"No tengo reales — I have no money",pos:"noun",freq:5,register:"casual"},
  {kr:"bolívar",ro:"bolívar",meaning:"Venezuelan currency",example:"Cuesta mil bolívares — It costs a thousand bolívares",pos:"noun",freq:6,register:"neutral"},
  // Venezuelan food
  {kr:"arepa",ro:"arepa",meaning:"arepa — corn flatbread (staple)",example:"Una arepa con queso — An arepa with cheese",pos:"noun",freq:9,register:"neutral"},
  {kr:"caraotas",ro:"caraotas",meaning:"black beans (Venezuela)",example:"Caraotas negras — Black beans",pos:"noun",freq:8,register:"neutral"},
  {kr:"pabellón criollo",ro:"pabellón criollo",meaning:"Venezuela's national dish (rice, beans, beef, plantain)",example:"Un pabellón completo — A full pabellón",pos:"noun",freq:6,register:"neutral"},
  {kr:"cachapa",ro:"cachapa",meaning:"sweet corn pancake (Venezuela)",example:"Una cachapa con queso de mano — A corn cake with local cheese",pos:"noun",freq:6,register:"neutral"},
  {kr:"tequeño",ro:"tequeño",meaning:"cheese-filled bread stick (Venezuelan snack)",example:"Unos tequeños bien calientes — Some hot tequeños",pos:"noun",freq:6,register:"casual"},
  {kr:"hallaca",ro:"hallaca",meaning:"Venezuelan tamale (Christmas food)",example:"Las hallacas de navidad — Christmas hallacas",pos:"noun",freq:5,register:"neutral"},
  {kr:"tajadas",ro:"tajadas",meaning:"fried sweet plantain slices",example:"Arroz con tajadas — Rice with fried plantain",pos:"noun",freq:6,register:"neutral"},
  {kr:"papelón",ro:"papelón",meaning:"raw cane sugar block / also: embarrassment",example:"Papelón con limón — Cane sugar with lime drink",pos:"noun",freq:5,register:"casual"},
  {kr:"mandarina",ro:"mandarina",meaning:"mandarin / tangerine",example:"Una mandarina dulce — A sweet mandarin",pos:"noun",freq:5,register:"neutral"},
  // Venezuelan transport
  {kr:"carrito",ro:"carrito",meaning:"minibus / shared taxi (Venezuela)",example:"Tomo el carrito — I take the minibus",pos:"noun",freq:7,register:"casual"},
  {kr:"buseta",ro:"buseta",meaning:"small bus (Venezuela)",example:"Voy en buseta — I go by small bus",pos:"noun",freq:6,register:"casual"},
  {kr:"cola",ro:"cola",meaning:"ride / hitchhike (pedir cola = ask for a ride)",example:"¿Me das una cola? — Can you give me a ride?",pos:"noun",freq:7,register:"casual"},
  {kr:"pedir cola",ro:"pedir cola",meaning:"to hitchhike / to ask for a ride",example:"Pedí cola hasta el centro — I hitchhiked to the center",pos:"expression",freq:6,register:"casual"},
  // Venezuelan places/culture
  {kr:"bola",ro:"bola",meaning:"rumor / gossip / ball",example:"Eso es pura bola — That's just a rumor",pos:"noun",freq:5,register:"casual"},
  {kr:"maracucho",ro:"maracucho",meaning:"person from Maracaibo",example:"Es maracucho — He's from Maracaibo",pos:"noun",freq:4,register:"casual"},
  {kr:"caraqueño",ro:"caraqueño",meaning:"person from Caracas",example:"Soy caraqueña — I'm from Caracas",pos:"noun",freq:5,register:"neutral"},
];

// ── GRAMMAR NOTES ─────────────────────────────────────────────────────────────
(function() {
  if (typeof GRAMMAR === 'undefined') return;

  const sharedNotes = [
    {
      title: 'Ser vs Estar — two verbs for "to be"',
      short: 'Ser is permanent. Estar is temporary or location.',
      body: 'English has one "to be." Spanish has two.\n\nSer — who or what something fundamentally IS:\n  Soy venezolano — I am Venezuelan\n  Es médico — He is a doctor\n  La casa es grande — The house is big\n\nEstar — how something IS right now, or WHERE it is:\n  Estoy cansada — I am tired (right now)\n  El banco está cerrado — The bank is closed\n  ¿Dónde está el baño? — Where is the bathroom?\n\nA classic trick:\n  Soy aburrido — I am a boring person (personality)\n  Estoy aburrido — I am bored (right now)',
      example: 'Soy de Caracas. — I am from Caracas.\nEstoy en Caracas. — I am in Caracas.\nLa sopa es caliente. — Soup is hot (by nature).\nLa sopa está caliente. — The soup is hot (right now).',
      level: 1
    },
    {
      title: 'Tener hambre — "have" hunger, not "be" hungry',
      short: 'Physical states use tener (to have) where English uses to be.',
      body: 'In Spanish you "have" hunger, cold, fear, etc.\n\nTener + noun:\n  Tengo hambre — I\'m hungry (I have hunger)\n  Tengo sed — I\'m thirsty\n  Tengo frío — I\'m cold\n  Tengo calor — I\'m hot\n  Tengo miedo — I\'m scared\n  Tengo sueño — I\'m sleepy\n  Tengo razón — I\'m right\n\nAlso age:\n  Tengo veinte años — I\'m twenty (I have twenty years)',
      example: '¿Tienes hambre? — Are you hungry?\nSí, tengo mucha hambre — Yes, I\'m very hungry\nTenemos frío — We\'re cold',
      level: 1
    },
    {
      title: 'Gustar works backwards',
      short: 'Me gusta means "it pleases me" — the thing you like is the subject.',
      body: 'Gustar means "to please" — the liked thing is the subject.\n\n  Me gusta el café — Coffee pleases me (I like coffee)\n  Me gustan los tacos — Tacos please me (I like tacos)\n\ngusta = singular thing, gustan = plural things\n\nThe pronouns:\n  Me gusta — I like\n  Te gusta — You like\n  Le gusta — He/she likes\n  Nos gusta — We like\n  Les gusta — They like',
      example: 'Me gusta la música. — I like music.\nMe gustan las arepas. — I like arepas.\n¿Te gusta el fútbol? — Do you like football?',
      level: 1
    },
    {
      title: '¿Por qué? vs porque',
      short: 'Question = ¿Por qué? (two words, accent). Answer = porque (one word, no accent).',
      body: '¿Por qué? — why? (in a question)\nporque — because (in an answer)\n\n¿Por qué no vienes? — Why aren\'t you coming?\nNo voy porque estoy cansado — I\'m not going because I\'m tired\n\nAlso:\npor qué — why (inside a sentence, no question mark)\nNo entiendo por qué — I don\'t understand why\n\nel porqué — the reason (as a noun)\nQuiero saber el porqué — I want to know the reason',
      example: '¿Por qué lloras? — Why are you crying?\nLloro porque estoy feliz. — I\'m crying because I\'m happy.',
      level: 2
    },
  ];

  if (!GRAMMAR.spanish_mx) GRAMMAR.spanish_mx = [];
  GRAMMAR.spanish_mx.push(...sharedNotes, {
    title: 'Ahorita — Mexico\'s most flexible word',
    short: 'Ahorita can mean right now, in a bit, or eventually — tone decides.',
    body: 'Ahorita looks like it means "right now" but it has three meanings in Mexico depending on tone:\n\nAhorita mismo — truly right now, this second\n"Ahorita vengo" from a waiter — I\'ll be right with you (5 minutes)\n"Ahorita lo hago" from someone relaxed — I\'ll do it... eventually\n\nThe safest interpretation: soon-ish. When you need an exact time, ask for one.',
    example: '"Ahorita te atiendo" — I\'ll help you in a moment\n"Ahorita llego" at 9pm could mean midnight\n"¡Ahorita mismo!" means truly right now',
    level: 1
  });

  if (!GRAMMAR.spanish_ve) GRAMMAR.spanish_ve = [];
  GRAMMAR.spanish_ve.push(...sharedNotes, {
    title: 'Vaina — Venezuela\'s most useful word',
    short: 'Vaina means thing / situation / stuff — it fills every gap.',
    body: 'Vaina is arguably the most Venezuelan word in the language. It fills the role of "thing," "stuff," "deal," "situation" — any noun you can\'t think of or don\'t want to specify.\n\n¿Qué es esa vaina? — What is that thing?\nDame esa vaina — Give me that thing\n¿Qué fue esa vaina? — What was that about?\nLa vaina es que... — The thing is that...\nQué vaina — What a situation / That sucks\n\nUsed constantly. If you only learn one Venezuelan word, learn vaina.',
    example: '¿Qué es la vaina? — What\'s going on?\nLa vaina está difícil. — Things are tough.\n¡Qué vaina tan chévere! — What a cool thing!',
    level: 1
  });
})();

// ── BUILD FINAL ARRAYS ────────────────────────────────────────────────────────
const SPANISH_MX_WORDS = [...SPANISH_CORE, ...SPANISH_MX_EXCLUSIVE];
const SPANISH_VE_WORDS = [...SPANISH_CORE, ...SPANISH_VE_EXCLUSIVE];

if (typeof window !== 'undefined') {
  window.SPANISH_MX_WORDS = SPANISH_MX_WORDS;
  window.SPANISH_VE_WORDS = SPANISH_VE_WORDS;
}

// ── CORE EXPANSION — added to both MX and VE ─────────────────────────────────
const SPANISH_CORE_2 = [

  // Body & Health
  {kr:"cabeza",ro:"cabeza",meaning:"head",example:"Me duele la cabeza — My head hurts",pos:"noun",freq:8,register:"neutral"},
  {kr:"cara",ro:"cara",meaning:"face",example:"Tienes una cara bonita — You have a pretty face",pos:"noun",freq:8,register:"neutral"},
  {kr:"ojo",ro:"ojo",meaning:"eye",example:"Tiene los ojos verdes — She has green eyes",pos:"noun",freq:8,register:"neutral"},
  {kr:"nariz",ro:"nariz",meaning:"nose",example:"Me sangra la nariz — My nose is bleeding",pos:"noun",freq:7,register:"neutral"},
  {kr:"boca",ro:"boca",meaning:"mouth",example:"Abre la boca — Open your mouth",pos:"noun",freq:7,register:"neutral"},
  {kr:"mano",ro:"mano",meaning:"hand",example:"Dame la mano — Give me your hand",pos:"noun",freq:8,register:"neutral"},
  {kr:"pie",ro:"pie",meaning:"foot",example:"Me duele el pie — My foot hurts",pos:"noun",freq:7,register:"neutral"},
  {kr:"brazo",ro:"brazo",meaning:"arm",example:"Me rompí el brazo — I broke my arm",pos:"noun",freq:7,register:"neutral"},
  {kr:"pierna",ro:"pierna",meaning:"leg",example:"Me duele la pierna — My leg hurts",pos:"noun",freq:7,register:"neutral"},
  {kr:"espalda",ro:"espalda",meaning:"back",example:"Me duele la espalda — My back hurts",pos:"noun",freq:7,register:"neutral"},
  {kr:"estómago",ro:"estómago",meaning:"stomach",example:"Me duele el estómago — My stomach hurts",pos:"noun",freq:7,register:"neutral"},
  {kr:"corazón",ro:"corazón",meaning:"heart",example:"Mi corazón late rápido — My heart beats fast",pos:"noun",freq:8,register:"neutral"},
  {kr:"pecho",ro:"pecho",meaning:"chest",example:"Me duele el pecho — My chest hurts",pos:"noun",freq:7,register:"neutral"},
  {kr:"pelo",ro:"pelo",meaning:"hair",example:"Tiene el pelo largo — She has long hair",pos:"noun",freq:7,register:"neutral"},
  {kr:"cuello",ro:"cuello",meaning:"neck",example:"Me duele el cuello — My neck hurts",pos:"noun",freq:6,register:"neutral"},
  {kr:"rodilla",ro:"rodilla",meaning:"knee",example:"Me lastimé la rodilla — I hurt my knee",pos:"noun",freq:6,register:"neutral"},
  {kr:"diente",ro:"diente",meaning:"tooth",example:"Me duele un diente — I have a toothache",pos:"noun",freq:6,register:"neutral"},
  {kr:"sangre",ro:"sangre",meaning:"blood",example:"Hay sangre — There's blood",pos:"noun",freq:6,register:"neutral"},
  {kr:"hueso",ro:"hueso",meaning:"bone",example:"Me rompí un hueso — I broke a bone",pos:"noun",freq:6,register:"neutral"},
  {kr:"piel",ro:"piel",meaning:"skin",example:"Tiene la piel suave — She has soft skin",pos:"noun",freq:6,register:"neutral"},
  {kr:"enfermo",ro:"enfermo",meaning:"sick / ill",example:"Estoy enfermo — I am sick",pos:"adjective",freq:8,register:"neutral"},
  {kr:"fiebre",ro:"fiebre",meaning:"fever",example:"Tengo fiebre — I have a fever",pos:"noun",freq:7,register:"neutral"},
  {kr:"tos",ro:"tos",meaning:"cough",example:"Tengo tos — I have a cough",pos:"noun",freq:6,register:"neutral"},
  {kr:"gripa",ro:"gripa",meaning:"cold / flu",example:"Agarré la gripa — I caught a cold",pos:"noun",freq:6,register:"casual"},
  {kr:"dolor",ro:"dolor",meaning:"pain / ache",example:"Tengo un dolor — I have a pain",pos:"noun",freq:7,register:"neutral"},
  {kr:"medicina",ro:"medicina",meaning:"medicine",example:"Toma tu medicina — Take your medicine",pos:"noun",freq:7,register:"neutral"},
  {kr:"médico",ro:"médico",meaning:"doctor",example:"El médico llegó — The doctor arrived",pos:"noun",freq:7,register:"neutral"},
  {kr:"farmacia",ro:"farmacia",meaning:"pharmacy",example:"Voy a la farmacia — I'm going to the pharmacy",pos:"noun",freq:7,register:"neutral"},
  {kr:"hospital",ro:"hospital",meaning:"hospital",example:"Está en el hospital — She's in the hospital",pos:"noun",freq:7,register:"neutral"},
  {kr:"sano",ro:"sano",meaning:"healthy",example:"Estoy sano — I am healthy",pos:"adjective",freq:7,register:"neutral"},
  {kr:"herida",ro:"herida",meaning:"wound / injury",example:"Tiene una herida — He has a wound",pos:"noun",freq:5,register:"neutral"},
  {kr:"alergia",ro:"alergia",meaning:"allergy",example:"Tengo alergia — I have an allergy",pos:"noun",freq:5,register:"neutral"},
  {kr:"embarazada",ro:"embarazada",meaning:"pregnant",example:"Está embarazada — She's pregnant",pos:"adjective",freq:5,register:"neutral"},

  // Family
  {kr:"mamá",ro:"mamá",meaning:"mom",example:"Mi mamá cocina bien — My mom cooks well",pos:"noun",freq:9,register:"casual"},
  {kr:"papá",ro:"papá",meaning:"dad",example:"Mi papá trabaja mucho — My dad works a lot",pos:"noun",freq:9,register:"casual"},
  {kr:"hermano",ro:"hermano",meaning:"brother",example:"Mi hermano mayor — My older brother",pos:"noun",freq:8,register:"neutral"},
  {kr:"hermana",ro:"hermana",meaning:"sister",example:"Mi hermana vive lejos — My sister lives far away",pos:"noun",freq:8,register:"neutral"},
  {kr:"hijo",ro:"hijo",meaning:"son",example:"Mi hijo tiene cinco años — My son is five",pos:"noun",freq:8,register:"neutral"},
  {kr:"hija",ro:"hija",meaning:"daughter",example:"Mi hija estudia medicina — My daughter studies medicine",pos:"noun",freq:7,register:"neutral"},
  {kr:"abuelo",ro:"abuelo",meaning:"grandfather",example:"Mi abuelo tiene ochenta años — My grandfather is eighty",pos:"noun",freq:7,register:"neutral"},
  {kr:"abuela",ro:"abuela",meaning:"grandmother",example:"La abuela cocina muy bien — Grandma cooks very well",pos:"noun",freq:7,register:"neutral"},
  {kr:"tío",ro:"tío",meaning:"uncle",example:"Mi tío vive en Monterrey — My uncle lives in Monterrey",pos:"noun",freq:6,register:"neutral"},
  {kr:"tía",ro:"tía",meaning:"aunt",example:"Mi tía es muy divertida — My aunt is very fun",pos:"noun",freq:6,register:"neutral"},
  {kr:"primo",ro:"primo",meaning:"cousin (male)",example:"Mi primo es muy listo — My cousin is very smart",pos:"noun",freq:6,register:"neutral"},
  {kr:"prima",ro:"prima",meaning:"cousin (female)",example:"Mi prima vive en Caracas — My cousin lives in Caracas",pos:"noun",freq:6,register:"neutral"},
  {kr:"esposo",ro:"esposo",meaning:"husband",example:"Mi esposo llega tarde — My husband arrives late",pos:"noun",freq:7,register:"neutral"},
  {kr:"esposa",ro:"esposa",meaning:"wife",example:"Su esposa es muy simpática — His wife is very nice",pos:"noun",freq:7,register:"neutral"},
  {kr:"novio",ro:"novio",meaning:"boyfriend",example:"Mi novio es muy cariñoso — My boyfriend is very affectionate",pos:"noun",freq:7,register:"casual"},
  {kr:"novia",ro:"novia",meaning:"girlfriend",example:"Su novia es actriz — His girlfriend is an actress",pos:"noun",freq:7,register:"casual"},
  {kr:"vecino",ro:"vecino",meaning:"neighbor",example:"El vecino es muy amable — The neighbor is very friendly",pos:"noun",freq:6,register:"neutral"},
  {kr:"suegro",ro:"suegro",meaning:"father-in-law",example:"Mi suegro es estricto — My father-in-law is strict",pos:"noun",freq:5,register:"neutral"},
  {kr:"suegra",ro:"suegra",meaning:"mother-in-law",example:"Mi suegra cocina bien — My mother-in-law cooks well",pos:"noun",freq:5,register:"neutral"},
  {kr:"cuñado",ro:"cuñado",meaning:"brother-in-law",example:"Mi cuñado trabaja con nosotros — My brother-in-law works with us",pos:"noun",freq:4,register:"neutral"},

  // Food expansion
  {kr:"desayuno",ro:"desayuno",meaning:"breakfast",example:"El desayuno es importante — Breakfast is important",pos:"noun",freq:8,register:"neutral"},
  {kr:"almuerzo",ro:"almuerzo",meaning:"lunch",example:"¿Qué hay de almuerzo? — What's for lunch?",pos:"noun",freq:8,register:"neutral"},
  {kr:"cena",ro:"cena",meaning:"dinner",example:"La cena estuvo deliciosa — Dinner was delicious",pos:"noun",freq:8,register:"neutral"},
  {kr:"leche",ro:"leche",meaning:"milk",example:"Café con leche — Coffee with milk",pos:"noun",freq:8,register:"neutral"},
  {kr:"jugo",ro:"jugo",meaning:"juice",example:"Jugo de naranja — Orange juice",pos:"noun",freq:8,register:"neutral"},
  {kr:"verduras",ro:"verduras",meaning:"vegetables",example:"Come más verduras — Eat more vegetables",pos:"noun",freq:7,register:"neutral"},
  {kr:"frutas",ro:"frutas",meaning:"fruit",example:"Me gustan las frutas tropicales — I like tropical fruits",pos:"noun",freq:7,register:"neutral"},
  {kr:"sal",ro:"sal",meaning:"salt",example:"Más sal, por favor — More salt, please",pos:"noun",freq:7,register:"neutral"},
  {kr:"azúcar",ro:"azúcar",meaning:"sugar",example:"Sin azúcar — Without sugar",pos:"noun",freq:7,register:"neutral"},
  {kr:"aceite",ro:"aceite",meaning:"oil",example:"Aceite de oliva — Olive oil",pos:"noun",freq:6,register:"neutral"},
  {kr:"vinagre",ro:"vinagre",meaning:"vinegar",example:"Un poco de vinagre — A little vinegar",pos:"noun",freq:4,register:"neutral"},
  {kr:"mantequilla",ro:"mantequilla",meaning:"butter",example:"Pan con mantequilla — Bread with butter",pos:"noun",freq:6,register:"neutral"},
  {kr:"crema",ro:"crema",meaning:"cream / sour cream",example:"Con crema y queso — With cream and cheese",pos:"noun",freq:6,register:"neutral"},
  {kr:"pescado",ro:"pescado",meaning:"fish (to eat)",example:"Pescado a la plancha — Grilled fish",pos:"noun",freq:7,register:"neutral"},
  {kr:"camarón",ro:"camarón",meaning:"shrimp",example:"Camarones al ajillo — Shrimp in garlic",pos:"noun",freq:5,register:"neutral"},
  {kr:"cerdo",ro:"cerdo",meaning:"pork",example:"Carne de cerdo — Pork",pos:"noun",freq:6,register:"neutral"},
  {kr:"res",ro:"res",meaning:"beef (Latin American)",example:"Carne de res — Beef",pos:"noun",freq:6,register:"neutral"},
  {kr:"tomate",ro:"tomate",meaning:"tomato",example:"Un tomate rojo — A red tomato",pos:"noun",freq:6,register:"neutral"},
  {kr:"cebolla",ro:"cebolla",meaning:"onion",example:"Cebolla picada — Chopped onion",pos:"noun",freq:6,register:"neutral"},
  {kr:"ajo",ro:"ajo",meaning:"garlic",example:"Con mucho ajo — With lots of garlic",pos:"noun",freq:6,register:"neutral"},
  {kr:"naranja",ro:"naranja",meaning:"orange (fruit)",example:"Jugo de naranja — Orange juice",pos:"noun",freq:6,register:"neutral"},
  {kr:"mango",ro:"mango",meaning:"mango",example:"Un mango maduro — A ripe mango",pos:"noun",freq:5,register:"neutral"},
  {kr:"plátano",ro:"plátano",meaning:"banana / plantain",example:"Plátano maduro — Ripe plantain",pos:"noun",freq:6,register:"neutral"},
  {kr:"piña",ro:"piña",meaning:"pineapple",example:"Agua de piña — Pineapple water",pos:"noun",freq:5,register:"neutral"},
  {kr:"sandía",ro:"sandía",meaning:"watermelon",example:"Sandía fría — Cold watermelon",pos:"noun",freq:5,register:"neutral"},
  {kr:"restaurante",ro:"restaurante",meaning:"restaurant",example:"Vamos a un restaurante — Let's go to a restaurant",pos:"noun",freq:8,register:"neutral"},
  {kr:"menú",ro:"menú",meaning:"menu",example:"¿Me trae el menú? — Can you bring me the menu?",pos:"noun",freq:7,register:"neutral"},
  {kr:"cuenta",ro:"cuenta",meaning:"bill / check",example:"La cuenta, por favor — The check please",pos:"noun",freq:7,register:"neutral"},
  {kr:"propina",ro:"propina",meaning:"tip (gratuity)",example:"Dejé buena propina — I left a good tip",pos:"noun",freq:6,register:"neutral"},
  {kr:"sabor",ro:"sabor",meaning:"flavor / taste",example:"¡Qué sabor! — What flavor!",pos:"noun",freq:6,register:"neutral"},
  {kr:"picante",ro:"picante",meaning:"spicy",example:"¿Está picante? — Is it spicy?",pos:"adjective",freq:7,register:"neutral"},
  {kr:"dulce",ro:"dulce",meaning:"sweet / candy / dessert",example:"Algo dulce — Something sweet",pos:"adjective",freq:7,register:"neutral"},
  {kr:"amargo",ro:"amargo",meaning:"bitter",example:"Está muy amargo — It's very bitter",pos:"adjective",freq:5,register:"neutral"},
  {kr:"salado",ro:"salado",meaning:"salty",example:"Está muy salado — It's very salty",pos:"adjective",freq:6,register:"neutral"},
  {kr:"fresco",ro:"fresco",meaning:"fresh / cool",example:"Comida fresca — Fresh food",pos:"adjective",freq:7,register:"neutral"},
  {kr:"caliente",ro:"caliente",meaning:"hot (temperature)",example:"¡Cuidado, está caliente! — Careful, it's hot!",pos:"adjective",freq:8,register:"neutral"},
  {kr:"frío",ro:"frío",meaning:"cold (temperature)",example:"Sirve frío — Serve cold",pos:"adjective",freq:8,register:"neutral"},

  // Home & Objects
  {kr:"cuarto",ro:"cuarto",meaning:"room / bedroom",example:"Mi cuarto está arriba — My room is upstairs",pos:"noun",freq:8,register:"neutral"},
  {kr:"baño",ro:"baño",meaning:"bathroom",example:"¿Dónde está el baño? — Where is the bathroom?",pos:"noun",freq:9,register:"neutral"},
  {kr:"cocina",ro:"cocina",meaning:"kitchen",example:"La cocina es pequeña — The kitchen is small",pos:"noun",freq:7,register:"neutral"},
  {kr:"sala",ro:"sala",meaning:"living room",example:"Estamos en la sala — We're in the living room",pos:"noun",freq:7,register:"neutral"},
  {kr:"cama",ro:"cama",meaning:"bed",example:"Voy a la cama — I'm going to bed",pos:"noun",freq:8,register:"neutral"},
  {kr:"silla",ro:"silla",meaning:"chair",example:"Siéntate en esa silla — Sit in that chair",pos:"noun",freq:7,register:"neutral"},
  {kr:"mesa",ro:"mesa",meaning:"table",example:"Pon la mesa — Set the table",pos:"noun",freq:8,register:"neutral"},
  {kr:"puerta",ro:"puerta",meaning:"door",example:"Cierra la puerta — Close the door",pos:"noun",freq:9,register:"neutral"},
  {kr:"ventana",ro:"ventana",meaning:"window",example:"Abre la ventana — Open the window",pos:"noun",freq:7,register:"neutral"},
  {kr:"piso",ro:"piso",meaning:"floor / story of a building",example:"Vivo en el tercer piso — I live on the third floor",pos:"noun",freq:7,register:"neutral"},
  {kr:"techo",ro:"techo",meaning:"ceiling / roof",example:"El techo está goteando — The ceiling is leaking",pos:"noun",freq:6,register:"neutral"},
  {kr:"pared",ro:"pared",meaning:"wall",example:"Hay un cuadro en la pared — There's a picture on the wall",pos:"noun",freq:6,register:"neutral"},
  {kr:"escalera",ro:"escalera",meaning:"stairs",example:"Sube por las escaleras — Go up the stairs",pos:"noun",freq:6,register:"neutral"},
  {kr:"llave",ro:"llave",meaning:"key",example:"Se me olvidaron las llaves — I forgot my keys",pos:"noun",freq:7,register:"neutral"},
  {kr:"cerradura",ro:"cerradura",meaning:"lock",example:"La cerradura está rota — The lock is broken",pos:"noun",freq:5,register:"neutral"},
  {kr:"refrigerador",ro:"refrigerador",meaning:"refrigerator",example:"Está en el refrigerador — It's in the fridge",pos:"noun",freq:6,register:"neutral"},
  {kr:"estufa",ro:"estufa",meaning:"stove / oven",example:"La estufa está encendida — The stove is on",pos:"noun",freq:6,register:"neutral"},
  {kr:"lavadora",ro:"lavadora",meaning:"washing machine",example:"Voy a poner la lavadora — I'm going to run the washing machine",pos:"noun",freq:5,register:"neutral"},
  {kr:"almohada",ro:"almohada",meaning:"pillow",example:"Una almohada suave — A soft pillow",pos:"noun",freq:5,register:"neutral"},
  {kr:"cobija",ro:"cobija",meaning:"blanket",example:"Dame una cobija — Give me a blanket",pos:"noun",freq:6,register:"casual"},
  {kr:"toalla",ro:"toalla",meaning:"towel",example:"Una toalla limpia — A clean towel",pos:"noun",freq:6,register:"neutral"},
  {kr:"jabón",ro:"jabón",meaning:"soap",example:"Lávate con jabón — Wash with soap",pos:"noun",freq:6,register:"neutral"},
  {kr:"espejo",ro:"espejo",meaning:"mirror",example:"Me miré en el espejo — I looked at myself in the mirror",pos:"noun",freq:6,register:"neutral"},

  // Transport & Directions
  {kr:"taxi",ro:"taxi",meaning:"taxi",example:"Pedí un taxi — I ordered a taxi",pos:"noun",freq:7,register:"neutral"},
  {kr:"carro",ro:"carro",meaning:"car (Latin American)",example:"Mi carro está descompuesto — My car is broken",pos:"noun",freq:8,register:"neutral"},
  {kr:"moto",ro:"moto",meaning:"motorcycle",example:"Va en moto — He goes by motorcycle",pos:"noun",freq:6,register:"neutral"},
  {kr:"bicicleta",ro:"bicicleta",meaning:"bicycle",example:"Voy en bicicleta — I go by bicycle",pos:"noun",freq:6,register:"neutral"},
  {kr:"avión",ro:"avión",meaning:"airplane",example:"Tomamos el avión — We take the plane",pos:"noun",freq:7,register:"neutral"},
  {kr:"aeropuerto",ro:"aeropuerto",meaning:"airport",example:"Voy al aeropuerto — I'm going to the airport",pos:"noun",freq:7,register:"neutral"},
  {kr:"vuelo",ro:"vuelo",meaning:"flight",example:"Mi vuelo sale a las seis — My flight leaves at six",pos:"noun",freq:6,register:"neutral"},
  {kr:"gasolina",ro:"gasolina",meaning:"gasoline / gas",example:"Necesito gasolina — I need gas",pos:"noun",freq:6,register:"neutral"},
  {kr:"semáforo",ro:"semáforo",meaning:"traffic light",example:"Para en el semáforo — Stop at the traffic light",pos:"noun",freq:6,register:"neutral"},
  {kr:"esquina",ro:"esquina",meaning:"corner (of a street)",example:"En la esquina — On the corner",pos:"noun",freq:6,register:"neutral"},
  {kr:"cruce",ro:"cruce",meaning:"intersection",example:"En el cruce — At the intersection",pos:"noun",freq:5,register:"neutral"},
  {kr:"derecho",ro:"derecho",meaning:"straight / right (law)",example:"Sigue derecho — Go straight",pos:"adverb",freq:7,register:"neutral"},
  {kr:"izquierda",ro:"izquierda",meaning:"left",example:"Dobla a la izquierda — Turn left",pos:"noun",freq:7,register:"neutral"},
  {kr:"derecha",ro:"derecha",meaning:"right",example:"Dobla a la derecha — Turn right",pos:"noun",freq:7,register:"neutral"},
  {kr:"norte",ro:"norte",meaning:"north",example:"Al norte de la ciudad — North of the city",pos:"noun",freq:5,register:"neutral"},
  {kr:"sur",ro:"sur",meaning:"south",example:"En el sur del país — In the south of the country",pos:"noun",freq:5,register:"neutral"},

  // School & Work expansion
  {kr:"escuela",ro:"escuela",meaning:"school",example:"Los niños van a la escuela — The children go to school",pos:"noun",freq:8,register:"neutral"},
  {kr:"universidad",ro:"universidad",meaning:"university",example:"Estudio en la universidad — I study at university",pos:"noun",freq:8,register:"neutral"},
  {kr:"maestro",ro:"maestro",meaning:"teacher",example:"El maestro explica bien — The teacher explains well",pos:"noun",freq:7,register:"neutral"},
  {kr:"alumno",ro:"alumno",meaning:"student / pupil",example:"Soy buen alumno — I'm a good student",pos:"noun",freq:7,register:"neutral"},
  {kr:"clase",ro:"clase",meaning:"class / classroom",example:"La clase empieza a las ocho — Class starts at eight",pos:"noun",freq:8,register:"neutral"},
  {kr:"tarea",ro:"tarea",meaning:"homework",example:"Tengo mucha tarea — I have a lot of homework",pos:"noun",freq:7,register:"neutral"},
  {kr:"examen",ro:"examen",meaning:"exam",example:"Tengo examen mañana — I have an exam tomorrow",pos:"noun",freq:7,register:"neutral"},
  {kr:"nota",ro:"nota",meaning:"grade / note",example:"Saqué buena nota — I got a good grade",pos:"noun",freq:6,register:"neutral"},
  {kr:"libro",ro:"libro",meaning:"book",example:"Olvide mi libro — I forgot my book",pos:"noun",freq:8,register:"neutral"},
  {kr:"cuaderno",ro:"cuaderno",meaning:"notebook",example:"Escribe en tu cuaderno — Write in your notebook",pos:"noun",freq:7,register:"neutral"},
  {kr:"pluma",ro:"pluma",meaning:"pen",example:"¿Me prestas tu pluma? — Can you lend me your pen?",pos:"noun",freq:6,register:"neutral"},
  {kr:"lápiz",ro:"lápiz",meaning:"pencil",example:"Dibuja con lápiz — Draw with a pencil",pos:"noun",freq:6,register:"neutral"},
  {kr:"oficina",ro:"oficina",meaning:"office",example:"Trabajo en una oficina — I work in an office",pos:"noun",freq:7,register:"neutral"},
  {kr:"reunión",ro:"reunión",meaning:"meeting",example:"Tengo una reunión — I have a meeting",pos:"noun",freq:6,register:"formal"},
  {kr:"sueldo",ro:"sueldo",meaning:"salary",example:"El sueldo es bajo — The salary is low",pos:"noun",freq:6,register:"neutral"},
  {kr:"jefe",ro:"jefe",meaning:"boss",example:"Mi jefe es muy exigente — My boss is very demanding",pos:"noun",freq:7,register:"neutral"},
  {kr:"empresa",ro:"empresa",meaning:"company / business",example:"Trabajo para una empresa — I work for a company",pos:"noun",freq:6,register:"neutral"},
  {kr:"negocio",ro:"negocio",meaning:"business",example:"Tengo mi propio negocio — I have my own business",pos:"noun",freq:6,register:"neutral"},
  {kr:"cliente",ro:"cliente",meaning:"client / customer",example:"El cliente siempre tiene razón — The customer is always right",pos:"noun",freq:6,register:"neutral"},
  {kr:"contrato",ro:"contrato",meaning:"contract",example:"Firmé el contrato — I signed the contract",pos:"noun",freq:5,register:"formal"},

  // Technology
  {kr:"celular",ro:"celular",meaning:"cell phone",example:"Se me olvidó el celular — I forgot my cell phone",pos:"noun",freq:9,register:"casual"},
  {kr:"computadora",ro:"computadora",meaning:"computer",example:"Mi computadora se apagó — My computer turned off",pos:"noun",freq:8,register:"neutral"},
  {kr:"internet",ro:"internet",meaning:"internet",example:"No hay internet — There's no internet",pos:"noun",freq:8,register:"neutral"},
  {kr:"mensaje",ro:"mensaje",meaning:"message",example:"Te mando un mensaje — I'll send you a message",pos:"noun",freq:8,register:"neutral"},
  {kr:"foto",ro:"foto",meaning:"photo",example:"¿Me sacas una foto? — Can you take my photo?",pos:"noun",freq:7,register:"casual"},
  {kr:"video",ro:"video",meaning:"video",example:"Vi un video — I watched a video",pos:"noun",freq:7,register:"neutral"},
  {kr:"red social",ro:"red social",meaning:"social media",example:"Lo vi en las redes sociales — I saw it on social media",pos:"noun",freq:6,register:"neutral"},
  {kr:"aplicación",ro:"aplicación",meaning:"app / application",example:"Descarga la aplicación — Download the app",pos:"noun",freq:6,register:"neutral"},
  {kr:"contraseña",ro:"contraseña",meaning:"password",example:"Olvidé mi contraseña — I forgot my password",pos:"noun",freq:5,register:"neutral"},
  {kr:"pantalla",ro:"pantalla",meaning:"screen",example:"La pantalla está rota — The screen is broken",pos:"noun",freq:6,register:"neutral"},
  {kr:"batería",ro:"batería",meaning:"battery",example:"Se murió la batería — The battery died",pos:"noun",freq:6,register:"casual"},
  {kr:"cargador",ro:"cargador",meaning:"charger",example:"¿Tienes tu cargador? — Do you have your charger?",pos:"noun",freq:6,register:"casual"},
  {kr:"auriculares",ro:"auriculares",meaning:"headphones / earphones",example:"Mis auriculares están rotos — My headphones are broken",pos:"noun",freq:5,register:"neutral"},

  // Nature & Weather
  {kr:"sol",ro:"sol",meaning:"sun",example:"Hace mucho sol — It's very sunny",pos:"noun",freq:8,register:"neutral"},
  {kr:"lluvia",ro:"lluvia",meaning:"rain",example:"Viene la lluvia — The rain is coming",pos:"noun",freq:7,register:"neutral"},
  {kr:"viento",ro:"viento",meaning:"wind",example:"Hay mucho viento — It's very windy",pos:"noun",freq:6,register:"neutral"},
  {kr:"nube",ro:"nube",meaning:"cloud",example:"El cielo está nublado — The sky is cloudy",pos:"noun",freq:6,register:"neutral"},
  {kr:"calor",ro:"calor",meaning:"heat",example:"¡Qué calor! — It's so hot!",pos:"noun",freq:8,register:"neutral"},
  {kr:"río",ro:"río",meaning:"river",example:"El río está crecido — The river is high",pos:"noun",freq:6,register:"neutral"},
  {kr:"lago",ro:"lago",meaning:"lake",example:"Un lago tranquilo — A calm lake",pos:"noun",freq:5,register:"neutral"},
  {kr:"montaña",ro:"montaña",meaning:"mountain",example:"Subimos la montaña — We climbed the mountain",pos:"noun",freq:6,register:"neutral"},
  {kr:"playa",ro:"playa",meaning:"beach",example:"Vamos a la playa — Let's go to the beach",pos:"noun",freq:7,register:"neutral"},
  {kr:"árbol",ro:"árbol",meaning:"tree",example:"Un árbol grande — A big tree",pos:"noun",freq:6,register:"neutral"},
  {kr:"flor",ro:"flor",meaning:"flower",example:"Unas flores bonitas — Some pretty flowers",pos:"noun",freq:6,register:"neutral"},
  {kr:"tierra",ro:"tierra",meaning:"earth / soil / land",example:"La tierra está seca — The soil is dry",pos:"noun",freq:6,register:"neutral"},
  {kr:"cielo",ro:"cielo",meaning:"sky / heaven",example:"El cielo está azul — The sky is blue",pos:"noun",freq:7,register:"neutral"},

  // Emotions & Personality
  {kr:"amor",ro:"amor",meaning:"love",example:"Con mucho amor — With a lot of love",pos:"noun",freq:8,register:"neutral"},
  {kr:"odio",ro:"odio",meaning:"hate",example:"Lo odio — I hate it",pos:"noun",freq:6,register:"casual"},
  {kr:"miedo",ro:"miedo",meaning:"fear",example:"Tengo miedo — I'm scared",pos:"noun",freq:7,register:"neutral"},
  {kr:"alegría",ro:"alegría",meaning:"joy / happiness",example:"¡Qué alegría verte! — What a joy to see you!",pos:"noun",freq:7,register:"neutral"},
  {kr:"tristeza",ro:"tristeza",meaning:"sadness",example:"Siento mucha tristeza — I feel a lot of sadness",pos:"noun",freq:6,register:"neutral"},
  {kr:"enojo",ro:"enojo",meaning:"anger",example:"Siento enojo — I feel anger",pos:"noun",freq:6,register:"neutral"},
  {kr:"sorpresa",ro:"sorpresa",meaning:"surprise",example:"¡Qué sorpresa! — What a surprise!",pos:"noun",freq:7,register:"neutral"},
  {kr:"vergüenza",ro:"vergüenza",meaning:"shame / embarrassment",example:"Me da vergüenza — I'm embarrassed",pos:"noun",freq:6,register:"neutral"},
  {kr:"orgullo",ro:"orgullo",meaning:"pride",example:"Con mucho orgullo — With great pride",pos:"noun",freq:6,register:"neutral"},
  {kr:"nervioso",ro:"nervioso",meaning:"nervous",example:"Estoy nervioso — I'm nervous",pos:"adjective",freq:7,register:"neutral"},
  {kr:"emocionado",ro:"emocionado",meaning:"excited / emotional",example:"Estoy muy emocionado — I'm very excited",pos:"adjective",freq:7,register:"neutral"},
  {kr:"asustado",ro:"asustado",meaning:"scared",example:"Estoy asustada — I'm scared",pos:"adjective",freq:6,register:"neutral"},
  {kr:"aburrido",ro:"aburrido",meaning:"bored / boring",example:"Estoy aburrido — I'm bored",pos:"adjective",freq:7,register:"casual"},
  {kr:"enojado",ro:"enojado",meaning:"angry",example:"Está muy enojado — He's very angry",pos:"adjective",freq:7,register:"neutral"},
  {kr:"orgulloso",ro:"orgulloso",meaning:"proud",example:"Estoy muy orgullosa de ti — I'm very proud of you",pos:"adjective",freq:6,register:"neutral"},
  {kr:"avergonzado",ro:"avergonzado",meaning:"ashamed / embarrassed",example:"Estoy avergonzado — I'm embarrassed",pos:"adjective",freq:5,register:"neutral"},
  {kr:"confundido",ro:"confundido",meaning:"confused",example:"Estoy confundido — I'm confused",pos:"adjective",freq:5,register:"neutral"},
  {kr:"enamorado",ro:"enamorado",meaning:"in love",example:"Está enamorado de ella — He's in love with her",pos:"adjective",freq:6,register:"neutral"},
  {kr:"solo",ro:"solo",meaning:"alone / lonely",example:"Me siento solo — I feel alone",pos:"adjective",freq:7,register:"neutral"},
  {kr:"simpático",ro:"simpático",meaning:"nice / likeable",example:"Es muy simpático — He's very nice",pos:"adjective",freq:7,register:"neutral"},
  {kr:"amable",ro:"amable",meaning:"kind / friendly",example:"Es muy amable — She's very kind",pos:"adjective",freq:7,register:"neutral"},
  {kr:"inteligente",ro:"inteligente",meaning:"intelligent",example:"Una persona muy inteligente — A very intelligent person",pos:"adjective",freq:7,register:"neutral"},
  {kr:"trabajador",ro:"trabajador",meaning:"hardworking",example:"Es muy trabajadora — She's very hardworking",pos:"adjective",freq:6,register:"neutral"},
  {kr:"perezoso",ro:"perezoso",meaning:"lazy",example:"No seas perezoso — Don't be lazy",pos:"adjective",freq:5,register:"casual"},
  {kr:"honesto",ro:"honesto",meaning:"honest",example:"Es una persona honesta — An honest person",pos:"adjective",freq:6,register:"neutral"},
  {kr:"sincero",ro:"sincero",meaning:"sincere",example:"Sea sincero conmigo — Be sincere with me",pos:"adjective",freq:5,register:"neutral"},
  {kr:"generoso",ro:"generoso",meaning:"generous",example:"Es muy generosa — She's very generous",pos:"adjective",freq:5,register:"neutral"},

  // More verbs (B1-B2)
  {kr:"tomar",ro:"tomar",meaning:"to take / to drink",example:"Voy a tomar un café — I'm going to have a coffee",pos:"verb",freq:9,register:"neutral"},
  {kr:"llevar",ro:"llevar",meaning:"to take / to carry / to wear",example:"Lleva un abrigo — He's wearing a coat",pos:"verb",freq:8,register:"neutral"},
  {kr:"dejar",ro:"dejar",meaning:"to leave / to let / to stop",example:"Deja eso — Leave that",pos:"verb",freq:8,register:"neutral"},
  {kr:"seguir",ro:"seguir",meaning:"to continue / to follow",example:"Sigue recto — Continue straight",pos:"verb",freq:7,register:"neutral"},
  {kr:"parecer",ro:"parecer",meaning:"to seem / to look like",example:"Parece difícil — It seems difficult",pos:"verb",freq:7,register:"neutral"},
  {kr:"recordar",ro:"recordar",meaning:"to remember",example:"No recuerdo su nombre — I don't remember his name",pos:"verb",freq:7,register:"neutral"},
  {kr:"olvidar",ro:"olvidar",meaning:"to forget",example:"Siempre olvido mis llaves — I always forget my keys",pos:"verb",freq:7,register:"neutral"},
  {kr:"preocupar",ro:"preocupar",meaning:"to worry",example:"No te preocupes — Don't worry",pos:"verb",freq:7,register:"neutral"},
  {kr:"mejorar",ro:"mejorar",meaning:"to improve / to get better",example:"Espero mejorar — I hope to improve",pos:"verb",freq:6,register:"neutral"},
  {kr:"cambiar",ro:"cambiar",meaning:"to change",example:"Las cosas cambian — Things change",pos:"verb",freq:7,register:"neutral"},
  {kr:"ganar",ro:"ganar",meaning:"to win / to earn",example:"Ganamos el partido — We won the match",pos:"verb",freq:7,register:"neutral"},
  {kr:"perder",ro:"perder",meaning:"to lose / to miss",example:"Perdí mi teléfono — I lost my phone",pos:"verb",freq:7,register:"neutral"},
  {kr:"jugar",ro:"jugar",meaning:"to play (games/sports)",example:"Me gusta jugar fútbol — I like to play soccer",pos:"verb",freq:7,register:"neutral"},
  {kr:"escuchar",ro:"escuchar",meaning:"to listen",example:"Escucha bien — Listen carefully",pos:"verb",freq:8,register:"neutral"},
  {kr:"sentir",ro:"sentir",meaning:"to feel",example:"¿Cómo te sientes? — How do you feel?",pos:"verb",freq:8,register:"neutral"},
  {kr:"entender",ro:"entender",meaning:"to understand",example:"No entiendo — I don't understand",pos:"verb",freq:8,register:"neutral"},
  {kr:"explicar",ro:"explicar",meaning:"to explain",example:"¿Me puedes explicar? — Can you explain to me?",pos:"verb",freq:7,register:"neutral"},
  {kr:"repetir",ro:"repetir",meaning:"to repeat",example:"¿Puedes repetir? — Can you repeat?",pos:"verb",freq:7,register:"neutral"},
  {kr:"mostrar",ro:"mostrar",meaning:"to show",example:"Muéstrame — Show me",pos:"verb",freq:6,register:"neutral"},
  {kr:"permitir",ro:"permitir",meaning:"to allow / to permit",example:"No se permite — It's not allowed",pos:"verb",freq:6,register:"formal"},
  {kr:"deber",ro:"deber",meaning:"must / should / to owe",example:"Debes estudiar — You should study",pos:"verb",freq:7,register:"neutral"},
  {kr:"intentar",ro:"intentar",meaning:"to try / to attempt",example:"Voy a intentarlo — I'm going to try it",pos:"verb",freq:7,register:"neutral"},
  {kr:"lograr",ro:"lograr",meaning:"to achieve / to manage to",example:"Logré terminarlo — I managed to finish it",pos:"verb",freq:6,register:"neutral"},
  {kr:"existir",ro:"existir",meaning:"to exist",example:"¿Existe alguna solución? — Is there a solution?",pos:"verb",freq:5,register:"neutral"},
  {kr:"depender",ro:"depender",meaning:"to depend",example:"Depende de ti — It depends on you",pos:"verb",freq:6,register:"neutral"},
  {kr:"resultar",ro:"resultar",meaning:"to turn out / to result",example:"Resultó bien — It turned out well",pos:"verb",freq:5,register:"neutral"},
  {kr:"convertir",ro:"convertir",meaning:"to convert / to become",example:"Se convirtió en actor — He became an actor",pos:"verb",freq:5,register:"neutral"},
  {kr:"aumentar",ro:"aumentar",meaning:"to increase / to raise",example:"Los precios aumentaron — Prices went up",pos:"verb",freq:5,register:"neutral"},
  {kr:"reducir",ro:"reducir",meaning:"to reduce",example:"Hay que reducir gastos — We need to reduce expenses",pos:"verb",freq:4,register:"neutral"},
  {kr:"establecer",ro:"establecer",meaning:"to establish / to set up",example:"Establecieron las reglas — They established the rules",pos:"verb",freq:4,register:"formal"},
  {kr:"desarrollar",ro:"desarrollar",meaning:"to develop",example:"Quiero desarrollar mis habilidades — I want to develop my skills",pos:"verb",freq:4,register:"formal"},
  {kr:"considerar",ro:"considerar",meaning:"to consider",example:"Hay que considerarlo — We need to consider it",pos:"verb",freq:4,register:"neutral"},
  {kr:"suponer",ro:"suponer",meaning:"to suppose / to assume",example:"Supongo que sí — I suppose so",pos:"verb",freq:4,register:"neutral"},
  {kr:"señalar",ro:"señalar",meaning:"to point out / to indicate",example:"Señala el problema — Point out the problem",pos:"verb",freq:4,register:"formal"},
  {kr:"afectar",ro:"afectar",meaning:"to affect",example:"Eso me afecta mucho — That affects me a lot",pos:"verb",freq:4,register:"neutral"},

  // Abstract & C1/C2 vocabulary
  {kr:"concepto",ro:"concepto",meaning:"concept",example:"Un concepto difícil — A difficult concept",pos:"noun",freq:5,register:"formal"},
  {kr:"proceso",ro:"proceso",meaning:"process",example:"Es un proceso largo — It's a long process",pos:"noun",freq:5,register:"neutral"},
  {kr:"resultado",ro:"resultado",meaning:"result / outcome",example:"El resultado fue positivo — The result was positive",pos:"noun",freq:6,register:"neutral"},
  {kr:"situación",ro:"situación",meaning:"situation",example:"Es una situación difícil — It's a difficult situation",pos:"noun",freq:7,register:"neutral"},
  {kr:"problema",ro:"problema",meaning:"problem",example:"Hay un problema — There's a problem",pos:"noun",freq:8,register:"neutral"},
  {kr:"solución",ro:"solución",meaning:"solution",example:"Buscamos una solución — We're looking for a solution",pos:"noun",freq:7,register:"neutral"},
  {kr:"decisión",ro:"decisión",meaning:"decision",example:"Tomé una decisión — I made a decision",pos:"noun",freq:7,register:"neutral"},
  {kr:"oportunidad",ro:"oportunidad",meaning:"opportunity",example:"Es una gran oportunidad — It's a great opportunity",pos:"noun",freq:6,register:"neutral"},
  {kr:"experiencia",ro:"experiencia",meaning:"experience",example:"Tengo mucha experiencia — I have a lot of experience",pos:"noun",freq:6,register:"neutral"},
  {kr:"conocimiento",ro:"conocimiento",meaning:"knowledge",example:"El conocimiento es poder — Knowledge is power",pos:"noun",freq:5,register:"neutral"},
  {kr:"habilidad",ro:"habilidad",meaning:"ability / skill",example:"Tiene muchas habilidades — She has many skills",pos:"noun",freq:5,register:"neutral"},
  {kr:"objetivo",ro:"objetivo",meaning:"objective / goal",example:"Mi objetivo es aprender — My objective is to learn",pos:"noun",freq:5,register:"neutral"},
  {kr:"propósito",ro:"propósito",meaning:"purpose",example:"¿Cuál es el propósito? — What is the purpose?",pos:"noun",freq:4,register:"neutral"},
  {kr:"consecuencia",ro:"consecuencia",meaning:"consequence",example:"Las consecuencias son graves — The consequences are serious",pos:"noun",freq:4,register:"formal"},
  {kr:"perspectiva",ro:"perspectiva",meaning:"perspective",example:"Desde mi perspectiva — From my perspective",pos:"noun",freq:4,register:"formal"},
  {kr:"evidencia",ro:"evidencia",meaning:"evidence",example:"No hay evidencia — There's no evidence",pos:"noun",freq:4,register:"formal"},
  {kr:"argumento",ro:"argumento",meaning:"argument / plot",example:"Un argumento sólido — A solid argument",pos:"noun",freq:4,register:"formal"},
  {kr:"contexto",ro:"contexto",meaning:"context",example:"Hay que entender el contexto — We need to understand the context",pos:"noun",freq:4,register:"formal"},
  {kr:"impacto",ro:"impacto",meaning:"impact",example:"El impacto fue enorme — The impact was enormous",pos:"noun",freq:4,register:"neutral"},
  {kr:"influencia",ro:"influencia",meaning:"influence",example:"Tiene mucha influencia — He has a lot of influence",pos:"noun",freq:4,register:"neutral"},
  {kr:"tendencia",ro:"tendencia",meaning:"trend / tendency",example:"Es una tendencia global — It's a global trend",pos:"noun",freq:3,register:"formal"},
  {kr:"paradoja",ro:"paradoja",meaning:"paradox",example:"Es una paradoja interesante — It's an interesting paradox",pos:"noun",freq:3,register:"formal"},
  {kr:"ambigüedad",ro:"ambigüedad",meaning:"ambiguity",example:"Hay mucha ambigüedad — There's a lot of ambiguity",pos:"noun",freq:3,register:"formal"},
  {kr:"contradicción",ro:"contradicción",meaning:"contradiction",example:"Una contradicción obvia — An obvious contradiction",pos:"noun",freq:3,register:"formal"},
  {kr:"implicación",ro:"implicación",meaning:"implication",example:"Las implicaciones son claras — The implications are clear",pos:"noun",freq:3,register:"formal"},
  {kr:"matiz",ro:"matiz",meaning:"nuance / shade",example:"Hay que entender el matiz — You need to understand the nuance",pos:"noun",freq:3,register:"formal"},

  // Colors
  {kr:"rojo",ro:"rojo",meaning:"red",example:"Un carro rojo — A red car",pos:"adjective",freq:7,register:"neutral"},
  {kr:"azul",ro:"azul",meaning:"blue",example:"El cielo azul — The blue sky",pos:"adjective",freq:7,register:"neutral"},
  {kr:"verde",ro:"verde",meaning:"green",example:"Los árboles verdes — The green trees",pos:"adjective",freq:7,register:"neutral"},
  {kr:"amarillo",ro:"amarillo",meaning:"yellow",example:"Un taxi amarillo — A yellow taxi",pos:"adjective",freq:7,register:"neutral"},
  {kr:"negro",ro:"negro",meaning:"black",example:"Un gato negro — A black cat",pos:"adjective",freq:7,register:"neutral"},
  {kr:"blanco",ro:"blanco",meaning:"white",example:"Una camisa blanca — A white shirt",pos:"adjective",freq:7,register:"neutral"},
  {kr:"gris",ro:"gris",meaning:"grey",example:"Un día gris — A grey day",pos:"adjective",freq:6,register:"neutral"},
  {kr:"morado",ro:"morado",meaning:"purple",example:"Un vestido morado — A purple dress",pos:"adjective",freq:5,register:"neutral"},
  {kr:"rosado",ro:"rosado",meaning:"pink",example:"Una flor rosada — A pink flower",pos:"adjective",freq:5,register:"neutral"},
  {kr:"naranja",ro:"naranja",meaning:"orange (color)",example:"El color naranja — The color orange",pos:"adjective",freq:5,register:"neutral"},

  // More expressions
  {kr:"¡qué bueno!",ro:"¡qué bueno!",meaning:"great! / how good!",example:"¡Qué bueno que viniste! — Great that you came!",pos:"expression",freq:8,register:"casual"},
  {kr:"¡qué lástima!",ro:"¡qué lástima!",meaning:"what a shame! / too bad!",example:"¡Qué lástima que no puedas venir! — What a shame you can't come!",pos:"expression",freq:7,register:"neutral"},
  {kr:"¡ojalá!",ro:"¡ojalá!",meaning:"hopefully / I hope so (from Arabic via Spanish)",example:"¡Ojalá llueva! — Hopefully it rains!",pos:"expression",freq:8,register:"neutral"},
  {kr:"a lo mejor",ro:"a lo mejor",meaning:"maybe / perhaps",example:"A lo mejor viene mañana — Maybe she's coming tomorrow",pos:"adverb",freq:7,register:"casual"},
  {kr:"por supuesto",ro:"por supuesto",meaning:"of course",example:"¡Por supuesto! — Of course!",pos:"expression",freq:8,register:"neutral"},
  {kr:"en serio",ro:"en serio",meaning:"seriously / really",example:"¿En serio? — Seriously?",pos:"adverb",freq:8,register:"casual"},
  {kr:"de verdad",ro:"de verdad",meaning:"really / truly",example:"De verdad no lo sé — I truly don't know",pos:"adverb",freq:7,register:"neutral"},
  {kr:"sin embargo",ro:"sin embargo",meaning:"however / nevertheless",example:"Sin embargo, no fue así — However, it wasn't like that",pos:"adverb",freq:5,register:"formal"},
  {kr:"por lo tanto",ro:"por lo tanto",meaning:"therefore",example:"Por lo tanto, decidimos... — Therefore, we decided...",pos:"adverb",freq:4,register:"formal"},
  {kr:"a pesar de",ro:"a pesar de",meaning:"despite / in spite of",example:"A pesar de todo — Despite everything",pos:"adverb",freq:4,register:"neutral"},
  {kr:"además",ro:"además",meaning:"furthermore / besides / also",example:"Además, es barato — Furthermore, it's cheap",pos:"adverb",freq:5,register:"neutral"},
  {kr:"aunque",ro:"aunque",meaning:"although / even though",example:"Aunque esté cansado, iré — Even though I'm tired, I'll go",pos:"adverb",freq:5,register:"neutral"},
  {kr:"mientras",ro:"mientras",meaning:"while / whereas",example:"Mientras espero — While I wait",pos:"adverb",freq:5,register:"neutral"},
  {kr:"según",ro:"según",meaning:"according to",example:"Según él — According to him",pos:"adverb",freq:5,register:"neutral"},
  {kr:"mediante",ro:"mediante",meaning:"through / by means of",example:"Mediante el diálogo — Through dialogue",pos:"adverb",freq:3,register:"formal"},
];

// ── MX C1/C2 EXCLUSIVE ────────────────────────────────────────────────────────
const SPANISH_MX_C1 = [
  {kr:"pinche",ro:"pinche",meaning:"damn / freaking (mild vulgar intensifier, Mexico)",example:"¡Pinche tráfico! — Damn traffic!",pos:"adjective",freq:6,register:"vulgar"},
  {kr:"chido de ley",ro:"chido de ley",meaning:"legitimately cool / for real cool",example:"Está chido de ley — It's genuinely cool",pos:"expression",freq:4,register:"casual"},
  {kr:"se me hace",ro:"se me hace",meaning:"it seems to me / I think (Mexican expression)",example:"Se me hace que no va a venir — It seems to me he's not coming",pos:"expression",freq:6,register:"casual"},
  {kr:"agarrar la onda",ro:"agarrar la onda",meaning:"to get it / to catch on / to understand the vibe",example:"Ya agarré la onda — I got it now",pos:"expression",freq:5,register:"casual"},
  {kr:"echar la mano",ro:"echar la mano",meaning:"to lend a hand / to help out",example:"¿Me echas la mano? — Can you help me out?",pos:"expression",freq:5,register:"casual"},
  {kr:"al chile",ro:"al chile",meaning:"honestly / for real (Mexican slang)",example:"Al chile, no entiendo — Honestly, I don't get it",pos:"adverb",freq:5,register:"casual"},
  {kr:"hacer el paro",ro:"hacer el paro",meaning:"to do someone a favor / to help out",example:"Hazme el paro — Do me a solid",pos:"expression",freq:5,register:"casual"},
  {kr:"qué pedo",ro:"qué pedo",meaning:"what's up / what's going on (vulgar but common)",example:"¿Qué pedo? — What's up? / What's going on?",pos:"expression",freq:5,register:"vulgar"},
  {kr:"me cae bien",ro:"me cae bien",meaning:"I like him/her (as a person)",example:"Me cae muy bien — I really like him",pos:"expression",freq:6,register:"casual"},
  {kr:"me cae mal",ro:"me cae mal",meaning:"I don't like him/her (as a person)",example:"Me cae muy mal — I really don't like her",pos:"expression",freq:5,register:"casual"},
  {kr:"ya cayó el veinte",ro:"ya cayó el veinte",meaning:"the penny dropped / it finally clicked",example:"Ya cayó el veinte — I finally got it",pos:"expression",freq:4,register:"casual"},
  {kr:"no hay pex",ro:"no hay pex",meaning:"no problem / no worries",example:"No hay pex — No worries",pos:"expression",freq:4,register:"casual"},
  {kr:"a huevo",ro:"a huevo",meaning:"hell yes / absolutely (vulgar affirmation)",example:"¿Vas? — ¡A huevo! — Are you going? — Hell yes!",pos:"expression",freq:4,register:"vulgar"},
  {kr:"mana",ro:"mana",meaning:"buddy / bro (short for hermana/hermano)",example:"¿Qué hay, mana? — What's up, bro?",pos:"noun",freq:4,register:"casual"},
  {kr:"chamba",ro:"chamba",meaning:"work / job (casual Mexico)",example:"Tengo mucha chamba — I have a lot of work",pos:"noun",freq:5,register:"casual"},
  {kr:"chambear",ro:"chambear",meaning:"to work (casual)",example:"Estoy chambeando — I'm working",pos:"verb",freq:4,register:"casual"},
  {kr:"transa",ro:"transa",meaning:"shady deal / corrupt person",example:"Es bien transa — He's really shady",pos:"noun",freq:3,register:"casual"},
  {kr:"gandalla",ro:"gandalla",meaning:"selfish / taking advantage",example:"Ese tipo es un gandalla — That guy is a jerk who takes advantage",pos:"noun",freq:3,register:"casual"},
  {kr:"fuchi",ro:"fuchi",meaning:"yuck / that stinks",example:"¡Fuchi, qué asco! — Yuck, how disgusting!",pos:"expression",freq:3,register:"casual"},
  {kr:"a toda madre",ro:"a toda madre",meaning:"awesome / excellent (vulgar superlative)",example:"Estuvo a toda madre — It was awesome",pos:"expression",freq:3,register:"vulgar"},
];

// ── VE C1/C2 EXCLUSIVE ────────────────────────────────────────────────────────
const SPANISH_VE_C1 = [
  {kr:"¿épale?",ro:"¿épale?",meaning:"hey! / yo! (Venezuelan greeting/exclamation)",example:"¡Épale, pana! — Yo, buddy!",pos:"expression",freq:5,register:"casual"},
  {kr:"chivísimo",ro:"chivísimo",meaning:"really cool / great (Venezuela)",example:"Eso estuvo chivísimo — That was really cool",pos:"adjective",freq:4,register:"casual"},
  {kr:"¿qué fue?",ro:"¿qué fue?",meaning:"what's up? / what happened? (Venezuela)",example:"¿Qué fue, chamo? — What's up, dude?",pos:"expression",freq:5,register:"casual"},
  {kr:"estar arrecho",ro:"estar arrecho",meaning:"to be furious / also: to be awesome (context)",example:"Estoy arrecho contigo — I'm furious with you",pos:"expression",freq:4,register:"casual"},
  {kr:"bicho",ro:"bicho",meaning:"bug / also: a sly/cunning person",example:"Ese tipo es un bicho — That guy is sly",pos:"noun",freq:4,register:"casual"},
  {kr:"guevón",ro:"guevón",meaning:"dude / idiot / buddy (very common, context-dependent)",example:"¡Guevón, espera! — Dude, wait!",pos:"noun",freq:5,register:"vulgar"},
  {kr:"musiú",ro:"musiú",meaning:"foreigner (especially European)",example:"Ese musiú no habla español — That foreigner doesn't speak Spanish",pos:"noun",freq:3,register:"casual"},
  {kr:"pran",ro:"pran",meaning:"gang leader in prison (contemporary Venezuelan slang)",example:"Es el pran del bloque — He's the block's gang leader",pos:"noun",freq:3,register:"casual"},
  {kr:"mamá de los pollitos",ro:"mamá de los pollitos",meaning:"big cheese / the one in charge",example:"Él es la mamá de los pollitos — He's the one running things",pos:"expression",freq:3,register:"casual"},
  {kr:"hacer una vaca",ro:"hacer una vaca",meaning:"to pool money / to chip in",example:"Hagamos una vaca — Let's all chip in",pos:"expression",freq:4,register:"casual"},
  {kr:"llevar el marrón",ro:"llevar el marrón",meaning:"to take the blame / to get the short end",example:"Siempre llevo el marrón — I always get the blame",pos:"expression",freq:3,register:"casual"},
  {kr:"tener palanca",ro:"tener palanca",meaning:"to have connections / pull (to get things done)",example:"Necesitas palanca para eso — You need connections for that",pos:"expression",freq:4,register:"casual"},
  {kr:"pasar el maco",ro:"pasar el maco",meaning:"to have a hard time / to go through a rough patch",example:"Estoy pasando el maco — I'm having a hard time",pos:"expression",freq:3,register:"casual"},
  {kr:"jeva",ro:"jeva",meaning:"girlfriend / girl",example:"Esa es mi jeva — That's my girlfriend",pos:"noun",freq:4,register:"casual"},
  {kr:"llave",ro:"llave",meaning:"close friend / buddy (lit: key)",example:"Ese es mi llave — He's my close buddy",pos:"noun",freq:4,register:"casual"},
  {kr:"estar empatado",ro:"estar empatado",meaning:"to be tied up / to have no money",example:"Estoy empatado — I'm broke / tied up",pos:"expression",freq:3,register:"casual"},
  {kr:"raspado",ro:"raspado",meaning:"broke / flat broke",example:"Estoy raspado — I'm flat broke",pos:"adjective",freq:3,register:"casual"},
  {kr:"el boche",ro:"el boche",meaning:"a scolding / to give someone a talking-to",example:"Le dio un boche — She gave him a scolding",pos:"noun",freq:3,register:"casual"},
  {kr:"quillarse",ro:"quillarse",meaning:"to get angry / to lose it",example:"Se quilló — He lost it / got furious",pos:"verb",freq:3,register:"casual"},
  {kr:"estar en la lucha",ro:"estar en la lucha",meaning:"to be getting by / to be hustling",example:"Aquí, en la lucha — Just getting by here",pos:"expression",freq:4,register:"casual"},
];

// Add C1/C2 entries to main arrays
SPANISH_MX_WORDS.push(...SPANISH_CORE_2, ...SPANISH_MX_C1);
SPANISH_VE_WORDS.push(...SPANISH_CORE_2, ...SPANISH_VE_C1);

// Update window references
if (typeof window !== 'undefined') {
  window.SPANISH_MX_WORDS = SPANISH_MX_WORDS;
  window.SPANISH_VE_WORDS = SPANISH_VE_WORDS;
}
