// ── KOREAN WORD LIST ──────────────────────────────────────────────────────────
// register: 'formal' | 'casual' | 'neutral'
// pos: verb | noun | adjective | adverb | pronoun | particle | expression
// freq: 1-10 (10 = most essential)

const KOREAN_WORDS = [
  // ── Magnetic by ILLIT ──
  {kr:"눈",ro:"nun",meaning:"eye / eyes",example:"눈이 예뻐요 — your eyes are pretty",pos:"noun",freq:9,register:"neutral"},
  {kr:"빠져",ro:"ppajyeo",meaning:"falling into / drawn in",example:"나 빠져 — I'm falling for you",pos:"verb",freq:7,register:"casual"},
  {kr:"느껴",ro:"neukkyeo",meaning:"feeling / I feel",example:"뭔가 느껴 — I feel something",pos:"verb",freq:7,register:"casual"},
  {kr:"자꾸",ro:"jakku",meaning:"repeatedly / keeps happening",example:"자꾸 생각나 — keeps coming to mind",pos:"adverb",freq:7,register:"neutral"},
  {kr:"끌려",ro:"kkeullyeo",meaning:"being pulled / attracted",example:"네게 끌려 — being pulled toward you",pos:"verb",freq:6,register:"casual"},
  {kr:"설레",ro:"seolle",meaning:"heart fluttering / excited feeling",example:"설레는 기분 — a heart-fluttering feeling",pos:"verb",freq:6,register:"casual"},
  {kr:"떨려",ro:"tteollyeo",meaning:"trembling / heart racing",example:"심장이 떨려 — my heart is trembling",pos:"verb",freq:6,register:"casual"},
  {kr:"자석",ro:"jaseok",meaning:"magnet",example:"자석처럼 끌려 — pulled like a magnet",pos:"noun",freq:4,register:"neutral"},
  {kr:"순간",ro:"sungan",meaning:"moment / instant",example:"그 순간 — that moment",pos:"noun",freq:8,register:"neutral"},
  {kr:"가까이",ro:"gakkai",meaning:"close / near",example:"가까이 와 — come closer",pos:"adverb",freq:7,register:"neutral"},
  {kr:"바라봐",ro:"barabwa",meaning:"look at / gaze at",example:"나를 바라봐 — look at me",pos:"verb",freq:6,register:"casual"},
  {kr:"심장",ro:"simjang",meaning:"heart (organ) / heartbeat",example:"심장이 뛰어 — my heart is beating",pos:"noun",freq:6,register:"neutral"},
  {kr:"머릿속",ro:"meoritssok",meaning:"inside one's head / mind",example:"머릿속이 복잡해 — my head is a mess",pos:"noun",freq:5,register:"neutral"},
  {kr:"두근두근",ro:"dugeundugeun",meaning:"thump-thump (heartbeat sound)",example:"두근두근 떨려 — thump thump I'm trembling",pos:"expression",freq:4,register:"casual"},
  {kr:"뻔해",ro:"ppeonhae",meaning:"obvious / predictable",example:"너무 뻔해 — so obvious",pos:"adjective",freq:5,register:"casual"},
  {kr:"온통",ro:"ontong",meaning:"entirely / all over",example:"온통 너야 — it's all you",pos:"adverb",freq:5,register:"neutral"},
  {kr:"멈춰",ro:"meomchwo",meaning:"stop / halt",example:"멈춰 서 — stop right there",pos:"verb",freq:6,register:"casual"},
  {kr:"달라",ro:"dalla",meaning:"different / unlike",example:"뭔가 달라 — something's different",pos:"adjective",freq:7,register:"casual"},
  {kr:"그냥",ro:"geunyang",meaning:"just / simply / without reason",example:"그냥 좋아 — I just like it",pos:"adverb",freq:9,register:"casual"},
  {kr:"왠지",ro:"waenji",meaning:"for some reason / somehow",example:"왠지 좋아 — I like it for some reason",pos:"adverb",freq:7,register:"casual"},
  {kr:"처음",ro:"cheoeum",meaning:"first time / beginning",example:"처음 만났을 때 — when we first met",pos:"noun",freq:8,register:"neutral"},
  // ── Pronouns ──
  {kr:"나",ro:"na",meaning:"I / me",example:"나 배고파 — I'm hungry",pos:"pronoun",freq:10,register:"casual"},
  {kr:"저",ro:"jeo",meaning:"I / me (humble)",example:"저는 학생이에요 — I am a student",pos:"pronoun",freq:9,register:"formal"},
  {kr:"너",ro:"neo",meaning:"you",example:"너 어디 가? — where are you going?",pos:"pronoun",freq:10,register:"casual"},
  {kr:"당신",ro:"dangsin",meaning:"you (written/formal)",example:"당신을 사랑해요 — I love you",pos:"pronoun",freq:6,register:"formal"},
  {kr:"우리",ro:"uri",meaning:"we / our",example:"우리 같이 가자 — let's go together",pos:"pronoun",freq:10,register:"neutral"},
  {kr:"그",ro:"geu",meaning:"he / that",example:"그 사람 — that person",pos:"pronoun",freq:8,register:"neutral"},
  {kr:"그녀",ro:"geunyeo",meaning:"she / her",example:"그녀는 예뻐 — she is pretty",pos:"pronoun",freq:7,register:"neutral"},
  {kr:"누구",ro:"nugu",meaning:"who",example:"누구야? — who is it?",pos:"pronoun",freq:9,register:"neutral"},
  {kr:"뭐",ro:"mwo",meaning:"what (casual)",example:"뭐 해? — what are you doing?",pos:"pronoun",freq:10,register:"casual"},
  {kr:"무엇",ro:"mueot",meaning:"what (formal)",example:"무엇을 원하세요? — what would you like?",pos:"pronoun",freq:8,register:"formal"},
  // ── Greetings & expressions ──
  {kr:"안녕하세요",ro:"annyeonghaseyo",meaning:"hello (standard polite)",example:"안녕하세요, 처음 뵙겠습니다 — hello, nice to meet you",pos:"expression",freq:10,register:"formal"},
  {kr:"안녕",ro:"annyeong",meaning:"hi / bye (casual)",example:"안녕! 잘 지냈어? — hey! have you been well?",pos:"expression",freq:10,register:"casual"},
  {kr:"감사합니다",ro:"gamsahamnida",meaning:"thank you (formal)",example:"도와주셔서 감사합니다 — thank you for your help",pos:"expression",freq:10,register:"formal"},
  {kr:"고마워",ro:"gomawo",meaning:"thanks (casual)",example:"고마워, 진짜 — thanks, seriously",pos:"expression",freq:9,register:"casual"},
  {kr:"죄송합니다",ro:"joesonghamnida",meaning:"I'm sorry (formal)",example:"늦어서 죄송합니다 — I'm sorry for being late",pos:"expression",freq:9,register:"formal"},
  {kr:"미안해",ro:"mianhae",meaning:"sorry (casual)",example:"미안해, 내 잘못이야 — sorry, it's my fault",pos:"expression",freq:9,register:"casual"},
  {kr:"괜찮아요",ro:"gwaenchanayo",meaning:"it's okay (polite)",example:"괜찮아요, 걱정 마세요 — it's okay, don't worry",pos:"expression",freq:9,register:"formal"},
  {kr:"괜찮아",ro:"gwaenchana",meaning:"it's okay / I'm fine (casual)",example:"괜찮아? — are you okay?",pos:"expression",freq:9,register:"casual"},
  {kr:"맞아요",ro:"majayo",meaning:"that's right (polite)",example:"네, 맞아요 — yes, that's right",pos:"expression",freq:9,register:"formal"},
  {kr:"맞아",ro:"maja",meaning:"that's right (casual)",example:"맞아! 그거야 — that's right! that's it",pos:"expression",freq:9,register:"casual"},
  {kr:"알겠습니다",ro:"algesseumnida",meaning:"I understand (formal)",example:"네, 알겠습니다 — yes, I understand",pos:"expression",freq:8,register:"formal"},
  {kr:"알겠어",ro:"algeseo",meaning:"got it (casual)",example:"알겠어, 그렇게 할게 — got it, I'll do that",pos:"expression",freq:8,register:"casual"},
  {kr:"대박",ro:"daebak",meaning:"wow / amazing (slang)",example:"대박이야! — that's insane!",pos:"expression",freq:7,register:"casual"},
  {kr:"파이팅",ro:"paiting",meaning:"you can do it / fighting",example:"파이팅! 잘 할 수 있어 — you've got this!",pos:"expression",freq:7,register:"casual"},
  {kr:"잠깐만요",ro:"jamkkanmanyo",meaning:"just a moment (polite)",example:"잠깐만요, 확인해볼게요 — one moment, let me check",pos:"expression",freq:8,register:"formal"},
  {kr:"잠깐만",ro:"jamkkanman",meaning:"wait a sec (casual)",example:"잠깐만, 다시 봐봐 — hold on, look again",pos:"expression",freq:8,register:"casual"},
  {kr:"사랑해요",ro:"saranghaeyo",meaning:"I love you (polite)",example:"항상 사랑해요 — I always love you",pos:"expression",freq:9,register:"formal"},
  {kr:"사랑해",ro:"saranghae",meaning:"I love you (casual)",example:"사랑해, 알지? — I love you, you know that?",pos:"expression",freq:10,register:"casual"},
  {kr:"보고싶어요",ro:"bogosipeoyo",meaning:"I miss you (polite)",example:"많이 보고싶어요 — I miss you a lot",pos:"expression",freq:8,register:"formal"},
  {kr:"보고싶어",ro:"bogosipeo",meaning:"I miss you (casual)",example:"너무 보고싶어 — I miss you so much",pos:"expression",freq:8,register:"casual"},
  {kr:"잘 자요",ro:"jal jayo",meaning:"good night (polite)",example:"잘 자요, 좋은 꿈 꾸세요 — good night, sweet dreams",pos:"expression",freq:8,register:"formal"},
  {kr:"잘 자",ro:"jal ja",meaning:"good night (casual)",example:"잘 자, 내일 봐 — good night, see you tomorrow",pos:"expression",freq:8,register:"casual"},
  // ── Core verbs ──
  {kr:"가다",ro:"gada",meaning:"to go",example:"학교에 가다 — to go to school",pos:"verb",freq:10,register:"neutral"},
  {kr:"오다",ro:"oda",meaning:"to come",example:"집에 와 — come home",pos:"verb",freq:10,register:"neutral"},
  {kr:"먹다",ro:"meokda",meaning:"to eat",example:"밥 먹었어? — have you eaten?",pos:"verb",freq:10,register:"neutral"},
  {kr:"마시다",ro:"masida",meaning:"to drink",example:"물 마셔 — drink some water",pos:"verb",freq:9,register:"neutral"},
  {kr:"자다",ro:"jada",meaning:"to sleep",example:"일찍 자 — sleep early",pos:"verb",freq:9,register:"neutral"},
  {kr:"보다",ro:"boda",meaning:"to see / watch",example:"영화 봐 — watch a movie",pos:"verb",freq:10,register:"neutral"},
  {kr:"듣다",ro:"deutda",meaning:"to listen / hear",example:"음악 들어 — listen to music",pos:"verb",freq:9,register:"neutral"},
  {kr:"말하다",ro:"malhada",meaning:"to speak / say",example:"천천히 말해 — speak slowly",pos:"verb",freq:10,register:"neutral"},
  {kr:"알다",ro:"alda",meaning:"to know",example:"알아? — do you know?",pos:"verb",freq:10,register:"neutral"},
  {kr:"모르다",ro:"moreuda",meaning:"to not know",example:"몰라요 — I don't know",pos:"verb",freq:9,register:"neutral"},
  {kr:"있다",ro:"itda",meaning:"to exist / have / be (location)",example:"집에 있어 — I'm at home",pos:"verb",freq:10,register:"neutral"},
  {kr:"없다",ro:"eopda",meaning:"to not exist / not have",example:"돈이 없어 — I don't have money",pos:"verb",freq:10,register:"neutral"},
  {kr:"좋아하다",ro:"joahada",meaning:"to like",example:"한국 음식 좋아해 — I like Korean food",pos:"verb",freq:10,register:"neutral"},
  {kr:"사랑하다",ro:"saranghada",meaning:"to love",example:"가족을 사랑해 — I love my family",pos:"verb",freq:9,register:"neutral"},
  {kr:"원하다",ro:"wonhada",meaning:"to want",example:"뭘 원해? — what do you want?",pos:"verb",freq:9,register:"neutral"},
  {kr:"생각하다",ro:"saenggakhada",meaning:"to think",example:"어떻게 생각해? — what do you think?",pos:"verb",freq:9,register:"neutral"},
  {kr:"만나다",ro:"mannada",meaning:"to meet",example:"내일 만나자 — let's meet tomorrow",pos:"verb",freq:9,register:"neutral"},
  {kr:"기다리다",ro:"gidarida",meaning:"to wait",example:"여기서 기다려 — wait here",pos:"verb",freq:8,register:"neutral"},
  {kr:"공부하다",ro:"gongbuhada",meaning:"to study",example:"한국어 공부해 — I'm studying Korean",pos:"verb",freq:9,register:"neutral"},
  {kr:"일하다",ro:"ilhada",meaning:"to work",example:"오늘 많이 일했어 — I worked a lot today",pos:"verb",freq:9,register:"neutral"},
  {kr:"살다",ro:"salda",meaning:"to live",example:"서울에 살아 — I live in Seoul",pos:"verb",freq:9,register:"neutral"},
  {kr:"웃다",ro:"utda",meaning:"to smile / laugh",example:"웃어봐 — try smiling",pos:"verb",freq:8,register:"neutral"},
  {kr:"울다",ro:"ulda",meaning:"to cry",example:"울지 마 — don't cry",pos:"verb",freq:8,register:"neutral"},
  {kr:"주다",ro:"juda",meaning:"to give",example:"나한테 줘 — give it to me",pos:"verb",freq:9,register:"neutral"},
  {kr:"받다",ro:"batda",meaning:"to receive",example:"선물 받았어 — I received a gift",pos:"verb",freq:9,register:"neutral"},
  {kr:"찾다",ro:"chatda",meaning:"to find / look for",example:"뭐 찾아? — what are you looking for?",pos:"verb",freq:8,register:"neutral"},
  {kr:"시작하다",ro:"sijakhada",meaning:"to start",example:"시작하자 — let's start",pos:"verb",freq:8,register:"neutral"},
  {kr:"끝나다",ro:"kkeutnada",meaning:"to end / finish",example:"수업이 끝났어 — class is over",pos:"verb",freq:7,register:"neutral"},
  {kr:"도와주다",ro:"dowajuda",meaning:"to help",example:"도와줘서 고마워 — thanks for helping",pos:"verb",freq:8,register:"neutral"},
  {kr:"이해하다",ro:"ihaehada",meaning:"to understand",example:"이해해? — do you understand?",pos:"verb",freq:8,register:"neutral"},
  {kr:"좋다",ro:"jota",meaning:"to be good / to like",example:"이 노래 좋아 — I like this song",pos:"verb",freq:10,register:"neutral"},
  // ── Adjectives ──
  {kr:"예쁘다",ro:"yeppeuda",meaning:"pretty / beautiful",example:"너 진짜 예뻐 — you're really pretty",pos:"adjective",freq:9,register:"neutral"},
  {kr:"귀엽다",ro:"gwiyeopda",meaning:"cute",example:"너무 귀여워 — so cute",pos:"adjective",freq:8,register:"neutral"},
  {kr:"멋있다",ro:"meositda",meaning:"cool / stylish",example:"진짜 멋있어 — so cool",pos:"adjective",freq:8,register:"casual"},
  {kr:"크다",ro:"keuda",meaning:"big / tall",example:"키가 커 — you're tall",pos:"adjective",freq:10,register:"neutral"},
  {kr:"작다",ro:"jakda",meaning:"small / short",example:"키가 작아 — you're short",pos:"adjective",freq:9,register:"neutral"},
  {kr:"많다",ro:"manta",meaning:"many / a lot",example:"사람이 많아 — there are a lot of people",pos:"adjective",freq:10,register:"neutral"},
  {kr:"어렵다",ro:"oryeopda",meaning:"difficult",example:"한국어 어려워 — Korean is difficult",pos:"adjective",freq:8,register:"neutral"},
  {kr:"쉽다",ro:"swipda",meaning:"easy",example:"이건 쉬워 — this is easy",pos:"adjective",freq:8,register:"neutral"},
  {kr:"재미있다",ro:"jaemiitda",meaning:"fun / interesting",example:"진짜 재미있어 — this is really fun",pos:"adjective",freq:8,register:"neutral"},
  {kr:"피곤하다",ro:"pigonhada",meaning:"tired",example:"너무 피곤해 — I'm so tired",pos:"adjective",freq:8,register:"neutral"},
  {kr:"배고프다",ro:"baegopeuda",meaning:"hungry",example:"배고파 죽겠어 — I'm starving",pos:"adjective",freq:8,register:"casual"},
  {kr:"행복하다",ro:"haengbokhada",meaning:"happy",example:"지금 행복해 — I'm happy right now",pos:"adjective",freq:8,register:"neutral"},
  {kr:"힘들다",ro:"himdeulda",meaning:"hard / exhausting",example:"오늘 진짜 힘들었어 — today was really tough",pos:"adjective",freq:8,register:"neutral"},
  {kr:"바쁘다",ro:"bappeuda",meaning:"busy",example:"요즘 너무 바빠 — I've been so busy lately",pos:"adjective",freq:8,register:"neutral"},
  {kr:"맛있다",ro:"masitda",meaning:"delicious",example:"진짜 맛있어 — it's so delicious",pos:"adjective",freq:9,register:"neutral"},
  {kr:"같다",ro:"gatda",meaning:"same / similar",example:"우리 취향이 같아 — we have the same taste",pos:"adjective",freq:9,register:"neutral"},
  {kr:"다르다",ro:"dareuda",meaning:"different",example:"생각이 달라 — our thoughts are different",pos:"adjective",freq:8,register:"neutral"},
  // ── Adverbs ──
  {kr:"너무",ro:"neomu",meaning:"so / too / very",example:"너무 좋아 — I love it so much",pos:"adverb",freq:10,register:"casual"},
  {kr:"정말",ro:"jeongmal",meaning:"really / truly",example:"정말이야? — is that true?",pos:"adverb",freq:10,register:"neutral"},
  {kr:"진짜",ro:"jinjja",meaning:"really / for real (slang)",example:"진짜? — for real?",pos:"adverb",freq:10,register:"casual"},
  {kr:"많이",ro:"mani",meaning:"a lot / very much",example:"많이 먹어 — eat a lot",pos:"adverb",freq:10,register:"neutral"},
  {kr:"빨리",ro:"ppalli",meaning:"quickly / hurry",example:"빨리 와 — come quickly",pos:"adverb",freq:9,register:"neutral"},
  {kr:"천천히",ro:"cheoncheonhi",meaning:"slowly",example:"천천히 말해줘 — please speak slowly",pos:"adverb",freq:8,register:"neutral"},
  {kr:"항상",ro:"hangsang",meaning:"always",example:"항상 고마워 — always thankful",pos:"adverb",freq:9,register:"neutral"},
  {kr:"가끔",ro:"gakkeum",meaning:"sometimes",example:"가끔 생각나 — I think of you sometimes",pos:"adverb",freq:8,register:"neutral"},
  {kr:"지금",ro:"jigeum",meaning:"now",example:"지금 어디야? — where are you now?",pos:"adverb",freq:10,register:"neutral"},
  {kr:"왜",ro:"wae",meaning:"why",example:"왜 그래? — why are you like that?",pos:"adverb",freq:10,register:"neutral"},
  {kr:"어떻게",ro:"eotteoke",meaning:"how",example:"어떻게 해? — how do I do it?",pos:"adverb",freq:9,register:"neutral"},
  {kr:"다시",ro:"dasi",meaning:"again",example:"다시 해봐 — try again",pos:"adverb",freq:9,register:"neutral"},
  {kr:"같이",ro:"gachi",meaning:"together",example:"같이 가자 — let's go together",pos:"adverb",freq:9,register:"casual"},
  {kr:"혼자",ro:"honja",meaning:"alone",example:"혼자 있고 싶어 — I want to be alone",pos:"adverb",freq:8,register:"neutral"},
  {kr:"아직",ro:"ajik",meaning:"still / not yet",example:"아직 몰라 — I don't know yet",pos:"adverb",freq:8,register:"neutral"},
  {kr:"계속",ro:"gyesok",meaning:"keep going / continuously",example:"계속 해봐 — keep trying",pos:"adverb",freq:8,register:"neutral"},
  {kr:"조금",ro:"jogeum",meaning:"a little",example:"조금만 더 — just a little more",pos:"adverb",freq:9,register:"neutral"},
  // ── Particles ──
  {kr:"은/는",ro:"eun/neun",meaning:"topic marker",example:"나는 학생이에요 — I am a student",pos:"particle",freq:10,register:"neutral"},
  {kr:"이/가",ro:"i/ga",meaning:"subject marker",example:"비가 와요 — rain is falling",pos:"particle",freq:10,register:"neutral"},
  {kr:"을/를",ro:"eul/reul",meaning:"object marker",example:"밥을 먹어요 — I eat rice",pos:"particle",freq:10,register:"neutral"},
  {kr:"에",ro:"e",meaning:"at / to (place/time)",example:"학교에 가요 — I go to school",pos:"particle",freq:10,register:"neutral"},
  {kr:"에서",ro:"eseo",meaning:"at / from (action location)",example:"집에서 공부해요 — I study at home",pos:"particle",freq:9,register:"neutral"},
  {kr:"도",ro:"do",meaning:"also / too",example:"저도 알아요 — I know too",pos:"particle",freq:10,register:"neutral"},
  {kr:"만",ro:"man",meaning:"only / just",example:"너만 바라봐 — I only look at you",pos:"particle",freq:9,register:"neutral"},
  {kr:"이랑/랑",ro:"irang/rang",meaning:"with / and (casual)",example:"친구랑 갔어 — I went with a friend",pos:"particle",freq:8,register:"casual"},
  {kr:"와/과",ro:"wa/gwa",meaning:"and / with (formal)",example:"부모님과 함께 — together with parents",pos:"particle",freq:8,register:"formal"},
  {kr:"한테",ro:"hante",meaning:"to / from a person",example:"친구한테 줬어 — I gave it to my friend",pos:"particle",freq:8,register:"casual"},
  {kr:"께",ro:"kke",meaning:"to / from a person (honorific)",example:"선생님께 드렸어요 — I gave it to the teacher",pos:"particle",freq:7,register:"formal"},
  {kr:"처럼",ro:"cheoreum",meaning:"like / resembling",example:"별처럼 빛나 — shining like a star",pos:"particle",freq:7,register:"neutral"},
  // ── Nouns — essential ──
  {kr:"사람",ro:"saram",meaning:"person / people",example:"좋은 사람이야 — they're a good person",pos:"noun",freq:10,register:"neutral"},
  {kr:"이름",ro:"ireum",meaning:"name",example:"이름이 뭐야? — what's your name?",pos:"noun",freq:9,register:"neutral"},
  {kr:"집",ro:"jip",meaning:"home / house",example:"집에 가고 싶어 — I want to go home",pos:"noun",freq:10,register:"neutral"},
  {kr:"학교",ro:"hakgyo",meaning:"school",example:"학교 어때? — how's school?",pos:"noun",freq:9,register:"neutral"},
  {kr:"친구",ro:"chingu",meaning:"friend",example:"친구들이랑 놀았어 — hung out with friends",pos:"noun",freq:10,register:"neutral"},
  {kr:"가족",ro:"gajok",meaning:"family",example:"가족이 최고야 — family is the best",pos:"noun",freq:9,register:"neutral"},
  {kr:"엄마",ro:"eomma",meaning:"mom",example:"엄마한테 물어봐 — ask mom",pos:"noun",freq:9,register:"casual"},
  {kr:"아빠",ro:"appa",meaning:"dad",example:"아빠 닮았어 — you look like your dad",pos:"noun",freq:9,register:"casual"},
  {kr:"시간",ro:"sigan",meaning:"time",example:"시간이 없어 — I don't have time",pos:"noun",freq:10,register:"neutral"},
  {kr:"밥",ro:"bap",meaning:"rice / meal / food",example:"밥 먹었어? — have you eaten?",pos:"noun",freq:10,register:"casual"},
  {kr:"물",ro:"mul",meaning:"water",example:"물 한 잔 줘 — give me a glass of water",pos:"noun",freq:10,register:"neutral"},
  {kr:"음악",ro:"eumak",meaning:"music",example:"음악 들어? — are you listening to music?",pos:"noun",freq:9,register:"neutral"},
  {kr:"노래",ro:"norae",meaning:"song",example:"이 노래 뭐야? — what song is this?",pos:"noun",freq:9,register:"neutral"},
  {kr:"마음",ro:"maeum",meaning:"heart / feelings / mind",example:"마음이 따뜻해 — my heart feels warm",pos:"noun",freq:9,register:"neutral"},
  {kr:"사랑",ro:"sarang",meaning:"love",example:"사랑은 어려워 — love is difficult",pos:"noun",freq:10,register:"neutral"},
  {kr:"꿈",ro:"kkum",meaning:"dream",example:"꿈을 포기하지 마 — don't give up on your dream",pos:"noun",freq:7,register:"neutral"},
  {kr:"오늘",ro:"oneul",meaning:"today",example:"오늘 기분 어때? — how are you feeling today?",pos:"noun",freq:10,register:"neutral"},
  {kr:"내일",ro:"naeil",meaning:"tomorrow",example:"내일 봐 — see you tomorrow",pos:"noun",freq:9,register:"neutral"},
  {kr:"어제",ro:"eoje",meaning:"yesterday",example:"어제 뭐 했어? — what did you do yesterday?",pos:"noun",freq:9,register:"neutral"},
];
