// ── ITALIAN WORD LIST ─────────────────────────────────────────────────────────
// register: 'formal' | 'casual' | 'neutral'
// ro field = pronunciation guide (stress in CAPS)

const ITALIAN_WORDS = [
  // ── Greetings & expressions ──
  {kr:"buongiorno",ro:"bwon-JOR-no",meaning:"good morning / good day (standard greeting)",example:"Buongiorno, come posso aiutarla? — Good morning, how can I help you?",pos:"expression",freq:10,register:"formal"},
  {kr:"ciao",ro:"CHOW",meaning:"hi / bye (casual only)",example:"Ciao! Tutto bene? — Hey! Everything good?",pos:"expression",freq:10,register:"casual"},
  {kr:"buonasera",ro:"bwo-na-SEH-ra",meaning:"good evening",example:"Buonasera, ho una prenotazione — Good evening, I have a reservation",pos:"expression",freq:9,register:"formal"},
  {kr:"salve",ro:"SAL-veh",meaning:"hello (neutral, safe with strangers)",example:"Salve, mi chiamo Marco — Hello, my name is Marco",pos:"expression",freq:9,register:"neutral"},
  {kr:"arrivederci",ro:"ar-ree-veh-DAIR-chee",meaning:"goodbye (formal)",example:"Arrivederci, a domani — Goodbye, see you tomorrow",pos:"expression",freq:9,register:"formal"},
  {kr:"a presto",ro:"a PRES-to",meaning:"see you soon",example:"A presto! — See you soon!",pos:"expression",freq:8,register:"neutral"},
  {kr:"per favore",ro:"pair fa-VO-reh",meaning:"please (polite request)",example:"Un caffè, per favore — A coffee, please",pos:"expression",freq:10,register:"formal"},
  {kr:"per piacere",ro:"pair pya-CHEH-reh",meaning:"please (slightly more emphatic)",example:"Parla più piano, per piacere — Please speak more slowly",pos:"expression",freq:9,register:"formal"},
  {kr:"grazie",ro:"GRAT-syeh",meaning:"thank you",example:"Grazie per tutto — Thank you for everything",pos:"expression",freq:10,register:"neutral"},
  {kr:"grazie mille",ro:"GRAT-syeh MEEL-leh",meaning:"thank you very much",example:"Grazie mille, sei gentilissimo — Thank you so much, you're very kind",pos:"expression",freq:9,register:"formal"},
  {kr:"prego",ro:"PREH-go",meaning:"you're welcome / please / go ahead",example:"Prego, si accomodi — Please, have a seat",pos:"expression",freq:10,register:"neutral"},
  {kr:"mi dispiace",ro:"mee dis-PYA-cheh",meaning:"I'm sorry",example:"Mi dispiace per il ritardo — I'm sorry for the delay",pos:"expression",freq:9,register:"neutral"},
  {kr:"scusa",ro:"SKOO-za",meaning:"excuse me / sorry (casual)",example:"Scusa, puoi ripetere? — Sorry, can you repeat that?",pos:"expression",freq:9,register:"casual"},
  {kr:"mi scusi",ro:"mee SKOO-zee",meaning:"excuse me (formal)",example:"Mi scusi, dov'è la stazione? — Excuse me, where is the station?",pos:"expression",freq:9,register:"formal"},
  {kr:"non capisco",ro:"non ka-PEES-ko",meaning:"I don't understand",example:"Non capisco, può ripetere? — I don't understand, can you repeat?",pos:"expression",freq:9,register:"neutral"},
  {kr:"non lo so",ro:"non lo SO",meaning:"I don't know",example:"Non lo so davvero — I really don't know",pos:"expression",freq:9,register:"neutral"},
  {kr:"come si dice",ro:"KO-meh see DEE-cheh",meaning:"how do you say",example:"Come si dice 'hello' in italiano? — How do you say hello in Italian?",pos:"expression",freq:8,register:"neutral"},
  {kr:"esatto",ro:"eh-ZAT-to",meaning:"exactly / that's right",example:"Esatto! Hai capito bene — Exactly! You understood well",pos:"expression",freq:8,register:"neutral"},
  {kr:"capisce?",ro:"ka-PEE-sheh",meaning:"do you understand? (formal)",example:"È chiaro? Capisce? — Is it clear? Do you understand?",pos:"expression",freq:8,register:"formal"},
  {kr:"capisci?",ro:"ka-PEE-shee",meaning:"do you understand? (casual)",example:"Capisci cosa intendo? — Do you understand what I mean?",pos:"expression",freq:8,register:"casual"},
  {kr:"dai",ro:"DYE",meaning:"come on / oh come on (interjection)",example:"Dai, non essere così — Come on, don't be like that",pos:"expression",freq:8,register:"casual"},
  {kr:"mamma mia",ro:"MAM-ma MEE-a",meaning:"oh my / goodness (exclamation)",example:"Mamma mia, che fila! — Oh my, what a line!",pos:"expression",freq:7,register:"casual"},
  {kr:"basta",ro:"BA-sta",meaning:"enough / that's enough",example:"Basta, non ne posso più — Enough, I can't take it anymore",pos:"expression",freq:8,register:"neutral"},
  {kr:"andiamo",ro:"an-DYA-mo",meaning:"let's go",example:"Andiamo, è già tardi — Let's go, it's already late",pos:"expression",freq:8,register:"neutral"},
  {kr:"benvenuto",ro:"ben-veh-NOO-to",meaning:"welcome",example:"Benvenuto in Italia! — Welcome to Italy!",pos:"expression",freq:7,register:"neutral"},
  {kr:"buonanotte",ro:"bwo-na-NOT-teh",meaning:"good night",example:"Buonanotte, dormi bene — Good night, sleep well",pos:"expression",freq:8,register:"neutral"},
  {kr:"ti voglio bene",ro:"tee VOL-yo BEH-neh",meaning:"I love you (affection, family/friends)",example:"Ti voglio bene, mamma — I love you, mom",pos:"expression",freq:9,register:"casual"},
  {kr:"ti amo",ro:"tee A-mo",meaning:"I love you (romantic)",example:"Ti amo con tutto il cuore — I love you with all my heart",pos:"expression",freq:9,register:"casual"},
  {kr:"mi manchi",ro:"mee MAN-kee",meaning:"I miss you",example:"Mi manchi tanto — I miss you so much",pos:"expression",freq:8,register:"casual"},
  {kr:"in bocca al lupo",ro:"in BOK-ka al LOO-po",meaning:"good luck (literally: in the wolf's mouth)",example:"In bocca al lupo per l'esame! — Good luck on the exam!",pos:"expression",freq:7,register:"neutral"},
  // ── Pronouns ──
  {kr:"io",ro:"EE-o",meaning:"I / me",example:"Io non lo sapevo — I didn't know that",pos:"pronoun",freq:10,register:"neutral"},
  {kr:"tu",ro:"TOO",meaning:"you (casual)",example:"Tu cosa fai? — What are you doing?",pos:"pronoun",freq:10,register:"casual"},
  {kr:"lei",ro:"LAY",meaning:"she / you (formal)",example:"Lei è la professoressa? — Are you the professor?",pos:"pronoun",freq:9,register:"formal"},
  {kr:"lui",ro:"LOO-ee",meaning:"he / him",example:"Lui parla troppo — He talks too much",pos:"pronoun",freq:9,register:"neutral"},
  {kr:"noi",ro:"NOY",meaning:"we / us",example:"Noi andiamo al mare — We are going to the sea",pos:"pronoun",freq:9,register:"neutral"},
  {kr:"voi",ro:"VOY",meaning:"you all",example:"Voi venite alla festa? — Are you all coming to the party?",pos:"pronoun",freq:8,register:"neutral"},
  {kr:"loro",ro:"LO-ro",meaning:"they / them",example:"Loro non sanno ancora — They don't know yet",pos:"pronoun",freq:8,register:"neutral"},
  {kr:"chi",ro:"KEE",meaning:"who",example:"Chi ha detto questo? — Who said that?",pos:"pronoun",freq:9,register:"neutral"},
  {kr:"cosa",ro:"KO-za",meaning:"what / thing",example:"Cosa vuoi fare? — What do you want to do?",pos:"pronoun",freq:10,register:"neutral"},
  {kr:"questo",ro:"KWES-to",meaning:"this",example:"Questo è mio — This is mine",pos:"pronoun",freq:9,register:"neutral"},
  {kr:"quello",ro:"KWEL-lo",meaning:"that",example:"Quello mi piace di più — I like that one more",pos:"pronoun",freq:8,register:"neutral"},
  // ── Core verbs ──
  {kr:"essere",ro:"ES-seh-reh",meaning:"to be",example:"Sono stanco — I am tired",pos:"verb",freq:10,register:"neutral"},
  {kr:"avere",ro:"a-VEH-reh",meaning:"to have",example:"Ho fame — I'm hungry",pos:"verb",freq:10,register:"neutral"},
  {kr:"fare",ro:"FA-reh",meaning:"to do / make",example:"Cosa fai? — What are you doing?",pos:"verb",freq:10,register:"neutral"},
  {kr:"andare",ro:"an-DA-reh",meaning:"to go",example:"Vado a casa — I'm going home",pos:"verb",freq:10,register:"neutral"},
  {kr:"venire",ro:"veh-NEE-reh",meaning:"to come",example:"Vieni con me — Come with me",pos:"verb",freq:10,register:"neutral"},
  {kr:"volere",ro:"vo-LEH-reh",meaning:"to want",example:"Voglio imparare l'italiano — I want to learn Italian",pos:"verb",freq:10,register:"neutral"},
  {kr:"potere",ro:"po-TEH-reh",meaning:"can / to be able to",example:"Puoi aiutarmi? — Can you help me?",pos:"verb",freq:10,register:"neutral"},
  {kr:"dovere",ro:"do-VEH-reh",meaning:"must / to have to",example:"Devo partire subito — I have to leave immediately",pos:"verb",freq:9,register:"neutral"},
  {kr:"sapere",ro:"sa-PEH-reh",meaning:"to know (facts)",example:"Sai parlare italiano? — Do you know how to speak Italian?",pos:"verb",freq:9,register:"neutral"},
  {kr:"conoscere",ro:"ko-NO-sheh-reh",meaning:"to know (people/places)",example:"Conosci Roma? — Do you know Rome?",pos:"verb",freq:8,register:"neutral"},
  {kr:"dire",ro:"DEE-reh",meaning:"to say / tell",example:"Cosa vuoi dire? — What do you mean?",pos:"verb",freq:10,register:"neutral"},
  {kr:"parlare",ro:"par-LA-reh",meaning:"to speak / talk",example:"Parla più lentamente — Speak more slowly",pos:"verb",freq:10,register:"neutral"},
  {kr:"capire",ro:"ka-PEE-reh",meaning:"to understand",example:"Non capisco niente — I don't understand anything",pos:"verb",freq:9,register:"neutral"},
  {kr:"sentire",ro:"sen-TEE-reh",meaning:"to hear / feel / sense",example:"Senti questa canzone? — Do you hear this song?",pos:"verb",freq:8,register:"neutral"},
  {kr:"vedere",ro:"veh-DEH-reh",meaning:"to see / watch",example:"Ci vediamo domani — We'll see each other tomorrow",pos:"verb",freq:9,register:"neutral"},
  {kr:"guardare",ro:"gwar-DA-reh",meaning:"to look at / watch",example:"Guardiamo un film — Let's watch a film",pos:"verb",freq:8,register:"neutral"},
  {kr:"mangiare",ro:"man-JA-reh",meaning:"to eat",example:"Ho mangiato troppo — I ate too much",pos:"verb",freq:9,register:"neutral"},
  {kr:"bere",ro:"BEH-reh",meaning:"to drink",example:"Vuoi bere qualcosa? — Do you want to drink something?",pos:"verb",freq:9,register:"neutral"},
  {kr:"dormire",ro:"dor-MEE-reh",meaning:"to sleep",example:"Devo dormire — I need to sleep",pos:"verb",freq:9,register:"neutral"},
  {kr:"pensare",ro:"pen-SA-reh",meaning:"to think",example:"Cosa pensi di me? — What do you think of me?",pos:"verb",freq:9,register:"neutral"},
  {kr:"credere",ro:"KREH-deh-reh",meaning:"to believe",example:"Ci credo davvero — I really believe it",pos:"verb",freq:8,register:"neutral"},
  {kr:"amare",ro:"a-MA-reh",meaning:"to love",example:"Amo la musica italiana — I love Italian music",pos:"verb",freq:9,register:"neutral"},
  {kr:"piacere",ro:"pya-CHEH-reh",meaning:"to like / please",example:"Mi piace molto — I like it a lot",pos:"verb",freq:10,register:"neutral"},
  {kr:"aspettare",ro:"as-pet-TA-reh",meaning:"to wait",example:"Aspetta, arrivo subito — Wait, I'm coming right away",pos:"verb",freq:8,register:"neutral"},
  {kr:"trovare",ro:"tro-VA-reh",meaning:"to find",example:"Non riesco a trovarlo — I can't find it",pos:"verb",freq:8,register:"neutral"},
  {kr:"dare",ro:"DA-reh",meaning:"to give",example:"Dammi un attimo — Give me a moment",pos:"verb",freq:9,register:"neutral"},
  {kr:"prendere",ro:"PREN-deh-reh",meaning:"to take / get",example:"Prendo un caffè — I'll have a coffee",pos:"verb",freq:9,register:"neutral"},
  {kr:"uscire",ro:"oo-SHEE-reh",meaning:"to go out",example:"Usciamo stasera? — Shall we go out tonight?",pos:"verb",freq:8,register:"neutral"},
  {kr:"tornare",ro:"tor-NA-reh",meaning:"to return",example:"Torno fra un'ora — I'll be back in an hour",pos:"verb",freq:8,register:"neutral"},
  {kr:"vivere",ro:"VEE-veh-reh",meaning:"to live",example:"Vivo a Milano — I live in Milan",pos:"verb",freq:8,register:"neutral"},
  {kr:"lavorare",ro:"la-vo-RA-reh",meaning:"to work",example:"Lavoro troppo — I work too much",pos:"verb",freq:8,register:"neutral"},
  {kr:"studiare",ro:"stoo-DYA-reh",meaning:"to study",example:"Studio italiano ogni giorno — I study Italian every day",pos:"verb",freq:8,register:"neutral"},
  {kr:"chiamarsi",ro:"kya-MAR-see",meaning:"to be called / named",example:"Mi chiamo Sofia — My name is Sofia",pos:"verb",freq:9,register:"neutral"},
  {kr:"capirsi",ro:"ka-PEER-see",meaning:"to understand each other",example:"Ci capiamo bene — We understand each other well",pos:"verb",freq:7,register:"neutral"},
  // ── Adjectives ──
  {kr:"bello",ro:"BEL-lo",meaning:"beautiful / nice",example:"Che posto bello! — What a beautiful place!",pos:"adjective",freq:10,register:"neutral"},
  {kr:"buono",ro:"BWO-no",meaning:"good / tasty / kind",example:"Sei una persona buona — You are a good person",pos:"adjective",freq:10,register:"neutral"},
  {kr:"grande",ro:"GRAN-deh",meaning:"big / great",example:"Hai fatto una cosa grande — You did something great",pos:"adjective",freq:9,register:"neutral"},
  {kr:"piccolo",ro:"PEE-ko-lo",meaning:"small / little",example:"Un piccolo favore — A small favor",pos:"adjective",freq:9,register:"neutral"},
  {kr:"nuovo",ro:"NWO-vo",meaning:"new",example:"Un nuovo inizio — A new beginning",pos:"adjective",freq:9,register:"neutral"},
  {kr:"vecchio",ro:"VEK-kyo",meaning:"old",example:"Il mio vecchio quartiere — My old neighborhood",pos:"adjective",freq:8,register:"neutral"},
  {kr:"felice",ro:"feh-LEE-cheh",meaning:"happy",example:"Sono felice per te — I'm happy for you",pos:"adjective",freq:9,register:"neutral"},
  {kr:"triste",ro:"TREES-teh",meaning:"sad",example:"Perché sei così triste? — Why are you so sad?",pos:"adjective",freq:8,register:"neutral"},
  {kr:"stanco",ro:"STAN-ko",meaning:"tired",example:"Sono stanco morto — I'm dead tired",pos:"adjective",freq:8,register:"neutral"},
  {kr:"pronto",ro:"PRON-to",meaning:"ready",example:"Sei pronto per partire? — Are you ready to leave?",pos:"adjective",freq:9,register:"neutral"},
  {kr:"facile",ro:"FA-chee-leh",meaning:"easy",example:"Non è così facile — It's not that easy",pos:"adjective",freq:8,register:"neutral"},
  {kr:"difficile",ro:"dee-FEE-chee-leh",meaning:"difficult",example:"La grammatica è difficile — Grammar is difficult",pos:"adjective",freq:8,register:"neutral"},
  {kr:"vero",ro:"VEH-ro",meaning:"true / real",example:"È vero quello che dicono? — Is what they say true?",pos:"adjective",freq:9,register:"neutral"},
  {kr:"stesso",ro:"STES-so",meaning:"same",example:"Abbiamo lo stesso problema — We have the same problem",pos:"adjective",freq:8,register:"neutral"},
  {kr:"bravo",ro:"BRA-vo",meaning:"good / well done / skilled",example:"Sei molto bravo — You're very good",pos:"adjective",freq:9,register:"neutral"},
  {kr:"simpatico",ro:"seem-PA-tee-ko",meaning:"nice / likeable / funny",example:"È una persona simpatica — They're a likeable person",pos:"adjective",freq:8,register:"neutral"},
  {kr:"carino",ro:"ka-REE-no",meaning:"cute / nice / sweet",example:"Che idea carina! — What a cute idea!",pos:"adjective",freq:8,register:"casual"},
  {kr:"occupato",ro:"ok-koo-PA-to",meaning:"busy",example:"Sono molto occupato adesso — I'm very busy right now",pos:"adjective",freq:7,register:"neutral"},
  {kr:"libero",ro:"LEE-beh-ro",meaning:"free / available",example:"Sei libero domani? — Are you free tomorrow?",pos:"adjective",freq:8,register:"neutral"},
  // ── Adverbs ──
  {kr:"molto",ro:"MOL-to",meaning:"very / a lot",example:"Mi piace molto — I like it a lot",pos:"adverb",freq:10,register:"neutral"},
  {kr:"poco",ro:"PO-ko",meaning:"a little / not much",example:"Parlo poco italiano — I speak a little Italian",pos:"adverb",freq:9,register:"neutral"},
  {kr:"troppo",ro:"TROP-po",meaning:"too / too much",example:"È troppo caldo oggi — It's too hot today",pos:"adverb",freq:8,register:"neutral"},
  {kr:"abbastanza",ro:"ab-bas-TAN-tsa",meaning:"enough / quite / fairly",example:"È abbastanza buono — It's quite good",pos:"adverb",freq:8,register:"neutral"},
  {kr:"subito",ro:"SOO-bee-to",meaning:"right away / immediately",example:"Vengo subito — I'll be right there",pos:"adverb",freq:8,register:"neutral"},
  {kr:"ancora",ro:"an-KO-ra",meaning:"still / yet / again",example:"Stai ancora qui? — Are you still here?",pos:"adverb",freq:8,register:"neutral"},
  {kr:"già",ro:"JA",meaning:"already",example:"L'ho già visto — I already saw it",pos:"adverb",freq:8,register:"neutral"},
  {kr:"sempre",ro:"SEM-preh",meaning:"always",example:"Ti penso sempre — I always think about you",pos:"adverb",freq:9,register:"neutral"},
  {kr:"mai",ro:"MY",meaning:"never / ever",example:"Non lo faccio mai — I never do that",pos:"adverb",freq:8,register:"neutral"},
  {kr:"forse",ro:"FOR-seh",meaning:"maybe / perhaps",example:"Forse vengo anch'io — Maybe I'll come too",pos:"adverb",freq:8,register:"neutral"},
  {kr:"insieme",ro:"in-SYEH-meh",meaning:"together",example:"Facciamolo insieme — Let's do it together",pos:"adverb",freq:8,register:"neutral"},
  {kr:"adesso",ro:"a-DES-so",meaning:"now",example:"Adesso capisco tutto — Now I understand everything",pos:"adverb",freq:9,register:"neutral"},
  {kr:"dopo",ro:"DO-po",meaning:"after / later",example:"A dopo! — See you later!",pos:"adverb",freq:9,register:"neutral"},
  {kr:"prima",ro:"PREE-ma",meaning:"before / first / earlier",example:"Prima di tutto, grazie — First of all, thank you",pos:"adverb",freq:8,register:"neutral"},
  {kr:"dove",ro:"DO-veh",meaning:"where",example:"Dove sei? — Where are you?",pos:"adverb",freq:10,register:"neutral"},
  {kr:"quando",ro:"KWAN-do",meaning:"when",example:"Quando torni? — When are you coming back?",pos:"adverb",freq:9,register:"neutral"},
  {kr:"come",ro:"KO-meh",meaning:"how / like / as",example:"Come stai? — How are you?",pos:"adverb",freq:10,register:"neutral"},
  {kr:"perché",ro:"pair-KEH",meaning:"why / because",example:"Perché non vieni? — Why aren't you coming?",pos:"adverb",freq:9,register:"neutral"},
  {kr:"quanto",ro:"KWAN-to",meaning:"how much",example:"Quanto costa? — How much does it cost?",pos:"adverb",freq:9,register:"neutral"},
  {kr:"anche",ro:"AN-keh",meaning:"also / too / even",example:"Anch'io voglio venire — I want to come too",pos:"adverb",freq:9,register:"neutral"},
  {kr:"solo",ro:"SO-lo",meaning:"only / just / alone",example:"Solo un momento — Just a moment",pos:"adverb",freq:9,register:"neutral"},
  // ── Nouns ──
  {kr:"amore",ro:"a-MO-reh",meaning:"love",example:"L'amore è complicato — Love is complicated",pos:"noun",freq:10,register:"neutral"},
  {kr:"amico",ro:"a-MEE-ko",meaning:"friend (m)",example:"Il mio miglior amico — My best friend",pos:"noun",freq:10,register:"neutral"},
  {kr:"casa",ro:"KA-za",meaning:"home / house",example:"A casa mi sento bene — I feel good at home",pos:"noun",freq:10,register:"neutral"},
  {kr:"famiglia",ro:"fa-MEE-lya",meaning:"family",example:"La famiglia è tutto — Family is everything",pos:"noun",freq:9,register:"neutral"},
  {kr:"tempo",ro:"TEM-po",meaning:"time / weather",example:"Non ho tempo — I don't have time",pos:"noun",freq:10,register:"neutral"},
  {kr:"vita",ro:"VEE-ta",meaning:"life",example:"La vita è bella — Life is beautiful",pos:"noun",freq:9,register:"neutral"},
  {kr:"nome",ro:"NO-meh",meaning:"name",example:"Come ti chiami? — What's your name?",pos:"noun",freq:9,register:"neutral"},
  {kr:"acqua",ro:"AK-kwa",meaning:"water",example:"Un bicchiere d'acqua, per favore — A glass of water, please",pos:"noun",freq:10,register:"neutral"},
  {kr:"caffè",ro:"kaf-FEH",meaning:"coffee (espresso)",example:"Un caffè al volo — A quick coffee",pos:"noun",freq:9,register:"neutral"},
  {kr:"cibo",ro:"CHEE-bo",meaning:"food",example:"Il cibo italiano è fantastico — Italian food is fantastic",pos:"noun",freq:9,register:"neutral"},
  {kr:"cuore",ro:"KWO-reh",meaning:"heart",example:"Parla col cuore — Speak from the heart",pos:"noun",freq:9,register:"neutral"},
  {kr:"parola",ro:"pa-RO-la",meaning:"word",example:"Non trovo le parole — I can't find the words",pos:"noun",freq:8,register:"neutral"},
  {kr:"lingua",ro:"LEEN-gwa",meaning:"language / tongue",example:"Imparo la lingua italiana — I'm learning Italian",pos:"noun",freq:8,register:"neutral"},
  {kr:"musica",ro:"MOO-zee-ka",meaning:"music",example:"La musica mi calma — Music calms me",pos:"noun",freq:9,register:"neutral"},
  {kr:"canzone",ro:"kan-TSO-neh",meaning:"song",example:"Conosci questa canzone? — Do you know this song?",pos:"noun",freq:8,register:"neutral"},
  {kr:"città",ro:"cheet-TA",meaning:"city",example:"Che bella città! — What a beautiful city!",pos:"noun",freq:8,register:"neutral"},
  {kr:"ragazzo",ro:"ra-GAT-tso",meaning:"boy / guy / boyfriend",example:"Il mio ragazzo è gentile — My boyfriend is kind",pos:"noun",freq:9,register:"casual"},
  {kr:"ragazza",ro:"ra-GAT-tsa",meaning:"girl / girlfriend",example:"La mia ragazza studia medicina — My girlfriend studies medicine",pos:"noun",freq:9,register:"casual"},
  {kr:"bambino",ro:"bam-BEE-no",meaning:"child / baby",example:"Che bambino carino! — What a cute child!",pos:"noun",freq:8,register:"neutral"},
  {kr:"giorno",ro:"JOR-no",meaning:"day",example:"Buona giornata! — Have a good day!",pos:"noun",freq:10,register:"neutral"},
  {kr:"notte",ro:"NOT-teh",meaning:"night",example:"La notte è silenziosa — The night is quiet",pos:"noun",freq:9,register:"neutral"},
];
